### ISSUE TITLE
How to Verify the thread-safety issues of singleton with lazy style?

### ISSUE THREAD

**Issue by wsdjeg** [iluwatar/java-design-patterns#100]
class Singleton{
 15     //1.私有化构造器,使得外部无法调用本类的构造器
 16     private Singleton(){
 17     }
 18     private static Singleton singleton = null;
 19     //2.提供公共方法
 20     public static Singleton getSingleton(){
 21         if(singleton == null){
 22             try{Thread.sleep(500);}catch(InterruptedException e){e.printStackTrace();}
 23             singleton = new Singleton();
 24             try{Thread.sleep(500);}catch(InterruptedException e){e.printStackTrace();}
 25         }
 26         return singleton;
 27     }
 28 }
class TestSingleton1{
 39     public void showYesOrNo(){
 40     Singleton1Thread s = new Singleton1Thread();
 41     Thread t1 = new Thread(s);
 42     Thread t2 = new Thread(s);
 43     Thread t3 = new Thread(s);
 44     Thread t4 = new Thread(s);
 45     System.out.println("验证单例无锁的安全性");
 46     t1.start();
 47     t2.start();
 48     t3.start();
 49     t4.start();
 50     }
 51 }
 52 class Singleton1Thread implements Runnable{
 53     public void run(){
 54         Object obj = Singleton.getSingleton();
 55         System.out.println(obj);
 56     }
 57 }

**Comment by wsdjeg** [comment]
why different Thread has the same hashCode()?

**Comment by wsdjeg** [comment]
thank you for add the label!

**Comment by iluwatar** [comment]
@wsdjeg This is a good question. I will try to create a test case that demonstrates the thread safety issues of certain Singleton implementations.

**Comment by iluwatar** [comment]
@wsdjeg See my commit https://github.com/iluwatar/java-design-patterns/commit/96241f63d2a28449d36f7a4d2cf502d0786caf8d

**Comment by wsdjeg** [comment]
Thank you very much.i got it!
