### ISSUE TITLE
Redundant dependency declarations on child poms

### ISSUE THREAD

**Issue by jjjimenez100** [iluwatar/java-design-patterns#1009]
I've noticed that there are redeclaration of dependencies (e.g: junit 5 engine/mockito) on our modules. I don't think we'll be needing those since they are already specified on the parent pom.

Might be a good idea to have an issue that will do cleanups on child poms. Wdyt? @iluwatar

**Comment by iluwatar** [comment]
@jjjimenez100 yes I think we should clean up. Can you point out some example where this redeclaration occurs?

**Comment by jjjimenez100** [comment]
Looking at the parent pom, we already have the `mockito-core` dependency specified in [here](https://github.com/iluwatar/java-design-patterns/blob/master/pom.xml#L276).

Some of the child poms like [this](https://github.com/iluwatar/java-design-patterns/blob/master/decorator/pom.xml#L43) and [this] (https://github.com/iluwatar/java-design-patterns/blob/master/observer/pom.xml#L48) seem to redeclare the same dependency (Same goes for the jupiter engine ones)

**Comment by iluwatar** [comment]
I think that example is just how Maven's dependency management works (see https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management)

**Comment by akrystian** [comment]
Can I take this issue?

**Comment by iluwatar** [comment]
Ok @akrystian

**Comment by akrystian** [comment]
I found two probably not needed dependencies:
- `spring-boot-dependencies` 
- `javassist`

I can try remove it.
