### ISSUE TITLE
ORM pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#101]

**Comment by movingSone** [comment]
I can help you if you want it.

**Comment by iluwatar** [comment]
Great! Your contribution is welcome.

**Comment by iluwatar** [comment]
@movingSone How do plan to implement the ORM example? Using a framework such as Hibernate or doing everything from scratch?

**Comment by movingSone** [comment]
Let me prepare the sample so you can check if I am going in right direction.

**Comment by iluwatar** [comment]
Ok, no problem.

**Comment by MSaifAsif** [comment]
@iluwatar Is this still under construction by anyone?

**Comment by iluwatar** [comment]
ping @movingSone

**Comment by iluwatar** [comment]
After reading this article http://www.vertabelo.com/blog/technical-articles/orms-under-the-hood I started thinking if we should close this issue and just implement #34 and #79 

@npathai what is your view on this?

**Comment by npathai** [comment]
@iluwatar Yes we can close it.
