### ISSUE TITLE
SonarCloud reports bugs

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1010]
The project is using SonarCloud static code analysis. The latest results are showing that it has found several blocker and critical severity bugs. In this task those are fixed or marked as false positives. To mark false positives, `SuppressWarnings` annotation should be used in code as explained in the linked documentation.

Links:
[Blocker and critical severity bugs in SonarCloud](https://sonarcloud.io/project/issues?id=iluwatar_java-design-patterns&resolved=false&severities=BLOCKER%2CCRITICAL&types=BUG)
[Sonar false positives](https://docs.sonarqube.org/latest/analysis/languages/java/#JavaFAQ-HowtoremoveFalse-Positiveissues)

**Comment by oconnelc** [comment]
I started taking a look at these errors and I think the first one will be a false positive. Specifically the rule: "Loops should not be infinite" in the file "api-gateway/.../java/com/iluwatar/api/gateway/ApiGateway.java" Based on the documentation in the above link, it seems like there are two options:

1. Add the following annotation: 
`@SuppressWarnings("squid:S2189")`
but this causes a Java compile warning that the squid:S2189 is not a valid warning. 
1. Mark the issue in the SonarCloud: I think this is probably what we should do, but I didn't want to act until this was discussed.

**Comment by iluwatar** [comment]
Hmm where do you see the error after adding the annotation? Is it in the Maven output or IDE? Tried that with Maven but did not get any warnings.

**Comment by oconnelc** [comment]
I was seeing it on the IDE. (I keep stumbling on the Eclipse annoyances).
If it's not showing up in Maven, I'll just leave it as is.

**Comment by iluwatar** [comment]
Ok, let's try to proceed with `SuppressWarnings`

**Comment by oconnelc** [comment]
It turns out the warning is a setting in Eclipse. Selecting Window->Preferences and navigating to the Java compiler options and changing the value of: 
`Unhandled Token in @SuppressWarnings` to ignore. By default this is warn.
![image](https://user-images.githubusercontent.com/1112973/67146172-7117b880-f256-11e9-857e-14e31bd7e0c1.png)

**Comment by oconnelc** [comment]
I just pushed #1020 to address.

**Comment by iluwatar** [comment]
The latest scan shows two critical issues left. See the screenshot:

![image](https://user-images.githubusercontent.com/582346/67150293-6f81db00-f2be-11e9-84b3-4ce1c3b96310.png)

**Comment by oconnelc** [comment]
That's weird. I know I made those changes. I'll make sure they weren't
missed in the commit.
