### ISSUE TITLE
SonarCloud reports vulnerabilities

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1011]
The project is using SonarCloud static code analysis. The latest results are showing that it has found several blocker level vulnerabilities. In this task those are fixed or marked as false positives. To mark false positives, `SuppressWarnings` annotation should be used in code as explained in the linked documentation.

Links:
[Blocker and critical severity vulnerabilities in SonarCloud](https://sonarcloud.io/project/issues?id=iluwatar_java-design-patterns&resolved=false&severities=BLOCKER%2CCRITICAL&types=VULNERABILITY)
[Sonar false positives](https://docs.sonarqube.org/latest/analysis/languages/java/#JavaFAQ-HowtoremoveFalse-Positiveissues)

**Comment by oconnelc** [comment]
I would like to take a look, if no one else is interested.

**Comment by oconnelc** [comment]
I just submitted #1017 to address.

**Comment by iluwatar** [comment]
Ok @oconnelc
