### ISSUE TITLE
Checkstyle should use google_checks.xml

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1016]
At the moment maven-checkstyle-plugin in main pom.xml has been configured to use custom rules defined in checkstyle.xml. However there shouldn't be many modifications compared to the builtin google_checks.xml and it would be beneficial to start using this so that own rules wouldn't have to be maintained.

**Comment by kaiwinter** [comment]
Why does the `maven-checkstyle-plugin` in the root pom use an execution? As a consequence running `mvn checkstyle:checkstyle-aggregate` on the command line doesn't use this configuration...

**Comment by iluwatar** [comment]
I think the source of the configuration has been the instructions on the plugin's web site https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html, see "Checking for Violations as Part of the Build"

**Comment by iluwatar** [comment]
Ok @kaiwinter
