### ISSUE TITLE
Checkstyle reports warnings

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1021]
In issue https://github.com/iluwatar/java-design-patterns/issues/1016 we switched using Checkstyle's builtin google_checks.xml. The new ruleset finds over 6k warnings. In this issue we try fix those gradually, one pattern at a time. If you want to help, please comment on the issue which patterns will you be working on. We will follow the progress using the following table.

[x] abstract-document
[x] abstract-factory
[x] acyclic-visitor
[x] adapter
[x] aggregator-microservices
[x] ambassador
[x] api-gateway
[x] async-method-invocation
[x] balking
[x] bridge
[x] builder
[x] business-delegate
[x] bytecode
[x] caching
[x] callback
[x] chain
[x] circuit breaker
[x] collection-pipeline
[x] command
[x] commander
[x] composite
[x] converter
[x] cqrs
[x] dao
[x] data-bus
[x] data-locality
[x] data-mapper
[x] data-transfer-object
[x] decorator
[x] delegation
[x] dependency-injection
[x] dirty-flag
[x] double-checked-locking
[x] double-dispatch
[x] eip-aggregator
[x] eip-message-channel
[x] eip-publish-subscribe
[x] eip-splitter
[x] eip-wire-tap
[x] event-aggregator
[x] event-asynchronous
[x] event-driven-architecture
[x] event-queue
[x] event-sourcing
[x] execute-around
[x] extension-objects
[x] facade
[x] factory-kit
[x] factory-method
[x] feature-toggle
[x] fluentinterface
[x] flux
[x] flyweight
[x] front-controller
[x] guarded-suspension
[x] half-sync-half-async
[x] hexagonal
[x] intercepting-filter
[x] interpreter
[x] iterator
[x] layers
[x] lazy-loading
[x] leader-election
[x] marker
[x] master-worker-pattern
[x] mediator
[x] memento
[x] model-view-controller
[x] model-view-presenter
[x] module
[x] monad
[x] monostate
[x] multiton
[x] mute-idiom
[x] mutex
[x] naked-objects
[x] null-object
[x] object-mother
[x] object-pool
[x] observer
[x] page-object
[x] partial-response
[x] pipeline
[x] poison-pill
[x] priority-queue
[x] private-class-data
[x] producer-consumer
[x] promise
[x] property
[x] prototype
[x] proxy
[x] queue-load-leveling
[x] reactor
[x] reader-writer-lock
[x] repository
[x] resource-acquisition-is-initialization
[x] retry
[x] semaphore
[x] servant
[x] serverless
[x] service-layer
[x] service-locator
[x] singleton
[x] spatial-partition
[x] specification
[x] state
[x] step-builder
[x] strategy
[x] template-method
[x] thread-pool
[x] throttling
[x] tls
[x] tolerant-reader
[x] trampoline
[x] twin
[x] typeobjectpattern
[x] unit-of-work
[x] value-object
[x] visitor

Links:
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml
https://google.github.io/styleguide/javaguide.html

**Comment by leonorader** [comment]
I would like to work on singleton, strategy and visitor patterns! :)

**Comment by leonorader** [comment]
> I would like to work on singleton, strategy and visitor patterns! :)

So I submitted #1054 :)

**Comment by anuragagarwal561994** [comment]
Hey I have picked up ambassador, async-method-invocation, balking, bridge, builder in https://github.com/iluwatar/java-design-patterns/pull/1058

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up business-delegate, bytecode and caching in https://github.com/iluwatar/java-design-patterns/pull/1059

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up callback, chain, circuit-breaker (missing from above list) in https://github.com/iluwatar/java-design-patterns/pull/1060

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up collection-pipeline, command, commander in https://github.com/iluwatar/java-design-patterns/pull/1061

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up converter, cqrs in https://github.com/iluwatar/java-design-patterns/pull/1063

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up guarded-suspension, half-sync-half-async, hexagonal in https://github.com/iluwatar/java-design-patterns/pull/1064

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up intercepting-filter, interpreter, iterator in https://github.com/iluwatar/java-design-patterns/pull/1065

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up api-gateway, lazy-loading, leader-election in https://github.com/iluwatar/java-design-patterns/pull/1066

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up dao data-bus data-locality data-mapper data-transfer-object decorator in https://github.com/iluwatar/java-design-patterns/pull/1067

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up delegation dependency-injection dirty-flag double-buffer double-checked-locking double-dispatch in https://github.com/iluwatar/java-design-patterns/pull/1068

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up eip-* in https://github.com/iluwatar/java-design-patterns/pull/1069, event-* in https://github.com/iluwatar/java-design-patterns/pull/1070 and execute-around, extension-objects in https://github.com/iluwatar/java-design-patterns/pull/1071

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up all that begins with `r` in https://github.com/iluwatar/java-design-patterns/pull/1072

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up all remainig that begins with t, u and v in https://github.com/iluwatar/java-design-patterns/pull/1073 and https://github.com/iluwatar/java-design-patterns/pull/1074

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up facade factory-kit spatial-partition state step-builder in https://github.com/iluwatar/java-design-patterns/pull/1077

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up feature-toggle fluentinterface flux flyweight front-controller in https://github.com/iluwatar/java-design-patterns/pull/1078

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up semaphore servant serverless service-layer service-locator in https://github.com/iluwatar/java-design-patterns/pull/1079

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up abstract-document abstract-factory acyclic-visitor adapter aggregator-microservices in https://github.com/iluwatar/java-design-patterns/pull/1080

**Comment by anuragagarwal561994** [comment]
Not able to find faq.md anywhere.

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up naked-objects null-object object-mother object-pool observer queue-load-leveling in https://github.com/iluwatar/java-design-patterns/pull/1082

**Comment by jjjimenez100** [comment]
Let me pick up the one for pipeline (and see if I can do the remaining and not being worked by others)

**Comment by anuragagarwal561994** [comment]
@jjjimenez100 
If you are using IntelliJ I can share with you my code style file so that there is consistency in correcting checkstyle errors.

**Comment by trjoshjimenez** [comment]
Sounds like a good idea. :smile: Maybe we can have it uploaded with the gitter room or whatsoever you can suggest?

**Comment by jjjimenez100** [comment]
Sounds like a good idea. :smile: Maybe we can have it uploaded in the gitter room or whatsoever you can suggest?

**Comment by iluwatar** [comment]
> Not able to find faq.md anywhere.

Yeah that was a typo, sorry :grin:

**Comment by anuragagarwal561994** [comment]
@jjjimenez100 are you working on it, I have shared the file in gitter room.

**Comment by anuragagarwal561994** [comment]
@iluwatar for the remaining PR https://github.com/iluwatar/java-design-patterns/pull/1090 and https://github.com/iluwatar/java-design-patterns/pull/1091

**Comment by iluwatar** [comment]
Great job on this @anuragagarwal561994 @leonorader @jjjimenez100 and other. Since commit https://github.com/iluwatar/java-design-patterns/commit/8747f1fd7a420353f1d0772aa682559baa177256 we are enforcing the Checkstyle rules during the build i.e. the build fails if the rules are not respected.
