### ISSUE TITLE
IDE instructions should be updated

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1022]
IDE instructions in Wiki are no longer up to date after we did the Checkstyle configuration change in https://github.com/iluwatar/java-design-patterns/issues/1016. Describe the updated instructions for each IDE in this ticket.

Links:
https://github.com/iluwatar/java-design-patterns/wiki/12.-IDE-instructions

**Comment by kaiwinter** [comment]
In the current Eclipse nothing needs to be configured. I just imported the maven project and everything seems to be set up correctly:
![checkstyle-config](https://user-images.githubusercontent.com/110982/67161993-39953300-f360-11e9-80b0-6798ef5b978c.PNG)

**Comment by iluwatar** [comment]
Thanks for the tip @kaiwinter. I now tried to update the instructions for Eclipse and IntelliJ. At least it looks much simpler now. Let me know if there's something wrong or missing.

**Comment by kaiwinter** [comment]
Looks good to me. This can be omitted I think:
> You can run Checkstyle in Eclipse IDE by selecting the project(s) in package/project explorer, right-clicking the project and choosing Checkstyle - Check Code with Checkstyle

This is done automatically IMHO.

**Comment by iluwatar** [comment]
Ok, thanks for input @kaiwinter. With these talks I'll close the issue.
