### ISSUE TITLE
Arrange the patterns into modules

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1047]
Currently all the patterns belong to the default unnamed module. To make them real Java modules, we need to add `module-info.java` to each of the patterns.

Links:
https://www.baeldung.com/java-9-modularity
http://tutorials.jenkov.com/java/modules.html

Progress tracking:
[x] abstract-document

**Comment by saksham93** [comment]
I am working on this issue.

**Comment by iluwatar** [comment]
Ok @saksham93

**Comment by npczwh** [comment]
@iluwatar @saksham93  In current implementation (ex. abstract-document), we created module-info.java in the code folder (src/main/java/com.iluwatar.abstractdocument),  but my idea suggests to put it in module's source root (src/main/java). And the OpenJDK Guide (http://openjdk.java.net/projects/jigsaw/quick-start) gives the same suggestion. I'd like to know what you think of this. Should we change its path?

**Comment by iluwatar** [comment]
@npczwh @saksham93 I think you're right. The module-info.java should be at the source root (src/main/java).
https://stackoverflow.com/questions/46061428/where-to-place-module-info-java-using-java-9

**Comment by iluwatar** [comment]
@saksham93 are you still working on this?

**Comment by saksham93** [comment]
@iluwatar  I got busy with something else but I will continue working on this as from tomorrow. Is that fine?

**Comment by iluwatar** [comment]
Yes, sure @saksham93

**Comment by iluwatar** [comment]
After a bit of reconsideration I've decided not to implement the module infos since it doesn't bring any benefit. In the commit above I remove the existing `module-info.java` files.
