### ISSUE TITLE
Half Sync/Half Async pattern

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#109]
This is a _concurrency_ pattern. The pattern separates asynchronous I/O from the synchronous one. Main thread doesn't block on incoming client requests and long-running operations are offloaded to a dedicated synchronous layer. Processing results are delivered by the means of callbacks.
Some resources:
 - http://www.cs.wustl.edu/~schmidt/PDF/PLoP-95.pdf
 - http://zezutom.blogspot.in/2014/08/concurrency-patterns-half-sync-half.html
 - http://www.dre.vanderbilt.edu/~schmidt/cs282/PDFs/6-Concurrency-and-Synchronization-part10.pdf

**Comment by iluwatar** [comment]
Great find, thanks for reporting this.

**Comment by npathai** [comment]
I am working on it.

**Comment by npathai** [comment]
Note to self - we also need to add reference to POSA book with this task in README

**Comment by iluwatar** [comment]
Please close this issue, if you are satisfied.

**Comment by npathai** [comment]
Once #204 is merged we can close this.
