### ISSUE TITLE
Composite Specification

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1093]
Specification pattern example now shows use of hard-coded and parameterized specifications. In this task we extend the example so that "composite specification" is also demonstrated. It is described in mr. Fowler's paper below.

Links:
https://martinfowler.com/apsupp/spec.pdf
https://java-design-patterns.com/patterns/specification/
https://github.com/iluwatar/java-design-patterns/tree/master/specification

**Comment by MaVdbussche** [comment]
I felt like this one was coming ;) I would be glad to work on it !

**Comment by iluwatar** [comment]
Wonderful @MaVdbussche, please go ahead :+1:

**Comment by MaVdbussche** [comment]
@iluwatar I have created a PR for this issue at https://github.com/iluwatar/java-design-patterns/pull/1094.
