### ISSUE TITLE
"Unknown host repository-estatio.forge.cloudbees.com" issue

### ISSUE THREAD

**Issue by numbernine9** [iluwatar/java-design-patterns#1097]
Hi, this is Masaki Mizobuchi.
I faced the below error when I build the projects. So, I report is.

**Unknown host repository-estatio.forge.cloudbees.com** is shown when I execute the commnad `mvn eclipse:eclipse`.
It seems that [(http://repository-estatio.forge.cloudbees.com/snapshot/)] is closed host.

Error message is below.

> [ERROR] Failed to execute goal on project naked-objects-fixture: Could not resolve dependencies for project com.iluwatar:naked-objects-fixture:jar:1.22.0-SNAPSHOT: Could not transfer artifact com.iluwatar:naked-objects-dom:jar:1.22.0-SNAPSHOT from/to Cloudbees snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com: Unknown host repository-estatio.forge.cloudbees.com -

**Comment by iluwatar** [comment]
Confirmed, I can repeat this.
