### ISSUE TITLE
Adding references to known uses of patterns

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#110]
It would be great if we could also include in `etc` directory or some other place all the known implementations of the patterns. Like AbstractFactory is used in `javax.xml.parsers.DocumentBuilderFactory#newInstance()`. It can be a cherry on the pie.
[Implementation of GoF patterns in java core libraries](http://stackoverflow.com/questions/1673841/examples-of-gof-design-patterns-in-javas-core-libraries) contains references to some well known uses. Plus many open source libraries use patterns which can be documented.
I personally feel that it will give a better understanding to all because they will be able to see different flavors of same pattern being utilized in different contexts.

**Comment by iluwatar** [comment]
@npathai Did you notice in `REAME.md` under each pattern we have listed "Real world examples" that contains the known uses of the pattern?

**Comment by npathai** [comment]
@iluwatar Oops I didn't actually. Its great if we already have it. So what I would suggest is we should create a wiki page for known references.
