### ISSUE TITLE
Factory method always returns the same instance of a weapon

### ISSUE THREAD

**Issue by eacdev** [iluwatar/java-design-patterns#1107]
https://github.com/iluwatar/java-design-patterns/blob/a9c3df78ee6f51f1678a9521d74b93e127e734e2/factory-method/src/main/java/com/iluwatar/factory/method/OrcBlacksmith.java#L39

Let's say you tell it to get you a WeaponType.AXE, it will always return the same instance of weapon won't it?

If you have an army of orcs, you give each of them a different axe of course. You can't give the same axe to every orc.

In the current implementation if an axe gets chipped or whatever, every orc's axe will be chipped too.

If this is a bug I would be glad to fix it :)

**Comment by iluwatar** [comment]
@eacdev it's not a bug, it's designed that way.
