### ISSUE TITLE
ImperativeProgramming does not demonstracte Imperative-style in CollectonsPipeline Pattern

### ISSUE THREAD

**Issue by yichen88** [iluwatar/java-design-patterns#1163]

**Comment by iluwatar** [comment]
Apparently you are talking about this https://github.com/iluwatar/java-design-patterns/blob/master/collection-pipeline/src/main/java/com/iluwatar/collectionpipeline/ImperativeProgramming.java? Could you provide a more detailed description what is missing?

**Comment by Sxtanna** [comment]
Am I missing something, or is this an example of purely declarative programming?

**Comment by iluwatar** [comment]
I think you are correct. The imperative style has been lost in recent refactoring. It should look more like https://github.com/iluwatar/java-design-patterns/blob/4904d7eea047b5b924dcf33092ed887300f44d10/collection-pipeline/src/main/java/com/iluwatar/collectionpipeline/ImperativeProgramming.java
