### ISSUE TITLE
Inversion of control principle is mentioned twice

### ISSUE THREAD

**Issue by Tarptaeya** [iluwatar/java-design-patterns#1192]
<img width="1454" alt="Screenshot 2020-02-29 at 11 31 21 AM" src="https://user-images.githubusercontent.com/22481002/75601999-17b67480-5ae7-11ea-97d8-1f76ecdf0001.png">

**Comment by iluwatar** [comment]
Fixed with commit https://github.com/iluwatar/programming-principles/commit/15fb5838cdc54f93d898fe894492afe4ea2368cc
