### ISSUE TITLE
Event Aggregator pattern can be made more granular with emitting notification to specific observers

### ISSUE THREAD

**Issue by protyay** [iluwatar/java-design-patterns#1206]
The current implementation of the event -aggregator source code chooses to notify all the observers whenever an event source emits an event. 
This is can be made more granular with letting the subscriber subscribe with the aggregator for a specific type of event and then ONLY it should be notified in case , such an event is emitted. 

I would like to contribute a working version of these example, may be a PR if this issue is discussed.

**Comment by iluwatar** [comment]
Sounds good @protyay :+1: I'll assign the issue to you. I'm looking forward to your pull request.

**Comment by iluwatar** [comment]
@protyay are you still working on this?

**Comment by protyay** [comment]
@iluwatar Hi Sorry, Got busy w/ my day job. I'm still interested but might need some time, especially with the pandemic around.

**Comment by winiga-lab** [comment]
hey ! @iluwatar can you review my pr on this issue ;-) thanks

**Comment by ohbus** [comment]
> hey ! @iluwatar can you review my pr on this issue ;-) thanks

Hi @winiga-lab, Please follow [Contributing Gudelines](https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute)

**Comment by winiga-lab** [comment]
hello @ohbus thanks for reply. can I change the implementation by the way. This implementation is more easier to understand https://www.youtube.com/watch?v=e6Cy6gf8EeY

**Comment by ohbus** [comment]
> hello @ohbus thanks for reply. can I change the implementation by the way, [Events and Delegates: Event Aggregator](https://www.youtube.com/watch?v=e6Cy6gf8EeY) implementation is much easier to understand

Will be glad to do so! Please go on!

**Comment by iluwatar** [comment]
@winiga-lab are you working on this?

**Comment by iluwatar** [comment]
Ok @Leisterbecker

**Comment by SriPrarabdha** [comment]
Hey , would love to work on this issue

**Comment by iluwatar** [comment]
This issue was already fixed in https://github.com/iluwatar/java-design-patterns/pull/1933
