### ISSUE TITLE
Add a few more design patterns

### ISSUE THREAD

**Issue by Sanaebadi97** [iluwatar/java-design-patterns#1211]
tnx for your idea . is a good idea ..you can complete it with added :
1.model-view-view-model
2.model-view-intent

**Comment by iluwatar** [comment]
@Sanaebadi97 thanks for the suggestion. Could you create new issues for each of the new patterns? The description needs to include a link to a definitive source where the pattern is well described so that it can be implemented easily.

**Comment by Sanaebadi97** [comment]
Ok, See [this](https://github.com/iluwatar/java-design-patterns/issues/1215#issue-588988342) and [this](https://github.com/iluwatar/java-design-patterns/issues/1216#issue-588989214)!

**Comment by iluwatar** [comment]
Thanks @Sanaebadi97, I think we can now close this issue since it has been split into the two new ones.
