### ISSUE TITLE
add Model-View-ViewModel Design Pattern

### ISSUE THREAD

**Issue by Sanaebadi97** [iluwatar/java-design-patterns#1215]
Intro to the Model-View-ViewModel Design Pattern 

https://dzone.com/articles/model-view-viewmodel-design

https://www.journaldev.com/20292/android-mvvm-design-pattern

**Comment by jinishavora** [comment]
@iluwatar Can I work on this one please?

**Comment by ohbus** [comment]
We are glad to have you here!

Sure you can start working on it.

Please mention a timeline about when we can expect a pull request against this.

**Comment by jinishavora** [comment]
By Monday, 8th March.

**Comment by jinishavora** [comment]
@ohbus I have reached out to you on glitter regarding my concern before I submit the PR.

**Comment by jinishavora** [comment]
Just an update, I am trying to move the grade MVVM project to maven, I am halfway through and just need to work with few more dependencies for the project to build like an android app while using maven to build and follow the conventions of this project.

**Comment by ohbus** [comment]
No worry as we are not in a hurry!

Jokes aside, please take as much time as you need. We would really
appreciate a quality Pull Request than anything else.
