### ISSUE TITLE
Arrange, Act, Assert pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1218]
AAA is a way to structure your unit tests so they're easier to read, maintain, and enhance.

Reference: https://blog.ncrunch.net/post/arrange-act-assert-aaa-testing.aspx

**Comment by nanlliu** [comment]
hi im a beginner. can u elaborate more? so what should be done?

**Comment by kwbr** [comment]
For me it sounds just like a different name for Given-When-Then.
https://en.wikipedia.org/wiki/Given-When-Then

**Comment by npczwh** [comment]
> For me it sounds just like a different name for Given-When-Then.
> https://en.wikipedia.org/wiki/Given-When-Then

I think you are right. You can also look at it as a reformulation of the Four-Phase Test pattern.
https://martinfowler.com/bliki/GivenWhenThen.html

**Comment by npczwh** [comment]
@iluwatar , I'd like to take this

**Comment by iluwatar** [comment]
Ok @npczwh
