### ISSUE TITLE
How to Build the whole project with maven

### ISSUE THREAD

**Issue by oneslideicywater** [iluwatar/java-design-patterns#1227]
can you add more document about building the project with maven?
I want to build the whole project with only one command,so that I can 
browse the code in IDE

**Comment by anancds** [comment]
mvn clean package -DskipTest

**Comment by katy246** [comment]
If resolved, please consider closing @oneslideicywater

**Comment by oneslideicywater** [comment]
my jdk version is 8u221,so there's still an jdk version problem caused by :

`project abstract-factory: Fatal error compiling: 无效的标记: --module-path -` ,that' `module-info.java` in `abstract-factory` project, which means `invalid token: --module-path`。

**Comment by iluwatar** [comment]
@oneslideicywater the project requires JDK 11 to build
