### ISSUE TITLE
no comment should in json

### ISSUE THREAD

**Issue by jasciiz** [iluwatar/java-design-patterns#1231]
in naked-objects, there are comments in 
dom/src/main/java/domainapp/dom/app/homepage/HomePageViewModel.layout.json , but we can not add any comment in it.

**Comment by iluwatar** [comment]
Sorry, I don't understand what the problem is. Please clarify.

**Comment by iluwatar** [comment]
Your PR doesn't make any sense https://github.com/iluwatar/java-design-patterns/pull/1232
