### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by xiaod-dev** [iluwatar/java-design-patterns#1245]
#I think this is a very nice repo to learn java design patterns.But as I see, there still no translations for other languages.So I want to join this repo and **translate this into chinese** if It's possible.(I' m a Chinese)

**Comment by iluwatar** [comment]
@xiaod-dev this is a roadmap item we haven't started to implement yet. See https://github.com/iluwatar/java-design-patterns/wiki/13.-Roadmap.

For these kind of larger roadmap items we usually design it first into the wiki https://github.com/iluwatar/java-design-patterns/wiki and then chop it into smaller pieces to make it implementable.

@xiaod-dev if you're interested to take on this kind of bigger task then I would suggest to start it from the design vision. I'll support you of course where ever help is needed.

**Comment by xiaod-dev** [comment]
You mean I should edit the wiki first?It's seems I have no right to do this. And another problem, I don't know the organize rules of translate files...

**Comment by iluwatar** [comment]
Yes, @xiaod-dev we need to plan how the internationalization will be implemented. Can you try editing the wiki again? I updated the access rights so that anyone can edit. What comes to the organization rules this is what we need to design and document among other things.

**Comment by iluwatar** [comment]
@xiaod-dev here's an example roadmap item that was designed earlier https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition.

**Comment by xiaod-dev** [comment]
I write a first simple version of "15.-Support-for-multiple-languages".Help me review it if there is something missing or wrong. I think we should just use one method to organize our translated files.
https://github.com/iluwatar/java-design-patterns/wiki/15.-Support-for-multiple-languages

**Comment by iluwatar** [comment]
Thanks for working on this @xiaod-dev. In this design document we need to envision how we want the end result to look like. We have multiple ways how the user can approach the repository:

1. Browse the Github repository directly https://github.com/iluwatar/java-design-patterns
2. Use the web site https://java-design-patterns.com

For 1) one option is to use links to translations like described here https://github.community/t/how-to-localize-the-readme-file/1756.
For 2) we could have a language selector component in the Bootstrap navbar. Based on the selection the web site (https://github.com/iluwatar/java-design-patterns-web) would then render the site using the correct language files.

There could be other good alternatives as well. Can you think of any? In any case we need to write down the objective very clearly and preferably with pictures. Then we can start dividing the overall goals into manageable tasks.

For the methods (append language code or create a directory) you mention in https://github.com/iluwatar/java-design-patterns/wiki/15.-Support-for-multiple-languages I think we should evaluate pros and cons of each approach. For 1) either one probably works as good but for 2) there may be technical limitations that will drive our approach.

**Comment by xiaod-dev** [comment]
Actually,I don't know how the website works.It seems like it is a static web project and use the original docs from this repo. Is it use github io?
I find a previous issue on the java-design-patterns-web repo.https://github.com/iluwatar/java-design-patterns-web/issues/3
Is there any chance that we could use gitlocalize to translate?

**Comment by iluwatar** [comment]
Yes, that's correct. The web site is a static one generated with Jekyll and uses the markdown files from the repository. The site is served from AWS S3 and uses CloudFront CDN.
At first glance I think gitlocalize looks good and we could try it out. Yes, https://github.com/iluwatar/java-design-patterns-web/issues/3 is related issue.

**Comment by MiJack** [comment]
It seems that the website gitlocalize provide a good experience for the translation. If gitlocalize can provide a Jekyll plugin, we can use it for the multi-language website.

**Comment by iluwatar** [comment]
@xiaod-dev are you working on this? Let me know if you need assistance.

**Comment by xiaod-dev** [comment]
I think we can use gitlocalize.The website shows that  GitLocalize can work with any static site generators including Jekyll.
https://docs.gitlocalize.com/file_formats.html
and I forked this repo into my own git account to initialize it in GitLocalize.The repo url is https://github.com/xiaod-dev/java-design-patterns.
I try to translated the root readme doc in chinese.The url is https://github.com/xiaod-dev/java-design-patterns/tree/master/zh-CN.
And if I translated the adapter chapter,the translated file will be in "zh-CN/adapter/README.md".
So,

1. Is it right that I forked the repo to initialize GitLocalize?As I know,I am not the member of this repo,So I can't initialize GitLocalize in the original repo.If it is right,I need send PR to you after I have updates.
2. organize rules of translated files are shown above.It is fine?
3. help me check out if the GitLocalize is work well with Jekyll.

**Comment by iluwatar** [comment]
> Is it right that I forked the repo to initialize GitLocalize?As I know,I am not the member of this repo,So I can't initialize GitLocalize in the original repo.If it is right,I need send PR to you after I have updates.Besides, It will more convenient if I initialize GitLocalize in the original repo, cos I don't need send PR to forked repo(myself).

@xiaod-dev since you're working on big important feature I'll add you as a collaborator. Then you should be able to initialize GitLocalize with the main repository.

> organize rules of translated files are shown above.It is fine?

Yes, I'm ok to start with that

> help me check out if the GitLocalize is work well with Jekyll.

Yes, you have my full support. Just let me know what's needed.

**Comment by xiaod-dev** [comment]
It seems that only the owner of repository can initialize GitLocalize. bPlease help me initialize GitLocalize through this site:gitlocalize.com. And add me as a member of Team(Moderator)

**Comment by iluwatar** [comment]
Ok, done. It started syncing now.

![image](https://user-images.githubusercontent.com/582346/86762754-871d1180-c04f-11ea-9f04-6394fab86b7d.png)

**Comment by iluwatar** [comment]
I added a couple of chapters to https://github.com/iluwatar/java-design-patterns/wiki/15.-Support-for-multiple-languages

**Comment by iluwatar** [comment]
@all-contributors please add @xiaod-dev for translation

**Comment by iluwatar** [comment]
@xiaod-dev are you still working on this, and do you need assistance?

**Comment by xiaod-dev** [comment]
@iluwatar yeah, I got some problems here. The Gitlocalize shows application error when I try to access this [url](https://gitlocalize.com/repo/4984/zh) .Can you visit this page successfully? I send emails and send messages through their homepage,also submit a [issue](https://github.com/gitlocalize/feedback/issues/87) but still got no responses.....

**Comment by iluwatar** [comment]
@xiaod-dev yes, it shows me the application error as well when visiting the above url.

**Comment by iluwatar** [comment]
In the settings view there's an option to delete a language. Should we try deleting and adding it again? The translations so far can be accessed from git history anyway.
![image](https://user-images.githubusercontent.com/582346/90668948-81733800-e259-11ea-9f15-22000826e021.png)

**Comment by xiaod-dev** [comment]
@iluwatar yeah, I think we can have a try. And if it doesn't work, may be we can delete the hole project in gitlocalize and add it again?

**Comment by xiaod-dev** [comment]
Ah...In that way,I think temporarily I have to translate and send pull request manually...

**Comment by tkhadir** [comment]
hello i think this project is indeed of french translation, do you agree with me ?

**Comment by iluwatar** [comment]
@xiaod-dev any updates from gitlocalize project? It would be an asset if we could use it. I working on a new web site that will be able to utilize the translations.

**Comment by xiaod-dev** [comment]
> @xiaod-dev any updates from gitlocalize project? It would be an asset if we could use it. I working on a new web site that will be able to utilize the translations.

Since last time the gitlocalize occurs error, I don' t use it any more. I translate with google and process it by myself. You mentioned a new website, Could you share the website or is there anything I can collaborate with you?

**Comment by iluwatar** [comment]
It's still very much in progress, but what I currently have can be seen here: https://fervent-booth-169ea6.netlify.app/

**Comment by iluwatar** [comment]
Help needed in translating the new website to Chinese. See https://github.com/iluwatar/java-design-patterns-vuepress-web/issues/13

**Comment by iluwatar** [comment]
Hey guys, since there are many languages incoming I've decided to split this issue into individual target languages. If you are willing to help, please look for issues such as "Translate to Chinese" and add a comment to indicate you are willing to work on it. I can then assign the issue to you.
