### ISSUE TITLE
Issue build with java 8

### ISSUE THREAD

**Issue by tranvantriet** [iluwatar/java-design-patterns#1253]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project abstract-factory: Fatal error compiling: invalid flag: --module-path -> [Help 1]

**Comment by hjcui** [comment]
you need jdk 11 to support var

**Comment by iluwatar** [comment]
Yes, the project requires JDK 11 to build
