### ISSUE TITLE
Compose Method pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1260]
https://www.informit.com/articles/article.aspx?p=1398607

**Comment by wangihzyue** [comment]
Hi, @iluwatar , I also want to try this pattern. Is it ok? I suppose that this is relatively easy, so I want to try it.

**Comment by ohbus** [comment]
Sure thing @wangihzyue

**Comment by vishhhhhhhh** [comment]
I am happy to have a go at this task, please assign it to me :)

**Comment by iluwatar** [comment]
Yes @vishhhhhhhh, it's assigned to you now
