### ISSUE TITLE
Collecting Parameter pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1261]
https://wiki.c2.com/?CollectingParameter

**Comment by santyelegy** [comment]
Hello, I would like to work on this issue. I manage to finish it within a month.

**Comment by ohbus** [comment]
Great to have you onboarded @santyelegy!

We are expecting the PR for this by the end of May '21

**Comment by JoshuaSinglaANU** [comment]
Hey @iluwatar, may I please pick up on this issue? I am interested in working on this.

**Comment by iluwatar** [comment]
Ok @JoshuaSinglaANU

**Comment by JoshuaSinglaANU** [comment]
@iluwatar I am almost ready to make a PR, however, the automatic class diagram generation isn't working on my end. I have updated the parent pom.xml file to include my work and locally installed PlantUML, yet still, no class diagram is made. The wiki does not give much detail either. May I please know how to have this feature work?

**Comment by JoshuaSinglaANU** [comment]
@iluwatar I've added the UML reverse wrapper to the pom.xml file, but I still can't see the class diagram. Would you know why that is?

**Comment by JoshuaSinglaANU** [comment]
UML diagram added.
