### ISSUE TITLE
Service to Worker pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1262]
https://www.oreilly.com/library/view/j2ee-design-patterns/0596004273/re05.html

**Comment by zWeBrain** [comment]
This design pattern looks cool and powerful!! I would like to work on this issue within one month.

**Comment by iluwatar** [comment]
Yes @zWeBrain, you're assigned

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by Liu-rj** [comment]
Hi! I'd like to work on this issue and plan to finish it before June. Can you assign it to me? Thx.

**Comment by iluwatar** [comment]
Ok @Liu-rj
