### ISSUE TITLE
Composite View pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1264]
https://www.oracle.com/technetwork/java/compositeview-137722.html

**Comment by Kevinyl3** [comment]
I would like to try my hand at implementing this

**Comment by Kevinyl3** [comment]
I have looked over the reference linked above, and I am currently leaning towards the Java-beans management with JSP for the implementation. My understanding of JSP is that to actually render the page requires a server like Tomcat. I was wondering if there was a lighter weight approach to demonstrate this design pattern, as it could be difficult for a user to download and configure a server to simply view this design pattern example, in addition I am not aware of any ways to unit test JSP. If no other options exist, I can proceed with the Java-beans management strategy.

**Comment by iluwatar** [comment]
JSP pages are not used that much anymore nowadays. Spring Boot makes it easy to execute stand-alone applications and it would be relatively easy to bundle it with a Javascript front-end. Any modern Javascript framework can do composite views.

**Comment by Kevinyl3** [comment]
I am mostly done with the JSP implementation, in the #1264 branch, would you like me to re-do it with Spring Boot and Java Script, or finish the JSP implementation?

**Comment by Kevinyl3** [comment]
If I were to re do the example with a JavaScript framework, say React, would making a pure React application that runs in nodejs be sufficient? Going by the J2EE reference and what I could find for composite view through google, this pattern doesn't seem to require much backend logic.

**Comment by iluwatar** [comment]
Pure Javascript sounds a bit too much, this is Java design patterns anyway :) There are also Java front-end frameworks you could use. I'm not dictating which one you should choose. Maybe pick the one you find most interesting?
