### ISSUE TITLE
Serialized Entity pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1275]
https://www.oreilly.com/library/view/j2ee-design-patterns/0596004273/re21.html

**Comment by komminen** [comment]
Hi iluwatar, I'd like to volunteer to take a crack at this and try to fix in November/December if you're okay with that.

**Comment by JurenXu** [comment]
Can I take this?

**Comment by iluwatar** [comment]
Ok, you're assigned @JurenXu

**Comment by JurenXu** [comment]
> Ok, you're assigned @JurenXu

Thank you! I will start working on this

**Comment by JurenXu** [comment]
> Ok, you're assigned @JurenXu

Hi, Iluwatar.
I got a question, do I have to use the h2 database, or can I use MySQL instead?
