### ISSUE TITLE
Optimistic Concurrency pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1280]
http://ommolketab.ir/aaf-lib/axkwht7wxrhvgs2aqkxse8hihyu9zv.pdf chapter 10.2

**Comment by vithlaithla** [comment]
Hi, I would like to work on this pattern. Is this available for taking?

**Comment by JeffersonJefferson-pixel** [comment]
I work with @vithlaithla on this one. I'll be making a pull a request for the issue.

**Comment by iluwatar** [comment]
Ok @JeffersonJefferson-pixel
