### ISSUE TITLE
J2EE message distribution patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1285]
http://ommolketab.ir/aaf-lib/axkwht7wxrhvgs2aqkxse8hihyu9zv.pdf chapter 11.3 ->

**Comment by dvsingh9** [comment]
hi @iluwatar there are few message distribution patterns like point-to-point, Publish-Subscribe, should create pattern for all ?

**Comment by iluwatar** [comment]
This issue needs splitting as labelled. I'm not sure what would be the best approach.
