### ISSUE TITLE
Producer Consumer pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1286]
https://dzone.com/articles/producer-consumer-pattern

Also in book "Java Concurrency in Practice"

**Comment by ravening** [comment]
Can I work on this?

**Comment by ravening** [comment]
Looks like this pattern already exists in the code

**Comment by iluwatar** [comment]
Yes, it seems it was already implemented in https://github.com/iluwatar/java-design-patterns/issues/271. Closing this as duplicate.
