### ISSUE TITLE
Client Session State pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1288]
https://dzone.com/articles/practical-php-patterns/practical-php-patterns-client

**Comment by nakul251197** [comment]
I would like to work on this issue. Could you assign me this?

**Comment by iluwatar** [comment]
Yes, please go ahead @nakul251197

**Comment by iluwatar** [comment]
@nakul251197, the PR build is failing and we need your effort to investigate it
