### ISSUE TITLE
Concrete Table Inheritance pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1290]
http://thierryroussel.free.fr/java/books/martinfowler/www.martinfowler.com/isa/leafTableInheritance.html

**Comment by lkpengcs** [comment]
hi, can I work on this issue?

**Comment by iluwatar** [comment]
Yep @lkpengcs, go ahead

**Comment by iluwatar** [comment]
@lkpengcs are you working on it?
