### ISSUE TITLE
Embedded Value pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1295]
https://www.youtube.com/watch?v=6n5O5mCdnew

**Comment by shivu2002a** [comment]
Can I work on this issue?

**Comment by iluwatar** [comment]
Assigned to @shivu2002a since he was the first. @kiratalreja3 I hope you find something else that interests you

**Comment by shivu2002a** [comment]
@iluwatar Thank you for assigning me. What's the deadline to solve this issue?

**Comment by iluwatar** [comment]
I'm not too strict, but if you would like to participate in Hacktoberfest, better do it during this month

**Comment by shivu2002a** [comment]
Yeah sure. Thank you.

**Comment by shivu2002a** [comment]
@iluwatar Hi. This pattern falls under the Relational-Structural design patterns but this category is not on the list of [categories and tags](https://github.com/iluwatar/java-design-patterns/wiki/07.-Categories-and-Tags), but there is a Structural pattern. I needed your suggestion regarding this and also about the tag that should be mentioned for this pattern. Thank you.

**Comment by shivu2002a** [comment]
Need to be reviewed #2164

**Comment by shivu2002a** [comment]
Need to be reviewed #2164

**Comment by shivu2002a** [comment]
@iluwatar #2164 Need to be reviewed

**Comment by iluwatar** [comment]
@shivu2002a, please address the review comments

**Comment by shivu2002a** [comment]
@iluwatar I've made a commit saying 'adding suggested changes'.
