### ISSUE TITLE
Gateway pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1297]
https://stackoverflow.com/questions/4422211/what-is-the-difference-between-facade-and-gateway-design-patterns

**Comment by kelumsampath** [comment]
Hi @iluwatar! can I work on this issue?

**Comment by iluwatar** [comment]
Please go ahead @kelumsampath

**Comment by shibicr93** [comment]
Hello @iluwatar , I can work on this pattern if there are no takers :-)

**Comment by iluwatar** [comment]
All right, it's yours @shibicr93

**Comment by FinnS-F** [comment]
Hi, I would like to help out. Could I work on this issue?

**Comment by FinnS-F** [comment]
Could you review Pull Request https://github.com/iluwatar/java-design-patterns/pull/2734?
I've implemented the gateway pattern based on my own interpretation. By the way, this is my first PR in an open-source project so I may need some advice and know where I can enhance my code.
