### ISSUE TITLE
Identity Map pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1299]
https://www.sourcecodeexamples.net/2018/04/identity-map-pattern.html
https://en.wikipedia.org/wiki/Identity_map_pattern

**Comment by SuperNovaExtrem** [comment]
Can I take this? I can probably finish this before this Sunday.

**Comment by SuperNovaExtrem** [comment]
@iluwatar Can I take this? I can probably finish this before this Sunday.

**Comment by ohbus** [comment]
⭐ Sure thing! Thanks for your interest in our project 😃

**Comment by DhavalsinhChavda** [comment]
Hello @iluwatar, @ohbus and @SuperNovaExtrem, I read the links you provided in the issue and I would like to work on this issue.
I found that pull request #1773 already made for this and it is inactive from some time. 
So if this issue is available can I work on this ?

**Comment by iluwatar** [comment]
Closed https://github.com/iluwatar/java-design-patterns/pull/1773 due to inactivity. @DhavalsinhChavda the issue is now assigned to you, please proceed.

**Comment by DhavalsinhChavda** [comment]
Sure @iluwatar, I will start working on this.

**Comment by u7275858** [comment]
Hey @iluwatar I would like to work on this pattern. Do you mind assigning it to me.

**Comment by iluwatar** [comment]
Ok @u7275858
