### ISSUE TITLE
Mapper pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1303]
https://books.google.fi/books?id=vqTfNFDzzdIC&pg=PA473#v=onepage&q&f=false

**Comment by bravogalano** [comment]
@iluwatar Hi, can I take this issue?

**Comment by ohbus** [comment]
⭐ Sure thing! Thanks for your interest in our project 😃 

✔️ Please mention a 📆 timeline 🕙 for when can we expect 🤔 a Pull Request against this issue.

**Comment by bravogalano** [comment]
I suppose tomorrow I can make a pull request.

**Comment by shibicr93** [comment]
Hello @iluwatar , I'd like to work on this issue. If assigned, I can open a PR in 2 days.

**Comment by iluwatar** [comment]
Assigned to you @shibicr93

**Comment by shibicr93** [comment]
to be fixed in https://github.com/iluwatar/java-design-patterns/pull/2064.
