### ISSUE TITLE
Metadata Mapping pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1304]
https://www.sourcecodeexamples.net/2018/04/metadata-mapping-pattern.html

**Comment by castleKing1997** [comment]
I want to work on this. 
Please assign it to me if you think it's still a valuable issue.

**Comment by iluwatar** [comment]
Oh yes, it's valuable and seems to be quite easy to demonstrate with Hibernate if you choose. Please go ahead, @castleKing1997.

**Comment by castleKing1997** [comment]
@iluwatar please review #1932
