### ISSUE TITLE
Optimistic Offline Lock pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1306]
https://books.google.fi/books?id=vqTfNFDzzdIC&pg=PA416#v=onepage&q&f=false

**Comment by MathewJaniec** [comment]
Hey @iluwatar, I would like to help with this issue.

**Comment by iluwatar** [comment]
Thanks @MathewJaniec, please go ahead

**Comment by iluwatar** [comment]
@MathewJaniec, the pull request is still a draft and the build is failing.

**Comment by Regyl** [comment]
Hi @iluwatar !
Could I take this?

**Comment by Regyl** [comment]
Please, it sounds like a really interesting topic @iluwatar 👉 👈

**Comment by iluwatar** [comment]
Closing this as completed. We have another related issue still open, see https://github.com/iluwatar/java-design-patterns/issues/1307
