### ISSUE TITLE
Registry pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1310]
https://www.martinfowler.com/eaaCatalog/registry.html
https://stackoverflow.com/questions/16744424/whats-the-difference-between-singleton-and-registry-design-pattern
https://wiki.c2.com/?RegistryPattern

**Comment by viveksb007** [comment]
Hi @iluwatar 
I would like to work on it.

**Comment by iluwatar** [comment]
Ok @viveksb007

**Comment by viveksb007** [comment]
Hi @iluwatar,

I understood that Registry Pattern is similar to `Multiton` pattern, the only difference is no restrictions on numbers of objects.
In simple words, it stores <key, object> and there is no restriction on number of objects stored.

So I am thinking of creating a `CustomerRegistry` which will store customer objects (with `customerId` as key) and provide a global access to them. It requires adding/registering the customer object in the registry. For that I was thinking of creating a `CustomerFactory` which would create a `Customer` object and add it to registry. And anyone can get customer object by giving a `customerId` to registry. 

Wanted to clarify is it good adding a `Factory` to create customer object as I don't want any knowledge of registry inside the `Customer` object and don't want to manually add customer object to registry.

Any inputs would be helpful. 
Thanks!!

**Comment by iluwatar** [comment]
I've understood that typically Registry pattern is implemented with separated interface and implementation. Basically there's two methods in the registry object: One to add objects to the registry and another to query them. It's also good to demonstrate how testing is handled in the pattern. To your question whether Factory should be used or not, I would not create one. I think initializing the registry can be simply handled when the program starts i.e. calling something like `addCustomer` multiple times.
