### ISSUE TITLE
Serialized LOB pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1314]
https://martinfowler.com/eaaCatalog/serializedLOB.html
https://www.youtube.com/watch?v=NnT1iZuSlR4

**Comment by gdjs2** [comment]
Hey I’d like to try on this

**Comment by ohbus** [comment]
> Hey I’d like to try on this

I believe a PR has already been submitted by @tao-ny.

**Comment by ohbus** [comment]
Under Construction by @tao-ny

**Comment by u6949604** [comment]
Hi, I would like to work on this issue. Could I please be assigned?

**Comment by iluwatar** [comment]
Ok @u6949604
