### ISSUE TITLE
Single Table Inheritance pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1316]
https://www.martinfowler.com/eaaCatalog/singleTableInheritance.html
https://books.google.co.in/books?id=vqTfNFDzzdIC&pg=PA278&redir_esc=y#v=onepage&q&f=false

**Comment by amit2103** [comment]
@iluwatar  Can you assign this to me ? And if using H2 and Hibernate is fine I can quickly create a PR for this

**Comment by iluwatar** [comment]
Sounds good @amit2103, go ahead!

**Comment by Sooraj2002** [comment]
package com.sdnext.hibernate.tutorial.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

@Entity
@Table(name="VEHICLE")
@Inheritance(strategy=InheritanceType.SINGLE_TABLE) //Least normalisation strategy
public class Vehicle 
{
 @Id
 @GeneratedValue(strategy=GenerationType.AUTO)
 @Column(name="VEHICLE_ID")
 private int vehicleId;
 
 @Column(name="VEHICLE_NAME")
 private String vehicleName;
 
 public int getVehicleId() {
  return vehicleId;
 }
 public void setVehicleId(int vehicleId) {
  this.vehicleId = vehicleId;
 }
 public String getVehicleName() {
  return vehicleName;
 }
 public void setVehicleName(String vehicleName) {
  this.vehicleName = vehicleName;
 }
}

**Comment by iluwatar** [comment]
No sign of pull request, so I have to unassign you @amit2103. This issue is free for taking once again.

**Comment by iluwatar** [comment]
Ok @Tha-Davong, it's assigned to you

**Comment by iluwatar** [comment]
@Tha-Davong are you working on this?

**Comment by Tha-Davong** [comment]
@iluwatar Yeah, I will find some time to make changes as suggested

**Comment by u7275858** [comment]
Hello @iluwatar I would like to work on this issue.

**Comment by ved-asole** [comment]
Hi @iluwatar, I would like to work on the above PR. Please assign me the ticket.

**Comment by ved-asole** [comment]
Hi @iluwatar, is it fine if I use a Spring Boot project for the pattern or only simple Maven project is allowed? I'm asking the above question because all other patterns seems to be normal Maven project.

**Comment by iluwatar** [comment]
Spring Boot is fine. I think it has been used in some of the other patterns as well.

**Comment by ved-asole** [comment]
Thanks for confirming @iluwatar. I will work on it and will add it soon.

**Comment by ved-asole** [comment]
Hi @iluwatar, could you please review and approve my PR?
