### ISSUE TITLE
Table Module pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1319]
https://inviqa.com/blog/architecture-patterns-domain-model-and-friends

**Comment by tao-sun2** [comment]
Could I take this？ @iluwatar

**Comment by ohbus** [comment]
Sure thing @tao-sun2 

Please mention a timeline for when can we expect a PR against this issue.

**Comment by tao-sun2** [comment]
I will finish this issue within a week.
