### ISSUE TITLE
Inheritence in Command pattern

### ISSUE THREAD

**Issue by ravening** [iluwatar/java-design-patterns#1324]
I see that the `Command` is a class instead of `interface` and all the target actions extends this class.
Typically `Command` should be interface and the targets should implement the interface.
So should we rewrite the command pattern to implement interface rather than using inheritance?

**Comment by iluwatar** [comment]
Yes, I agree that would be the typical scenario and in this case it would suit the example fine.

**Comment by iluwatar** [comment]
@ravening let's leave the issue open if somebody wants to implement it

**Comment by ravening** [comment]
@iluwatar I can work on it if you are ok with it.
Should I write separate classes/interfaces or rewrite the existing abstract classes with interfaces?

**Comment by iluwatar** [comment]
I think you can modify the existing
