### ISSUE TITLE
Anti-Corruption Layer pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1325]
https://docs.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer

**Comment by Priya103** [comment]
I have gone through some of docs/blogs of Anti corruption layer.I would love to create sample project for Anti corruption layer.Can you please assign me this issue?

**Comment by ohbus** [comment]
> I have gone through some of docs/blogs of Anti corruption layer.I would love to create sample project for Anti corruption layer.Can you please assign me this issue?

Go ahead @Priya103.

Please mention an expected date of your Pull Request.

Looking forward to your contribution.

**Comment by Priya103** [comment]
Thank you... i am targeting for mid of jan

**Comment by Priya103** [comment]
I kind of stuck in other issues ... will try to raise pr in 2nd week of march

**Comment by ohbus** [comment]
No problem.

Thank you for letting us know.

Regards,
<https://subho.xyz>

**Comment by iluwatar** [comment]
This doesn't look like cloud-only pattern. I think it's a generic microservice pattern and we should implement it.

**Comment by besok** [comment]
Hi there!
I would like to take it on. 
But, presumably, I will do that in a couple of weeks gap

**Comment by besok** [comment]
@iluwatar or @ohbus.
What do I need to do to push forward the current pr?
