### ISSUE TITLE
Asynchronous Request-Reply pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1326]
https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply

**Comment by ravening** [comment]
I can work on this

**Comment by iluwatar** [comment]
Yes @ravening

**Comment by jporwal05** [comment]
@ravening I can help if you would like. I am new to this project and would like to contribute. Do let me know.

**Comment by ravening** [comment]
@iluwatar sorry didnt get time to work on this

**Comment by iluwatar** [comment]
This issue is looking for contributor once again

**Comment by Linly1080** [comment]
Hi, I'd like to work on this issue. Could it be assigned to me if still available?

**Comment by iluwatar** [comment]
Yes @Linly1080, it's all yours

**Comment by Linly1080** [comment]
@iluwatar sorry, I have no time to do the work now.
