### ISSUE TITLE
Claim-Check pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1329]
https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check
Please notice that this is a cloud pattern and should be implemented using cloud technologies (see https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections)

**Comment by Shrirang97** [comment]
Can you assigned this to me? I have already worked upon Azure Cloud Technologies by using this pattern.

**Comment by iluwatar** [comment]
Yes @Shrirang97 it's now assigned to you

**Comment by Shrirang97** [comment]
I have written code and readme file for the above pattern. Please check the PR.
