### ISSUE TITLE
Gateway Aggregation pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1331]
https://docs.microsoft.com/en-us/azure/architecture/patterns/gateway-aggregation
Please notice that this is a cloud design pattern and should be implemented using cloud technologies (see https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections)

**Comment by sharoha** [comment]
Hi @iluwatar, first time here. For this issue, I wanted to clarify if this is a new pattern that you were thinking to introduce in the project?

**Comment by ohbus** [comment]
> Hi @iluwatar, first time here. For this issue, I wanted to clarify if this is a new pattern that you were thinking to introduce in the project?

Yes, please let us know if you are willing to work on this.

Thanks for your interest.

**Comment by sharoha** [comment]
Yeah sure. Could you please assign it to me?

**Comment by ohbus** [comment]
> Yeah sure. Could you please assign it to me?

⭐ Sure thing! Thanks for your interest in our project 😃 

✔️ Please mention a 📆 timeline 🕙 for when can we expect 🤔 a Pull Request against this issue.

**Comment by sharoha** [comment]
It will take 2weeks for me, trying to get some time out from work. Will that work?

**Comment by iluwatar** [comment]
This issue is free for taking again.
