### ISSUE TITLE
Gateway Offloading pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1332]
https://docs.microsoft.com/en-us/azure/architecture/patterns/gateway-offloading
Please notice that this is a cloud design pattern that should be implemented using cloud technologies (see https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections)

**Comment by viveksb007** [comment]
Hey @iluwatar 
I would like to work on it.

**Comment by iluwatar** [comment]
Ok @viveksb007
