### ISSUE TITLE
Geode pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1334]
https://docs.microsoft.com/en-us/azure/architecture/patterns/geodes
Please notice that this is a cloud design pattern that should be implemented using cloud technologies (see https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections)

**Comment by Borumer** [comment]
I'll take this up

**Comment by aayushbest** [comment]
Hi @iluwatar  I want give this a try. :)

**Comment by iluwatar** [comment]
Ok @aayushbest go ahead

**Comment by knguyen100000010** [comment]
@iluwatar I can work on this.

**Comment by iluwatar** [comment]
Nice, go ahead @knguyen100000010, and please notice that it should be implemented using a cloud platform
