### ISSUE TITLE
Sequential Convoy pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1335]
https://docs.microsoft.com/en-us/azure/architecture/patterns/sequential-convoy
Please notice that this is a cloud design pattern that should be implemented using cloud technologies (see https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections)

**Comment by Shrirang97** [comment]
Assigned it to me!

**Comment by iluwatar** [comment]
Ok @Shrirang97

**Comment by winiga-lab** [comment]
@Shrirang97 We have a school class project on this one would you like to let me work with you on it ?

**Comment by iluwatar** [comment]
This issue is free for taking again.
