### ISSUE TITLE
xUnit test patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1337]
http://xunitpatterns.com/List%20of%20Patterns.html

http://martinfowler.com/books/meszaros.html

**Comment by erikaya** [comment]
@iluwatar can I get this issue?

**Comment by iluwatar** [comment]
@erikaya yes, but since there are so many test patterns here we need to think how to implement it. Any suggestions?

**Comment by iluwatar** [comment]
![Image](https://user-images.githubusercontent.com/582346/205487312-28f740c9-6ff3-4ecf-8050-08db4a00e9c0.png)

**Comment by sarswat001** [comment]
Hi @iluwatar , Can you please explain what is the task here?

**Comment by iluwatar** [comment]
Demonstrate the xUnit test patterns, but I think this should be split up
