### ISSUE TITLE
Guaranteed Delivery (EIP)

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#138]

**Comment by stephen-lazarionok** [comment]
Can help with this. Please let me know if it's okay with you.

**Comment by iluwatar** [comment]
First you should be aware that we have agreed to implement the EIPs using Apache Camel. To see the full discussion see #93 and #82.

If you are still willing to help, you are welcome to proceed.

**Comment by stephen-lazarionok** [comment]
Okay, understood. I will work on this pattern using Apache Camel.
