### ISSUE TITLE
Functional implementation of Command pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1468]
Command pattern has been implemented in traditional style using classes. In modern Java it's possible to pass around method references. Command pattern example should be amended to demonstrate modern style implementation.

**Comment by ravening** [comment]
@iluwatar I just made changes to the command pattern to use interfaces rather than abstract classes. I can probably work on this also. Please assign to me if you are ok with it

**Comment by iluwatar** [comment]
Ok @ravening

**Comment by IsuruAriyarathne** [comment]
can you assign this to me. I will comeup with a examle.

**Comment by ravening** [comment]
> can you assign this to me. I will comeup with a examle.
> 
> 

There's already a PR for it
