### ISSUE TITLE
Functional implementation of Strategy pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1469]
Strategy has been implemented using Java classes. In modern Java about the same can be achieved by passing methods. Let's amend the Strategy example with functional style implementation.

**Comment by maheshsv** [comment]
Please assign to me thx

**Comment by iluwatar** [comment]
Ok @maheshsv

**Comment by maheshsv** [comment]
Do we need to implement Strategy Pattern using Lambda Expressions in Java 8

**Comment by iluwatar** [comment]
Yes, that would be great addition to this pattern example

**Comment by maheshsv** [comment]
ok can i create a branch and work on it, ?

**Comment by iluwatar** [comment]
Go ahead @maheshsv

**Comment by ignite1771** [comment]
Hi, I want to solve this issue if it is still open.
May I? @iluwatar

**Comment by iluwatar** [comment]
There's a pull request from @Tubaleviao but haven't heard of him for a while

**Comment by Tubaleviao** [comment]
Go ahead @ignite1771 , I'm in a quest right now

**Comment by ignite1771** [comment]
Ok, I will work on this and send a PR to fix this issue.

**Comment by iluwatar** [comment]
Thanks @ignite1771, looking forward to it
