### ISSUE TITLE
Factory pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1477]
At the moment we have Factory Method, Abstract Factory and Factory Kit but we are lacking basic Factory. Let's implement that in this ticket.

**Comment by samilAyoub** [comment]
@iluwatar do you mean simple Factory?

**Comment by iluwatar** [comment]
Yes @samilAyoub, would you like to implement that?

**Comment by samilAyoub** [comment]
@iluwatar yes, i'll give it a try
