### ISSUE TITLE
Update/replace Naked Objects example

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1483]
Naked Objects example has been implemented using a very old Apache Isis version. In this task we'll replace it with an example generated using the latest Isis.

Apache Isis framework: https://isis.apache.org/

**Comment by dieuph** [comment]
Hi @iluwatar, I'll take it up.

**Comment by iluwatar** [comment]
Thanks @dieuph, go ahead!

**Comment by berlincho** [comment]
@dieuph, did you fix the issue? Thanks.

**Comment by ohbus** [comment]
Thank you for your efforts!

**Comment by berlincho** [comment]
@ohbus Although the current example uses the old version of Apace isis, could you share the info of how to run it?

**Comment by iluwatar** [comment]
Good question. Previously we could follow the instructions at https://github.com/iluwatar/java-design-patterns/blob/master/naked-objects/README, but it seems that they removed it from the website.

**Comment by berlincho** [comment]
@iluwatar Thanks for your reply. I check the webpage archive (http://web.archive.org/web/20150717233428/http://isis.apache.org/guides/ug.html#3.-getting-started). 
It seems that the existing example uses the sample application in the above link. I will replace it with the newer Apache isis version.

**Comment by iluwatar** [comment]
Great @berlincho, I'm looking forward to the PR

**Comment by chirag-cyber** [comment]
hi @iluwatar can you this task to me?

**Comment by iluwatar** [comment]
Thanks @chirag-cyber, this issue is much anticipated
