### ISSUE TITLE
Upgrade mockito

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1486]
The current version declared in the main `pom.xml` is very old:

```
<mockito.version>1.10.19</mockito.version>
```

Let's try to upgrade it to a newer version in this task.

**Comment by amit1307** [comment]
I can look into it if you can assign it to me please.

**Comment by iluwatar** [comment]
Ok @amit1307

**Comment by charlesfinley** [comment]
If you are going to upgrade Mockito, you should probably consider upgrading the entire repo to JUnit 5. It will be a big update but it's worthwhile as JUnit 5 has some nice improvements.

**Comment by amit1307** [comment]
Hey, sorry I was out of the town for few days and came back this week. Just catching up the stuff. I should get back with some progress soon. Hope that's fine.
