### ISSUE TITLE
Message Router (EIP)

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#149]

**Comment by treslines** [comment]
hi @iluwatar! i have a router implementation that i would like to share with you! how can i do that. fork and create a pull request?

**Comment by iluwatar** [comment]
Hello @treslines and thank you for the proposal. We have agreed to implement the EIPs based on Apache Camel. See discussion in #82 and #93. If you are still interested to work on this please see the instructions in `README.md` section "How to contribute".
