### ISSUE TITLE
Use the same JUnit version everywhere

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1500]
At the moment there are some modules that are still using JUnit 4. Most of the codebase uses JUnit 5, but even with that there are different versions. For example `unit-of-work` and `partial-response` declare their own versions.

In this ticket let's try to apply the same version of JUnit 5 everywhere upgrading from JUnit 4 where needed.

## This issue has been partially addressed using #1542 and #1668

Tests from two modules [**serverless**](https://github.com/iluwatar/java-design-patterns/tree/master/serverless) and [**naked-objects**](https://github.com/iluwatar/java-design-patterns/tree/master/naked-objects) are not being executed.

Respective issues have been opened for resolving the tests in favour of these two modules.
- [x] #1667 against [**serverless**](https://github.com/iluwatar/java-design-patterns/tree/master/serverless)
- [ ] #1669 against [**naked-objects**](https://github.com/iluwatar/java-design-patterns/tree/master/naked-objects)

Resolving these two issues should close this [current issue](https://github.com/iluwatar/java-design-patterns/issues/1500)

**Comment by stefanbirkner** [comment]
@ToxicDreamz FYI: I created #1505 which removes the dependency of `subclass-sandbox` to Rule, which is a JUnit 4 only feature.

**Comment by ToxicDreamz** [comment]
@stefanbirkner Okay, thank you for the heads up. I'll wait for @iluwatar to merge that PR, until I continue with that module.

**Comment by iluwatar** [comment]
It's merged now

**Comment by mookkiah** [comment]
Using JUnit 5 in Trampoline module. PR #1529 created.

**Comment by sgarg5794** [comment]
I want to work on this issue if its is still unassigned .

**Comment by iluwatar** [comment]
Ok @sgarg5794

**Comment by charlesfinley** [comment]
I'm working on updating all the modules to JUnit5 right now. @ohbus

**Comment by ohbus** [comment]
Sure @charlesfinley you're good to go!

**Comment by charlesfinley** [comment]
> Sure @charlesfinley you're good to go!

Sorry I opened a new PR for this - #1668

**Comment by ohbus** [comment]
@charlesfinley no need to be sorry for 😄  It is easier for us to review code in smaller chunks and this helps a lot 💯 

Thank you so much for your help!

**Comment by charlesfinley** [comment]
> @charlesfinley no need to be sorry for 😄 It is easier for us to review code in smaller chunks and this helps a lot 💯
> 
> Thank you so much for your help!

This issue should probably be closed since the PR was merged and we have 2 new issues identifying the only modules lacking JUnit5.

**Comment by ohbus** [comment]
@charlesfinley great work!

We will close this issue for sure.

**Comment by ohbus** [comment]
This issue has been partially addressed using #1542 and #1668 thanks to @charlesfinley 

Tests from two modules [**serverless**](https://github.com/iluwatar/java-design-patterns/tree/master/serverless) and [**naked-objects**](https://github.com/iluwatar/java-design-patterns/tree/master/naked-objects) are not being executed.

Respective issues have been opened for resolving the tests in favour of these two modules.
- [ ] #1667
- [ ] #1669

Resolving these two issues should close this [current issue](https://github.com/iluwatar/java-design-patterns/issues/1500)

**Comment by anuragagarwal561994** [comment]
@iluwatar let me know how can I help with this, I am confused about the status of the what has been resolved and what is pending.

**Comment by iluwatar** [comment]
Thanks for asking @anuragagarwal561994. I think the only remaining issue is that naked objects pattern still uses JUnit 4. Resolving this is covered by issues https://github.com/iluwatar/java-design-patterns/issues/1669 and https://github.com/iluwatar/java-design-patterns/issues/1683. I think we should close this task.
