### ISSUE TITLE
Introduce Lombok to get rid of boilerplate

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1503]
[Project Lombok](https://projectlombok.org/) enables using of annotations to generate code. Let's introduce it to the project to reduce amount of boilerplate. In the first stage we could utilize the simplest annotations like `@Getter @Setter @Slf4j @ToString @EqualsAndHashCode`. I think the more advanced ones sacrifice code readability and should be avoided.

**Comment by amit1307** [comment]
Hello @iluwatar, I can work on this issue if its still unassigned?

**Comment by iluwatar** [comment]
Sure @amit1307, go ahead

**Comment by amit1307** [comment]
Sorry for the delay, have just started on this issue. Since it's going to be a big change so I am thinking to do it in smaller chunks, please let me know if that's okay and here is the first PR: https://github.com/iluwatar/java-design-patterns/pull/1527

**Comment by ohbus** [comment]
Can I take it up @amit1307

**Comment by amit1307** [comment]
Sorry @ohbus it's in progress on my side and I am kind of in the middle of it so not sure it would be a good idea for you to take it up.

**Comment by carousel** [comment]
Hi everybody,

I am very familiar with Lombok and I use it often. I can work on this issue @iluwatar so feel free to assign issue to me also.

**Comment by ohbus** [comment]
> Sorry @ohbus it's in progress on my side and I am kind of in the middle of it so not sure it would be a good idea for you to take it up.

Sure No problem. Go ahead!

**Comment by sgarg5794** [comment]
Hi @iluwatar ,
I have 3 years of work experience in micro services development where i have worked on lombok , Can i take up this issue if it is still unassigned?

**Comment by va1m** [comment]
Hi @iluwatar,
Check the PR, please.

**Comment by sirNikolai** [comment]
@iluwatar I am not sure if this is honestly a good step to take. Lombok reduces boilerplate but kills legibility quite a bit, especially those unfamiliar with Lombok. One of the reasons I liked this repo is because it was very straightforward with vanilla Java, this would hinder it. Although I understand it does make writing code a little more tedious.

**Comment by va1m** [comment]
> @iluwatar I am not sure if this is honestly a good step to take. Lombok reduces boilerplate but kills legibility quite a bit, especially those unfamiliar with Lombok. One of the reasons I liked this repo is because it was very straightforward with vanilla Java, this would hinder it. Although I understand it does make writing code a little more tedious.

Ah, common! 😟

**Comment by iluwatar** [comment]
@sirNikolai that's a valid concern and I have thought about it myself over the years. The thing is that there's more pros than cons and I think this will reduce the boilerplate significantly.

**Comment by sirNikolai** [comment]
@iluwatar But isn't the key point of the repo being a bit pedantic to understand the patterns? I may be missing your vision on this, so more looking at kinda getting the bigger picture than criticize, because what it ends up being from my POV is someone new stumbling on the repo but then having to backtrack and learn lombok (as some parts aren't that intuitive) to understand what's going on.

**Comment by iluwatar** [comment]
@sirNikolai that's a valid point and certainly one of the downsides. However I think getting the basics of Lombok is quite easy. Our audience is programmers and we can provide good instructions. As you said, the point is to teach about design patterns and using Lombok makes the examples clearer by removing large amounts of repeating non-pattern related code.

**Comment by vivekvara** [comment]
@iluwatar Limited use of Lombok annotations could improve readability and easy to understand as well based on name of annotations ie. @Data, @Getter, @Setter, @ToString, @Log. I found other annotations ie. @SneakyThrows, @Sychronized, @Builder are hard to understand for those who are not familiar with Lombok.

**Comment by sirNikolai** [comment]
yeah that scans to me, and definitely agree on the triviality (and lack thereof) of some of the lombok operators. Guess it would be a judicial case of what should and shouldn't be done that way.

**Comment by iluwatar** [comment]
I started to collect the "allowed" Lombok annotations to this list: https://github.com/iluwatar/java-design-patterns/wiki/18.-Lombok Let me know if there's something missing or something that should be disallowed.

**Comment by vivekvara** [comment]
@iluwatar thanks for creating Wiki for the same. I think @NonNull should be allowed. Please check if you can add it.

**Comment by iluwatar** [comment]
Thanks @vivekvara, added that one

**Comment by iluwatar** [comment]
Thanks to @va1m and https://github.com/iluwatar/java-design-patterns/pull/1560, we were able to significantly reduce the amount of boilerplate in the project. Here are the numbers from the pull request:

![image](https://user-images.githubusercontent.com/582346/111030079-195c8d00-8409-11eb-9251-d39ee66bcc9c.png)

**Comment by ltyocg** [comment]
I really think lombok is not a good choice.
