### ISSUE TITLE
Improvements needed to Circuit Breaker

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1510]
I suggest we make several improvements to the Circuit Breaker pattern:
- Make `CircuitBreaker` more generic so that it doesn't need to be modified when applied to new services (see https://java-design-patterns.com/principles/#openclosed-principle)
- Make `MonitoringService` call couple of different remote services to demonstrate usage of `CircuitBreaker`
- Make `CircuitBreaker` delay algorithm configurable
- Get rid of the eternal loop in `App.java` and add `AppTest.java` to run the example
- Introduce interfaces and avoid depending on concrete implementations

**Comment by swarajsaaj** [comment]
Can I pick this one?

**Comment by iluwatar** [comment]
Thanks @swarajsaaj, please go ahead

**Comment by swarajsaaj** [comment]
@iluwatar Here is my proposed approach for the requested improvements, please provide your thoughts : 
1. `CircuitBreaker` will be refactored to an interface, with a `DefaultCircuitBreaker` implementation (with current time-based logic)
2. Introduce a `RemoteService` interface with `call()` method, which will be injected in `CircuitBreaker` implementation class and can be executed for any `RemoteService` implementation. `CircuitBreaker` will act as a fault tolerant wrapper on `RemoteService` implementations
3. Provide two implementations of  `RemoteService` interface as 'DelayedRemoteService` and `QuickRemoteService` to show interaction with remote services. DelayedRemoteService will accept the delay parameter.
4. Remove the infinite while loop in App.java and call all services from monitoring service with certain delays (Thread sleep), showing the CLOSED->HALF_CLOSED->OPEN->CLOSED state worflow of CircuitBreaker.
