### ISSUE TITLE
Data transfer object pattern using Enums

### ISSUE THREAD

**Issue by siavashsoleymani** [iluwatar/java-design-patterns#1569]
I'm going to implement a DTO pattern using java Enums.
In this way the code is going to be more **Type safe**, **Consistent Syntax**, **Consistent Semantics**, and more **Readable & Maintainable**.

**Comment by ohbus** [comment]
@siavashsoleymani Please provide us some solid references to this pattern.

**Comment by iluwatar** [comment]
Created follow-up ticket https://github.com/iluwatar/java-design-patterns/issues/1617
