### ISSUE TITLE
SLOB design pattern

### ISSUE THREAD

**Issue by LizMoreno** [iluwatar/java-design-patterns#1596]
Could you help me with SLOB design pattern?

https://martinfowler.com/eaaCatalog/serializedLOB.html

thanks!

**Comment by StefanoFibbi** [comment]
I would like to work on it

**Comment by ohbus** [comment]
@StefanoFibbi I have assigned the issue to you. **Good Luck!**

Sorry for being late to reply we have been keeping a little busy.

@LizMoreno Thank you for your suggestion.

**Comment by ohbus** [comment]
@StefanoFibbi Please let us know of the timeline and when can we expect a Pull Request against this.

Looking forward to you.
Thanks.

**Comment by berlincho** [comment]
@StefanoFibbi, are you still working on this issue? Thanks.

**Comment by ohbus** [comment]
Due to inactivity from @StefanoFibbi .

This issue is again free to be taken.

**Comment by dctrue2** [comment]
I will implement the pattern with @berlincho.

**Comment by u6810889** [comment]
Hi @iluwatar , can I work on this issue?

**Comment by iluwatar** [comment]
Go ahead @u6810889

**Comment by iluwatar** [comment]
@u6810889, are you planning to complete this?

**Comment by u6810889** [comment]
Sorry I don't think I can work on the issue at the moment

**Comment by KishalayP** [comment]
Hi @iluwatar, can I work on this issue?

**Comment by KishalayP** [comment]
Hi @iluwatar have created the PR #2795 for this issue, please review.
