### ISSUE TITLE
careless grammer mistake in  zh/decorator/README.md

### ISSUE THREAD

**Issue by HKTangShuo** [iluwatar/java-design-patterns#1600]
line 36:程序mple. First of all we have a simple troll implementing the troll interface
should be  程序example. First of all we have a simple troll implementing the troll interface
Thank you!

**Comment by HKTangShuo** [comment]
line 13 : 包装器 should be 装饰器 。
装饰器 is well known than 包装器  in Chinese

**Comment by iluwatar** [comment]
@xiaod-dev could you check this issue?

**Comment by xiaod-dev** [comment]
> line 13 : 包装器 should be 装饰器 。
> 装饰器 is well known than 包装器 in China

Thank your feedback. the line 36 was corrected, and about the line13, the  original text is " Wrapper", not "decorator", so there is nothing go wrong with "包装器".
