### ISSUE TITLE
Word mistake in factory/README.md

### ISSUE THREAD

**Issue by warp125** [iluwatar/java-design-patterns#1601]
![image](https://user-images.githubusercontent.com/48073115/100273344-f44e2680-2f9f-11eb-8f9f-393c4667932f.png)
Lines 83-84: Could not find CarSimpleFactory. Isn't it CarsFactory?

**Comment by Priya103** [comment]
I am new to this. Can I take up this?

**Comment by iluwatar** [comment]
@ohbus when handling issues set the correct labels and on close set the milestone

**Comment by ohbus** [comment]
> @ohbus when handling issues set the correct labels and on close set the milestone

Thank you for this guiding me on this.

And Hacktoberfest is over, I guess we should remove this tag from the repository  or stop using it for the time being.

**Comment by iluwatar** [comment]
@ohbus before you know it, it will be the next Hactoberfest, so I would just leave it there :)
