### ISSUE TITLE
Publish-Subscribe Channel (EIP)

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#161]

**Comment by npathai** [comment]
This pattern is similar in intent to Observer pattern. 

Observer
-------------
 - Is used for same process events
 - Subscriber is aware of the publisher's existence
 - It is one (pub) to many (subs)
 - Publisher fires the on change events
 - Events are fired in sync
 - Implementation: `Observable` and `Observer` classes in Java

Pub-Sub
-------------
 - Used when there are two different processes
 - Optionally there is topic based or content based filter
 - There is a middle layer (queuing layer involved)
 - Publishers and subscribers don't know about existence of each other

**Comment by JaXt0r** [comment]
A friend of mine is very pleased with this pattern. So it's about time to present him an example in Java.

I'll offer some testable code these days.

**Comment by kunalnangia** [comment]
What is going on here?

**Comment by JaXt0r** [comment]
I'm working on an implementation of this pattern. If you like, please alter the ticket labels.

**Comment by iluwatar** [comment]
Please note https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections

So you would have to implement the pattern using Apache Camel and then document how the framework implements this.

**Comment by JaXt0r** [comment]
Thanks for the information. Yeah I'll do it. Seems to be much smarter to implement it with Apache Camel then on my own.

**Comment by npathai** [comment]
Ok I will alter the labels.

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/publisher-subscriber
