### ISSUE TITLE
Page Factory Design Pattern 

### ISSUE THREAD

**Issue by ohbus** [iluwatar/java-design-patterns#1615]
### [Page Factory Design Pattern (Enhanced POM)](https://www.seleniumeasy.com/selenium-tutorials/page-factory-pattern-in-selenium-webdriver)

- https://www.seleniumeasy.com/selenium-tutorials/page-factory-pattern-in-selenium-webdriver
- https://www.toptal.com/selenium/test-automation-in-selenium-using-page-object-model-and-page-factory

**Comment by ohbus** [comment]
@osandadeshan is working on this.

**Comment by iluwatar** [comment]
@ohbus I don't think it's a valid design pattern. See the discussion in https://github.com/iluwatar/java-design-patterns/pull/1552
