### ISSUE TITLE
Fan-Out/Fan-In pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1627]
https://dzone.com/articles/understanding-the-fan-out-fan-in-api-integration-p

**Comment by lodenrogue** [comment]
Would this be in the context of HTTP or a more general context?

**Comment by lodenrogue** [comment]
If my understanding is correct the interface would be something like this?

```
fanOutFanIn.fan(listOfRequests, responseConsumer);
```

Where ```listOfRequests``` is a collection of long running processes that return a callback
And ```responseConsumer``` is a Consumer that is given a single result object and implements some action to be taken on that result object

**Comment by karthikbhat13** [comment]
@lodenrogue I am not sure if you are taking this up. If not, @iluwatar Can I try this out?

Thanks!

**Comment by lodenrogue** [comment]
Go for it. I just wanted to clarify the pattern

**Comment by ohbus** [comment]
> @lodenrogue I am not sure if you are taking this up. If not, @iluwatar Can I try this out?
> 
> Thanks!

⭐ Sure thing! Thanks for your interest in our project 😃 

✔️ Please mention a 📆 timeline 🕙 for when can we expect 🤔 a Pull Request against this issue.
