### ISSUE TITLE
Semaphore is not a java design pattern

### ISSUE THREAD

**Issue by satur9nine** [iluwatar/java-design-patterns#1628]
Semaphore located at https://github.com/iluwatar/java-design-patterns/tree/master/semaphore should be removed. A semaphore is a standard synchronization mechanism that is already part of the Java standard libraries: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Semaphore.html

Obviously this project shouldn't include custom implementations of other standard data structures and synchronization mechanisms like: hash maps, array lists (vector) or mutexes.

**Comment by iluwatar** [comment]
Good point, and I tend to agree with you. Semaphone and Mutex could be removed from the catalog.
