### ISSUE TITLE
Parameter Object idiom

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1638]
It's a simple workaround for Java not having default parameters:
http://dolszewski.com/java/java-default-parameters/

**Comment by richardmr36** [comment]
Can I work on this?

**Comment by iluwatar** [comment]
Go ahead @richardmr36

**Comment by richardmr36** [comment]
The link mentioned in the issue gives enough details I guess. It is easier to understand if you are aware about default parameters feature of JavaScript ES6. Let us know if you have any specific questions.

**Comment by richardmr36** [comment]
@iluwatar could you help me with the tool or IntelliJ plugin used to generate class diagram?

**Comment by iluwatar** [comment]
@richardmr36 there's brief explanation in https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

**Comment by richardmr36** [comment]
@iluwatar ucls file is not getting generated. Is there any other additional steps required for that?

**Comment by iluwatar** [comment]
@richardmr36 ucls file is not mandatory, and it's not autogenerated. Those are source files of [ObjectAid's UML plugin](https://www.objectaid.com/home). If you want to generate the UML diagram by hand for some reason, then that could be something to try.
