### ISSUE TITLE
Tests not being executed in serverless module

### ISSUE THREAD

**Issue by charlesfinley** [iluwatar/java-design-patterns#1667]
While upgrading other modules to JUnit 5, I noticed the tests for these 2 classes are not being executed during the build:

FindPersonApiHandlerTest.java
SavePersonApiHandlerTest.java

I tried a quick upgrade to JUnit 5 but these will take some time to refactor. 

Te replicate - remove the Junit dependency and replace with Junit-vintage-engine, or run the tests directly using your IDE. 

⚠️ This module requires knowledge of **AWS**

> This issue partially resolves #1500

**Comment by ohbus** [comment]
Thank you so much @charlesfinley for looking into this and helping us refactor our code.

**Comment by tan31989** [comment]
@ohbus is this being worked upon? Would love to fix this.

**Comment by ohbus** [comment]
> @ohbus is this being worked upon? Would love to fix this.

⭐ Sure thing! Thanks for your interest in our project 😃 

✔️ Please mention a 📆 timeline 🕙 for when can we expect 🤔 a Pull Request against this issue.

🤝  Looking forward to your contribution.
📖  Be sure to check out our [Wiki](https://github.com/iluwatar/java-design-patterns/wiki) section

**Comment by tan31989** [comment]
Sure @ohbus!
I have tested this locally as of now, I should be able to raise a Pull Request in another day.

**Comment by tan31989** [comment]
@ohbus have added the PR for now. Should I tag someone for review?

**Comment by ohbus** [comment]
> @ohbus have added the PR for now. Should I tag someone for review?

We mostly review PRs during the weekend and our free time.

And we always appreciate feedback on PRs and we value contributing to this repository for all kinds. So **`cc`** somebody for review for getting an insight on your code.

**Comment by tan31989** [comment]
Thanks, @ohbus for the update
