### ISSUE TITLE
License issue in MVVM pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1690]
In https://github.com/iluwatar/java-design-patterns/pull/1678 we merged the MVVM pattern using zkoss framework licensed under LGPL. We noticed the need to follow-up with some tasks related to handling the licensing issues correctly. In this issue let's fix

- [ ] Give prominent notice with each copy of the Combined Work that the Library is used in it and that the Library and its use are covered by this License.
- [ ] Accompany the Combined Work with a copy of the GNU GPL and this license document.

**Comment by iluwatar** [comment]
I would probably fix the first task by editing the `license-maven-plugin` configuration so that the license header is fetched from a local file instead. The local file could contain the normal MIT license and after that declaration about the deviant modules such as MVVM. The second task looks clear enough, just add the LGPL and GPL license files to the project root.

**Comment by jinishavora** [comment]
@iluwatar @ohbus Can I work on this?

**Comment by ohbus** [comment]
Go ahead!

**Comment by jinishavora** [comment]
@iluwatar @ohbus sorry, I still haven't submitted the PR. I am traveling this week so won't be able to submit it, but will surely be doing so by end of 2nd week of April.

**Comment by iluwatar** [comment]
That's ok @jinishavora, looking forward to your pull request after the trip.
