### ISSUE TITLE
Improve caching pattern code quality

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1694]
Here are some suggestions on how to improve the caching pattern implementation
- There is a lot of if-else code related to the `CachingPolicy` choice. Maybe we could use the strategy pattern to pick the policy we use.
- There are 2 database choices. The virtual database is the default one but one can configure the application to use MongoDB as well. Perhaps we could create an abstraction for the database implementation and get rid of if-else code in the `DbManager`.
- The logging output of the example is not very clear. I think it should be possible to see the log output and understand what's going on without consulting the code implementation.
- Exception handling is not very clear. Especially declaring that `connect()` throws `ParseException` seems odd and probably never happens.
- It would be great to have simple setup instructions for the MongoDB database choice

**Comment by jnayan1** [comment]
@iluwatar first timer here, can I get started with contributing to this issue?

**Comment by ohbus** [comment]
Sure thing!

Please mention a timeline when can we expect a PR against this.

**Comment by barathgdkrish** [comment]
Hi @ohbus and @jnayan1 - I'm a first timer too. Can I join to collaborate?

**Comment by ohbus** [comment]
> Hi @ohbus and @jnayan1 - I'm a first timer too. Can I join to collaborate?

Hi @barathgdkrish as this issue has been already assigned to @jnayan1 you can try picking up some other issues. Or you may want to contact the assigned person on this issue to talk to them and decide if they will be moving forward with it or not.

**Comment by barathgdkrish** [comment]
Thank you, sure I'll follow the same.

Regards,
Barath.
________________________________

**Comment by vrushofficial** [comment]
Hey @ohbus, @jnayan1 is still working on this? i'm gonna to pick this up.

**Comment by dchar** [comment]
Was this ever taken any further? I can maybe provide PR in the coming days.

Thanks,

**Comment by ohbus** [comment]
Looks like our contributors who were assigned to be inactive and no commits are showing in here as logs as it should according to our contributing guidelines.

So I would assign this to you @dchar. Looking forward to your PR in the coming weeks.

@jnayan1 and @barathgdkrish Please do let me know and try to contact @dchar in case you are looking to collaborate together.

**Comment by VictorZZZZ** [comment]
Hello!
I just now provided the PR
[Link to PR #1810](https://github.com/iluwatar/java-design-patterns/pull/1810)

I don't know if it OK, if the issue was not assigned to me. I just see that it is not moving almost 8 days after last assign.

**Comment by dchar** [comment]
This is partly complete from my end, was mainly tied finishing other work last week. It is okay to reassign to Victor if the PR looks complete. 

Thanks

**Comment by AJESH-CR** [comment]
@iluwatar Did we completed this issue or still in work in progress? Didn't see any activities so far.

**Comment by VictorZZZZ** [comment]
Here is my PR: https://github.com/iluwatar/java-design-patterns/pull/1810

**Comment by AJESH-CR** [comment]
I saw that, but that hasn't reviewed yet right?

**Comment by iluwatar** [comment]
The PR is under review.
