### ISSUE TITLE
Double Buffer Pattern Credits Link Not Found

### ISSUE THREAD

**Issue by sujithmenonp** [iluwatar/java-design-patterns#1703]
https://java-design-patterns.com/patterns/double-buffer/

Credits Link mentioned in the above page is not working -> https://java-design-patterns.com/patterns/double-buffer/[http://gameprogrammingpatterns.com/double-buffer.html](http://gameprogrammingpatterns.com/double-buffer.html)

**Comment by DEV-VRUPER** [comment]
Hello Team, My above PR updates the Readme.md file to re-direct the credits link to the correct URL . Please let me know if any additional details required.
