### ISSUE TITLE
Update next-generation circleci convenience images

### ISSUE THREAD

**Issue by ohbus** [iluwatar/java-design-patterns#1736]
The next-generation convenience images in this section were built from the ground up with CI, efficiency, and determinism in mind. Here are some of the highlights:

**Faster spin-up time** - In Docker terminology, these next-gen images will generally have fewer and smaller layers. Using these new images will lead to faster image downloads when a build starts, and a higher likelihood that the image is already cached on the host.

**Improved reliability and stability** - The current images are rebuilt practically every day with potential changes from upstream that we can’t always test fast enough. This leads to frequent breaking changes, which is not the best environment for stable, deterministic builds. Next-gen images will only be rebuilt for security and critical bugs, leading to more stable and deterministic images.

> https://circleci.com/docs/2.0/circleci-images/#next-generation-convenience-images
> https://hub.docker.com/u/cimg
> https://github.com/CircleCI-Public/cimg-overview
> https://hub.docker.com/r/cimg/openjdk
> https://discuss.circleci.com/tag/convenience-images

**Comment by sapsinh** [comment]
I want to work on this

**Comment by ohbus** [comment]
Thank you so much for your interest in this project!

We are happy to have you here.

Please mention an expected timeline for when can we expect  PR against this.

**Comment by sapsinh** [comment]
I will resolve this by the end of the next week.

**Comment by ohbus** [comment]
Currently facing problems due to misconfiguration of **`xvfb`** or there might be some other problem related to this.
