### ISSUE TITLE
Issue with all contributors badge in Readme.md file

### ISSUE THREAD

**Issue by DEV-VRUPER** [iluwatar/java-design-patterns#1747]
Observed that when we click on the `all contributors` badge on the project page , it does not re-direct us to the sections where all the project contributors are listed . 

![image](https://user-images.githubusercontent.com/30525467/117465715-df5fc100-af49-11eb-8a72-e0181a11478b.png)

**Possible fix will be to correct the URL for this badge inside the projects Readme.md file .**

**Comment by ohbus** [comment]
Thanks, @DEV-VRUPER for mentioning the problem.

There seems to be an error due to an additional hyphen at the end of the URL.

Please do let me know if you want to raise a PR for fixing this.

**Comment by DEV-VRUPER** [comment]
@ohbus   I have fixed it and raised the PR . Please could you review .

Thanks.
