### ISSUE TITLE
Create instructions for contributing pattern translations

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1755]
As suggested by @ohbus, we need to improve the instructions in our wiki to cover contributing pattern translations.

**Comment by ohbus** [comment]
@iluwatar Made some changes to https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

What do you suggest for https://github.com/iluwatar/java-design-patterns/wiki/15.-Support-for-multiple-languages

**Comment by iluwatar** [comment]
@ohbus Thanks for updating the contribution guidelines. I updated the latter page you mentioned, please check it out. Feel free to close this issue if we are happy.

**Comment by ohbus** [comment]
Thanks, @iluwatar for the much-needed improvement.

The changes Look Good To Me! 🎉
