### ISSUE TITLE
Wire Tap (EIP)

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#176]

**Comment by JaXt0r** [comment]
Some Informations:
* Description from EIP: http://www.enterpriseintegrationpatterns.com/patterns/messaging/WireTap.html
* Implementation inside Apache Camel: http://camel.apache.org/wire-tap.html

**Comment by codinghog** [comment]
I can help you out with most EIP patterns, starting from this one.

**Comment by iluwatar** [comment]
Thanks @codinghog go ahead :+1:
