### ISSUE TITLE
Ambiguity mapper pattern definition.

### ISSUE THREAD

**Issue by marouaneaba** [iluwatar/java-design-patterns#1762]
Ambiguity mapper pattern definition.
Defining the mapper model for a specific problem case (fetching data) that produces a definition is not correct.
we need an explanation on how/why to use this design template.

**Comment by ohbus** [comment]
Thank you so much for your interest @marouaneaba.

Please let us know if you are willing to work on this issue.

**Comment by iluwatar** [comment]
I'm not entirely sure what we need to do here. Please elaborate @marouaneaba what pattern are you referring to and where exactly do you see a problem?

**Comment by ohbus** [comment]
> Ambiguity mapper pattern definition.
> Defining the mapper model for a specific problem case (fetching data) that produces a definition is not correct.
> we need an explanation on how/why to use this design template.

The explanation is indeed ambiguous.

Please provide a detailed explanation _(with line numbers if possible)_ to show us where exactly the problem lies so that we can investigate the matter and understand the issue with a clear picture in our mind. 

This would also help any fellow who is looking to resolve this issue as well and make us all understand the goal that we should have in mind while handling this issue.

**Comment by marouaneaba** [comment]
Hello @ohbus @iluwatar ,
In the description, it is specified that the mapper should be used only for retrieving/mapped data from the database.
On the other hand, a mapper is a pattern which makes it possible to create an object in a single sence, is responsible for executing operations to construct the parameters of a constructor.
In another way, a mapper takes care of centralizing a set of operations that produces the arguments of a constructor to create an object.

**Comment by iluwatar** [comment]
@marouaneaba let's start from the basics.

1. Which pattern are you talking about? Please provide a direct link.
2. I understood that you see a problem in the pattern's `README.md` file, is that correct? Can you point out the exact line numbers there?
3. Since at the moment you seem to know the problem best and how to fix it, why not raise a pull request to fix it?

**Comment by marouaneaba** [comment]
Hello,
I talk about this mapper pattern : https://github.com/iluwatar/java-design-patterns/tree/master/data-mapper.
The description used to describe this mapper pattern, it is too specific for retrieving data from the database.

- Description currently used:

Intent
A layer of mappers that moves data between objects and a database while keeping them independent of each other and the mapper itself

Applicability
Use the Data Mapper in any of the following situations:
 -when you want to decouple data objects from DB access layer


- Mapper Pattern used for: 

Mapper is a pattern which makes it possible to create an object in a single sence, is responsible for executing operations to construct the parameters of a constructor.
In another way, a mapper takes care of centralizing a set of operations that produces the arguments of a constructor to create an object.


Yes I can contribute and thank you.

**Comment by iluwatar** [comment]
Thanks @marouaneaba for the clarification. It looks like data mapper pattern's readme is not currently fulfilling our quality criteria (see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute) and there's a lot to improve. We surely would appreciate your help here.

**Comment by IAmPramod** [comment]
@marouaneaba Are you working on this issue?

**Comment by ohbus** [comment]
As I can see @marouaneaba is not responding to any communications.

This issue is free to be taken again!

**Comment by KyleSongxy** [comment]
If this problem still needs to be solved, I think I can help, can this issue be assigned to me?

**Comment by iluwatar** [comment]
Ok @KyleSongxy, thanks for helping out
