### ISSUE TITLE
Spanish translation and languages codes

### ISSUE THREAD

**Issue by JuanManuelAbate** [iluwatar/java-design-patterns#1771]
Hello I'd like to contribute this project by adding Spanish translation and also to define a standard language code representation to follow. I propose to use the codes defined in [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1). I also propose to eliminate the images of the flags of the languages, it is not considered a good practice, there is no standard that defines flags for the languages and it can be taken as a discrimination for some countries or cultures. 

Do you agree? @iluwatar @xiaod-dev

**Comment by ohbus** [comment]
⭐ Sure thing! Thanks for your interest in our project 😃

**Comment by iluwatar** [comment]
@JuanManuelAbate thanks for the suggestion. At the moment our localization specification is a bit on the short side but you can see it here: https://github.com/iluwatar/java-design-patterns/wiki/15.-Support-for-multiple-languages. We use separate folders for different languages and what we have at the moment is `zh`, `ko`, `fr`, `tr`, `ar`. Do you know if it conforms to ISO-639-1, or do we need to do some changes first?

**Comment by JuanManuelAbate** [comment]
> @JuanManuelAbate thanks for the suggestion. At the moment our localization specification is a bit on the short side but you can see it here: https://github.com/iluwatar/java-design-patterns/wiki/15.-Support-for-multiple-languages. We use separate folders for different languages and what we have at the moment is `zh`, `ko`, `fr`, `tr`, `ar`. Do you know if it conforms to ISO-639-1, or do we need to do some changes first?

Hi @iluwatar, yes, before I send the changes I check that these codes follow the norm and are correct, you can see the full list of ISO-639-1 languages codes [here](http://www.loc.gov/standards/iso639-2/php/code_list.php)

**Comment by iluwatar** [comment]
Thanks, great job on unifying the localizations!

@all-contributors please add @JuanManuelAbate for translation
