### ISSUE TITLE
Add Backend for front end pattern(BFF)

### ISSUE THREAD

**Issue by FuncGuy** [iluwatar/java-design-patterns#1789]

**Comment by ohbus** [comment]
Hi @FuncGuy thanks for mentioning this, please provide relevant and trusted references to this pattern.

I know this is a widely used pattern in many companies especially startups, and hence I would encourage you to cite some links for the same.

**Comment by FuncGuy** [comment]
https://blog.bitsrc.io/bff-pattern-backend-for-frontend-an-introduction-e4fa965128bf

**Comment by iluwatar** [comment]
I think we already have an open issue about this pattern here: https://github.com/iluwatar/java-design-patterns/issues/300
@FuncGuy can you confirm that this is the same pattern? If yes, I think we can add the references provided here to that issue and close this issue as a duplicate.

**Comment by FuncGuy** [comment]
Yes
