### ISSUE TITLE
Leader/Followers pattern

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#179]
Leader/Followers pattern is also a _concurrency pattern_. This pattern behaves like a taxi stand where one of the threads acts as leader thread which listens for event from event sources, de-multiplexes, dispatches and handles the request. It promotes the follower to be the new leader. When processing completes the thread joins the followers queue, if there are no followers then it becomes the leader and cycle repeats again.

This pattern can be used in lieu of Half-Sync/Half-Async that we described in #109 

In Half-Sync/Half-Async there is a dedicated I/O thread which listens for incoming requests and then dispatches them to workers which is not good for performance due to context switching and cache coherency problems. Cache coherency problems occur because memory for request is allocated in I/O thread and then is accessed in worker threads.

There is a great reference for this http://www.cs.wustl.edu/~schmidt/PDF/lf.pdf

**Comment by iluwatar** [comment]
Once again, great finding. :+1:

**Comment by amit2103** [comment]
I can try to implement this. Can you guys please assign this to me?

**Comment by npathai** [comment]
Go ahead. Issues can only be assigned to team members. I will change the label.

**Comment by amit2103** [comment]
@npathai Okay. Will start working on this.

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by Pauligfast** [comment]
I'd like to take it

**Comment by iluwatar** [comment]
@Pauligfast ok, please go ahead.

**Comment by slowlizard** [comment]
thanks  very  much

**Comment by iluwatar** [comment]
@Pauligfast  are you still implementing this?

**Comment by iluwatar** [comment]
Issue available again

**Comment by bglmmz** [comment]
Leader/Followers pattern locates which folder?

**Comment by iluwatar** [comment]
It's not implemented yet

**Comment by npczwh** [comment]
@iluwatar , I'd like to take this

**Comment by iluwatar** [comment]
Ok @npczwh
