### ISSUE TITLE
Enum based strategy

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1790]
The current strategy example demonstrates the classic pattern with interfaces and implementations, but there is another way using enums. The basic principle is explained here: https://mcvalls.medium.com/how-to-implement-the-strategy-pattern-with-enums-in-java-19eb7168c247

Let's amend our strategy pattern example with the enum-based implementation.

**Comment by AndriyPyzh** [comment]
Hello! Can I start working on that?

**Comment by iluwatar** [comment]
Yes @AndriyPyzh, please go ahead!

**Comment by AndriyPyzh** [comment]
Is it already implemented?
https://github.com/iluwatar/java-design-patterns/blob/master/strategy/src/main/java/com/iluwatar/strategy/LambdaStrategy.java

**Comment by iluwatar** [comment]
I think you're right @AndriyPyzh, let's close this as a duplicate
