### ISSUE TITLE
Update Lombok version (possible migration issue for JDK17)

### ISSUE THREAD

**Issue by beooo79** [iluwatar/java-design-patterns#1803]
Lombok does not work in the current master branch when using JDK16.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project abstract-factory: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x4809c771) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x4809c771 -> [Help 1]`

To fix it i used:

```
diff --git a/pom.xml b/pom.xml
index 31cf03b4d..d7f05d796 100644
--- a/pom.xml
+++ b/pom.xml
@@ -71,7 +71,7 @@
         <system-lambda.version>1.1.0</system-lambda.version>
         <urm.version>2.0.0</urm.version>
         <mockito-junit-jupiter.version>3.5.0</mockito-junit-jupiter.version>
-        <lombok.version>1.18.14</lombok.version>
+        <lombok.version>1.18.20</lombok.version>
         <byte-buddy.version>1.10.21</byte-buddy.version>
         <javassist.version>3.27.0-GA</javassist.version>
         <maven-surefire-plugin.version>3.0.0-M5</maven-surefire-plugin.version>
```

**Comment by iluwatar** [comment]
Thanks @beooo79 for reporting. Although we currently claim to support only JDK11, I would like to see Lombok in the most recent version. If someone is willing to work on this, update Lombok to the latest version and test that the build and the tests still work.

**Comment by ohbus** [comment]
> Thanks @beooo79 for reporting. Although we currently claim to support only JDK11, I would like to see Lombok in the most recent version. If someone is willing to work on this, update Lombok to the latest version and test that the build and the tests still work.

I tested Lombok version 1.18 with Eclipse version v4.20 (2021-06) creating problems for me with reflection API for Java.
