### ISSUE TITLE
Adapter Pattern page is stuck in Chinese

### ISSUE THREAD

**Issue by blizzardengle** [iluwatar/java-design-patterns#1807]
I'm fairly confident the [Adapter Pattern](https://java-design-patterns.com/patterns/adapter/) page was in English a few days ago. Now it's appearing as Chinese with no visible option to switch back to English.

![adapter-page](https://user-images.githubusercontent.com/11205240/127930752-2454952a-cbc2-4e46-9d8d-8915a1d9480d.png)

**Comment by ohbus** [comment]
Thank you @blizzardengle for bringing this to our notice.

We have been trying to upgrade the website and make some changes to support different locales. We are extremely sorry for this and will provide a fix soon.

@iluwatar Can you suggest us a way out?

**Comment by blizzardengle** [comment]
I ran a check to test other pages and as of today (17 August 2021) these pages are also stuck in Chinese:

[API Gateway](https://java-design-patterns.com/patterns/api-gateway/)
[Acyclic Visitor](https://java-design-patterns.com/patterns/acyclic-visitor/)
[Adapter](https://java-design-patterns.com/patterns/adapter/)
[Ambassador](https://java-design-patterns.com/patterns/ambassador/)
[Caching](https://java-design-patterns.com/patterns/caching/)
[Callback](https://java-design-patterns.com/patterns/callback/)
[State](https://java-design-patterns.com/patterns/state/)

**Comment by ohbus** [comment]
Thank you so much @blizzardengle for running the analysis and submitting a report.

**Comment by iluwatar** [comment]
Fixed in commit https://github.com/iluwatar/java-design-patterns-web/commit/0d65edba37c37f6505d9016295b8743476df7d63. As @ohbus said, we've been working on localization for the next-gen website and unfortunately, it broke the current/old website. The localization folder is now completely removed from the old website's build process.
