### ISSUE TITLE
Event Sourcing pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#183]
http://martinfowler.com/eaaDev/EventSourcing.html
https://msdn.microsoft.com/en-us/library/dn589792.aspx
https://msdn.microsoft.com/en-us/library/jj591559.aspx

**Comment by npathai** [comment]
:+1:

**Comment by Alexandra-Giosan** [comment]
I'd like to make an implementation for this one. Could you please add the under construction tag to it?

**Comment by iluwatar** [comment]
@Alexandra-Giosan it's done

**Comment by iluwatar** [comment]
@Alexandra-Giosan are you still working on this?

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by iluwatar** [comment]
http://krasserm.github.io/2015/01/13/event-sourcing-at-global-scale/

**Comment by radresian** [comment]
I lead a financial trade project in which we implemented Event Sourcing Pattern. Our project is in production. I would like to implement an example of this pattern here. Could you please add the under construction tag for me.

**Comment by iluwatar** [comment]
Ok @radresian

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing
