### ISSUE TITLE
Currying

### ISSUE THREAD

**Issue by javatlacati** [iluwatar/java-design-patterns#1842]
I's a functional programming design pattern. As far as I understand you call a function with less parameters than usual and it can be used to defer processing when it has many steps involved.

UML example

```
@startuml
'https://plantuml.com/class-diagram

interface BiFunction <ParamType1, ParamType2, ResultType>{
}

interface Curried<ParamType1, ParamType2 extends Simple> {
  +ParamType2 apply(final ParamType1 a);
}

interface Simple<ParamType1, ParamType2, ResultType> extends BiFunction {
  +ResultType apply(final ParamType1 a, final ParamType2 b);
}

@enduml
```

![image](https://user-images.githubusercontent.com/1063901/136424980-f7ab35e9-5654-419e-8f7d-6a1257e12585.png)

With the curried version you can do stuff like:

```
   System.out.println(curriedAdd.apply(4).apply(5));

    Function1<Integer, Integer> adder5 = curriedAdd.apply(5);
    //some complicate and time consuming process here
    System.out.println(adder5.apply(4));
    System.out.println(adder5.apply(6));

```

**Comment by hkattt** [comment]
Hey @iluwatar, could I work on this issue?

**Comment by iluwatar** [comment]
All right @hkattt, you're free to proceed

**Comment by iluwatar** [comment]
@hkattt is still working on this
