### ISSUE TITLE
Loan pattern

### ISSUE THREAD

**Issue by javatlacati** [iluwatar/java-design-patterns#1843]
Reference: https://www.javacodegeeks.com/2013/01/loan-pattern-in-java-a-k-a-lender-lendee-pattern.html

**Comment by iluwatar** [comment]
You are free to take a shot @Pikmin1211

**Comment by iluwatar** [comment]
@Pikmin1211 are you working on this?

**Comment by Surya-Prakash-Reddy** [comment]
@iluwatar If no one is working on this, can you assign this to me?

**Comment by iluwatar** [comment]
Yes, assigned to @Surya-Prakash-Reddy

**Comment by iluwatar** [comment]
@Surya-Prakash-Reddy are you working on this?

**Comment by u7341910** [comment]
I am working on this. Could you assign this to me?

**Comment by iluwatar** [comment]
Ok @u7341910

**Comment by sabalanga06** [comment]
hello sir ,can you assign this issue to me ?

**Comment by iluwatar** [comment]
It's already under construction @sabalanga06, so please find something else

**Comment by iluwatar** [comment]
The issue is free, if anyone wants to work on it

**Comment by Shelly-Shih** [comment]
@iluwatar I am happy to do this issue, can you assign it to me?

**Comment by Shelly-Shih** [comment]
Sorry, I clicked the wrong button. Can you assign this issue to me? thanks
