### ISSUE TITLE
Integrate with Gitter chat room

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#185]
I recently stumbled upon [Gitter - chat rooms for github](https://gitter.im/) and I think it would be a great idea to integrate with it, because discussions regarding design patterns can be really interesting and may be more suitable in chat format.

**Comment by iluwatar** [comment]
Yes, why not. We could also setup a mailing list.

**Comment by npathai** [comment]
@iluwatar Great then. Let's do that. There is one more thing, I was thinking of setting up a wiki page describing usages of all design patterns. Do you think that is a good idea? IMO it would be better search optimized than README.md. We should continue doing what we do in README but we can also set up wiki. If you think it is a good idea then I can create a issue and start working on it.

**Comment by iluwatar** [comment]
@npathai Take a look at #56 This is under construction by @noobxgockel I don't think there will be wiki after this task, but nevertheless it is going to be a great step forward from `README.md` Maybe we should re-evaluate the wiki functionality after #56 is live.

**Comment by iluwatar** [comment]
I made an issue for the mailing list. It is #186

**Comment by npathai** [comment]
@iluwatar Can we set up chat room on priority so that we can start having discussions on our ongoing implementations of patterns. We should also add link to add our gitter chat room in README.

**Comment by iluwatar** [comment]
Resolved with https://github.com/iluwatar/java-design-patterns/commit/76fe68f591f6b341a4b6d254a5c4d2d4b4e0cba5

**Comment by npathai** [comment]
Yayy :+1:
