### ISSUE TITLE
More Singleton wisdom

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#187]
Analyze the following article from Oracle: https://community.oracle.com/docs/DOC-918906

Improve Singleton examples and their documentation where necessary.

**Comment by npathai** [comment]
@iluwatar There is an issue #188 where concern regarding lazy loading of Singleton is raised. I was going through the singleton documentation yesterday and found that the disadvantages of approaches are not discussed. We should document that the lazy loading example with `synchronized` keyword is ok for small applications but actually is too slow for production and should not be preferred. I think we are missing documentation there. Do you think we can address that in this issue?

**Comment by npathai** [comment]
http://programmers.stackexchange.com/questions/179386/what-are-the-downsides-of-implementing-a-singleton-with-javas-enum covers downsides of `Enum` based singleton.

**Comment by npathai** [comment]
Misko Hevery has discussed Singleton vs single instance in this blog post http://misko.hevery.com/2008/08/25/root-cause-of-singletons/
In his blog Misko discusses that there is nothing wrong in having a single instance of something, like having a single application scope object maintained by IoC containers, they don't have private constructors or global instance variable. The singletonness is maintained by container. We can also include this in FAQ "Are Singletons bad?" or some better name.
Further references which I found useful:
 - http://misko.hevery.com/2008/08/17/singletons-are-pathological-liars/
 - http://misko.hevery.com/2008/08/21/where-have-all-the-singletons-gone/
 - http://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons

I feel much can be said about Singletons so we need to figure out how we are going to address this. Your thoughts?

**Comment by mafagafogigante** [comment]
I haven't read those links yet but by my own experience I know that in some simple scenarios a singleton can be perfectly replaced by a uninstantiable class.

**Comment by iluwatar** [comment]
There are interesting findings in the Oracle's article particularly about double-checked locking. However, I think our implementation [ThreadSafeDoubleCheckLocking](https://github.com/iluwatar/java-design-patterns/blob/master/singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java) is correct.

**Comment by iluwatar** [comment]
Those are excellent articles @npathai :+1:  Thanks for sharing.

**Comment by amit2103** [comment]
@iluwatar  Is there an implementation of Singleton with Enum in this repo ? I think Effective Java recommends that we use Enum as Singleton as it is the most bulletproof construction of singleton.

**Comment by mafagafogigante** [comment]
Yes but there are known downsides for that. EJ is old and much have been learned since then.

An issue is that it will have the following public static methods:

```
    public static Foo[] values()
    public static Foo valueOf(String name)
```

**Comment by iluwatar** [comment]
http://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons

**Comment by npathai** [comment]
@iluwatar We already had the link in my previous comment. :+1: though.

**Comment by iluwatar** [comment]
Ah, didn't notice that. This thread is getting long...

**Comment by sanghisha145** [comment]
@iluwatar is this task still open. Can you assign this to me? 
I am reading about singletons
Task is: "Improve Singleton examples and their documentation where necessary." ?

**Comment by iluwatar** [comment]
Great, go ahead @sanghisha145

**Comment by ohbus** [comment]
> @iluwatar is this task still open. Can you assign this to me?
> I am reading about singletons
> Task is: "Improve Singleton examples and their documentation where necessary." ?

Hey @sanghisha145, Any updates?

**Comment by Vikashratn** [comment]
hey @iluwatar is this issue still open. You can assign this to me. 
I will try to finish it within 1 month.
and I will ask for help if necessary from you all.

**Comment by ohbus** [comment]
After a long period of not receiving any updates from @sanghisha145

I am assigning this issue to @Vikashratn.

Good Luck!!

**Comment by iluwatar** [comment]
@Vikashratn are you working on this?

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by Speiger** [comment]
```java
public class Example {
	public static final Example INSTANCE = new Example();
}
```

Why isn't something like this included in the singleton as a option?
Yes you could create more instances from that class, but this unique instance is technically also a singleton.
Which you can identify.

It provides a aspect that enums can not provide. If you have singleton instances that require expand ability, adding new elements later, is not possible with enums without having resort to something like reflection/asm.

ofcourse you could just move functions from the enum into a interface too and let the enum extend them and have multiple enums.

**Comment by OtherHorizon** [comment]
Hi, I'm new to this project. How would i go about contributing to it?Thanks.

**Comment by iluwatar** [comment]
@OtherHorizon see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

**Comment by shivu2002a** [comment]
Can I work on this issue? Thanks.

**Comment by iluwatar** [comment]
Ok @Omar-ahmed314, this is assigned for you

**Comment by Omar-ahmed314** [comment]
Thank you for considering me, @iluwatar , may I know the deadline for this issue? away from the deadline of hacktoberfest

**Comment by iluwatar** [comment]
I'd be happy for you if you completed it during the hacktober month 😀

**Comment by iluwatar** [comment]
We should document Bill Pugh's singleton solution

**Comment by jasokolowska** [comment]
I would like to contribute, can I be assigned to this issue?

**Comment by iluwatar** [comment]
That's excellent, please go ahead @jasokolowska

**Comment by Owen-CH-Leung** [comment]
@iluwatar I think in the current Singleton example we are just missing Bill Pugh's singleton solution. I'm happy to take over if needed
