### ISSUE TITLE
Monitor pattern is not being built

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1871]
In https://github.com/iluwatar/java-design-patterns/pull/1640 we merged the monitor pattern but noticed that it's not included in the main `pom.xml` and not being built. Let's fix that in this issue.

**Comment by ohbus** [comment]
I strongly recommend @Dev-AliGhasemi to take this up.

**Comment by Dev-AliGhasemi** [comment]
> > i added monitor module to parent POM.
> 
> Please submit a PR

[#1873](https://github.com/iluwatar/java-design-patterns/pull/1873)

**Comment by arnabsen1729** [comment]
Hi, @iluwatar @ohbus I am looking forward to fixing this issue. I saw that a PR was raised against it, but it had some failing tests and there was no update after 24 October 2021. I am willing to work on this.

So will you assign this issue to me?

> **PS:** I am new to Java, so any kind of feedback or guidance would be really appreciated.

**Comment by iluwatar** [comment]
Assigned to @arnabsen1729

**Comment by arnabsen1729** [comment]
Thanks for assigning the issue @iluwatar 

---

I have raised a PR here https://github.com/iluwatar/java-design-patterns/pull/1956
I need some help in improving the final coverage, the rest of the builds are passing.

**Comment by akash19coder** [comment]
Hii..@iluwatar I am looking forward to working on this issue. So, will you please assign this issue to me?

**Comment by arnabsen1729** [comment]
Hello, @akash19coder I have already made changes and the build is passing. You can take a look at my PR https://github.com/iluwatar/java-design-patterns/pull/1956, just stuck at improving the test coverage. If you can help in that respect it would be really helpful.

**Comment by akash19coder** [comment]
Hi, @arnabsen1729 I don't have real-world experience with Java but with guidance, I can surely help out with improving the test coverage
