### ISSUE TITLE
Synchronized lazy loading example is slow.

### ISSUE THREAD

**Issue by mafagafogigante** [iluwatar/java-design-patterns#188]
There is unnecessary synchronization going on there: synchronizing the
whole method is overkill. A double-checked lock works best and
improves performance.

My pseudocode for this:

    // Do not forget the volatile keyword <- this comment should be in the code.
    private volatile static T instance; 

    // ...

    T get() {
        if (instance == null) {
            synchronized(T.class) {
                if (instance == null) {
                    instance = new T();
                }
            }
        }
        return instance;
    }

Why is this necessary? This is a repository with over 6K stars. It
has become a **reference**. It gives **examples**. Although I always
avoid complexity when I can, giving an example of lazy loading that
simply adds the synchronized keyword to the method definition is not
as helpful as providing a strong double lock example.

Note that a synchronized method can be up to 100 times slower than an unsynchronized one.

Just trying to make this an even better resource, Bernardo.

**Comment by npathai** [comment]
@mafagafogigante Yes I agree with you. There is already an issue #187 related to singletons. I will add a comment over there that we should document that these ways are not recommended and are slow. I suggest an even better approach of using `Enum` based singletons which guarantees single instance even after serialization.

**Comment by mafagafogigante** [comment]
Yeah. I don't suppose it is possible to lazily load an enum, right?

-----Original Message-----

**Comment by iluwatar** [comment]
I agree that [ThreadSafeLazyLoadedIvoryTower](https://github.com/iluwatar/java-design-patterns/blob/master/singleton/src/main/java/com/iluwatar/singleton/ThreadSafeLazyLoadedIvoryTower.java) is very slow to access and it should be documented in the example.

However, the other styles to implement the Singleton deserve to be documented better as well as @npathai said. I think this is one of the most visited patterns on the site so I find this issue quite important.

**Comment by npathai** [comment]
@mafagafogigante No I don't think it is possible.

**Comment by geniusgeek** [comment]
@mafagafogigante please note that although you are trying to illustrate an example with your code. But the use of generics there is not valid. instance=new T(). is the problem. You can't instantiate a generic Type parameter.

**Comment by mafagafogigante** [comment]
@geniusgeek T is a concrete type.

**Comment by geniusgeek** [comment]
ok. Then i guess we should learn to use conventions.

**Comment by mafagafogigante** [comment]
@geniusgeek Did you see that get() isn't even ``static``? You would have bothered with that, too, right? This is not code you should be able to use, the key idea is there. Stop being an annoying prick on a closed issue.
