### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by liuyangyudaxia** [iluwatar/java-design-patterns#1965]
![image](https://user-images.githubusercontent.com/39300225/154443661-c12f821f-5942-4903-b158-8c5450711ab8.png)

**Comment by xyllq999** [comment]
I want to try fixing this issue, thank u. @iluwatar

**Comment by xyllq999** [comment]
Can you give more specific info about this bug or sth. ?

**Comment by xmnh** [comment]
![image](https://user-images.githubusercontent.com/48951804/190574787-9a6ca2d2-522b-4aa0-80d8-60506ad54696.png)

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by nairpranav331** [comment]
Can you specify more about this.!

**Comment by ohbus** [comment]
@nairpranav331 It is a Chinese translation error.

**Comment by iluwatar** [comment]
Subtask of #2289

**Comment by saiteja55** [comment]
I can fix this! Can I take it?

**Comment by saiteja55** [comment]
@iluwatar can you please check this?
https://github.com/iluwatar/java-design-patterns/pull/2470

**Comment by saiteja55** [comment]
#2470

**Comment by saiteja55** [comment]
@iluwatar Can you check this please? 
#2470
