### ISSUE TITLE
Accepting presentations for the design patterns

### ISSUE THREAD

**Issue by zafarella** [iluwatar/java-design-patterns#197]
@iluwatar What do u think if we create presentations for these nice collections of design patterns.
Either one for each for one for all. Something based on impress.js or similar would be great I think.
Happy to contribute.
Kiitos

**Comment by npathai** [comment]
@zafarella Presentations are nice. I think we can also have Refcardz similar to [Javazone](https://dzone.com/refcardz/design-patterns). But I think #56 can get closer to Refcardz.
As far as presentation goes you can prepare first draft with 2-3 patterns and share with us, so that we can have a discussion on it.

**Comment by iluwatar** [comment]
I agree we need better presentation. There is something boiling in #56 but I'm not sure what is the status of that. @zafarella I agree with @npathai Feel free to demostrate your ideas.

**Comment by zafarella** [comment]
Yep, thanks, whenever will find some time - will implement one presentation. The idea behind is to simply open the repository and start sessions about the patterns. It would be nice I think when you have some classes to do or simply want to go through some patterns in a wide screen.

**Comment by npathai** [comment]
:+1:

**Comment by iluwatar** [comment]
Sounds awesome. I'm looking forward to see the first presentation.

**Comment by npathai** [comment]
Ping @zafarella Any luck?

**Comment by zafarella** [comment]
Today :). Singleton on it's way.

**Comment by npathai** [comment]
Wow we are so excited to see the first presentation :+1:

**Comment by iluwatar** [comment]
I saw the first presentation at https://github.com/iluwatar/java-design-patterns/pull/244 and I love the idea :+1:

**Comment by npathai** [comment]
:+1: from me as well. It is impressive for first draft and we can surely take it forward and make it even better. I have some concerns regarding the snaps and material being out of sync from our codebase as our code evolves.

**Comment by iluwatar** [comment]
Yes, I share your concern.

**Comment by npathai** [comment]
I was thinking can't we enhance the website in future to be usable in presentation form. We can have something like presentation mode with pattern listings. That will keep content up to date. I don't know if it is feasible though.

**Comment by noobxgockel** [comment]
@npathai as i wrote in PR #244 allready:
> Hmmm... We could automate the process of generating the presentation with the data visible on the website. I highly doubt it would be a good presentation though...

Its possible and it might be feasible. I think the thing we are still lacking is a concrete target audience. Do we want to target the Coders at home, on mobile, in conferences? We could even optimize the website for printing. Or do we just want to do them all? How should the presentation look? Is there really much of a gain from just displaying the website fullscreen, a little bit bigger and with a different background?

My opinion on this is to keep the website and presentations seperate, maybe link the presentations from the website or something...

**Comment by zafarella** [comment]
Let me also add few words. I think the target of having presentation would be coders in conference/classes. I personally needed it for the team I worked. You already know all those patterns, but need to share and may be discuss in the context of the architecture.

In regards the outdated code in the slides - it is possible to read the code from the file. I am working on it and will commit soon.

I agree with @noobxgockel  to have website and the presentations separate.

**Comment by iluwatar** [comment]
It would be awesome to be able to launch the presentations from the web site.

**Comment by npathai** [comment]
We can keep website and presentations separate. As far as the audience is concerned it will be used in classes, meetups, individuals for reference purpose. Print we can, but now is not the right time. @zafarella has got something going on, so let us play with the idea of presentation and see how much traction we get.

**Comment by iluwatar** [comment]
@zafarella any updates? I would love to incorporate nice presentations like you demonstrated.

**Comment by zafarella** [comment]
A bit busy coming month. If not in rush, I can work on it later

**Comment by iluwatar** [comment]
There is no rush. Good to know you're still around @zafarella

**Comment by iluwatar** [comment]
If someone wants to work on this, the issue is free for taking.

**Comment by iluwatar** [comment]
I've created a presentation for Hexagonal Architecture in https://github.com/iluwatar/java-design-patterns/pull/519

**Comment by salman-bhai** [comment]
@iluwatar can u list what all presentations are up for the taking? I'd like to contribute to one of them if possible!

**Comment by iluwatar** [comment]
The checked ones have already been implemented.

- [ ] abstract-document
- [ ] abstract-factory
- [ ] adapter
- [ ] aggregator-microservices
- [ ] api-gateway
- [ ] async-method-invocation
- [ ] bridge
- [ ] builder
- [ ] business-delegate
- [ ] caching
- [ ] callback
- [ ] chain
- [ ] command
- [ ] composite
- [ ] dao
- [ ] data-mapper
- [ ] decorator
- [ ] delegation
- [ ] dependency-injection
- [ ] double-checked-locking
- [ ] double-dispatch
- [ ] event-aggregator
- [ ] event-asynchronous
- [ ] event-driven-architecture
- [ ] execute-around
- [ ] facade
- [ ] factory-kit
- [ ] factory-method
- [ ] feature-toggle
- [ ] fluentinterface
- [ ] flux
- [ ] flyweight
- [ ] front-controller
- [ ] guarded-suspension
- [ ] half-sync-half-async
- [X] hexagonal
- [ ] intercepting-filter
- [ ] interpreter
- [ ] iterator
- [ ] layers
- [ ] lazy-loading
- [ ] mediator
- [ ] memento
- [ ] message-channel
- [ ] model-view-controller
- [ ] model-view-presenter
- [ ] module
- [ ] monad
- [ ] monostate
- [ ] multiton
- [ ] mute-idiom
- [ ] mutex
- [ ] naked-objects
- [ ] null-object
- [ ] object-mother
- [ ] object-pool
- [ ] observer
- [ ] page-object
- [ ] poison-pill
- [ ] private-class-data
- [ ] producer-consumer
- [ ] promise
- [ ] property
- [ ] prototype
- [X] proxy
- [ ] publish-subscribe
- [ ] queue-load-leveling
- [ ] reactor
- [ ] reader-writer-lock
- [ ] repository
- [ ] resource-acquisition-is-initialization
- [ ] semaphore
- [ ] servant
- [ ] service-layer
- [ ] service-locator
- [ ] singleton
- [ ] specification
- [ ] state
- [ ] step-builder
- [ ] strategy
- [ ] template-method
- [ ] thread-pool
- [ ] tolerant-reader
- [ ] twin
- [ ] value-object
- [ ] visitor

**Comment by panksy2k** [comment]
Hi,

I want to re-factor Prototype pattern to avoid using new and rather only use Objet.clone(). How can I contribute / pull request?

panksy2k

**Comment by iluwatar** [comment]
@panksy2k create a new issue describing the problem and we can start discussion there.

**Comment by panksy2k** [comment]
ok - done that for #584
