### ISSUE TITLE
[Question] Difference between Mediator and Event Bus

### ISSUE THREAD

**Issue by javatlacati** [iluwatar/java-design-patterns#1971]
I was reading about [event bus design patern](https://dzone.com/articles/design-patterns-event-bus) but I can't differentiate it from Mediator.

If there's any difference kindly add a new entry for event bus design pattern.

Aditional reading:

https://medium.com/elixirlabs/event-bus-implementation-s-d2854a9fafd5

Best regards.

**Comment by alainalawson02** [comment]
I would like to add a new design pattern entry for event bus and help @javatlacati understand how event bus is its own design patter.  Can you please assign me? @iluwatar

**Comment by iluwatar** [comment]
Thanks @javatlacati, good answer 💪
