### ISSUE TITLE
Direct links to pattern descriptions are broken

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#198]
Example link:

https://github.com/iluwatar/java-design-patterns#state

When the link is opened in browser it does not lead to the correct anchor.

**Comment by noobxgockel** [comment]
Its github's fault i think. If you open the README the links work:

https://github.com/iluwatar/java-design-patterns/blob/master/README.md#state

Anyhow, the Site will better this situation hopefully...

**Comment by npathai** [comment]
@noobxgockel Can we raise an issue at GitHub's side for the same?

**Comment by iluwatar** [comment]
At the moment the individual patterns are not visible in `README.md` so this issue might not be relevant anymore.

**Comment by noobxgockel** [comment]
As the website will take over and the links will be removed from the root README in master this issue isnt relevant anymore.
