### ISSUE TITLE
Always have 1 Checkstyle violation

### ISSUE THREAD

**Issue by KingOfXi** [iluwatar/java-design-patterns#1992]
There's always a checkstyle violation in my pull request.  I have run several kinds of checkstyle tools in my local machine but there's no error. So I can't find the checkstyle violation. Do anyone know the cause of the checkstyle violation .This is the pull request link https://github.com/iluwatar/java-design-patterns/pull/1977.

**Comment by KingOfXi** [comment]
![image](https://user-images.githubusercontent.com/61463030/164980154-5558fa08-037d-4ac6-883f-39ef9eade886.png)

**Comment by iluwatar** [comment]
Seems fixed in the PR, so I'll close this @KingOfXi
