### ISSUE TITLE
Add contributors section to README

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#201]
I think this is a very good idea because it will encourage more contribution and provides better visibility of major contributors. Hamcrest team and JUnit team does this and I am sure many more as well. 

@iluwatar your thoughts on this? After this I think we will be good to go and I will also focus on adding and improving content.

**Comment by iluwatar** [comment]
It is more maintenance but I don't object if there's a PR.

**Comment by noobxgockel** [comment]
I think the overview of github is enough, maybe some "special thank" here and there but not another list to maintain ^^

The Website will get such overview, so it will be visible even on the website C:

**Comment by npathai** [comment]
@noobxgockel Yes I agree. As we will move forward there will be a team of people who will become frequent contributors and maintainers. So I thought it would be worth mentioning them. Not a problem if this is not a good idea.

**Comment by iluwatar** [comment]
We could list the core team members in the `README.md` and then link to https://github.com/iluwatar/java-design-patterns/graphs/contributors to view all contributors.

**Comment by npathai** [comment]
@iluwatar Good idea. :+1:

**Comment by iluwatar** [comment]
This section is now in the developer wiki https://github.com/iluwatar/java-design-patterns/wiki/9.-Team
