### ISSUE TITLE
Sunsetting EIPs and cloud patterns from this repository

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2026]
In the future, we want to concentrate on pure Java design patterns. Implementing EIPs requires an asynchronous messaging framework, and there are plenty of those. Similarly, implementing cloud design patterns requires a cloud platform. Basically, one could create a new repository for each technology choice e.g. camel-enterprise-integration-patterns, spring-enterprise-integration-patterns, aws-cloud-design-patterns, etc. If anyone is interested, go ahead and use one these ideas, you have my full support.

Acceptance criteria

- Remove the enterprise integrations patterns (eip-*) from this repository
- Remove the cloud design patterns (cloud-*) from this repository
- Clean up the parent pom.xml from the removed modules, dependencies, and plugins that are no longer needed

**Comment by mohanaraosv** [comment]
Your proposal is good, Instead of removing it!! Shall we create new repositories and move these patterns to save efforts already done and archive them if you wish to do?

**Comment by iluwatar** [comment]
It's ok to remove. Anyone can find them from version history if needed.

**Comment by koriop** [comment]
Can I take this issue?

**Comment by iluwatar** [comment]
Ok @koriop

**Comment by shibicr93** [comment]
@iluwatar I am willing to work on this issue

**Comment by iluwatar** [comment]
@shibicr93 that's fine since the user @ghost doesn't seem to exist anymore 🤷🏻‍♂️
