### ISSUE TITLE
Update JVM version to the latest stable release

### ISSUE THREAD

**Issue by yonatankarp** [iluwatar/java-design-patterns#2032]
As the end of support of JVM 11 would be in exactly 1 year (September 2023) this repository should probably consider moving to the next stable JVM release (JVM 17) while adopting the features that have been introduced in it to update the existing patterns.

like to Oracle’s page regarding support versions: 
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by iluwatar** [comment]
This is important for us. Some steps that should be considered are laid out in the plan https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition

**Comment by yonatankarp** [comment]
it might be also a good time to remove Lombok as most of the functionality provided by it would be available in a `Record` classes

**Comment by yonatankarp** [comment]
Couple more thoughts:

* I think that we can also remove Lombok with this upgrade, as 99% of the functionality it provides is available in a `Record` class now.
* The change is pretty big, maybe it would make sense to create a dedicated feature branch with branch protection for this task? how was the previous migration from JVM 8 to JVM 11? are there any learnings from it?

Also, I could probably work on it but might need some assistance as I almost never worked with Maven but mainly with Gradle 😅

**Comment by ohbus** [comment]
Hey!

I would like to help!

Thanks,
Subhrodip.

**Comment by iluwatar** [comment]
Hey guys, I've created the first issues to start the [Java 17 transition](https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition). Feel free to pick up issues from this list

- https://github.com/iluwatar/java-design-patterns/issues/2033
- https://github.com/iluwatar/java-design-patterns/issues/2034
- https://github.com/iluwatar/java-design-patterns/issues/2035
- https://github.com/iluwatar/java-design-patterns/issues/2036
- https://github.com/iluwatar/java-design-patterns/issues/2037

**Comment by iluwatar** [comment]
Some subtasks are still in progress, so I'm keeping this open

- https://github.com/iluwatar/java-design-patterns/issues/2375
- https://github.com/iluwatar/java-design-patterns/issues/2376
- https://github.com/iluwatar/java-design-patterns/issues/2377
- https://github.com/iluwatar/java-design-patterns/issues/2378
