### ISSUE TITLE
Upgrade Lombok version to support Java 17

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2034]
This issue is a part of the Java 17 transition plan at https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition.

According to https://github.com/projectlombok/lombok/issues/2898, Lombok supports Java 17 since version 1.18.22. Our version is a bit behind that, so let's upgrade to the latest.

Acceptance criteria

- Lombok version has been updated to the latest available

**Comment by karshil2309** [comment]
@iluwatar : I will update those hotfixes for java 17. Will create separate branch and create pr for the same.

**Comment by iluwatar** [comment]
Ok @karshil2309
