### ISSUE TITLE
Build with JDK 17

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2035]
This task is part of the transition plan at https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition. Here we address the issues that come up when building the project with JDK 17 using language level Java 11.

Acceptance criteria

- Build the project with JDK 17 while keeping the maven-compiler-plugin language level at 11
- Fix the errors that come up during the build

**Comment by harikesh409** [comment]
@iluwatar ,
Can I work on this

**Comment by iluwatar** [comment]
Yes, go ahead @harikesh409

**Comment by tylnesh** [comment]
Is this already fixed in master branch? I've built the current state against JDK17 and have no errors.

**Comment by iluwatar** [comment]
For me, it fails during naked objects integration tests

**Comment by robertvolkmann** [comment]
@iluwatar Could I work on this?

**Comment by iluwatar** [comment]
@harikesh409 I'll assign @robertvolkmann to this issue as well. This is high priority and would like to see it completed soon.
