### ISSUE TITLE
Run with Java 17

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2036]
This is part of the transition plan at https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition. In this issue, we build the project using JDK 11 and try to run it with Java 17 runtime.

Acceptance criteria

- The project is built with JDK 11
- The pattern examples are executed with Java 17 runtime e.g. `java -jar proxy.jar`
- The errors that come up in the testing are fixed

**Comment by ArinCodes** [comment]
I want to help in this issue

**Comment by iluwatar** [comment]
Ok @ArinCodes

**Comment by rohitgautam16** [comment]
Can I help in this isssue ..?

**Comment by robertvolkmann** [comment]
@iluwatar Could I work on this?

**Comment by iluwatar** [comment]
@ArinCodes I'll assign this issue to @robertvolkmann as well since this is high priority.
