### ISSUE TITLE
Upgrade dependencies to support Java 17

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2037]
This issue is a part of the transition plan at https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition. Here we upgrade the dependencies so that they support Java 17.

Acceptance criteria

- Project dependencies have been upgraded so that each of them supports Java 17

**Comment by akhilpamwani** [comment]
Hi I am interested in your project 
Please Hire me

**Comment by SumukhaGargeshP** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Aarav238** [comment]
I would like to work on this issue . Please assign it to me

**Comment by Rajat-Sharma1710** [comment]
I can work on this issue. Assign it to me

**Comment by iluwatar** [comment]
To be fair, @akhilpamwani expressed interest first

**Comment by VivM1** [comment]
Hey, its been 9 days since... do we have any upgrade ? . If not then I would like to work on this one.

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by robertvolkmann** [comment]
@iluwatar could you assign it to me?

**Comment by iluwatar** [comment]
Assigned to you @robertvolkmann
