### ISSUE TITLE
Add localization for Vietnamese

### ISSUE THREAD

**Issue by m-inh** [iluwatar/java-design-patterns#2056]
I translate `README.md` file and add it as new file under `/localization/vi/` folder.

**Comment by m-inh** [comment]
#2047

**Comment by iluwatar** [comment]
Let's keep it open until the PR has been merged

**Comment by m-inh** [comment]
It's been merged already @iluwatar , pls check #2047

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by iluwatar** [comment]
You're right @m-inh, thanks for notifying
