### ISSUE TITLE
add Filter pattern

### ISSUE THREAD

**Issue by MohammadRehanPatel** [iluwatar/java-design-patterns#2062]
please give PR with Hacktoberfest badge

**Comment by skullkim** [comment]
I like to work on this issue.

**Comment by MohammadRehanPatel** [comment]
I already have code for that woth a good example

**Comment by iluwatar** [comment]
Ok, assigned to @MohammadRehanPatel. Can you also list an authoritative source for the pattern?

**Comment by MohammadRehanPatel** [comment]
done

**Comment by MohammadRehanPatel** [comment]
please add hacktoberfest tag

**Comment by iluwatar** [comment]
The repository has the hacktoberfest tag. I believe it's enough for the contributors to submit any pull request, and once it gets approved, the hactoberfest PR count is increased.

**Comment by MohammadRehanPatel** [comment]
I Learn this pattern during a course from udamy

**Comment by aniketkumar-1907** [comment]
Can I work on this issue @skullkim.

**Comment by drashan14** [comment]
Sir i would like to do work on this topic could you assign me this issue.

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by ArchontisKostis** [comment]
is anyone assigned to this issue? Iwould like to work on it

**Comment by MohammadRehanPatel** [comment]
I Already Done it

**Comment by iluwatar** [comment]
The issue is free, if anyone wants to take a shot

**Comment by lollanlollan** [comment]
We're a group of students that would like to work on this issue.

**Comment by iluwatar** [comment]
Go ahead @lollanlollan

**Comment by Pratik-kp** [comment]
Is this issue still open @iluwatar , I would like to take a shot

**Comment by sugan0tech** [comment]
@Pratik-kp  can I know the status of your progress?
