### ISSUE TITLE
Translate the active-object readme to Spanish

### ISSUE THREAD

**Issue by aitorfi** [iluwatar/java-design-patterns#2077]
I'll translate the readme file of the active-object design pattern to Spanish and place it under localization.es.active-object.

**Comment by iluwatar** [comment]
Ok @aitorfi

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by Kshitij-200** [comment]
Hello Sir
I want to contribute in this project.
It will be a great beginning for me if you assign me this issue.
Thank you
