### ISSUE TITLE
Document design principles | SOLID | YAGNI

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#208]
Some of the design principles that I know of are:
 - [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) 
 - [Tell Don't Ask](http://martinfowler.com/bliki/TellDontAsk.html)
 - [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)
 - [KISS](https://en.wikipedia.org/wiki/KISS_principle)
 - [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

These are the foundational principles which lead to design patterns. I think we should document them.

**Comment by iluwatar** [comment]
:+1:

**Comment by iluwatar** [comment]
This could be its own section, like for example the "Idioms" is.

**Comment by iluwatar** [comment]
We should borrow some things from here http://webpro.github.io/programming-principles/

**Comment by npathai** [comment]
@iluwatar That's a great link. I will go through it. Yes it should be in a dedicated section something like "Design guidelines or principles".

**Comment by mafagafogigante** [comment]
I dare to say YAGNI about this very idea.

@iluwatar Awesome link. Why not just reference it in the suggested section? Also keep a fork of it so that if the original repository is removed we still have our copy.

**Comment by npathai** [comment]
@mafagafogigante I was kinda thinking in the same line. I will change the task to just add reference to the link @iluwatar provided. How does that sound?

**Comment by iluwatar** [comment]
@mafagafogigante @npathai This is a good idea. We also may have something to contribute to that repository.

**Comment by npathai** [comment]
Ok I will pick this up once I am done with #74 Turns out its difficult to work with NIO :smile:

**Comment by mafagafogigante** [comment]
Great. I think that helping that repository would be a great thing to do.

**Comment by npathai** [comment]
It's done. Closing this issue.
