### ISSUE TITLE
Translate template-method pattern readme to Korean

### ISSUE THREAD

**Issue by seongkyu-lim** [iluwatar/java-design-patterns#2082]
I'll translate the readme file of the template-method design pattern to Korean and place it under localization/ko/template-method.

**Comment by astitva0011** [comment]
!assign

**Comment by iluwatar** [comment]
Ok @seongkyu-lim

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by Kshitij-200** [comment]
Hello sir,
Can you please assign me this issue.
