### ISSUE TITLE
Link error: Fix broken link in "How to contribute" page.

### ISSUE THREAD

**Issue by mdfaizanahmed786** [iluwatar/java-design-patterns#2083]
### A broken link found in "How to contribute" page present in **New Pattern** section.
**Where?**
7th point.

**Comment by vikashkr-07** [comment]
I love to do this if you'll assign this task to me

**Comment by csankhala** [comment]
Hi @mdfaizanahmed786 ,Would you provide more details for issue? I did not find issue any link.
Please share screenshot if possible. Thanks

**Comment by iluwatar** [comment]
Assigned to @vikashkr-07

**Comment by vikashkr-07** [comment]
Doing

**Comment by mdfaizanahmed786** [comment]
> Hi @mdfaizanahmed786 ,Would you provide more details for issue? I did not find issue any link. Please share screenshot if possible. Thanks

Yeah sure, the link is now working! There was a broken link in [this page](https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute) in the 7th point under New Pattern.

**Comment by mdfaizanahmed786** [comment]
> Doing

> I think the link is now working.

**Comment by being-nitin** [comment]
could you assign this task to me

**Comment by csankhala** [comment]
> > Hi @mdfaizanahmed786 ,Would you provide more details for issue? I did not find issue any link. Please share screenshot if possible. Thanks
> 
> Yeah sure, the link is now working! There was a broken link in [this page](https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute) in the 7th point under New Pattern.

Great. Can we close this issue if its already fixed?

**Comment by mdfaizanahmed786** [comment]
The link is now working.

**Comment by iluwatar** [comment]
Thanks for fixing this!

@all-contributors please add @mdfaizanahmed786 for docs
