### ISSUE TITLE
Add lombok to data-transfer-object pattern 

### ISSUE THREAD

**Issue by burno1** [iluwatar/java-design-patterns#2096]
I noticed that the pattern is well written but is using a lot of getters and setters without need. We can add lombok to it and have it cleaner to read and understand

**Comment by burno1** [comment]
Also, I noticed that a lot of modules in the project has the same situation, should we create one issue per each, since a module is not coupled or you suggest another approach @iluwatar

**Comment by burno1** [comment]
I have opened 2 PRS, haven't noticed the bot who handles contributors (sorry about that)

**Comment by iluwatar** [comment]
> Also, I noticed that a lot of modules in the project has the same situation, should we create one issue per each, since a module is not coupled or you suggest another approach @iluwatar

Yes, this approach is fine @burno1
