### ISSUE TITLE
CSS/JS is not loaded when browsing site with HTTPS

### ISSUE THREAD

**Issue by ntfc** [iluwatar/java-design-patterns#210]
Developer console shows warnings like:

> Mixed Content: The page at 'https://iluwatar.github.io/java-design-patterns/' was loaded over HTTPS, but requested an insecure stylesheet 'http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.

Maybe the solution is to include  stylesheets/js with **//** instead of **http://** as reported [here](https://www.maxcdn.com/one/tutorial/solving-mixed-content/)

**Comment by noobxgockel** [comment]
@ntfc Hello there
i just committed a rather large batch of misc. fixes and that included a fix for this. I dont get any errors in the developer console anymore.

Can u please verify it works now ?

**Comment by ntfc** [comment]
Hi there,

Working perfectly, thanks!
