### ISSUE TITLE
Add hindi language localization support for the design patterns

### ISSUE THREAD

**Issue by rishu1601** [iluwatar/java-design-patterns#2121]
Add the following README files:
- localization/hi/adapter/README.md
- localization/hi/factory/README.md
- localization/hi/observer/README.md

**Comment by rishu1601** [comment]
I nominate myself to work on the issue @iluwatar

**Comment by iluwatar** [comment]
Looking forward to the PR @rishu1601

**Comment by rishu1601** [comment]
Hey @iluwatar , please review this PR: https://github.com/iluwatar/java-design-patterns/pull/2128

**Comment by Rizwan102003** [comment]
Hello,i would like to work on this issue if noone is working on it.

**Comment by Rizwan102003** [comment]
Thanks

**Comment by ibrahim89** [comment]
Is there any progress on this issue. If no one is working on this can you please assign it to me?

**Comment by ibrahim89** [comment]
Thanks @iluwatar. I'll look into this.

**Comment by ibrahim89** [comment]
Hi @iluwatar befoe starting actual wok on this hindi translation I wanted to ensure that no other person is working on this. but as I can see there is already one PR  [https://github.com/iluwatar/java-design-patterns/pull/2557](url) is open and @surjendu104 is working on this. let me know what is your opinion on this.

**Comment by iluwatar** [comment]
Yes, please collaborate and agree on the parts each of you will translate

**Comment by surjendu104** [comment]
Hey @ibrahim89 I have added Hindi translation upto `command` pattern in this or #2557 . You can work on after this. Thanks for collaboration.

**Comment by ibrahim89** [comment]
Thans @surjendu104  for the update. I'll be looking into it

**Comment by Parth152004** [comment]
I want to work on this issue if no one is working.

**Comment by iluwatar** [comment]
Sure @Parth152004, just indicate which parts you are working on

**Comment by tiger3768** [comment]
Hey, I would like to work on the observer pattern of the documentation, thank you.

**Comment by KunjMaheshwari** [comment]
Please assign this issue to me. I am new to Hacktoberfest. I will resolve this issue in Minimum Time.

**Comment by amanmunjekar** [comment]
Please assign this issue to me. I am new to Hacktoberfest. I will resolve this issue in Minimum Time

**Comment by KunjMaheshwari** [comment]
ok

**Comment by iluwatar** [comment]
Duplicate of #2279
