### ISSUE TITLE
Categorize and Tag all patterns

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#213]
Due to splitting the issues up some information like the category got lost. And we have those cool new Tags.

All the index.md files of the patterns should get relevant categories and tags in the yaml frontmatter. The 'pattern_cat' and 'pattern_tag' stuff can be removed as it is only a placeholder...

The 'How to Contribute' Section of the README in master should explain everything that is needed for this issue.

EDIT:
After this point is done we should remove the pattern list from the master README file.

TODO:
- [X] Categorized all Patterns (done with adbb4ac4dedf54a13c5d70589c33bcab7d103dad)
- [X] ~~Clarify~~ Test if we can use proper casing instead of camel case as shown in adbb4ac4dedf54a13c5d70589c33bcab7d103dad. EDIT: I looked it up, it should work without "", e.g. just -> Creational Patterns
(done with 5ce932ceb7768e9f8f975524af9758f614ef68ee)
- [ ] Tag all Patterns
(partially done the with usage of tag "Java" instead of placeholder :P  5ce932ceb7768e9f8f975524af9758f614ef68ee)
- [X] Remove pattern list from master README
(done with 5ce932ceb7768e9f8f975524af9758f614ef68ee)

**Comment by iluwatar** [comment]
Is there some limitation why we need to use snake casing e.g. `presentation_tier`? Can't we just type `Presentation tier` or maybe YAML need `"Presentation tier"`.

**Comment by iluwatar** [comment]
What would be good tags to use? I'm thinking of implementation technologies e.g. `Spring` and `Camel`.

**Comment by noobxgockel** [comment]
Hmmm, to be honest im not too sure about beeing able to use proper casing with spaces. I'd say try it out and if it works then it definitly looks better than camel casing, right ?

And Tags, yeah. Maybe some things that differences this pattern from other ones. Like if its an EJB only pattern, JEE or JSE, ... The technologies used or similar to the pattern also sounds quite good. But i agree, this needs more clarification...

**Comment by npathai** [comment]
Some other tags: `Functional`, 'Persistence`, `I/O`. But I am still figuring it out.

**Comment by npathai** [comment]
We need to tag based on difficulty as well.

**Comment by iluwatar** [comment]
I did the categorization and tagging of the patterns today. The used categories and tags can be seen [here](https://github.com/iluwatar/java-design-patterns/blob/gh-pages/_config.yml).
