### ISSUE TITLE
Translate abstract-document pattern to Vietnamese

### ISSUE THREAD

**Issue by m-inh** [iluwatar/java-design-patterns#2140]
I would like to translate `abstract-document` pattern to Vietnamese and add it under `/localization/vi/` folder.

**Comment by iluwatar** [comment]
Ok @m-inh

**Comment by m-inh** [comment]
I have created a PR here: #2169 , pls take a look when you have time, thanks

**Comment by iluwatar** [comment]
Subtask of #2288
