### ISSUE TITLE
Translate abstract-factory pattern to Vietnamese

### ISSUE THREAD

**Issue by m-inh** [iluwatar/java-design-patterns#2141]
I would like to translate `abstract-factory` pattern to Vietnamese and add it under `/localization/vi/` folder.

**Comment by iluwatar** [comment]
Ok @m-inh

**Comment by m-inh** [comment]
Hi @iluwatar , I have opened a PR #2186 to close this issue, pls take a look when you have time, thanks

**Comment by iluwatar** [comment]
Subtask of #2288
