### ISSUE TITLE
about abstract factory

### ISSUE THREAD

**Issue by dengWuuu** [iluwatar/java-design-patterns#2142]
In my view, maybe AbstractFactory need a superfactory and it can include many factory.
I think the  AbstractFactory code in the project is not good enough......

**Comment by iluwatar** [comment]
The classic implementation consists of abstract factory interface and concrete factories that produce products through factory methods. See https://en.wikipedia.org/wiki/Abstract_factory_pattern

**Comment by dengWuuu** [comment]
oh!! you are right.
thanks
