### ISSUE TITLE
Add Model-View-Intent design pattern

### ISSUE THREAD

**Issue by JanFidor** [iluwatar/java-design-patterns#2151]
I noticed that while MVP, MVC and MVVM have been added, it wasn't the case for MVI. I'll be happy fix that.

**Comment by iluwatar** [comment]
Thanks @JanFidor for the suggestion. Could you provide a link that explains the pattern?

**Comment by JanFidor** [comment]
Sure thing, here are 2 of the best ones I found https://apiumacademy.com/blog/model-view-intent-pattern/  , https://www.raywenderlich.com/817602-mvi-architecture-for-android-tutorial-getting-started  . The pattern was created with android in mind, so most explanations lean heavily on it with explanations. It also heavily utilizes sealed classes from kotlin, but it can still be implemented in Java and I think it's worth a mention for its focus on encapsulation.

**Comment by iluwatar** [comment]
Looks great! Thanks so much for providing the links.

**Comment by iluwatar** [comment]
I assume @JanFidor is still working on it
