### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2152]
There is a nice broken links checker tool available at https://github.com/stevenvachon/broken-link-checker

After installation, one can run it against our website e.g.

`blc https://java-design-patterns.com -roe`

The results indicate 16 broken links. Let's fix them in this task.

Acceptance criteria

- The broken links reported by the tool have been fixed

**Comment by Jeremy-Cains-ANU** [comment]
Hi, I will happily have a look at this.

**Comment by iluwatar** [comment]
Thanks @Jeremy-Cains-ANU, assigned to you now
