### ISSUE TITLE
I'll translate the readme file of the iterator design pattern to Korean

### ISSUE THREAD

**Issue by seongkyu-lim** [iluwatar/java-design-patterns#2162]
I'll translate the readme file of the iterator design pattern to Korean and place it under localization/ko/iterator.

---
Contributing to the repo is almost my first contribution.
And I realized that contributing to translation helped me a lot in my own learning.
Thank you for creating this opportunity! @iluwatar

**Comment by iluwatar** [comment]
Thanks for contributing back to the community @seongkyu-lim 😄 Looking forward to the next pull request!

**Comment by iluwatar** [comment]
Subtask of #2282
