### ISSUE TITLE
Automagically update the website's submodule

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#218]
Update the submodule (of master) inside of the gh-pages branch to the latest commit automagically. 
This is so we dont have to manually do that everytime. Possible solution is to use travis-ci.

Here are some related links i found:
- http://awestruct.org/auto-deploy-to-github-pages/
- http://stackoverflow.com/questions/18027115/committing-via-travis-ci-failing
- https://evansosenko.com/posts/automatic-publishing-github-pages-travis-ci/

**Comment by iluwatar** [comment]
:+1:

**Comment by npathai** [comment]
@noobxgockel have you consciously chosen `AutoMAGICALLY` as the title? Or is it supposed to be `automatically`? :)

**Comment by noobxgockel** [comment]
@npathai yep npathai. I like to do that from time to time. Its like magic, you only think its magic until you know how the trick is done. And updating the website each travis build might seem magically to some C:

**Comment by noobxgockel** [comment]
Sorry for the amount of commits.
I tried testing it in my fork, but travis didnt behave well...
It seems to work now though C: 10de139c771bfac1d2d5679d1365e427802a05a8

**Comment by npathai** [comment]
That's great :+1:

**Comment by iluwatar** [comment]
Awesome feature, thanks!

**Comment by iluwatar** [comment]
@noobxgockel Could you additionally please briefly explain the automagic updating system in https://github.com/iluwatar/java-design-patterns/wiki/7.-Working-with-the-web-site ?

**Comment by noobxgockel** [comment]
@iluwatar i updated it. There isnt much explaining to do

**Comment by iluwatar** [comment]
Thanks!
