### ISSUE TITLE
Translate active-object pattern to Vietnamese

### ISSUE THREAD

**Issue by m-inh** [iluwatar/java-design-patterns#2184]
I would like to translate active-object pattern to Vietnamese and add it under /localization/vi/ folder.

**Comment by m-inh** [comment]
@iluwatar I have opened 2 PR, one for this issue, one for additional refactor. Pls take a look when you have time, thanks: #2190 #2192

**Comment by iluwatar** [comment]
Ok @m-inh

**Comment by iluwatar** [comment]
Subtask of #2288
