### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by mafagafogigante** [iluwatar/java-design-patterns#219]
To help @iluwatar : consider labelling website and question.

@noobxgockel - I would have e-mailed you if your e-mail were public. So here is the question: what is the purpose of this https://github.com/iluwatar/java-design-patterns/blob/gh-pages/pages/2about.md ? Do we need it for any reason?

**Comment by noobxgockel** [comment]
Well... not really, in raw you can see the old content (https://raw.githubusercontent.com/iluwatar/java-design-patterns/gh-pages/pages/2about.md) but i guess we can delete it.

- [ ] Delete [2about.md](https://github.com/iluwatar/java-design-patterns/blob/gh-pages/pages/2about.md)

**Comment by mafagafogigante** [comment]
OK. I just thought you had inserted it in there for some weird reason. I saw it with Vim, don't like to use GH for this.

Also, why this naming? Can't we have about.md and patterns.md? Is there any reason for the number? If we only have one page, is there any reason left for it?

**Comment by noobxgockel** [comment]
Number was used when there were multiple pages to properly arrange em in the navbar. So yes, i'd keep it for that reason.

**Comment by mafagafogigante** [comment]
If we have only one page that wouldn't be necessary. Also, it is just a dirty hack, jekyll certainly has a superior way to solve this. You could sort using Liquid, I suppose.

**Comment by noobxgockel** [comment]
The FAQ would be an example that might get an extra page. And yes its a hack, but its how the theme maker did it. But if you want to change it feel free to make a pull request, i'd be happy to merge it C:
I'd do it myself but im kinda busy at the moment. Most of the time i can just organize stuff at my workplace, but not really code.
