### ISSUE TITLE
Document agreed Java guidelines to README.md

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#221]
To keep the things in sync and properly formatted we need to follow some style guide.
My vote is for [Google Style Guide](https://google.github.io/styleguide/javaguide.html) as it is used in many open source projects. Other option is to follow Oracle coding convention.

Google Style guide configuration for IDE
 - [Eclipse configuration](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml)
 - [IntelliJ configuration](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml)

Tasks to complete

- [x] Add agreed guideline in How to contribute section
- [x] Provide links to IntelliJ and Eclipse configurations for the same

**Comment by iluwatar** [comment]
I can live with the Google guide.

**Comment by iluwatar** [comment]
Maybe we can change this issue title to document the agreed conventions to `README.md`

**Comment by npathai** [comment]
@iluwatar I have changed the title. Should we target changing existing pattern implementations with this issue?

**Comment by iluwatar** [comment]
I think we should. But this can be another task.

**Comment by npathai** [comment]
@iluwatar Sure. Maybe I will be able to squeeze in some time this weekend for it.
