### ISSUE TITLE
Explanation for Collection Pipeline

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2215]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by hindu-muppala** [comment]
@iluwatar, I am interested to work on this issue.Will you assign this to me?

**Comment by hindu-muppala** [comment]
@iluwatar ,Can I know should I add about collection pipeline in existing folder, or should I create new folder and add the explanation ?

**Comment by iluwatar** [comment]
We need to provide a better explanation for the pattern in https://github.com/iluwatar/java-design-patterns/blob/master/collection-pipeline/README.md 

More info in https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute 

Check out the other patterns for good examples

**Comment by hindu-muppala** [comment]
@iluwatar ,is there any guide related to the symbols used in the class diagram. So, that I can understand the classes better. At present, I felt difficulty when I am implementing the class diagram as example.

**Comment by iluwatar** [comment]
The class diagram is generated automatically from the code by [uml-reverse-mapper](https://github.com/iluwatar/uml-reverse-mapper) plugin

**Comment by hindu-muppala** [comment]
@iluwatar ,I notice the example suite to class diagram in the Collection Pipeline repo. I have a doubt ,should I include the example in the repo or I should create another example?

**Comment by iluwatar** [comment]
Ah, I see there is a class diagram generated with another plugin. I don't mind if you want to use the existing class diagram or generate a new one with uml-reverse-mapper. Both alternatives work.
