### ISSUE TITLE
Explanation for Command Query Responsibility Segregation (CQRS)

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2217]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by SkSadaf** [comment]
I'm excited to contribute to this project, and I'd like to start by working on this issue as my first contribution. Could you please assign this issue to me? I would greatly appreciate it if you could provide some guidance on how to get started with addressing this issue.

**Comment by SkSadaf** [comment]
I've updated the pattern documentation in pull request #2590 with improvements. Please review it so that I can continue enhancing the documentation for other patterns.
