### ISSUE TITLE
Explanation for Data Mapper

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2220]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by XianWu99** [comment]
Hi, I want to take this issue(I have taken this issue before but was closed)

**Comment by XianWu99** [comment]
Sorry to bother you, but I accidentally removed myself as the issue assignee, can you assign this issue to me again. Thank you so much!
