### ISSUE TITLE
Explanation for Delegation

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2221]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by hemanthsvs27** [comment]
Hi @iluwatar, I would like to work on this issue. Please assign it to me.
