### ISSUE TITLE
Explanation for Double Checked Locking

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2224]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by lukaszosowicki** [comment]
Hi @iluwatar, I can pick this issue, could you please assign me?
