### ISSUE TITLE
Explanation for Event Driven Architecture

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2227]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by JabezBrew** [comment]
I'll take this @iluwatar

**Comment by JabezBrew** [comment]
@iluwatar Need a little bit of clarification. Am I adding the definition (with all the listed components) to the current readme? if so, the current readme already has a real world examples section. so?

**Comment by iluwatar** [comment]
That's handled already then, so what's left is just filling out the rest of the sections
