### ISSUE TITLE
Explanation for Event Sourcing

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2228]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by JabezBrew** [comment]
I'll take this @iluwatar

**Comment by JabezBrew** [comment]
@iluwatar how should I structure the readme if wikipedia doesn't have an article on the topic? just ignore the what wikipedia says section?

**Comment by iluwatar** [comment]
Yeah, either replace Wikipedia with some other credible source like book/article or then just leave it out.
