### ISSUE TITLE
Explanation for Feature Toggle

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2230]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by JackH408** [comment]
Hi! Could I please be assigned to this issue?

**Comment by JackH408** [comment]
Hey Iluwatar! I've finished my addition, please let me know if you need me to change anything!
