### ISSUE TITLE
Explanation for Front Controller

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2232]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by ved-asole** [comment]
Hi @iluwatar, I would like to take care of the above request/feature. Please assign it to me.
