### ISSUE TITLE
Explanation for Hexagonal Architecture

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2235]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by k1w1dev** [comment]
Hello ! I can have a go at this, can you please assign this to me? Thanks.
