### ISSUE TITLE
Explanation for Lazy Loading

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2237]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by satyajitbhatt** [comment]
Hello @iluwatar I want to contribute in this issue, if you give me an opportunity to solve this isssue then I'll try to give my best.

Thank you...!!

**Comment by ved-asole** [comment]
Hi @iluwatar, I would like to take care of the above request/feature. Please assign it to me.

**Comment by iluwatar** [comment]
@satyajitbhatt are you working on it?

**Comment by satyajitbhatt** [comment]
Right now I'm not working on this part...!!
