### ISSUE TITLE
Reformat existing code using Google Style Guide

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#224]
This issue is related to #221 . With this issue we will re-format existing implementation to confirm to Google Style guide.

**Comment by iluwatar** [comment]
https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml does not seem to work in Eclipse Mars.

**Comment by npathai** [comment]
@iluwatar I will take a look.

**Comment by iluwatar** [comment]
It has been suggested that we take into use [Maven checkstyle](https://maven.apache.org/plugins/maven-checkstyle-plugin/) plugin.

**Comment by npathai** [comment]
@iluwatar Yes good point. It will reduce PR review effort.

**Comment by iluwatar** [comment]
Checkstyle was added in a033c079f7d1c49f1736fb9d87fc281deadc2dbd

**Comment by iluwatar** [comment]
I updated the instructions at https://github.com/iluwatar/java-design-patterns/wiki/3.-Coding-conventions

**Comment by npathai** [comment]
@iluwatar The style guide worked for me in Eclipse Mars. To make sure this is how I imported it:
`Java > Code Style > Formatter > Import`

**Comment by iluwatar** [comment]
Are you importing this https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml? 

I'm getting "Problems reading profiles from XML Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character."

**Comment by npathai** [comment]
Build no of eclipse: `20150621-1200`
I get a version compatibility warning while importing but once I skip it, works fine.

**Comment by iluwatar** [comment]
Strange, I have the same version.

**Comment by Jahhein** [comment]
I was able to import these settings into intellij ultimate edition using an eclipse preferences plugin and use the reformat whole project feature. I have yet to make sure I meet all standards with what I have added. Is this still an issue to be resolved?

**Comment by iluwatar** [comment]
@Jahhein That is great news. Would you create a pull request?

**Comment by npathai** [comment]
@Jahhein Yes its still unresolved. Awaiting your PR.

**Comment by Jahhein** [comment]
Will do, double checking to ensure all is correct. Intellij has a problem with spacing after class headers, and brackets, even if it is in the settings.

**Comment by mafagafogigante** [comment]
@Jahhein I know it has been a while, but if you need help, I may be useful. I have configured Intellij IDEA to a fork of Google Java Style I made, and for what I saw, it can be almost 100% compliant to the original style guide.

**Comment by mafagafogigante** [comment]
@ankurkaushal Thanks for doing this.

**Comment by mafagafogigante** [comment]
BTW, are we there already? 100% compliance?

**Comment by ankurkaushal** [comment]
I guess we are :) Let me know if I could help with anything else :)

**Comment by Lonzak** [comment]
@iluwatar I also got the exception (

> Problems reading profiles from XML Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.

But when I opened the file I realized that I tried to download the file from the github webpage thus the **content is an HTML file and NOT the XML file**! If you do a real download it works...

**Comment by iluwatar** [comment]
Thanks for sharing this @Lonzak
