### ISSUE TITLE
Explanation for Marker Interface

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2240]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by satyajitbhatt** [comment]
Hello @iluwatar I want to contribute in this issue. If you give me an opportunity for contribute then I'll try to give my best.

Thank you...!!

**Comment by satyajitbhatt** [comment]
@iluwatar I have one question for this issue, As per my understanding it's right steps which I'm following right now ?

Step - 1 : Real world example for Marker Interface
Step - 2 : In plain words explain What is Marker Interface and it's usage
Step - 3 : What Wikipedia says ?
Step - 4 : Programmatic example for Marker Interface

So, tell me if I clone this project then practical example will be added but for theory scenario where I need to add that explanation ?

**Comment by iluwatar** [comment]
Take a look at the other pattern `README.md` files, e.g. https://github.com/iluwatar/java-design-patterns/blob/master/abstract-factory/README.md Follow the example and fill the explanation for this pattern using the same style.

**Comment by satyajitbhatt** [comment]
Thank you...!! @iluwatar For the suggetion.
