### ISSUE TITLE
Explanation for Master-Worker

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2241]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by sanchitbansal10** [comment]
hi @iluwatar , can I take this up? Thanks

**Comment by sanchitbansal10** [comment]
hi @iluwatar , have opened this PR: https://github.com/iluwatar/java-design-patterns/pull/2583
Thanks
