### ISSUE TITLE
Explanation for Model-View-Presenter

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2243]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by prasad-333** [comment]
@iluwatar Raised PR https://github.com/iluwatar/java-design-patterns/pull/2303 . Kindly review.

Thanks
