### ISSUE TITLE
Explanation for Monad

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2245]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by Chant3ll3** [comment]
Hi @iluwatar I would like to contribute to this issue. If you give me the opportunity, I will try my best to solve it. Thank you!
