### ISSUE TITLE
Explanation for Mute Idiom

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2247]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by ComplexOW** [comment]
Hi @iluwatar, I would like to contribute to this issue. Could you please assign this to me?
