### ISSUE TITLE
Explanation for Producer-Consumer

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2253]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by ManviGoel26** [comment]
I have added the explanation for this design pattern in #2179

**Comment by ManviGoel26** [comment]
@iluwatar Requesting for a review and adding the hactoberfest tag.
