### ISSUE TITLE
Explanation for Resource Acquisition Is Initialization

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2257]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by ComplexOW** [comment]
Hi @iluwatar, I would like to contribute to this issue. Could you please assign this to me?

**Comment by nooynayr** [comment]
I would like to contribute, would I be able to work on this? Also to confirm, is this in regards to java and not C++?

**Comment by iluwatar** [comment]
Yes, everything in this repository is in Java
