### ISSUE TITLE
Explanation for Role Object

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2258]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by hindu-muppala** [comment]
@iluwatar ,Can you assign this issue to me?

**Comment by damlaYasarr** [comment]
can I make it? So assing to me please.

**Comment by hindu-muppala** [comment]
I want some time. If any one willing to contribute, feel free to take over this issue.

**Comment by hheanly123** [comment]
Hi, I would to please be assigned to this issue!
