### ISSUE TITLE
Move pattern specific references to respective pattern page

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#226]
At the landing page we have references section where we have mix of both general and pattern specific references. I think it will be good to move pattern specific references to respective pattern pages. It provides better organization.

Tasks:
 - [X] Move existing pattern specific credits to respective patterns
 - [X] Add credits to pattern template section in wiki

**Comment by npathai** [comment]
@iluwatar Should we add credits general credits such as GoF book or POSA book to all the applicable patterns as well? These credits are presently in README but after #237 I doubt whether it would be the best place.
There are few advantages that the website visitor will get all the applicable references from the pattern specific page itself.

**Comment by iluwatar** [comment]
I think it would be clear that way. We would remove the credits section from the `README.md` entirely and put the information under the corresponding patterns.

**Comment by npathai** [comment]
Lets get it done already. I am back. How should we proceed with remaining references @iluwatar . Some of the books are generic books like Effective Java, Java collections and generics, where should we place them on the website?

**Comment by iluwatar** [comment]
Effective Java mentions Singleton and Builder patterns.

**Comment by iluwatar** [comment]
Java Generics and Collections reference has come with generic Observer example.

**Comment by iluwatar** [comment]
This is for Servant pattern: Let's Modify the Objects-First Approach into Design-Patterns-First

**Comment by iluwatar** [comment]
This is for Null Object: Pattern Languages of Program Design

**Comment by iluwatar** [comment]
This link is for Intercepting Filter and Front Controller: http://www.javagyan.com/tutorials/corej2eepatterns

**Comment by iluwatar** [comment]
Functional Programming in Java mentions the following patterns: Decorator, Execute Around and Strategy.

**Comment by iluwatar** [comment]
Patterns of Enterprise Application Architecture was added by you @npathai I think?

**Comment by iluwatar** [comment]
Spring Data is used in Repository.

**Comment by iluwatar** [comment]
J2EE Design Patterns mentions at least the following patterns: Business Delegate, DAO, DTO, Decorator, Adapter, Lazy Loading, MVC, Publish-Subscribe and Value Object.

**Comment by npathai** [comment]
Thanks a ton @iluwatar for your help. I will complete this task tomorrow. And I am not sure about Patterns of Application Architecture. I will take a look. I added POSA reference.

**Comment by iluwatar** [comment]
@npathai can this issue be closed?

**Comment by npathai** [comment]
Yes i was abt to close it.
