### ISSUE TITLE
Explanation for Servant

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2260]
In this issue, let's add a proper explanation for the pattern.

Acceptance criteria

- The pattern's README.md has been amended with an explanation
- The explanation consists of
  - Real world example
  - In plain words
  - Wikipedia says
  - Programmatic example

**Comment by mm-saiful6854** [comment]
Hello. I want to nominate myself for written explanation about Servant design pattern.

**Comment by ved-asole** [comment]
Hi @iluwatar, I would like to take care of the above feature. Please assign it to me.
