### ISSUE TITLE
Information meant for project developers should be in the wiki

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#228]
`README.md` is the front page of the web site. We should target it for the "users" of the site, not for the project developers. Let's move information meant for the project developers into the wiki.

**Comment by iluwatar** [comment]
I'm thinking changes as follows. Comments are welcome.

Move from readme to wiki
- how to contribute
- versioning
- license

Add to readme
- link to developer information in wiki

Add to wiki
- agreed coding conventions
- agreed pattern format
- instructions how to update the web site
- agreed working methods (e.g. peer reviews, monthly releases)

**Comment by npathai** [comment]
:+1:

**Comment by noobxgockel** [comment]
I think the license should stay in the readme, its a defacto standard on github to let it sit there (at least from what i have seen). But the rest sounds good to me. :+1:

**Comment by mafagafogigante** [comment]
Code-wise this project not even needs a license, as no one is ever going to reuse source code from this repository in production. A "more artistic" license could be used to prevent or restrict resource usage in books if there was a reason for it.

@noobxgockel Not **the license**, but just a license note (as it currently is).

If it is just a note in the very bottom of the readme it is not a problem and better than not having it.

**Comment by iluwatar** [comment]
Ok, we can leave the license note. The rest of the stuff I mentioned is going to move [here](https://github.com/iluwatar/java-design-patterns/wiki).
