### ISSUE TITLE
Translate to Japanese

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2281]
This task tracks the translation of the patterns. More information about the translation process is available at https://github.com/iluwatar/java-design-patterns/wiki/15.-Support-for-multiple-languages

Acceptance criteria

- The patterns have been translated
- The patterns can be browsed in Github and on the website https://java-design-patterns.com

**Comment by shogohida** [comment]
Hi @iluwatar, I will work on this because I'm Japanese! It seems there are fewer materials that were translated into Japanese compared to other languages...
