### ISSUE TITLE
Fix language folders and YAML frontmatters

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2283]
Some translation folders have been named incorrectly and are not in line with the [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

Additionally in this task, we are going to check that all the translated patterns conform to the updated YAML frontmatter specification described in https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

Acceptance criteria

- Marathi language folder renamed to localization/mr
- Nepali language renamed to localization/ne
- The YAML frontmatter of all the translated patterns has been checked
  - Conforms with https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute
  - Has the same values as the main English pattern

**Comment by bhati00** [comment]
Hello Sir, 
Its my first time to contributing open source project.
in the above task , did we just have to change readme.md file according to rule above you mentioned in a link and change the folder names to localization/language ?

**Comment by iluwatar** [comment]
Yes, that's all there is. Would you like to try it @bhati00 ?

**Comment by bhati00** [comment]
Much appreciated your quick response ,Sir. 
 Yes i do want to try.

**Comment by bhati00** [comment]
i made the pull request @iluwatar
