### ISSUE TITLE
Page Object pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#229]
http://martinfowler.com/bliki/PageObject.html

**Comment by colinbut** [comment]
Hi @iluwatar 
I would like to contribute to your project as i have a deep interests in design patterns.

I have been using this pattern for implementing our UI tests using Selenium in the last 4-5 months so i know this pattern very well. 

Any chance i can work on this particular pattern?

**Comment by iluwatar** [comment]
That is great news. Please go ahead @colinbut - your contribution is welcome!

**Comment by iluwatar** [comment]
@colinbut any updates? Are you working on this?

**Comment by colinbut** [comment]
@iluwatar Apologies, not had the time to start this due to important work commitments that came up lately.

Feel free to un-assign me from this issue, otherwise i will commence work on this asap.

**Comment by iluwatar** [comment]
@colinbut no problem, you can continue on this when you are able.

**Comment by colinbut** [comment]
Pull Request created for this pattern - #434
