### ISSUE TITLE
Redux pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#232]
This is a presentation tier pattern, similar to Flux .

http://rackt.github.io/redux/

**Comment by geniusgeek** [comment]
This pattern uses Model , Update , View as described in Elm. But in this case, it view action in form of tree nodes (as Commands in Command Pattern) with different states(as State in State pattern) for which all current actions can be tracked from root. I think this pattern can be implemented in java using Pattern Compound of (Composite, Command, State and Iterator pattern). I will be happy to attempt an implementation of this

**Comment by npathai** [comment]
@geniusgeek Sure we welcome contribution. Go ahead. If you do decide to pick it up then I will change the status of issue.

**Comment by geniusgeek** [comment]
i will take up the redux pattern implementation today

**Comment by iluwatar** [comment]
Closing this as dupllcate of #301
