### ISSUE TITLE
Context Object pattern

### ISSUE THREAD

**Issue by ekostadinov** [iluwatar/java-design-patterns#233]
This pattern helps avoid using protocol-specific system information outside of its relevant context. It forces only the relevant APIs to be exposed and decouples the components and services from the protocol specifics of system information. We use it to encapsulate state in a protocol-independent way to be shared throughout the application.

**Comment by iluwatar** [comment]
Do you have a reference book or link describing the pattern?

**Comment by ekostadinov** [comment]
This is the official [description](http://corej2eepatterns.com/ContextObject.htm) of the pattern

**Comment by geniusgeek** [comment]
The Context Object Simply hides implementation details from clients in a particular context and their invocation in a protocol specific system

**Comment by ekostadinov** [comment]
Well, [Singleton](https://github.com/iluwatar/java-design-patterns/blob/master/singleton/index.md) simply ensures that a single instance will exists.

**Comment by ekostadinov** [comment]
Will I get permission to publish my branch and changes?

**Comment by iluwatar** [comment]
https://www.dre.vanderbilt.edu/~schmidt/PDF/Context-Object-Pattern.pdf

**Comment by npathai** [comment]
A.K.A Ambient Context, Scope

https://aabs.wordpress.com/2007/12/31/the-ambient-context-design-pattern-in-net/

**Comment by Chak-C** [comment]
Can I take on this issue?

**Comment by iluwatar** [comment]
Ok @Chak-C
