### ISSUE TITLE
Broken linkage on Chinese localization document

### ISSUE THREAD

**Issue by limingho456** [iluwatar/java-design-patterns#2333]
Broken linkage [Java CI with Maven](https://github.com/iluwatar/java-design-patterns/workflows/Java%20CI%20with%20Maven/badge.svg) on the following Chinese localization README file.

https://github.com/iluwatar/java-design-patterns/blob/master/localization/zh/README.md

**Comment by Pawank06** [comment]
Hello ! I am new in opensource and I am also familiar with java I want to use this skill in real-world project. can anyone help me too start this project or how can I solve this .

**Comment by iluwatar** [comment]
There is just a broken link in the mentioned document @Pawank06 I suppose it should be an easy fix.

**Comment by limingho456** [comment]
> Hello ! I am new in opensource and I am also familiar with java I want to use this skill in real-world project. can anyone help me too start this project or how can I solve this .

You can fix it by updating the path from
`https://github.com/iluwatar/java-design-patterns/workflows/Java%20CI%20with%20Maven/badge.svg`
to
`https://github.com/iluwatar/java-design-patterns/workflows/Java%20CI/badge.svg`
