### ISSUE TITLE
CRPT idiom

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2342]
Implement Curiously Recurring Template Pattern (CRPT) idiom in Java. See the example at https://nuah.livejournal.com/328187.html

Acceptance criteria

- CRPT pattern implemented according to guidance at https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

**Comment by AddeusExMachina** [comment]
Hi @iluwatar, can I work on this issue?

**Comment by AddeusExMachina** [comment]
Thanks for assigning me this issue. My implementation idea is based on the use of method chaining in a hierarchy of objects like in the link example

**Comment by AddeusExMachina** [comment]
I've included a new example that was inspired by an example from Effective Java. These examples can be found in the [space](https://github.com/AddeusExMachina/java-design-patterns/tree/crtp/crtp/src/main/java/crtp/space) and [fight](https://github.com/AddeusExMachina/java-design-patterns/tree/crtp/crtp/src/main/java/crtp/fight) packages respectively. Please let me know if you prefer to keep both examples or just one of them.
