### ISSUE TITLE
Uniform handling for H2 databases

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2366]
At the moment, many of the patterns utilize H2 databases to demonstrate data access (search for `jdbc:h2`). The problem is that we don't have a unified approach. Some of the patterns use file-based database written somewhere under the home directory and some use in-memory databases. Perhaps we could use in-memory databases everywhere so the user's disk would not be cluttered? If not possible, at least store the database files under the same directory.

Acceptance criteria

- H2 database handling is unified

**Comment by shivu2002a** [comment]
@iluwatar Can I work on this issue?

**Comment by Pratik-kp** [comment]
I would like to work on this issue, can I join?

**Comment by takikuba** [comment]
Hello, I don't see any PR related to this problem. 
I still see both h2 db versions in the code, please assign this to me.
