### ISSUE TITLE
Enable the MongoDB tests in hexagonal pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2368]
Currently, the tests `MongoBankTest`, `MongoTicketRepositoryTest`, and `MongoEventLogTest` are disabled supposedly because they require a real MongoDB present. Let's try to re-enable the tests either by utilizing embedded MongoDB or using mocking techniques.

Acceptance criteria

- Hexagonal MongoDB tests are enabled and working

**Comment by Taz03** [comment]
id like to work on this

**Comment by Taz03** [comment]
sorry, but i was unable to solve this. u can unassign me now

**Comment by mohanaraosv** [comment]
Please assign this to me

**Comment by boscha1** [comment]
Assign this to me please

**Comment by k1w1dev** [comment]
Hi, I have a working solution using TestContainers, can you please assign this to me and I'll raise a PR for review  ?

<img width="648" alt="image" src="https://github.com/iluwatar/java-design-patterns/assets/121696782/7be5cd24-9136-4824-afec-1e031acc7f74">

**Comment by iluwatar** [comment]
Fixed in https://github.com/iluwatar/java-design-patterns/pull/2511
