### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#237]
- [ ] Remove Self-Links, if really still wanted we could use Github's permalink feature (e.g. https://github.com/iluwatar/java-design-patterns#how-to-contribute- )
- [ ] Remove TOC, if the Readme is as small as now, it doesnt make a lot of sense to keep it
- [ ] Remove Back to top arrows, as mentioned above, the readme isnt that long too need this feature
- [ ] Make the FAQ an extra page, because its related to patterns directly and should be represented like patterns. Maybe we should even somehow integrate the questions in the pattern pages ? (with some jekyll magic)

This would make the website look better and generally make more sense. The Readme isnt that long anymore to loose the overview.
Thanks to @mafagafogigante for bringing this up.

@iluwatar what do you think about the ideas here?

**Comment by iluwatar** [comment]
Yes, this totally makes sense since the content of the `README.md` is so short now. And yes, FAQ could be externalized somehow (I'm not sure what are your thoughts).

**Comment by mafagafogigante** [comment]
Let's just transfer the FAQ and Credits to the wiki. Maybe mention that the wiki has this and that...

As mentioned, TOC for 5 items is unnecessary.

Lastly, Intro, How to contribute, and License are not OK if we are only going to have three headers, Intro actually describes what the repository has so it could be **About** or What is this? (about is cleaner).

**Comment by iluwatar** [comment]
I'm thinking the wiki to be the place for developer information. FAQ and Credits are aimed at the users of the site, so in my opinion they do not belong in the wiki. Using **About** instead of **Introduction** may be an improvement.
