### ISSUE TITLE
Java 17: Start using text blocks

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2375]
Available since Java 15, we can now use the text blocks feature. See the tutorial at https://www.baeldung.com/java-text-blocks

Acceptance criteria

- Text blocks have been applied throughout the repository to improve readability

**Comment by Damzxyno** [comment]
Hi @iluwatar !
Can you assign me this issue? This task will get me acquinted with the project as a whole.

**Comment by amol-can** [comment]
Hey is this issue still in progress, @iluwatar can I help with it?

**Comment by iluwatar** [comment]
@Damzxyno are you still working on it?

**Comment by CoderRahul01** [comment]
@Damzxyno Hey are you working on it ..... Can I give you a help

**Comment by iluwatar** [comment]
@Damzxyno is not responding, so I guess we can reassign the issue. Go ahead @CoderRahul01

**Comment by CoderRahul01** [comment]
> @Damzxyno is not responding, so I guess we can reassign the issue. Go ahead @CoderRahul01

Thank you for handing over me this issue

**Comment by Damzxyno** [comment]
Apologies for the late response, I had an issue with my machine for a while. @iluwatar @CoderRahul01

**Comment by sarswat001** [comment]
@CoderRahul01 Are you still working on it?

**Comment by ved-asole** [comment]
Hi @iluwatar , I would like to take care of the above request/feature. Please assign it to me.

**Comment by Manojkumarchow** [comment]
Hi @iluwatar I would like to have a look into this issue, if no one is working on it. Can you please assign it to me?

Thanks 🙂

**Comment by Manojkumarchow** [comment]
Hi @iluwatar 

Raised a PR for this issue [Text Blocks](https://github.com/iluwatar/java-design-patterns/pull/2791).

Can you please review this PR? I am unable to assign this 🙂
