### ISSUE TITLE
Java 17: Start using records

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2377]
Available since Java 16, we can now use the record type for immutable classes. It's well described at https://dzone.com/articles/what-are-java-records

Acceptance criteria

- The repository code has been refactored to use the record type

**Comment by bharathkalyans** [comment]
Hey is this issue still in-progress, can I help with it??

**Comment by iluwatar** [comment]
Assigned to @ayushanand308, but maybe there's a way to split the work?

**Comment by bharathkalyans** [comment]
I think @ayushanand308  is not quite active right now!!
Sure, would love to split the work 😃

**Comment by iluwatar** [comment]
Reassigned to @bharathkalyans due to inactivity

**Comment by MugheesQasim** [comment]
After finding out there is no assignee for this issue, I have refactored the codebase to use the record classes. It would be great if this issue can be re-assigned to me. I have opened a new Pull Request which needs to be reviewed. Following is the link to the PR:
https://github.com/iluwatar/java-design-patterns/pull/2505
