### ISSUE TITLE
Java 17: Stream.toList()

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2378]
Since Java 16, there is now the method Stream.toList() available. This allows us to write more concise code when using streams. Good tutorial is available at https://www.baeldung.com/java-stream-to-list-collecting

Acceptance criteria

- The repository code has been refactored to use the Stream.toList() method

**Comment by Ap284** [comment]
Hi, I'll collaborate for this issue.

**Comment by ayushanand308** [comment]
Hey @Ap284 ,are you still working on the issue?

**Comment by Ap284** [comment]
Yes, I am woking on build fix
