### ISSUE TITLE
Using headings instead of bold text inside index.md

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#238]
Currently we are using bold text as a heading of a chapter (Intent, Applicability, Real world examples, ...)
Example: ``` **Intent:** ```
Correct me if i'm wrong but i think this is a relic from the time before the great split. Nowadays we wont clutter the readme with too much headings.

I think turning those into Headings would improve the readability, the overview and, if i re-implement the TOC in the sidebar, even the navigation.

If we do that we should use at least the second level heading, as the first level is the name of the pattern.

**Comment by noobxgockel** [comment]
@iluwatar, @npathai any thoughts on this ?
If this feature is wanted i could try and script something up.

**Comment by iluwatar** [comment]
Good that you brought this up. When I look at it the bold text seems rather small for the purpose. :+1: for the bigger headings.

**Comment by npathai** [comment]
:+1: from me too. Go for it.

**Comment by fluxw42** [comment]
Just created [this script](https://gist.github.com/fluxw42/464820d08e3b567fda48) to update the bold titles with a level 2 header. Running this gives 3d642cd. Does that look ok to you?

**Comment by noobxgockel** [comment]
With the PR merged and the wiki edited this issue is fixed.

**Comment by iluwatar** [comment]
:+1: Looks great
