### ISSUE TITLE
Code snippet of **_<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>_** in _**org.slf4j:jcl-over-slf4j:jar:1.7.16:compile**_ (loaded version):

### ISSUE THREAD

**Issue by vangirja** [iluwatar/java-design-patterns#2395]
Code snippet of **_<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>_** in _**org.slf4j:jcl-over-slf4j:jar:1.7.16:compile**_ (loaded version):
![01](https://user-images.githubusercontent.com/46306510/55683799-534bcb80-5976-11e9-800a-a3b00a00cafa.png)

Code snippet of **_<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>_** in _**commons-logging:commons-logging:jar:1.2:compile**_ 
 (shadowed but expected to invoke method):
![02](https://user-images.githubusercontent.com/46306510/55683800-5777e900-5976-11e9-82f0-3e7a8e44bff2.png)
**.......**

As a result, these conflicting method included in **commons-logging:commons-logging:jar:1.2:compile** deals with different cases, which changes the control flows and data flows. So being forced to use these methods in **org.slf4j:jcl-over-slf4j:jar:1.7.16:compile** may lead to inconsisitent semantic behaviors.

_Originally posted by @HelloCoCooo in https://github.com/iluwatar/java-design-patterns/issues/868#issuecomment-480587255_

**Comment by jatinsihag234** [comment]
anyone woring on this issue??

**Comment by iluwatar** [comment]
Not at the moment. Would like to to work on it @jatinsihag234?

**Comment by jatinsihag234** [comment]
> Not at the moment. Would like to to work on it @jatinsihag234?

Yes sir i wanna work on it

**Comment by mohanaraosv** [comment]
Please assign this to me.

**Comment by jatinsihag234** [comment]
> Please assign this to me.

bro i forget my github id pass now i am free and active i am alread working on that
