### ISSUE TITLE
Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties

### ISSUE THREAD

**Issue by girolamo-giordano** [iluwatar/java-design-patterns#2399]
When you try to build the project using `./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonarit` gives the following error:

### Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project java-design-patterns: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator

Both in local and when you try to do the pull request. 

If the project is no longer in the sonarcloud, it can be a suggestion to remove the following dependencies:

```
<sonar.host.url>https://sonarcloud.io</sonar.host.url>
<sonar.organization>iluwatar</sonar.organization>
<sonar.projectKey>iluwatar_java-design-patterns</sonar.projectKey>
<sonar.moduleKey>${project.artifactId}</sonar.moduleKey>
<sonar.projectName>Java Design Patterns</sonar.projectName>
```

and to build using: `./mvnw clean verify`

In order to continue to build the project and do pull request without building errors.

**Comment by iluwatar** [comment]
Kind of works, see https://github.com/iluwatar/java-design-patterns/pull/2398, but maybe we can improve it
