### ISSUE TITLE
Upgrade to Spring Boot 3.x

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2407]
Spring Boot has recently released 3.x. In this task we are going to upgrade the dependency. There is a helpful migration guide available here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide

Acceptance criteria

- Spring Boot upgraded to 3.x

**Comment by MihSawant** [comment]
Hello, I can try to help out in this case, which projects need to be upgraded to latest version ?
Any changes need to be made

**Comment by iluwatar** [comment]
@MihSawant thanks for your help! You can find out the projects by looking at the pom.xml files. I think there are about 10 or so submodules that use Spring Boot. Hopefully the migration guide highlights the issues we need to tackle.

**Comment by tyagi-data-wizard** [comment]
Hello @iluwatar ,
I am new to open source and would like to contribute to this issue, please let me know if its okay. 
I went ahead and looked into the pom files of few of the projects ([price-mcirservice](https://github.com/iluwatar/java-design-patterns/blob/d20993a9f8518012b5d7c779e62f05a7420ab9e5/api-gateway/price-microservice/pom.xml), had some doubts :
1. In parent tag, springboot is not mentioned.
![image](https://user-images.githubusercontent.com/56214203/225973289-ef8bfddc-7a06-4525-bada-b04b2773cac0.png)

2. Coming to the dependencies, I am not seeing the version given, do I add them explicitly ? 
![image](https://user-images.githubusercontent.com/56214203/225973425-165395de-1a66-44ef-864a-6a23342c5016.png)

**Comment by Harsh4902** [comment]
@iluwatar I want to contribute to this issue, can I??

**Comment by tyagi-data-wizard** [comment]
Hello @Harsh4902 ,
I was looking on working on it but if you want to collaborate I am open to it!

**Comment by Harsh4902** [comment]
Sure, I am ready to collaborate 👍

**Comment by vishalsingh2972** [comment]
@iluwatar @Harsh4902 @tyagi-data-wizard is this issue resolved or still open, I would like to help!

**Comment by Harsh4902** [comment]
Hey @vishalsingh2972 , me and @tyagi-data-wizard working on it. We are happy if you join us.

**Comment by vishalsingh2972** [comment]
@Harsh4902 I would like to join, how far have you both done....some brief update?

**Comment by MihSawant** [comment]
I made changes earlier, but i think it didn't got accepted, would like to work with you guys on this one again

**Comment by vishalsingh2972** [comment]
> I made changes earlier, but i think it didn't got accepted, would like to work with you guys on this one again

What was the issue, I think we need to change the version number in the dependencies....am I right? @MihSawant

**Comment by MihSawant** [comment]
Actually we need to change from spring 2 to spring 3, 3.0.5 version (stable) and all the projects which should then follow spring boot 3.0 features where needed.

**Comment by vishalsingh2972** [comment]
all old dependencies would work in the newer version, some dependencies which are now not compatible with spring 3 needs to be changed, only making these corrections would suffice I believe!

**Comment by vishalsingh2972** [comment]
for changing version we need to make changes in "spring-boot-starter-parent" in pom.xml but I don't see that here anywhere...which version of spring boot are they using currently any idea? Also @MihSawant could you send me your earlier PR that wasn't accepted want to have a look!

**Comment by vishalsingh2972** [comment]
@MihSawant If you don't mind can you unassign I want to give it a try, also @iluwatar can you assign it to me if @MihSawant unassigns!

**Comment by vishalsingh2972** [comment]
@MihSawant If you don't mind can you unassign yourself I want to give it a try, also @iluwatar can you assign it to me if @MihSawant unassigns!

**Comment by Ayush-Thakur-geek** [comment]
hey, I'm new to open source and wanted to work on this.
Is anybody working on it,?
If yes can I collaborate.

**Comment by vishalsingh2972** [comment]
@iluwatar could you please check PR updated spring boot version #2526

**Comment by vishalsingh2972** [comment]
@iluwatar could you please check PR https://github.com/iluwatar/java-design-patterns/pull/2526

**Comment by Pratik-kp** [comment]
Hi @iluwatar @Harsh4902 Can I also join you guys in this project?

**Comment by ved-asole** [comment]
Hi @iluwatar  @Harsh4902  Can I also join you guys in this project?

**Comment by Harsh4902** [comment]
> Hi @iluwatar @Harsh4902 Can I also join you guys in this project?

Currently, I am not working on this issue. You can individually work on this issue.

**Comment by iluwatar** [comment]
@Pratik-kp are you working on it?

**Comment by Deeptarko** [comment]
@iluwatar Can I work on this issue if it is not resolved?

**Comment by iluwatar** [comment]
Please note that it's possible to split the issue and upgrade the patterns one by one

**Comment by Deeptarko** [comment]
@iluwatar How can I first only change the version in a single project ? Is there a way that I can modify the version in a single project first?

**Comment by nilandev** [comment]
@Deeptarko are you working on this issue?

**Comment by iluwatar** [comment]
I've split the issue by pattern and will close this one. See

- #2821 
- #2822 
- #2823 
- #2824 
- #2825 
- #2826 
- #2827
