### ISSUE TITLE
Add Search Feature

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#243]
As discussed in Gitter, we should add a search feature for all the patterns. To enable the feature as soon as possible Google CSE should be used.
I allready created a search engine for it, here is the link:
https://cse.google.com/cse/publicurl?cx=008960609897446712051:upn_v7v8dba

**Comment by npathai** [comment]
:+1:

**Comment by iluwatar** [comment]
Well done :+1:

**Comment by noobxgockel** [comment]
@iluwatar thanks C:
sorry it took so long, had a busy time setting up my linux mint and fixing wierd layout issues when using bootstrap with google cse :neutral_face:
