### ISSUE TITLE
Refactor Layers Architecture

### ISSUE THREAD

**Issue by JabezBrew** [iluwatar/java-design-patterns#2450]
Hi, I want to implement these refactorings on the layered architecture pattern:

Annotating the `App` class with `@SpringBootApplication` and calling the `SpringApplication.run(App.class, args)` method in the `main` method creates an application context for us so there would be no need to create an application context like what has been done in the services layer to manage the beans.

Also want to refactor and use annotation based configuration instead of the `ClassPathXmlApplicationContext` configuration as that's more recommended in new spring applications.

All this will help autowire the daos into the services layer for easier DI without having to use `context.getBean()` everytime you want to use it.

Lastly, I think the daos should extend `PagingAndSortingRepository<T,ID>` as it extends `CrudRepository` but also adds additional methods that help return responses in pages and in a desired manner too.

I'll be glad to take these on! @iluwatar

**Comment by iluwatar** [comment]
Sounds good @JabezBrew, the proposed changes are welcome!
