### ISSUE TITLE
Update Checkstyle to 3.2.0

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2451]
The project currently uses Checkstyle 3.1.0, but there is a newer version 3.2.0 available. According to dependabot's pull request https://github.com/iluwatar/java-design-patterns/pull/2449, the upgrade is not straightforward.

Acceptance criteria

- Checkstyle upgraded to 3.2.0
- Any build issues that arise have been resolved

**Comment by rahul-raj** [comment]
@iluwatar 
Here is a PR that I started:
[https://github.com/iluwatar/java-design-patterns/pull/2464](https://github.com/iluwatar/java-design-patterns/pull/2464)

No new source code added from my side. Just the code/class name/method formatting as per checkstyle and respective changes in pom.xml and suppressions.xml
