### ISSUE TITLE
Wrong generic type for deques in command README

### ISSUE THREAD

**Issue by AddeusExMachina** [iluwatar/java-design-patterns#2462]
Hi, inside the README.md for the command pattern the Wizard class presents these two instance variables:
```java
private final Deque<Command> undoStack = new LinkedList<>();
private final Deque<Command> redoStack = new LinkedList<>();
```

The generic type for these deques should be ```Runnable``` as it is in the Wizard class under src directory

**Comment by KetanParmar03** [comment]
can you assign me this issue?

I am interest in solve this issue?

**Comment by AddeusExMachina** [comment]
Can you assign me this issue?

**Comment by jaswanthg76** [comment]
I'm new to open-sourcing and I have no clue about what I should be doing. Can anyone guide me? I have basic knowledge of java  
let me know in which way I can help you.

**Comment by AddeusExMachina** [comment]
@jaswanthg76 https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

**Comment by vatsasiddhartha** [comment]
Hey I can help in this issue, provide me  the information of issue

**Comment by AddeusExMachina** [comment]
Hi @vatsasiddhartha, the problem has actually been solved and the fix has been merged
