### ISSUE TITLE
Translate arrange-act-assert to spanish (Task of issue #2277)

### ISSUE THREAD

**Issue by KarmaTashiCat** [iluwatar/java-design-patterns#2479]
Translation of [arrange-act-assert/README.md](https://github.com/iluwatar/java-design-patterns/blob/master/arrange-act-assert/README.md) to [java-design-patterns/localization/es/arrange-act-assert/](https://github.com/iluwatar/java-design-patterns/tree/master/localization/es/) folder
Task of issue #2277

**Comment by iluwatar** [comment]
Subtask of https://github.com/iluwatar/java-design-patterns/issues/2277
