### ISSUE TITLE
Setup domain name and attach it to Github pages

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#248]
Domain java-design-patterns.com is available.

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by npathai** [comment]
:+1:

**Comment by noobxgockel** [comment]
:+1:

**Comment by iluwatar** [comment]
https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/

**Comment by iluwatar** [comment]
I don't know if this is exactly what we want but this is the situation:

http://java-design-patterns.com redirects to http://iluwatar.github.io/java-design-patterns
http://www.java-design-patterns.com redirects to http://iluwatar.github.io/java-design-patterns

**Comment by noobxgockel** [comment]
Urls like http://java-design-patterns.com/patterns/abstract-factory/ look nicer and more trustworthy to me than http://iluwatar.github.io/java-design-patterns/patterns/abstract-factory/.
Just using redirects seems kinda unnecessary to me, for that an url shortener could be used like bit.ly or goo.gl.

I'd vote for using the domain properly.

**Comment by iluwatar** [comment]
I agree. It would probaby be better the other way around:

http://iluwatar.github.io/java-design-patterns redirects to http://java-design-patterns.com

If I understand correctly the instructions this bit would do that:

> To redirect your GitHub Pages site, you must create and commit a CNAME file that contains the custom domain to your repository's root directory.

So I put the file here: https://github.com/iluwatar/java-design-patterns/blob/gh-pages/CNAME

Now in the [repository settings](https://github.com/iluwatar/java-design-patterns/settings) I can see the text:

> Your site is published at http://java-design-patterns.com.

I don't know what this does though, since the gh-pages site doesn't seem to redirect to that domain.

**Comment by noobxgockel** [comment]
Correct, but the DNS seems to be configured incorrectly, because we seem to use an apex domain instead of a subdomain.

IIRC its something like this:
```
apex: java-design-patterns.com
subdomain: java-design-patterns.iluwatar.com
```

For more Info on this topic look at those links:
* https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/
* https://help.github.com/articles/about-custom-domains-for-github-pages-sites/#apex-domains
* https://help.github.com/articles/my-custom-domain-isn-t-working/

**Comment by iluwatar** [comment]
After a bit of a struggle it seems to be hard to get it working the way I would like. The gh-pages cannot be mapped directly to java-design-patterns.com domain. It would be possible to put it to <project>.java-design-patterns.com but this is not what I'm trying to achieve.

So I started another route. I built the site with Jekyll and uploaded it to S3. Then I setup Route 53 to map java-design-patterns.com and www.java-design-patterns.com to my S3 buckets.

Now the site is available at java-design-patterns.com but there are some problems linking the pages together. I guess these are quite easy to resolve by editing the site configuration files but I'm not that familiar with the site code. @noobxgockel can you take a look at java-design-patterns.com and help me find the places in the site source code I need to edit? For example when I click the `Patterns` link it is linking me to URL http://java-design-patterns.com/java-design-patterns/patterns/ which is not quite right.

I'm hoping that we can quite easily migrate from gh-pages to a process that deploys the site to S3 via Travis configuration. The details are still a bit mystery to me but I think this is doable.

**Comment by iluwatar** [comment]
Ok, I found the configuration settings and was able to solve the page linking issues. The site seems to be working ok now.

**Comment by noobxgockel** [comment]
@iluwatar very good job! :+1:

**Comment by npathai** [comment]
Great job! :+1:
