### ISSUE TITLE
Temporal patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#249]
http://martinfowler.com/eaaDev/timeNarrative.html

Temporal Property
Snapshot
Effectivity
Audit Log
Temporal Object

**Comment by tainarareis** [comment]
Can I elaborate a proposal for this pattern?

**Comment by iluwatar** [comment]
@tainarareis Yes please, go ahead and propose.

**Comment by iluwatar** [comment]
@tainarareis are you working on this pattern? I'm about to revert `under construction` label since there is no progress.

**Comment by iluwatar** [comment]
This is issue is free for taking again.

**Comment by Jesonzavic** [comment]
Hello @iluwatar, I'm interested in working on this issue.

**Comment by iluwatar** [comment]
Ok, assigned to you @Jesonzavic
