### ISSUE TITLE
Candidate for Known Uses of Proxy

### ISSUE THREAD

**Issue by VladimirCreator** [iluwatar/java-design-patterns#2507]
I propose the UIKit's [`UIAppearance`](https://developer.apple.com/documentation/uikit/uiappearance) protocol as the known use of the proxy design pattern.

**Comment by thestbar** [comment]
Hey, I would like to work on this issue.

**Comment by RobinKumar5986** [comment]
Hey I am new to the open source contribution can any one tell me how can I contribute and request and merge the pull requests...

**Comment by damlaYasarr** [comment]
if no one solves it, can you assign it to me?

**Comment by iluwatar** [comment]
@thestbar are you working on this?

**Comment by RobinKumar5986** [comment]
Yes I am looking on this

**Comment by thestbar** [comment]
@iluwatar I thought that I just had to add it in the known uses of this part, which I added here https://github.com/iluwatar/java-design-patterns/pull/2554. Is there anything else I should do? Of course if someone has started working on the extra stuff feel free to assign this to them!

**Comment by SnehangshuChakraborty** [comment]
@iluwatar should this be closed ? looks like this is merged (asking this since this showed up under the good first issue label)
