### ISSUE TITLE
Abstract factory assertions

### ISSUE THREAD

**Issue by Jahhein** [iluwatar/java-design-patterns#252]
To follow the intent of assertion with Junit, the String of each class should be checked in the tests to ensure it's contents is what it was intended to contain.

example-
    @Test public void king() {
        final King elfKing = app.getKing(elfFactory);
        assertTrue(elfKing instanceof ElfKing);
        assertEquals(ElfKing.DESCRIPTION, "This is the Elven king!");  // Check for string contents
        assertEquals(ElfKing.DESCRIPTION, elfKing.getDescription());  // The integrity of this test relies on above assertion.
        final King orcKing = app.getKing(orcFactory);
        assertTrue(orcKing instanceof OrcKing);
        assertEquals(OrcKing.DESCRIPTION, orcKing.getDescription());
    }

**Comment by Jahhein** [comment]
Pushed a new revision with thorough testing.

**Comment by npathai** [comment]
Please create a Pull Request?
