### ISSUE TITLE
ThreadSafeDoubleCheckLocking class result what does it do?

### ISSUE THREAD

**Issue by pondered** [iluwatar/java-design-patterns#2525]
https://github.com/iluwatar/java-design-patterns/blob/cf64d6ae9a2196b0b9f190922c68e789484592eb/singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java#L59

i dont know why this use result，What does it do？

**Comment by cristivlad** [comment]
Using the extra local variable there are cases where it is said that it improves performance. Saying it differently, you can implement Double Check idiom without the local variable just fine.

**Comment by pondered** [comment]
thx
