### ISSUE TITLE
Adding Sponsorship Section

### ISSUE THREAD

**Issue by bharathkalyans** [iluwatar/java-design-patterns#2528]
* I am surprised that this repository with 25k+ forks and 82k+ stars, doesn't have a **sponsor** section.
* @iluwatar, please consider adding a sponsorship section so that it can help the project. 
* Github provides a sponsorship section or you can use a third-party payment gateway like stripe.

**Comment by bharathkalyans** [comment]
* Once the sponsor section is added, we can have a separate section in the project's README dedicated to the sponsorship.

**Comment by iluwatar** [comment]
Enabled the sponsor button in the repository settings
