### ISSUE TITLE
Dynamic proxy pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2542]
Proxies are fronts or wrappers that pass function invocation through their own facilities (usually onto real methods) – potentially adding some functionality.

Dynamic proxies allow one single class with one single method to service multiple method calls to arbitrary classes with an arbitrary number of methods.

See https://www.baeldung.com/java-dynamic-proxies

Acceptance criteria

- Dynamic proxy pattern example added to the library
- Follows the instructions at https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

**Comment by mohamedelghaouth** [comment]
Hello, I would like to work on this, can it be assigned to me, please

**Comment by pkkht** [comment]
Hi,
I am happy to work on this. This is another link that I will refer to:
[https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/proxy.html](url)

Let me know if it makes sense. Please assign to me when you are able to.

**Comment by iluwatar** [comment]
@mohamedelghaouth are you working on this? If not, please indicate so we can progress on it.

**Comment by mohamedelghaouth** [comment]
Hi, 
yes, I am working on this, 
I will try to push ma MR this week-end

**Comment by sashirestela** [comment]
@iluwatar I have worked with this Dynamic Proxy pattern in the library [simple-openai](https://github.com/sashirestela/cleverclient/blob/main/src/main/java/io/github/sashirestela/cleverclient/util/ReflectUtil.java#L12) and I know that it has been used in popular libraries such as Spring, Hibernate, Retrofit, etc., so I think I could contribute here. Just let me know if you could assign this issue to me, please?

**Comment by sashirestela** [comment]
> Hi, yes, I am working on this, I will try to push ma MR this week-end

@mohamedelghaouth have you already pushed a PR?

**Comment by iluwatar** [comment]
No sign from @mohamedelghaouth so I'll assign to @sashirestela

**Comment by sashirestela** [comment]
Forking the repo and working on this

**Comment by sashirestela** [comment]
@iluwatar The PR is ready for you revision https://github.com/iluwatar/java-design-patterns/pull/2814
