### ISSUE TITLE
Code repetition in Flyweight/README.md

### ISSUE THREAD

**Issue by rajivaPavan** [iluwatar/java-design-patterns#2546]
>https://github.com/iluwatar/java-design-patterns/blob/5b147b00367a500e8dfeac882d4b0d6a0540c6b9/flyweight/README.md?plain=1#L85
The following code is quoted from the documentation of the flyweight design pattern (link above).
```java
if (potion == null) {
      switch (type) {
        case HEALING -> {
          potion = new HealingPotion();
          potions.put(type, potion);
        }
        case HOLY_WATER -> {
          potion = new HolyWaterPotion();
          potions.put(type, potion);
        }
        case INVISIBILITY -> {
          potion = new InvisibilityPotion();
          potions.put(type, potion);
        }
        default -> {
        }
      }
    }
```
**The following code line is repeating.**
```java
potions.put(type, potion);
```

_Suggestion: It can be taken out of the switch-case statement._

**Comment by ShivanshCharak** [comment]
LOL nice, i wanna work on this issue

**Comment by ShivanshCharak** [comment]
wait i dont think moving that part out will work because, lets say if the input doesnot match the condition  it will show default section which is nothing but if you move the "potions.put(type, potion);" out it will execute irrespective of the user input

**Comment by rajivaPavan** [comment]
An exception can be thrown in the default case

**Comment by ShivanshCharak** [comment]
Exception for what, Invalid argument?

**Comment by rajivaPavan** [comment]
Well yeah. But we don't need to consider a lot about the Exception since the we are talking about design patterns here 😅

**Comment by ShivanshCharak** [comment]
Yeah if we create a exception there it will halt the normal execution and will show the error on console which will ruin the whole code flow ig

**Comment by Gauravkumar1502** [comment]
This code snippet demonstrates the creation of a potion using the PotionType class. If the PotionType class is a sealed class, 
we can utilize the new Pattern Matching for Switch.
The switch statement will be fully executed without requiring a default case.

**Comment by Khomendra** [comment]
is this issue still open?
