### ISSUE TITLE
Caching patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#256]
https://en.wikipedia.org/wiki/Cache_(computing)
https://docs.oracle.com/cd/E15357_01/coh.360/e15723/cache_rtwtwbra.htm#COHDG5177
http://www.alachisoft.com/resources/articles/readthru-writethru-writebehind.html
http://www.ehcache.org/documentation/2.8/get-started/getting-started.html
http://www.computerweekly.com/feature/Write-through-write-around-write-back-Cache-explained

**Comment by waisuan** [comment]
Hi.

I'd like to try my hand on the caching patterns (if no one has volunteered to do them yet).

**Comment by npathai** [comment]
@waisuan Sure go ahead. Create issue of the particular pattern you wish to work on and I will label it.

**Comment by waisuan** [comment]
@npathai Sure thing. Thanks.

**Comment by iluwatar** [comment]
Some of the caching patterns will be implemented in https://github.com/iluwatar/java-design-patterns/issues/273
