### ISSUE TITLE
can you help me with my MathUtil

### ISSUE THREAD

**Issue by wsdjeg** [iluwatar/java-design-patterns#259]
I have wrote a util to find the collection from a List,which sum == the appointed sum!
here is my utils ,i use jetty:run to start the server
https://github.com/wsdjeg/JavaWeb

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/JavaWeb/blob/master/src/main/java/com/wsdjeg/util/MathUtils.java
now it works well,but only can deal with 25 digital at most!

**Comment by npathai** [comment]
This issue is not related to our repository. So I am closing it. If you need help please ask the question on StackOverflow.

**Comment by wsdjeg** [comment]
ok
thank you
