### ISSUE TITLE
BUG: content overlapping and merging at different pixels

### ISSUE THREAD

**Issue by techmannih** [iluwatar/java-design-patterns#2601]
Hello @ibrahim89 @iluwatar ,
I found an issue in your website in which "**Study the design pattern** " and its content merging at different pixels and its underline also overlap at many pixels or like **320px to 368px ,420px to 508px , 720px to 958px  OR iphone5** . its not good for your website .
i want to work on this issue....... please assign me 
![2023-10-02_21-38_1](https://github.com/iluwatar/java-design-patterns/assets/125847751/3655788b-27bd-458e-a08f-7ceaa0f7ab98)
![2023-10-02_21-38_2](https://github.com/iluwatar/java-design-patterns/assets/125847751/779e65ca-e820-46e2-a61c-16b20e5c4d96)

**Comment by Pratham-Verma7** [comment]
can i take care this issue

**Comment by techmannih** [comment]
Hello @Pratham-Verma7 ,
 I am working on this issue please you can work on another issue
