### ISSUE TITLE
Decorator pattern: SmartTroll should be SmartHostile

### ISSUE THREAD

**Issue by Niko-O** [iluwatar/java-design-patterns#264]
As the SmartTroll decorates any Hostile object, it should be named SmartHostile instead. Because if there's a Goblin class implementing the Hostile interface, the SmartTroll class is technically able to decorate it too, even though it is named SmartTroll (which indicates that it should only be a Troll).

**Comment by iluwatar** [comment]
I would suggest that we change the example so that `SmartTroll extends Troll`. It wouldn't hurt to add `Goblin` to the example too :smile:

**Comment by Niko-O** [comment]
@iluwatar 
That would be a possible solution too, but the SmartTroll doesn't do anything Troll-specific (allthough the string "The troll throws a rock at you!" is hardcoded). It just increases the attack power.

**Comment by opg7371** [comment]
Pl tell me what should I do....I am new to Open source and i want to make it as my first commit
Thankyou

**Comment by Niko-O** [comment]
@opg7371 
You could rename the SmartTroll-class to SmartHostile and replace the hardcoded strings in that class with generic examples (e.g. "It throws a rock at you!").

**Comment by tomroy** [comment]
Since this issue hasn't been update for a while, I would like to give it a try. I renamed the SmartTroll-class to SmartHostile and replaced the hardcoded strings in that class to "It throws a rock at you!"
I also updated the class naming in the UML digram.

 I would like to submit a pull request. :)
