### ISSUE TITLE
Type Tunnel pattern

### ISSUE THREAD

**Issue by savaliyagautam** [iluwatar/java-design-patterns#266]
https://en.wikipedia.org/wiki/Type_Tunnel_pattern

**Comment by iluwatar** [comment]
It looks like a serialization mechanism. In Java it is a built-in feature with `java.io.Serializable`. Additionally Java platform guarantees that the serialization works between different platforms. Whereas in the example the code would not be sufficient to transfer objects between platforms having different byte order.

**Comment by geniusgeek** [comment]
Although serialization is a variant of type tunnel pattern, but i thing
stub implementations really define this pattern.

**Comment by iluwatar** [comment]
Not many comments were received unfortunately, but I do not see this as a design pattern.
