### ISSUE TITLE
Alias names for patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#267]
Many design patterns have multiple names. For example Decorator is also known as Wrapper.

We should supplement the [pattern template](https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template) with `Also known as` where applicable.

**Comment by npathai** [comment]
:+1: Good idea.

**Comment by mafagafogigante** [comment]
This is a good idea, but I'd like to point out that the given example may lead to mistakes. Adapters are also sometimes called wrappers, and many wrappers are not decorators nor adapters. I'd say wrappers are broader than these two design patterns. But I've seen both of them referenced by the name wrapper.

**Comment by iluwatar** [comment]
It is a valid point. Maybe this is why Wrapper is the secondary name (source: GOF book).

**Comment by mafagafogigante** [comment]
I agree that it is still called wrapper nowadays (GoF is a bit outdated and should be read with caution). Just pointing out that one may see the Decorator pattern as Wrapper pattern is a great thing, though.
