### ISSUE TITLE
Microservice pattern: Idempotent consumer

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2683]
**Description:**
The Idempotent Customer design pattern is essential in microservices architectures to ensure that repeated processing of the same request does not produce different outcomes. This pattern helps in avoiding duplicate operations in distributed systems where network issues or retries might cause the same request to be sent multiple times.

**Main Elements of the Pattern:**
1. **Unique Request Identifier:** Assign a unique identifier to each request to track and manage its state.
2. **Request Storage:** Store the request data and its state to check for duplicates.
3. **State Management:** Implement mechanisms to manage the state of requests (e.g., pending, processing, completed) and to handle retries gracefully.
4. **Response Handling:** Ensure that the same response is returned for repeated requests, preventing inconsistent outcomes.
5. **Concurrency Control:** Use locking mechanisms or transactional processes to manage concurrent requests and ensure data integrity.

**References:**
- [Microservices Architecture - Idempotent Operations](https://martinfowler.com/bliki/IdempotentOperations.html)
- [Microservices Patterns - Chris Richardson](https://microservices.io/patterns/fault-tolerance/idempotent-consumer.html)
- [Project Contribution Guidelines](https://github.com/iluwatar/java-design-patterns/wiki)

**Acceptance Criteria:**
1. Implement a unique request identifier mechanism for the Idempotent Customer design pattern.
2. Develop a request storage and state management system to handle and track the state of requests.
3. Ensure that repeated requests return consistent responses and implement concurrency control mechanisms to maintain data integrity.

**Comment by mm-saiful6854** [comment]
Hi, Could you assign me for contributing.

**Comment by dmgodoy** [comment]
Hi @iluwatar. I'd like to work on this one.

**Comment by dmgodoy** [comment]
Just submitted a pull request, looking forward to your feedback.

Kind regards,

David.
