### ISSUE TITLE
Microservice pattern: Distributed tracing

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2693]
### Description
The objective is to implement the Distributed Tracing design pattern within the context of a microservices architecture. Distributed Tracing is essential for monitoring and troubleshooting complex microservices systems, as it provides visibility into the flow of requests across various services.

Main elements of the Distributed Tracing pattern include:
- **Trace Collection:** Collecting trace data from each microservice involved in processing a request.
- **Trace Propagation:** Ensuring trace context is propagated across service boundaries.
- **Trace Aggregation:** Aggregating trace data centrally for analysis and visualization.
- **Trace Visualization:** Providing tools to visualize and analyze traces to identify performance bottlenecks, errors, and latency issues.

### References
- [Microservices Patterns](https://microservices.io/patterns/observability/distributed-tracing.html)
- [Distributed Tracing on DZone](https://dzone.com/articles/distributed-tracing-1)
- [OpenTracing Documentation](https://opentracing.io/docs/)
- [Jaeger: open source, end-to-end distributed tracing](https://www.jaegertracing.io/)
- [Project Contribution Guidelines](https://github.com/iluwatar/java-design-patterns/wiki)

### Acceptance Criteria
- **Trace Collection Implementation:** Implement trace collection mechanisms in each microservice, ensuring that trace data is collected and associated with individual requests.
- **Trace Propagation Mechanism:** Develop and integrate a mechanism for propagating trace context across service boundaries, ensuring that trace data remains consistent as requests traverse different microservices.
- **Trace Aggregation System:** Set up a centralized system for aggregating trace data from all microservices. This can be an existing solution like Jaeger or a custom implementation.
- **Trace Visualization Tools:** Integrate tools for visualizing trace data, allowing for detailed analysis of request flows, performance bottlenecks, and errors.
- **Documentation:** Provide comprehensive documentation detailing the implementation, configuration, and usage of the Distributed Tracing system within the microservices architecture.
- **Testing:** Thoroughly test the implementation to ensure trace data is accurate, trace context is consistently propagated, and the visualization tools effectively display the aggregated trace data.

**Comment by yuhangbin** [comment]
I want to try it. Could you assign this one to me?

**Comment by 244Walyson** [comment]
I'd like to work on this issue. Could you please assign it to me?
