### ISSUE TITLE
producer consumer

### ISSUE THREAD

**Issue by hoswey** [iluwatar/java-design-patterns#271]
Hi,  le me work on it

**Comment by iluwatar** [comment]
Are you referring to this https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem ?

**Comment by hoswey** [comment]
Yeah, I think I can refer to that wiki.

Btw, I find there is already a design pattern named poison pill in this projects. It is like a extension of producer-consumer design pattern.  I think i may also refer to this one to write a pure producer-consumer.

Any suggestion?

**Comment by iluwatar** [comment]
Yes, I think you are on the right track. Poison Pill utilizes producer-consumer and it is useful as an example.

I'll update the tags to indicate you are working on it.
