### ISSUE TITLE
Read-through, Write-through, Write-back, and Write-around Caching Patterns (#256)

### ISSUE THREAD

**Issue by waisuan** [iluwatar/java-design-patterns#273]
Hello.

I would like to work on the following patterns:-

Read-through
Write-through
Write-back/Write-behind
Write-around

**Comment by npathai** [comment]
What I meant was that there are a few caching patterns, I think Write back, write through etc. You can work on any one of them and create an issue for that particular pattern. This task presently is just a clone of original one. Maybe @iluwatar  can add more on this.

**Comment by waisuan** [comment]
Apologies. I should've added a little more details to my post. The main caching patterns/strategies (that I could gather) are as follows:-

Read-through
Write-through
Write-back/Write-behind
Write-around

After going through the provided documents (by @iluwatar), I felt that their logic are quite similar to one another albeit with different methods of achieving the caching goal. So, I was wondering if I could attempt to handle all of the above strategies at once.

**Comment by iluwatar** [comment]
Yes, I think a single example could be enough to implement the caching patterns you have listed.

**Comment by waisuan** [comment]
Great! I'll get started on it ASAP. Thanks.

**Comment by waisuan** [comment]
Kindly refer to my pull request for the new commit.
