### ISSUE TITLE
About coding style "Format the code according to Google Java Style Guide"

### ISSUE THREAD

**Issue by hoswey** [iluwatar/java-design-patterns#274]
Hi, I try to using the  [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) according the [How to contribute](https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute).

But it seems its style is different with the one in the project. Like the indent.
I find the code in this project indent with **Tab** while google is indent by [2 Space](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation)

Any suggestions?

**Comment by iluwatar** [comment]
We're migrating to Google style and major part of the code has not yet been migrated. However, new code should use Google style.
