### ISSUE TITLE
Migrate from Lombok to records

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2807]
See the article https://medium.com/thefreshwrites/migrating-from-lombok-to-records-in-java-fa2ece28bd68

Acceptance criteria

- Lombok code replaced with Java records

**Comment by JabezBrew** [comment]
Assign to me

**Comment by shiyayonn** [comment]
Hi @iluwatar, I would also like to work on this issue, but I have a question regarding the use of Slf4j annotation, it's not mentioned in the article you posted, should we leave it as is? It is heavily used in code 
<img width="680" alt="image" src="https://github.com/iluwatar/java-design-patterns/assets/52842991/c92c45eb-9492-4813-9088-5e7270cc883f">

**Comment by iluwatar** [comment]
I think we can leave Slf4j out of scope in this issue. The idea is just to start using records, not to get rid of Lombok totally.

@shiyayonn if you'd like to work on this, please coordinate with @JabezBrew so that duplicate work can be avoided.

**Comment by shiyayonn** [comment]
Hi @JabezBrew are you still working on this issue? I would love to help you on this! Thanks!

**Comment by JabezBrew** [comment]
> Hi @JabezBrew are you still working on this issue? I would love to help you on this! Thanks!

sure. you can take half of the architectures.  I'll take the other half.

**Comment by leiferksn** [comment]
I've recently done that for one of my own projects and I would gladly help you reduce your lombok usage :smile: Let me know if I can take over some part of the work.
