### ISSUE TITLE
Upgrade Repository pattern to Spring Boot 3.x

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2823]
Acceptance criteria

- Pattern upgraded to use the latest Spring Boot version

**Comment by leiferksn** [comment]
Is this issue still open? I would like to take it. Thx.

**Comment by iluwatar** [comment]
This was recently split into multiple smaller issues. Feel free to take one of them @leiferksn

**Comment by leiferksn** [comment]
ok, thank you. how can I assign it to me, @iluwatar?

**Comment by iluwatar** [comment]
Comment on the issue you're interested in, and I'll assign it to you

**Comment by leiferksn** [comment]
I think the parent issue of this one is https://github.com/iluwatar/java-design-patterns/issues/2407. It says in your last comment, that the issue was split into smaller ones and this one (#2837) is one of them.  So I think you can assign to me #2837, @iluwatar. 
:smile:

**Comment by iluwatar** [comment]
You're right @leiferksn, sorry for the confusion 😄 I'll assign this to you

**Comment by leiferksn** [comment]
Created a PR for the issue. https://github.com/iluwatar/java-design-patterns/pull/2837
