### ISSUE TITLE
Delegation DP?

### ISSUE THREAD

**Issue by llitfkitfk** [iluwatar/java-design-patterns#283]
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html

> Delegation

> Delegation is a design pattern that enables a class or structure to hand off (or delegate) some of its responsibilities to an instance of another type. This design pattern is implemented by defining a protocol that encapsulates the delegated responsibilities, such that a conforming type (known as a delegate) is guaranteed to provide the functionality that has been delegated. Delegation can be used to respond to a particular action, or to retrieve data from an external source without needing to know the underlying type of that source.

**Comment by iluwatar** [comment]
Can you explain a bit how to apply this in Java?

**Comment by llitfkitfk** [comment]
```
interface DiceGame {
    Dice dice;
    void play();
}

interface DiceGameDelegate {
    void gameDidStart(DiceGame game);
    void game(DiceGame game, int didStartNewTurnWithDiceRoll);
    void gameDidEnd(DiceGame game);
}

class SnakesAndLadders implements DiceGame {
	
	Dice dice;
	DiceGameDelegate delegate;
	
	void play() {
		...
        delegate.gameDidStart(this);
		//game loop
        while true {
 			...
			int diceRoll = dice.roll();
            delegate.game(this, diceRoll);
            ...
            }
        }
        delegate.gameDidEnd(this);
	}
}

class DiceGameTracker implements DiceGameDelegate {

	private numberOfTurns = 0
	
    void gameDidStart(DiceGame game) {
		numberOfTurns = 0
        if game.xxx() {
            System.out.println("Started a new game of Snakes and Ladders");
        }
        System.out.println("The game is using a " + game.dice.sides + "-sided dice");
    }
	
    void game(DiceGame game, int didStartNewTurnWithDiceRoll) {
        ++numberOfTurns
        System.out.println("Rolled a " + diceRoll);
    }
	
    void gameDidEnd(DiceGame game) {
        System.out.println("The game lasted for " + numberOfTurns + " turns");
    }
}

```

**Comment by jwerba** [comment]
Folks Delegation is not a design patters as i see it. Its a basic principle of software design. Delegation its just a consecuence of choosing composition over inheritance and if you add proper encapsulation there you are.  But it seems that many people writes about this on the web as a Pattern.... Just thinking out loud...

**Comment by iluwatar** [comment]
I agree with @jwerba I do not see this as a design pattern.

**Comment by llitfkitfk** [comment]
fair enough
