### ISSUE TITLE
Composite View refactoring needed

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2853]
Servlets are components in Java web development, responsible for processing HTTP requests and generating responses. In this context, exceptions are used to handle and manage unexpected errors or exceptional conditions that may occur during the execution of a servlet.

Exceptions should not be thrown from servlet methods. These 4 hotspots need to be fixed:

AppServlet.java:64
AppServlet.java:71
AppServlet.java:81
AppServlet.java:90

Acceptance criteria

- The aforementioned exceptions have been caught properly

**Comment by surjendu104** [comment]
Can you assign it to me?

**Comment by surjendu104** [comment]
Did you want exception rethrown from the catch block or simply log the exception message?

**Comment by surjendu104** [comment]
Hi @iluwatar I have made the pr. ps review it. #2886
