### ISSUE TITLE
Upgrade jackson-databind

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2870]
The version bump of jackson-databind seems to need some work. See https://github.com/iluwatar/java-design-patterns/pull/2867

Acceptance criteria
- jackson-databind successfully upgraded to the latest version

**Comment by surjendu104** [comment]
Hi @iluwatar ,
Upgrading version of `jackson-databind` to 2.17.0 incompatible with current versions of `jackson-core` in the project which I have found 2.13.4 and 2.15.4. So we also have to upgrade the `jackson-core`.
I have seen that only upgrading `jackson-databind` to 2.17.0 internally using 2.13.4.

![jackson-1](https://github.com/iluwatar/java-design-patterns/assets/101238933/d2e7a3be-1088-40ea-be5f-abb12c57d519)

So I have added one extra dependency in project to upgrade the `jackson:core` to 2.17.0.

![dynamic-proxy-dependency-list](https://github.com/iluwatar/java-design-patterns/assets/101238933/84a31efb-6cb5-41bb-bbdb-d438c2f30e34)

After this all the testcase passed in `dynamic-proxy` and `event-sourcing`

![dynamic-proxy-test-result](https://github.com/iluwatar/java-design-patterns/assets/101238933/fa196dde-aeed-4163-8bb0-6e6ef2c61d17)
![event-sourcing-test-result](https://github.com/iluwatar/java-design-patterns/assets/101238933/262ebd70-9d39-4962-84aa-7a2526165832)

**Comment by surjendu104** [comment]
If this is acceptable then I can raise a pr

**Comment by iluwatar** [comment]
Hey, sounds good @surjendu104 I'm looking forward to receiving the PR 👍🏻

**Comment by surjendu104** [comment]
Hi @iluwatar I have made the pr. ps review it. #2885
