### ISSUE TITLE
May I ask what design pattern is best for this kind of business?

### ISSUE THREAD

**Issue by xufei56789** [iluwatar/java-design-patterns#2873]
![未命名文件 (1)](https://github.com/iluwatar/java-design-patterns/assets/22664500/7b94f8fc-9791-41fc-ae25-2eb62a48c357)

**Comment by AritraThakurta** [comment]
@iluwatar I think it would be best if we use Visitor Design Pattern

**Comment by SahithyaCherukuri** [comment]
@iluwatar I believe the Factory design pattern better matches this business model (and if you plan on using encapsulation to determine the category of the object, this is the best pattern). 

Take a look at this link for more information about Factory Pattern (https://refactoring.guru/design-patterns/factory-method)
