### ISSUE TITLE
api-gateway - create a new class, PriceService to return the price to the controller

### ISSUE THREAD

**Issue by tal-zigdong** [iluwatar/java-design-patterns#2904]
We should remove the whole of the logic from the controller and move this logic to a service. 
move logic from 
`api-gateway/price-microservice/src/main/java/com/iluwatar/price/microservice/PriceController.java`
to a new class
`api-gateway/price-microservice/src/main/java/com/iluwatar/price/microservice/PriceService.java`
and call from the controller to this service.

**Comment by iluwatar** [comment]
There's no logic, it simply returns a static number
