### ISSUE TITLE
Adapter needs better example

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#292]
The Adapter example kind of sucks and needs a more descriptive implementation. For inspiration these are quite good:

http://www.journaldev.com/1487/adapter-design-pattern-in-java-example-tutorial
http://www.tutorialspoint.com/design_pattern/adapter_pattern.htm

**Comment by JuhoKang** [comment]
May I work on this issue?
Q: I found that the original example is based on the "Object Adapter Pattern" and there is an alternative which is the "Class Adapter Pattern". Which would be the better?
Should I just change _example (names of the Objects?) and description_ or _else_?

**Comment by iluwatar** [comment]
Hi @JuhoKang it's great that you can work on this. It would be ideal to show both object adapter and class adapter in the example. Look at the links I gave above to get the idea what kind of example would be good. You can use the existing example as a base and just modify it as needed.
