### ISSUE TITLE
Implement Virtual Proxy pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2940]
The Virtual Proxy design pattern is used to delay the creation and loading of expensive objects until their actual use, thereby reducing resource consumption. Here are the main points to consider when implementing this pattern:

1. **Proxy Class:**
   - Implement a proxy class that implements the same interface or inherits from the same base class as the actual expensive object. This class acts as a stand-in for the real object.
   - The proxy class holds a reference to the real object, but initializes it only when necessary.

2. **Real Subject (Expensive Object):**
   - Implement the actual, resource-intensive object, known as the real subject or real object.
   - Ensure that the interface provided by the real object matches that of the proxy.

3. **Deferred Initialization:**
   - In the proxy class, encapsulate the creation logic of the real object.
   - Initialize the real object lazily, meaning that it is created only when one of its methods is accessed.

4. **Transparent Usage:**
   - The proxy should appear to be the real object to clients.
   - The client should not notice whether they are accessing the proxy or the real object. All interactions should be routed seamlessly to the real object through the proxy.

5. **Efficiency Considerations:**
   - Implement caching mechanisms or logic to prevent redundant initialization.
   - Make sure that the proxy introduces minimal overhead and improves performance in cases where the real object is not always required.

By encapsulating resource management in this way, the Virtual Proxy pattern makes expensive operations more efficient and ensures that unnecessary resource usage is avoided.

**Acceptance Criteria:**

- Implementation: The Virtual Proxy pattern is implemented following the project's contribution guidelines and includes an interface and a proxy class to encapsulate the actual object.

- Documentation: The implementation is documented with clear examples, diagrams, and explanations in the README.md file.

- Tests: Comprehensive unit tests validate the behavior of the proxy in controlling object creation and access.

**Comment by Adelechka** [comment]
Hi, can you assign it to me?
