### ISSUE TITLE
API Gateway pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#297]
The example should demonstrate how to use API Gateway in microservices architecture as described here: http://microservices.io/patterns/apigateway.html

**Comment by TylerMcConville** [comment]
I can work on this issue.

**Comment by iluwatar** [comment]
:+1: Great, please go ahead @TylerMcConville

**Comment by npathai** [comment]
@iluwatar @TylerMcConville I would suggest actually using Micro services architecture by deploying various services in separate docker or some other container and letting the API gateway communicate with appropriate service based on device type.

I agree this would be tedious but it would actually represent how pattern is utilized in production. We will need to figure out how to run docker instances while unit testing. Maybe we can mock them out or something. 

Let me know what you think about this.

**Comment by npathai** [comment]
A high quality link: https://www.nginx.com/blog/building-microservices-using-an-api-gateway/

**Comment by TylerMcConville** [comment]
@npathai Sure, I can try to accomplish that. I'll investigate how we would be able to run the Docker instances while unit testing and see what I can come up with.

**Comment by npathai** [comment]
@TylerMcConville We don't necessarily need docker instances in unit testing. We can abstract the Services with interfaces and replace them with our mocks while unit testing.

**Comment by TylerMcConville** [comment]
Just a status update: I've got this pattern code complete, I'm just working on documentation, diagrams, and test coverage.

**Comment by npathai** [comment]
@TylerMcConville That's great :+1:
