### ISSUE TITLE
Upgrade Guice

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2974]
### Description
Upgrade the Guice dependency in the project to the latest stable version to ensure compatibility and leverage new features and improvements.

### Acceptance Criteria
1. Update the Guice dependency in the project's build configuration to the latest stable version.
2. Ensure all existing tests pass without modification after the upgrade.
3. Verify the project builds successfully and runs as expected with the new version of Guice.
4. Update any documentation if there are changes in usage or configuration due to the upgrade.
5. Conduct a code review to confirm that the upgrade adheres to project contribution guidelines and does not introduce any regressions.

**Comment by Mayankchoudhary294** [comment]
Hello @iluwatar 

Could you please take a look on this PR?
