### ISSUE TITLE
Refactor Visitor

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2975]
### Description

`VisitorTest` has some code smells regarding `Optional` usage.

1. `Optional<String>` has been used as class field type.
2. `Optional<String>` has been used as parameter type.

`Optional` is primarily intended for use as a method return type where there is a clear need to represent "no result," and where using `null` is likely to cause errors. A variable whose type is `Optional` should never itself be null; it should always point to an `Optional` instance.

### Acceptance Criteria

- Code smells refactored

**Comment by ankurnotwarikoo** [comment]
Can this be assigned to me ?

**Comment by Joel-Dandin** [comment]
Hi @iluwatar,
I've noticed that this issue has been unresolved for a while. I've made some changes to the code and hope they address the problem.
