### ISSUE TITLE
Refactor Layered Architecture

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2976]
### Description

Layered Architecture example has some code smells.

CakeInfo - 'Optional<Long>' used as type for field 'id' 
CakeLayerInfo - 'Optional<Long>' used as type for field 'id' 
CakeToppingInfo - 'Optional<Long>' used as type for field 'id' 

### Acceptance Criteria

- Code smells fixed

**Comment by ankurnotwarikoo** [comment]
Willing to work on this.
However in my sts I am unable to see the code smells as such. Followed the instructions mentioned here :-
https://github.com/iluwatar/java-design-patterns/wiki/12.-IDE-instructions

![image](https://github.com/iluwatar/java-design-patterns/assets/158599734/1a9261d1-005e-4de6-9ad1-911b839a78ec)
Could only see identation issues as such.
Please let me know how do I proceed to resolve this.
P.S. - Interested to contribute to this repo !

**Comment by iluwatar** [comment]
Don't know about other IDE's, but in IntelliJ IDEA you can reproduce the warnings by using command 'Analyze - Inspect Code' on the `layered-architecture` module.

**Comment by ankurnotwarikoo** [comment]
Could you assign this issue to me? This is my first time contributing, so I also need some guidance on how to commit and raise a pull request. Thank you!

**Comment by iluwatar** [comment]
Sure @ankurnotwarikoo Here are a couple of good starting points to get started with Github and this project:

- https://docs.github.com/en/get-started
- https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

**Comment by iluwatar** [comment]
Checkstyle is configured here: https://github.com/iluwatar/java-design-patterns/blob/master/pom.xml#L334-L356

It uses built-in Google Checks. We have added some of our own rule suppressions.

IDE instructions have some hints on how to work with Checkstyle https://github.com/iluwatar/java-design-patterns/wiki/12.-IDE-instructions

**Comment by iluwatar** [comment]
Noticed that we have a partly duplicate issue https://github.com/iluwatar/java-design-patterns/issues/2936

**Comment by abhishek-singh0710** [comment]
Can this issue be assigned to me?

**Comment by abhishek-singh0710** [comment]
Also I'm sorry if this seems like a poor question but are we only concerned with the optional type given to the ids of those three classes and none other?

**Comment by PALASH2201** [comment]
I checked the concerned code files,  I guess the code smells are fixed

**Comment by abhishek-singh0710** [comment]
Ok. Thanks for letting me know.

**Comment by PALASH2201** [comment]
Yea, no issues

**Comment by pujakarakoti07** [comment]
Can you please assign this issue to me?

**Comment by iluwatar** [comment]
Fixed in https://github.com/iluwatar/java-design-patterns/pull/2988
