### ISSUE TITLE
Refactor Commander

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2978]
### Description

Commander pattern has some dead code and it should be refactored. At the moment it has 4 different `App` classes and `main` functions. Each `App`'s `main` function only executes the success case, but not the failure cases (dead code).

### Acceptance Criteria

- 4 `App` classes refactored into one
- There is only one `main` function
- The `main` function executes all the success cases and the failure cases

**Comment by Mayankchoudhary294** [comment]
Hello @iluwatar 
Do you mean to refactor all 5 App classes into one, with the main function executing both the success and failure cases?

**Comment by iluwatar** [comment]
Yes, I think that would make the example easier to use and understand.
