### ISSUE TITLE
Java Design Patterns blog

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#298]
I was thinking about adding a blog to the Java Design Patterns web site. This would let us write about the pattens from a bit different perspective and add more depth to the site.

The blog entries could be for example
 - tutorials for using a pattern
- pattern evolution from earlier Java version to functional Java 8
- glances into real world usage of design patterns
- guest writings from the fathers of the design patterns (would be awesome!)

@npathai @noobxgockel and others, any comments are welcome.

**Comment by npathai** [comment]
I am totally up for this. Real world examples explanation and documenting the usage will be a big plus for readers. And the third point will be super awesome. :+1:

**Comment by npathai** [comment]
Also if we keep it open, i.e. after review, people can also contribute their use case maybe.

**Comment by iluwatar** [comment]
@noobxgockel we would appreciate your vision how to enable this feature on the web site?

**Comment by noobxgockel** [comment]
Excuse me beeing so inactive. Im currently learning towards the A-Levels in a shortened time frame (called BOS in Germany) and its quite time consuming.

I know that jekyll provides a blog system and i dont think that its very difficult. If i find the time i will try and look into it on the weekend...

**Comment by iluwatar** [comment]
@noobxgockel no problem, take your time. Anyone else wanting to work on this issue?

**Comment by noobxgockel** [comment]
@iluwatar take a look at the first draft of a blog: http://iluwatar.github.io/java-design-patterns/blog/
Basic funtionality should be in there. If you need anything then just tell me ^^ i have a bit of time over the holidays now...

More info on writing Blog posts here:

* https://github.com/iluwatar/java-design-patterns/blob/gh-pages/_posts/2015-12-18-jdp-blog-goes-live.md
* http://jekyllrb.com/docs/posts/

**Comment by iluwatar** [comment]
Looks awesome! :+1: RSS feed seems to be there also which is great. I think this covers what I had in mind (for now) :smile:

**Comment by iluwatar** [comment]
It would be great to have the instructions for creating blog entries in the [developer wiki](https://github.com/iluwatar/java-design-patterns/wiki). After that I think we can close this issue and create another one e.g. "Accepting blog entries" where we can refer to those instructions.

**Comment by noobxgockel** [comment]
okay now, @iluwatar i have edited the 01. How to contribute wiki part and added the respective explanation.
It is very technical though. We might need some guidance for content in the future.
If you are satisfied we can close this issue :smile:

**Comment by iluwatar** [comment]
:+1: The instructions are good. Ok to close. I will create another issue calling for blog entries later on.
