### ISSUE TITLE
Could you add my website codestep.io links to README of each corresponding project in java-design-patterns?

### ISSUE THREAD

**Issue by CodeStepIO** [iluwatar/java-design-patterns#3000]
I created a website www.codestep.io to host runtime view in HTML files of every running process of java design patterns in our java-design-patterns project.

For example, to study  pattern abstract-document  better, you can get a runtime debugging view of each step of a running process of this pattern here: https://codestep.io/p/jdp@20240509:abstract-document/

And for a more complex example, you can get runtime view of pattern half-sync-half-async here: https://codestep.io/p/jdp@20240509:half-sync-half-async/

At last, I want to join you to make java design patterns easy to understand, thanks a lot:)

**Comment by SamarthKoli** [comment]
can i get this issue assigned i can work on it
