### ISSUE TITLE
Redux architectural pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#301]
http://www.infoq.com/news/2015/11/redux
http://redux.js.org/

**Comment by geniusgeek** [comment]
please assign this to me. I will work on it this weekend

**Comment by iluwatar** [comment]
Ok, you're good to @geniusgeek

**Comment by npathai** [comment]
@iluwatar Is it same as #232 ? If it is we should mark one as duplicate and close one of them.

**Comment by iluwatar** [comment]
Well spotted. Since this is under constructions I'm closing the other issue.

**Comment by iluwatar** [comment]
This is a presentation tier pattern, similar to Flux .

http://rackt.github.io/redux/

**Comment by iluwatar** [comment]
@geniusgeek are still working on this?

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by iluwatar** [comment]
Redux is specifically designed for JavaScript applications and is most commonly used with libraries like React. It is not directly applicable to Java applications.
