### ISSUE TITLE
The Chinese and Spanish skip directories are empty

### ISSUE THREAD

**Issue by aeryzhao** [iluwatar/java-design-patterns#3040]
When the two catalog pages are accessed in an online site, the list appears empty.
https://java-design-patterns.com/zh/patterns/
https://java-design-patterns.com/es/patterns/

**Comment by wizaye** [comment]
I Just figured out the issue, can you assign me this issue so that i can solve it and make a pr

**Comment by aeryzhao** [comment]
Thank you for resolving this issue! Thanks again!

> I make a pr only for Chinese [3056](https://github.com/iluwatar/java-design-patterns/pull/3056)
