### ISSUE TITLE
Add Home component on header section.

### ISSUE THREAD

**Issue by ishapandey007** [iluwatar/java-design-patterns#3049]
There should be Home component on the header section so that we can return to the home page from any other page. There is no option from which we can return to the home page again. So I think there should be this feature also.

**Comment by neerajmanivarnan** [comment]
Isn't this a frontend issue?

**Comment by ishapandey007** [comment]
I am saying that there should be a way to come back to the home page.

**Comment by VaibhavVermaa16** [comment]
I would like to work on this issue please assign it to me.

**Comment by LakshyaPunyani-01** [comment]
what's is the purpose of contributing to this project , if the owner doesn't merging any PR since months

**Comment by iluwatar** [comment]
This issue is relevant to the website. The website is another project: https://github.com/iluwatar/java-design-patterns-vuepress-web

Returning to home page is already possible by clicking the site logo in the top left corner.

**Comment by iluwatar** [comment]
Ok now I saw the [related PR](https://github.com/iluwatar/java-design-patterns/pull/3059) and understood that this issue refers to composite view pattern.
