### ISSUE TITLE
Website Improvements

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#338]
So i worked on the website a little bit and came up with some ideas. But im unsure if all or even some of them fit in. I'd be glad to hear your feedback on them.
- [x] Disqus/Comments on patterns
- [ ] Disqus/Comments on blogposts(after some discussion this should also be implemented)
- [x] Automated author informations for blogposts (e.g. only write `author: iluwatar` in yaml frontmatter and links to github/twitter/etc will be autogenerated with nice looking buttons etc.)
- [x] Tooltips or any sort of description for Tags/Categories, because they are getting more and more complex and tooltips might help with that?

**Comment by mikulucky** [comment]
Just my little opinion;

:+1: for Disqus on blog posts
:-1: for Disqus on pattern entries, as I can see this getting very chatty, and could become a serious workload for the person assigned to reply. Or even maintain.
:+1: For the automated author information on blog posts and I always :+1: nice buttons!
:+1: Tooltips always help!

**Comment by iluwatar** [comment]
To be honest I'm not familiar with Disqus. How would the commenting work? Would there be some kind of Disqus button to redirect the reader?

:+1: for the author info and tooltips

**Comment by noobxgockel** [comment]
@iluwatar Here is an example:
http://blog.disqus.com/post/135793811850/disqus-glides-into-community-service
Scroll down to the bottom, under the blue box is the disqus element

**Comment by iluwatar** [comment]
Ok thanks @noobxgockel for the example. :+1: for Disqus

**Comment by npathai** [comment]
I agree with above points. Can Reddit fit here somehow? I dont know much about it, but have found it useful sometimes.

**Comment by noobxgockel** [comment]
@npathai i dunno how reddit would fit in here. I kinda doubt it would be good as a main source because the direct interaction would be obstructed by a link. But doing regular publishing of our blogposts or new patterns onto reddits like /r/java or /r/learnprogramming would be a very nice idea.

Even if an integration into the website would be wanted i could just add a Link to Reddit button, but i doubt it would be needed now as we have disqus.

**Comment by iluwatar** [comment]
@npathai for simple sharing blog posts to Reddit, there is a button for that in the top right corner.

**Comment by npathai** [comment]
@iluwatar :+1:

**Comment by noobxgockel** [comment]
Commit https://github.com/iluwatar/java-design-patterns/commit/0d67f61fd08dc7a052f564f1088c90ecee55c7f9 includes the Addition of Tooltips. Sorry i forgot to add the issue number in the commit...
All tasks complete -> closed

**Comment by iluwatar** [comment]
I think it would be a good idea to also implement "Disqus/Comments on patterns"

**Comment by noobxgockel** [comment]
@iluwatar Could you try and elaborate why you think this would be a good idea?

I think @mikulucky has a very good point about this:
> :-1: for Disqus on pattern entries, as I can see this getting very chatty, and could become a serious workload for the person assigned to reply. Or even maintain.

@npathai what do you think about this ?

On a side note, the implementation would only affect a very small amount of code, so that shouldn't be a problem...

**Comment by iluwatar** [comment]
The patterns are the deliveries of this project. Discussion is feedback to us and it enables us to improve. 

Which would you rather take: chatty discussions or no discussion at all? I think comments and opinions are a resource that should not remain untapped.

Also, I don't see the discussions purely as questions taking time from the maintainers. Although it may take some of the team's time I think most of the discussion will be between the community. People want to share their opinions and other people will comment on them.

**Comment by npathai** [comment]
@noobxgockel @iluwatar  I think it would be a good idea, because it will allow opinions and discussions on particular patterns. This can be viewed as bad and good. Good points include openness and ideas flowing (which I think will be quite helpful).

Yes it can get chatty and I hope we have the control to remove such comments. It may require a bit of our time to maintain.

We can try it and then disable it if we feel that we are not reaping any benefits from this.

**Comment by noobxgockel** [comment]
Okay i'll work on adding disqus to patterns too. Also i edited the the Main post...

**Comment by npathai** [comment]
@noobxgockel I have added comment on first blog post

**Comment by iluwatar** [comment]
My Disqus username is @ilkkaseppl

**Comment by noobxgockel** [comment]
I added you both as an admin with ability to edit comments and edit settings c:
