### ISSUE TITLE
ReaderWriterLock unit tests fail on CI

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#343]
Something wrong with the ReaderWriterLock unit tests.

See Travis builds:

https://travis-ci.org/iluwatar/java-design-patterns/builds/101906103
https://travis-ci.org/iluwatar/java-design-patterns/builds/101915400
https://travis-ci.org/iluwatar/java-design-patterns/builds/101917864

**Comment by hoswey** [comment]
From the log file of [Travis-Ci](https://api.travis-ci.org/jobs/101915401/log.txt?deansi=true), it pointouts that reader thread submited to the thread pool cannot  be executed in 149(99+50)ms. I suspect that the Travis-Ci has a high load and it can't assume the read can executed in accurate time.  I have revised the test case with another form. 

 >Failed tests: 
>  ReaderAndWriterTest.testReadAndWrite:45 
>Wanted but not invoked:
>reader.read();
>-> at com.iluwatar.reader.writer.lock.ReaderAndWriterTest.testReadAndWrite(ReaderAndWriterTest.java:45)
>
>However, there were other interactions with this mock:
>reader.run();
>-> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

```java
  @Test
  public void testReadAndWrite() throws Exception {

    ReaderWriterLock lock = new ReaderWriterLock();

    Reader reader1 = spy(new Reader("Reader 1", lock.readLock()));
    Writer writer1 = spy(new Writer("Writer 1", lock.writeLock()));

    executeService.submit(reader1);
    // Let reader1 execute first
    Thread.sleep(50);
    executeService.submit(writer1);

45: verify(reader1, timeout(99).atLeastOnce()).read();
    verify(writer1, after(10).never()).write();
    verify(writer1, timeout(100).atLeastOnce()).write();

  }
```

**Comment by iluwatar** [comment]
@hoswey just create pull request when ready
