### ISSUE TITLE
Data Transfer Object pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#348]
http://martinfowler.com/eaaCatalog/dataTransferObject.html

**Comment by raviteja1992y** [comment]
I started working on this

**Comment by iluwatar** [comment]
Ok, I will update the labels. Don't hesitate to ask if you need support.

**Comment by iluwatar** [comment]
@raviteja1992y are you still on working on this?

**Comment by raviteja1992y** [comment]
@iluwatar  Yeah. I am working on this.

**Comment by iluwatar** [comment]
@raviteja1992y how's it going? Please let us know if you are still implementing this pattern.

**Comment by iluwatar** [comment]
There is no answer, so this issue is free for taking again.

**Comment by squla** [comment]
@iluwatar 
I can do it. But it should be simple example i.e. we get two things from db and we prepare DTO, or maybe i should present usage with rest api ?

**Comment by gopinath-langote** [comment]
@iluwatar 
Is anyone still working on it? I can take it up for development.

**Comment by iluwatar** [comment]
@squla are you still working on it?

**Comment by iluwatar** [comment]
@gopinath-langote no reply from @squla so I guess we can transfer the issue for you to work on.

**Comment by gopinath-langote** [comment]
@iluwatar I am working on this.

**Comment by iluwatar** [comment]
Ok @gopinath-langote

**Comment by iluwatar** [comment]
Puml id missing

**Comment by gopinath-langote** [comment]
@iluwatar Added Piml id to README.md
