### ISSUE TITLE
Value Object pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#349]
http://martinfowler.com/bliki/ValueObject.html

**Comment by JuhoKang** [comment]
I think the definition of the Value Object is a little bit inclusive.
Thinking of implementing a pattern. How about this : VALJO - Value Java Objects
which has more strict set of rules for a correctly defined immutable value object. 
Suggested by Stephen Colebourne.
http://blog.joda.org/2014/03/valjos-value-java-objects.html
If this is not bad I want to work on this.

**Comment by iluwatar** [comment]
This is a good specification. I think we're still talking about the same Value Object pattern even though the author mr. Colebourne invents this new term VALJO. So my suggestion would be to implement the Value Object pattern using the VALJO specs. Does this sound reasonable?

**Comment by JuhoKang** [comment]
:+1:  Yes it is. I will get these details in the code and documentation. Can I work on this?

**Comment by npathai** [comment]
Sure go ahead. :+1: I will update the labels.
