### ISSUE TITLE
Page Controller pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#350]
http://martinfowler.com/eaaCatalog/pageController.html

**Comment by nagarro-bhavya** [comment]
Hi, Can I work on this one?

**Comment by iluwatar** [comment]
Ok @nagarro-bhavya

**Comment by iluwatar** [comment]
Issue available

**Comment by Linly1080** [comment]
Hi, I'd like to work on this issue. Could it be assigned to me if still available?

**Comment by iluwatar** [comment]
Ok @Linly1080

**Comment by Linly1080** [comment]
Sorry, I have no time work on it now.

**Comment by Marikattt** [comment]
Hi @iluwatar, I would like to work on this issue. Could you assign this to me if it is available?

**Comment by iluwatar** [comment]
All right, go ahead @Marikattt

**Comment by Marikattt** [comment]
Hi @iluwatar, 
I made a PR for this issue, so could you please review [this pr #2202](https://github.com/iluwatar/java-design-patterns/pull/2202)?
