### ISSUE TITLE
Unit of Work pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#352]
http://martinfowler.com/eaaCatalog/unitOfWork.html

**Comment by ragzisme** [comment]
I will work on this issue

**Comment by iluwatar** [comment]
@ragzisme :+1:

**Comment by iluwatar** [comment]
@ragzisme are you working on this?

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by andy-williams** [comment]
I can probably give this a go since I own the book anyway.

**Comment by iluwatar** [comment]
Ok, you're good to go @andy-williams

**Comment by iluwatar** [comment]
@andy-williams how is it progressing? Please let us know if you are still working on this.

**Comment by iluwatar** [comment]
Since we received no comment this issue is free for taking again.

**Comment by piyushchaudhari04** [comment]
@iluwatar I will work on this pattern

**Comment by iluwatar** [comment]
Ok @piyushchaudhari04
