### ISSUE TITLE
Pattern Category/Tag descriptions

### ISSUE THREAD

**Issue by markusmo3** [iluwatar/java-design-patterns#353]
Hello there,

since we now are able to display more information about specific Categories and Tags we maybe should do so, especially for those that might be confusing. The Categories and Tags confusing me the most (before looking them up):
- Business Tier, all of patterns could be used in a business, why is this special ?
- Camel, after research i found out it means the Apache Camel Project, is this correct?
- EIP, abbreviations...

Maybe it would help to describe the others too, but im really unsure about that.
To add or remove a tooltip you just have to look at the documentation in [tags.yml](https://github.com/iluwatar/java-design-patterns/blob/gh-pages/_data/tags.yml) and [categories.yml](https://github.com/iluwatar/java-design-patterns/blob/gh-pages/_data/categories.yml)

**Comment by npathai** [comment]
@noobxgockel 
 - In Multi-tiered applications of J2EE, Business tier is where server side logic resides. Example EJB (Enterprise Java Beans)
 - Camel is for Apache Camel, Yes. You got it right.
 - EIP abbreviation? I didn't get you.

Presently I don't think we have tags or categories that really require any tooltip. @iluwatar What do you think?

**Comment by iluwatar** [comment]
Spring Data is used in Repository.

**Comment by iluwatar** [comment]
Well, not really required, but makes the user interface nicer and friendlier. EIP is Enterprise Integration Patterns.

**Comment by markusmo3** [comment]
I recently had an idea about this. Rather than using tooltips (which is quite bad for disabled people or smartphone/tablet users) we could add a Question mark icon to the right of the headings and explain the different Categories and tags in detail...

I mainly want that to _really_ clarify what is meant with what category/tag so we can save the user the googling :smile:
