### ISSUE TITLE
Abstract document pattern

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#355]
https://en.m.wikipedia.org/wiki/Abstract_Document_Pattern

**Comment by wael-sakhri** [comment]
I can start to add this pattern

**Comment by iluwatar** [comment]
Please, go ahead @wael-sakhri

**Comment by iluwatar** [comment]
@wael-sakhri did you notice this article https://www.voxxed.com/blog/2016/01/type-safe-views-using-abstract-document-pattern/

**Comment by iluwatar** [comment]
Ping @wael-sakhri are you working on this?

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by qza** [comment]
Hi. I can work on this.

**Comment by iluwatar** [comment]
@qza please go ahead.
