### ISSUE TITLE
Links within some of the Wiki Pages are broken.

### ISSUE THREAD

**Issue by mikulucky** [iluwatar/java-design-patterns#361]
Some of the links within the wiki pages content are broken. Causing the user to be directed to the first page of the wiki. It seems to be that within the link, the proceeding "0" on the page titles are missing. 

For example

```Markdown
[coding conventions](https://github.com/iluwatar/java-design-patterns/wiki/3.-Coding-conventions)
``` 
Should be
```Markdown
[coding conventions](https://github.com/iluwatar/java-design-patterns/wiki/03.-Coding-conventions)
```

**Comment by iluwatar** [comment]
I believe the broken links are now fixed. Please reopen this issue if not satisfied.
