### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by mikulucky** [iluwatar/java-design-patterns#369]
When navigating to  http://java-design-patterns.com/patterns/ there is an error message of **AccessDeniedAccess Denied92B077064E60271FJkLpNqms3dcnxsOd+4f2dcNQ7CSWlUqCQ74A4TcVtnA4NqzqbINoKbq6rxXizZTdVaXIqXEBEd0=**

<img width="1920" alt="screenshot 2016-02-02 19 42 41" src="https://cloud.githubusercontent.com/assets/4526195/12761989/29d8770e-c9e5-11e5-9a46-a64442b8bf0f.png">

**Comment by markusmo3** [comment]
@mikulucky seems strange, the main site http://java-design-patterns.com/ works but no sublinks of it...
Use the more upstream version in the meantime: http://iluwatar.github.io/java-design-patterns/patterns/

@iluwatar Could it be your domain? If not i'll try and look at the recent website changes...

**Comment by mikulucky** [comment]
Could it be the recent GitHub pages update?

**Comment by iluwatar** [comment]
The site is currently down due to my configuration error. I'm working on it...

**Comment by iluwatar** [comment]
As far as I know, the [java-design-patterns.com](http://java-design-patterns.com) site should be working again. The downtime was due to my Amazon S3 + CloudFront misconfiguration.
