### ISSUE TITLE
What is the use of UML drawing software

### ISSUE THREAD

**Issue by mrljdx** [iluwatar/java-design-patterns#38]
Can you tell me the UML diagram is  used  what software to draw?

**Comment by iluwatar** [comment]
ObjectAid UML Explorer is the primary tool - see section "How to contribute" of README.md.

**Comment by mrljdx** [comment]
Thanks

**Comment by ItaloQualisoni** [comment]
Just for reference, LucidChart (https://www.lucidchart.com) is a great tool for drawing UML diagram and you can share your diagrams and edit it online in real time.

Also, if you're a student you can use it for free :D
https://www.lucidchart.com/pages/education/students
