### ISSUE TITLE
Mute idiom

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#385]
http://blog.jooq.org/2016/02/18/the-mute-design-pattern/

**Comment by npathai** [comment]
Have used this idiom numerous times. On it.

I will be creating two mute methods:
 - `mute()` throws `AssertionError` if unexpected exception occurs. Should be used when some class declares exception but should never throw exception.
 - `loggedMute()` swallows exception by logging it on err stream. Should be used when all you can do about exception is trace it.
