### ISSUE TITLE
Should we have a discussion prior to implementation?

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#399]
We have recently faced issue where the implementation of the pattern is not upto the mark and does not fulfill all the requirements of the pattern.

I was wondering whether we should have a under-discussion tag, under which once someone shows interest in working on pattern we can gather ideas and use cases from the contributors and then start working on the pattern. 

There are several advantages:
 - Will allow us to come up with best implementation based on inputs (a time frame of maybe a week for gathering inputs). This also allows indirect contribution to pattern as some people have ideas but are not able to dedicate enough time to implement the pattern.
 - Will reduce the chances of gaps in PRs
 - Will not require us to validate PR in terms whether it is a valid implementation
 - Saves time

Let me know if this is a good idea?

**Comment by iluwatar** [comment]
I guess we could offer more assistance when someone starts working on issue. But I'm not sure if this should be mandatory.

**Comment by geniusgeek** [comment]
Please what pattern are we talking about?

**Comment by npathai** [comment]
@iluwatar fair enough. Once the contributor figures out an implementation discussing that with peers from community will only improve things. This also gives us another collaborative opportunity. Presently PRs are the only collaborative part. 
Awaiting further comments.

**Comment by npathai** [comment]
@geniusgeek firstly I am not pin pointing any mistakes. I highly appreciate contribution of any size. 
Recently this happened with plugin pattern implementation that it did not fully represent pattern n its true power. Also happened with API gateway, the sample stripped out so much complexity that it did not showcase why is pattern so useful. I rose the point n clarified with the contributor. That's why I was thinking it will be a gud idea.

**Comment by iluwatar** [comment]
@npathai maybe we can encourage discussion before implementation in https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute. Also, the new label `needs discussion` should be described in the instructions here https://github.com/iluwatar/java-design-patterns/wiki/06.-Working-with-issues. After these steps I think we can close this issue.
