### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by Person-93** [iluwatar/java-design-patterns#403]
Intent
------
The purpose is for a function that performs some asynchronous action to immediately return an interface that allows other functions to queue other functions to be called when it completes.

**Comment by npathai** [comment]
Called `Future`s in Java World.

**Comment by geniusgeek** [comment]
I think this is not a regular future. Because it not just return an object
for which the result is to be retrieved, we are expected to include list of
functions to be performed after the future result comes. Therefore i see it
as a combination of future, command & command processor pattern(to queue
the functinos) and active Object pattern(to define the new context to
implement the functions).

**Comment by Person-93** [comment]
It would include that, also it would let you chain promises. If you have several asynchronous tasks and you want to wait until they all finish, you can pass all of the promises that they return into a factory method and it will return a promise that won't be resolved until they're all completed.

**Comment by npathai** [comment]
Yes to be precise Guava's SettableFuture is similar to promises. It allows chaining too.

**Comment by npathai** [comment]
I am picking this up.

**Comment by iluwatar** [comment]
I don't follow what this issue is about. Can you update the subject, description and labels?

**Comment by npathai** [comment]
@iluwatar This task can be considered asan enhancement over `AsyncMethodInvocation`. 
If our `AsyncResult` had provided some methods to operate on future result then it can be called a promise sort of.

Here are some useful links:
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

http://www.nurkiewicz.com/2013/05/java-8-definitive-guide-to.html?m=1

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by iluwatar** [comment]
@npathai is this a new pattern or an enhancement to existing one?

**Comment by npathai** [comment]
@iluwatar I am in favor of treating this as a new pattern and keep our AsyncMethodInvocation as is. I will find out whether we can utilize its dependency while implementing this pattern. This is more of a functional approach. But again I will get concrete feel of it when I start implementing it. So for now I am treating it as new pattern.

**Comment by iluwatar** [comment]
:+1:
