### ISSUE TITLE
Bump up JUnit version to 5

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#408]
Presently JUnit 5 is under alpha stage, once it is open for public use we should update library. 

JUnit 5 is lambda ready and provides variety of features pre-built that will remove some library dependencies.

Plus it never hurts to stay updated and we can provide feedback on any broken features.

**Comment by iluwatar** [comment]
It should be quite stable already http://junit.org/junit5/

**Comment by amogozov** [comment]
@iluwatar I would like to give it a try!

**Comment by iluwatar** [comment]
Ok @amogozov
