### ISSUE TITLE
IDE instructions

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#409]
We need step-by-step instructions for setting up and working in IDE such as Eclipse or IntelliJ Idea. The page could be created in [developer wiki](https://github.com/iluwatar/java-design-patterns/wiki).

**Comment by npathai** [comment]
:+1:

**Comment by iluwatar** [comment]
I added some Eclipse instructions https://github.com/iluwatar/java-design-patterns/wiki/12.-IDE-instructions

**Comment by iluwatar** [comment]
It also contains Idea instructions now.

**Comment by neonds** [comment]
got it

2016-04-20 13:44 GMT-06:00 Ilkka Seppälä <notifications@github.com>:

> It also contains Idea instructions now.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/iluwatar/java-design-patterns/issues/409#issuecomment-212574965>
>



-- 
Guillermo B Díaz Solís
UCR Informática Empresarial

**Comment by iluwatar** [comment]
Can someone contribute NetBeans instructions?

**Comment by zafarella** [comment]
you don't really need any instructions i think. this is maven project - all of the ide's can deal with it. Just saying that you need to import it as maven project is enough + checkstyle of course.

**Comment by iluwatar** [comment]
I agree that importing the project is easy, but setting up the code style according to Checkstyle rules may not be so straightforward.
