### ISSUE TITLE
Builder Pattern: issue accessing inner static class

### ISSUE THREAD

**Issue by aagarw33** [iluwatar/java-design-patterns#411]
Shouldn't you access it as 
` Hero mage =
	        new Hero.HeroBuilder(Profession.MAGE, "Riobard").withHairColor(HairColor.BLACK)
	            .withWeapon(Weapon.DAGGER).build();`

instead of
` Hero mage =
	        new HeroBuilder(Profession.MAGE, "Riobard").withHairColor(HairColor.BLACK)
	            .withWeapon(Weapon.DAGGER).build();`

**Comment by rinormaloku** [comment]
import com.iluwatar.builder.Hero.HeroBuilder

**Comment by geniusgeek** [comment]
Cant we make it cleaner by introducing a static factory to the Hero class that returns the instance of a herobuilder.

eg:
Hero mage = Hero.HeroBuilder(Profession.MAGE, "Riobard").withHairColor(HairColor.BLACK) .withWeapon(Weapon.DAGGER).build();

**Comment by npathai** [comment]
@geniusgeek Yes we can do that. I can settle with
`Hero hero = Hero.newBuilder(Profession.MAGE, "Riobard").withHairColor(HairColor.BLACK).build();`

So we can introduce a static method `newBuilder(requiredParams...)` in `Hero` class.

**Comment by iluwatar** [comment]
Using the style described in Joshua Bloch's Effective Java this would be: 

`Hero mage =
        new Hero.Builder(Profession.MAGE, "Riobard").withHairColor(HairColor.BLACK)
            .withWeapon(Weapon.DAGGER).build();`

In this case we would need to rename `HeroBuilder` to `Builder`.

**Comment by kevcomedia** [comment]
Hi. If I understood it correctly, changing any of `Hero`'s fields means the `HeroBuilder` must be changed also. Isn't that bad? I'm new here. Please enlighten me.

**Comment by iluwatar** [comment]
@kevcomedia you are right. The attribute duplication is a downside of the pattern. Builders are fancy to use but writing them tends to be boilerplate. In cases like this Lombok can be really helpful. Take a look at [@Builder annotation](https://projectlombok.org/features/Builder.html).
