### ISSUE TITLE
Circuit Breaker pattern

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#413]
http://martinfowler.com/bliki/CircuitBreaker.html

The basic idea behind the circuit breaker is very simple. You wrap a protected function call in a circuit breaker object, which monitors for failures. Once the failures reach a certain threshold, the circuit breaker trips, and all further calls to the circuit breaker return with an error, without the protected call being made at all. Usually you'll also want some kind of monitor alert if the circuit breaker trips.

A production ready implementation of pattern can be found here.
https://github.com/Comcast/jrugged/blob/master/jrugged-core/src/main/java/org/fishwife/jrugged/CircuitBreaker.java

**Comment by geniusgeek** [comment]
From the implementation, CircuitBreaker-State Pattern is a great pattern
compound to use for our implementation. The state pattern is to map
different state of the CircuitBreaker.  I love this pattern.

**Comment by npathai** [comment]
@geniusgeek Yes we used this pattern for years in production but didnt know its name. Found it today while exploring cloud patterns. We had implemented it without official name n now i am going to refactor our production code to use it.

**Comment by iluwatar** [comment]
I'll implement this pattern.

**Comment by iluwatar** [comment]
http://techblog.netflix.com/2011/12/making-netflix-api-more-resilient.html

**Comment by iluwatar** [comment]
https://msdn.microsoft.com/en-us/library/dn589784.aspx

**Comment by iluwatar** [comment]
http://www.hascode.com/2017/02/resilient-architecture-circuit-breakers-for-java-hystrix-vert-x-javaslang-and-failsafe-examples/

**Comment by MohitNarula** [comment]
Hi .. can I work on this one ?

**Comment by iluwatar** [comment]
Ok @MohitNarula

**Comment by iluwatar** [comment]
Issue is free

**Comment by PalAditya** [comment]
Hi, wondering if I could take this issue up since it's free? Would love to contribute to this awesome repository 😄

**Comment by iluwatar** [comment]
Wonderful @PalAditya, please go ahead. Looking forward to your pull request.
