### ISSUE TITLE
Thread-local singleton

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#418]
Add to Singleton example: https://dzone.com/articles/singleton-implementation-1

**Comment by YusufGandhi** [comment]
Hi,

I'm Yusuf and am new to this project. I'm currently trying to learn to contribute something. Willing to work on this enhancement, if I may, as the first baby step to contributing to this project in the long run.

Please let me know.

**Comment by iluwatar** [comment]
@YusufGandhi welcome! I'll change the issue labels to indicate you're working on this. Please don't hesitate to ask here or in [Gitter](https://gitter.im/iluwatar/java-design-patterns) if you need help.

**Comment by YusufGandhi** [comment]
@iluwatar Thanks for the prompt reply! I'll definitely ask for help if required.

**Comment by geniusgeek** [comment]
@YusufGhandi @iluwatar, ThreadLocal singleton is not necessarily a
singleton pattern, it is a concurrency resource management pattern. Take a
look at Pattern Oriented Software Architecture by D. Schmidth, This pattern
has been adopted into Java for resource management. Please dont add this as
a Singleton, It was implemented as a singleton so that it can be both
threadsafe, process safe and memory safe.

Cheers

**Comment by iluwatar** [comment]
@geniusgeek I see your point. However, it is inherent to Singleton to take a stand against concurrency. The most basic version creates the static instance eagerly providing thread-safety. The lazily initialized Singletons employ various tricks to be safe when the instance is accessed concurrently. Isn't thread-local Singleton just one more way to solve this?
Also, take a look at related Multiton pattern https://github.com/iluwatar/java-design-patterns/blob/master/multiton/src/main/java/com/iluwatar/multiton/Nazgul.java how it ensures thread-safery with ConcurrentHashMap.

**Comment by geniusgeek** [comment]
All i am saying is that ThreadLocal pattern is not necessarily a Singleton
pattern, it is one of the Concurrent Pattern that ensures shared memory and
shared process pattern. The reason why it is implemented using singleton
pattern is for data consistency. So it is wrong to use it as a Singleton
pattern

**Comment by npathai** [comment]
@iluwatar I second @geniusgeek here. It does not feel right to call thread locals singleton. Though I don't have arguments against that as well. I will figure it out and leave a comment.

**Comment by iluwatar** [comment]
The example is not entirely clear how it relates to Singleton. How about if we write it this way:

```
public final class President {

    // Instance per thread
    private static final ThreadLocal<President> INSTANCE 
        = new ThreadLocal<President>() {
        @Override
        protected President initialValue() {
            return new President();
        }
    };

    /**
     * @return instance
     */
    public static President getInstance() {
        return INSTANCE.get();
    }

    /**
     * Hidden constructor
     */
    private GlobalConfExtensions() {
    }
}
```

**Comment by iluwatar** [comment]
@npathai @geniusgeek looking forward to hear your comments. In your opininion, can the presented code be treated as a variant of Singleton? I think so.

**Comment by npathai** [comment]
@iluwatar I have reservations to not call it thread local singleton.

**Comment by iluwatar** [comment]
@npathai @geniusgeek thanks for your valuable comments. Since you guys disagree, this thread-local Singleton will not be added.
