### ISSUE TITLE
Search function on web site does not find all the patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#419]
Typing into the search field gives no results for these keywords:

`Caching` - no results found
`Flyweight` - no results found
`Mute` - no results found
`Iterator` - no results found
`Memento` - no results found

The list is not comprehensive, I did not try them all. I suspect there are others too.

**Comment by markusmo3** [comment]
Woops, didnt mean to close this issue... I did activate a manual indexing though.
So we'll have to wait at least a full 24h for google to crawl it according to its docs

**Comment by iluwatar** [comment]
Ok, thumbs up, let's wait and see.

**Comment by iluwatar** [comment]
Just tested this, unfortunately the search still seems broken.

**Comment by markusmo3** [comment]
yep allready working on it, should come very soon

**Comment by iluwatar** [comment]
Seems to work flawlessly :+1: Great work @markusmo3
