### ISSUE TITLE
Game programming patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#420]
http://gameprogrammingpatterns.com/contents.html

**Comment by qpi** [comment]
Hello @iluwatar. Could You split this issue?
It would be needed as we are a group from university and for one of our course we have to participate in an open source project. So if possible we would like to take these patterns:
- Double Buffer
- Update Method
- Type Object
- Event Queue
- Service Locator

**Comment by iluwatar** [comment]
@qpi it's done now. Please comment on the individual patterns you would like to take and I will assign them to you.
