### ISSUE TITLE
Leader/Followers

### ISSUE THREAD

**Issue by hoswey** [iluwatar/java-design-patterns#424]
[DelayQueue](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/concurrent/DelayQueue.java#DelayQueue) has using the the Leader/Followers pattern to detect the head of expire item, it is a very interest pattern

http://www.cs.wustl.edu/~schmidt/PDF/lf.pdf
http://www.cs.wustl.edu/~schmidt/POSA/POSA2/pattern-abstracts.html#lf

**Comment by iluwatar** [comment]
Ping @amit2103

**Comment by amit2103** [comment]
Yes.. I read this...I saw the implementation too...But I thought its best to implement something that will be easily undrestandable..also copying the Delay Queue wouldn't have made much sense .

**Comment by amit2103** [comment]
@iluwatar  I had made a new pull request. Please review it when you have time
