### ISSUE TITLE
Web site build failing

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#426]
The most recent gh-pages build has failed and java-design-patterns.com site has not been updated:

https://travis-ci.org/iluwatar/java-design-patterns/builds/125283578

**Comment by iluwatar** [comment]
It would be nice to show the gh-pages build status in the `README.md` as well for easier error detection.

**Comment by markusmo3** [comment]
Wooops, forgot to mention this issue in the commits...
Here they are:
on master: https://github.com/iluwatar/java-design-patterns/commit/71e3443e0ea28a6c8e2b94c2e4cc6c0bf24dc7a2
on gh-pages: https://github.com/iluwatar/java-design-patterns/commit/e0ccffa279398e8e5d050c6126ec167cb4f19f6c

Waiting for travis to build everything fully...

**Comment by markusmo3** [comment]
Build passed: https://travis-ci.org/iluwatar/java-design-patterns/builds/125362212

~closed

**Comment by iluwatar** [comment]
Thanks for looking into this @markusmo3 :+1:
