### ISSUE TITLE
Handling/Supporting Translations

### ISSUE THREAD

**Issue by markusmo3** [iluwatar/java-design-patterns#428]
Hello everybody,
so i recently got an email from a nice Brazilian developer who wants to translate our repo for his people. Im not sure if he wants to be in the spotlight so i wont give any names.

But the main question is:
Do we want to support translation on our side ? Or should he just copy/fork our repo?
On the technical side it would be quite the work to get i18 or multi-language support working with the website, especially if we just do branches for all the other languages.
The most impacting change would be that we wont be able to use the github-pages autobuild anymore and would have to build manually with travis or sorts because we need a specific i18n jekyll plugin.

I think the easiest route would be to convert to an organization and do it similar to [DiscoverMeteor](https://www.discovermeteor.com/blog/community-translations-with-github-middleman-codeship-heroku)

@iluwatar @npathai Some input on this maybe ?

**Comment by iluwatar** [comment]
I think this feature should definitely be on our roadmap. Not the whole world runs on English.

In general I like the way they put it together in DiscoverMeteor. There would be separate language files and the correct one would be referenced in the web site config. I understand this would require significant design and implementation effort. Would the person who suggested this be willing to work on this?

**Comment by markusmo3** [comment]
probably a good idea to use this: https://github.com/untra/polyglot

**Comment by iluwatar** [comment]
:+1:

**Comment by npathai** [comment]
Totally up for this :+1:

**Comment by dougg0k** [comment]
Hi @markusmo3 If the person who wants to translate needs any help, I'm open to help.

**Comment by IAmTheUnderTaker** [comment]
I think we should. I not sure he's tryna get spotlight though. Thonk....

**Comment by iluwatar** [comment]
Moved to https://github.com/iluwatar/java-design-patterns-web/issues/3
