### ISSUE TITLE
Add criticism to Singleton

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#437]
http://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons

**Comment by iluwatar** [comment]
https://sites.google.com/site/steveyegge2/singleton-considered-stupid

**Comment by iluwatar** [comment]
http://www.yegor256.com/2016/06/27/singletons-must-die.html

**Comment by npathai** [comment]
http://misko.hevery.com/2008/08/17/singletons-are-pathological-liars/

**Comment by dmitraver** [comment]
HI!

I would like to pick this one and #436 as well.

**Comment by iluwatar** [comment]
@dmitraver you're good to go!
