### ISSUE TITLE
Saga pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#438]
http://kellabyte.com/2012/05/30/clarifying-the-saga-pattern/
http://vasters.com/clemensv/2012/09/01/Sagas.aspx
https://www.youtube.com/watch?v=nSfXcSWq0ug&list=WL

**Comment by MohitNarula** [comment]
hi @iluwatar 

Can I pick up this one ?

**Comment by iluwatar** [comment]
Ok @MohitNarula

**Comment by talipkorkmaz** [comment]
Is there any development?

**Comment by iluwatar** [comment]
@MohitNarula are you still working on this? If not, @talipkorkmaz can pick this up.

**Comment by iluwatar** [comment]
The task is free

**Comment by besok** [comment]
IF no objections i will sign myself up

**Comment by iluwatar** [comment]
Ok @besok
