### ISSUE TITLE
Cache Aside pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#440]
https://msdn.microsoft.com/en-us/library/dn589799.aspx

This pattern could be incorporated into https://github.com/iluwatar/java-design-patterns/tree/master/caching example.

**Comment by christofferh** [comment]
Thanks for an excellent project, I thought I should contribute something back and this one seemed like a low-hanging fruit.

Would it make sense to simply add two helper methods in AppManager, e.g. `saveAside` and `findAside`

```java
private static void saveAside(UserAccount userAccount) {
    DbManager.updateDb(userAccount);
    CacheStore.invalidate(userAccount.getUserId());
}
```

and then either delegate `CacheStore.(get,set,invalidate)` to `cache`

```java
public static void invalidate(String userId) {
    cache.invalidate(userId);
}
```

or simply expose `cache` with a `CacheStore.getCache()` getter?

And then add a new case:
```java
public static void save(UserAccount userAccount) {
    if (cachingPolicy == CachingPolicy.THROUGH) {
      CacheStore.writeThrough(userAccount);
    } else if (cachingPolicy == CachingPolicy.AROUND) {
      CacheStore.writeAround(userAccount);
    } else if (cachingPolicy == CachingPolicy.BEHIND) {
      CacheStore.writeBehind(userAccount);
    } else if (cachingPolicy == CachingPolicy.ASIDE) {
      saveAside(userAccount);
}
```

Would that make sense, @iluwatar?

**Comment by iluwatar** [comment]
@christofferh the plan looks reasonable. Just create a pull request and we'll review.
