### ISSUE TITLE
Compensating Transaction pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#441]
https://msdn.microsoft.com/en-us/library/dn589804.aspx

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/compensating-transaction

**Comment by mohanaraosv** [comment]
I hope you have considered segregating cloud and EIP patterns

**Comment by iluwatar** [comment]
Interested to hear your ideas, how would you segregate them? At the moment we have categories and tags for the patterns that can be used to distinguish for example cloud patterns and enterprise integration patterns.
