### ISSUE TITLE
Federated Identity pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#443]
https://msdn.microsoft.com/en-us/library/dn589790.aspx

**Comment by piyushchaudhari04** [comment]
hi @iluwatar i am interested in implementing this pattern

**Comment by iluwatar** [comment]
Ok @piyushchaudhari04

**Comment by iluwatar** [comment]
The issue is free

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/federated-identity

**Comment by lkpengcs** [comment]
hi, can I work on this issue?

**Comment by iluwatar** [comment]
Ok @lkpengcs
