### ISSUE TITLE
Gatekeeper pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#444]
https://msdn.microsoft.com/en-us/library/dn589793.aspx
Please notice that this is a cloud design pattern that should be implemented using cloud technologies (see https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections)

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/gatekeeper

**Comment by Anditty** [comment]
Hey, @iluwatar , I'd like to work on it, and I think I can finish this issue before this Sunday.

**Comment by ohbus** [comment]
Great @Anditty!

Looking forward to your contributions.
