### ISSUE TITLE
Index Table pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#446]
https://msdn.microsoft.com/en-us/library/dn589791.aspx

**Comment by ghost-60** [comment]
Working on it

**Comment by iluwatar** [comment]
Ok @ghost-60

**Comment by iluwatar** [comment]
@ghost-60 are you still working on this?

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by ghost-60** [comment]
Sorry, no.

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/index-table

**Comment by rajanpatel4578** [comment]
I am working on this issue for my University Term Project. I have a few naive questions:
What is the expected output from normalized tables- primary keys only or the entire data? I will mold my code accordingly.
Do you think this pattern needs to make connections with any available database or Java code is a sufficient solution?

**Comment by iluwatar** [comment]
It would be great to have a database backend and an emulation layer. When the user queries objects by the primary key, the results would be fetched directly from the database. For other queries where the table wouldn't have indexes available, the emulation layer would be called and it would return the pre-sorted objects quickly. Hopefully you can grasp the idea @rajanpatel4578
