### ISSUE TITLE
Materialized View pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#448]
https://msdn.microsoft.com/en-us/library/dn589782.aspx

**Comment by akhambir** [comment]
I'll implement this.

**Comment by iluwatar** [comment]
This issue is reserved to @akhambir

**Comment by iluwatar** [comment]
@akhambir if you have questions or want to discuss the strategies of implementing this pattern please comment here.

**Comment by iluwatar** [comment]
@akhambir are you still working on this?

**Comment by salman-bhai** [comment]
Is this issue open ?

**Comment by iluwatar** [comment]
@akhambir does not answer, so I assume it is. I'm changing the labels to indicate it is free for taking.

**Comment by iluwatar** [comment]
@salman-bhai still interested to work on this?

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view
