### ISSUE TITLE
Priority Queue pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#449]
https://msdn.microsoft.com/en-us/library/dn589794.aspx

**Comment by harshSE** [comment]
Hi @iluwatar @npathai , I would like to contribute on this issue.

**Comment by iluwatar** [comment]
@harshSE go ahead, it's all yours :)

**Comment by npathai** [comment]
Good to see you @harshSE. Looking forward to your long term support 😊

**Comment by iluwatar** [comment]
@harshSE are you still working on this?

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by pelmegov** [comment]
Hi @iluwatar @npathai , I would like to contribute on this issue.

**Comment by iluwatar** [comment]
Ok @pelmegov

**Comment by HaydenMeloche** [comment]
@iluwatar Can I take over this issue?

**Comment by iluwatar** [comment]
@pelmegov are you still working on this? Please comment or @HaydenMeloche takes it over.

**Comment by ranjeet-floyd** [comment]
@iluwatar  Can i take this please ?. Raised PR https://github.com/iluwatar/java-design-patterns/pull/888

**Comment by ranjeet-floyd** [comment]
@iluwatar  Please review PR https://github.com/iluwatar/java-design-patterns/pull/888.  Thanks

**Comment by iluwatar** [comment]
Ok @ranjeet-floyd

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/priority-queue
