### ISSUE TITLE
DAO Design Pattern

### ISSUE THREAD

**Issue by ozlerhakan** [iluwatar/java-design-patterns#45]
Hi @iluwatar ,

First of all, thank you for this comprehensive repo!  I haven't seen the dao design pattern among the rest. So, I am just wondering whether it is actually part of the design solutions or not.

**Comment by iluwatar** [comment]
Hi there @ozlerhakan !

I'm glad you find the repository interesting. The [DAO](http://en.wikipedia.org/wiki/Data_access_object) pattern certainly belongs here, we just don't have an implementation for it yet.

**Comment by ozlerhakan** [comment]
Ah okay then, so If the current contributors (including you) will not plan to implement it, I can give you a hand for the implementation via PR but not now (:

**Comment by iluwatar** [comment]
Contributions are welcome @ozlerhakan . Please leave the issue open and it will be fixed soon.

**Comment by mgiovenco** [comment]
I believe I have the implementation for this ready to go.  If it's okay for me to contribute, I can create a pull request for this.

**Comment by iluwatar** [comment]
@mgiovenco That is great! Please proceed with the pull request and we'll check it.

**Comment by mgiovenco** [comment]
Will do!  I just need to add the diagram piece before creating pull request.  Expect the pull request in the next day or two.

**Comment by iluwatar** [comment]
Resolved with commit 58da95b4676ff09cbed607934ab3722063128e16

**Comment by ozlerhakan** [comment]
Thanks @iluwatar  and @mgiovenco :+1:

**Comment by pavansn** [comment]
Hi @iluwatar ,
Can I add these design patterns into the repository?
          1. 2-way adapter
          2. IOC - Inversion of Control
          3. Dependency Injection
I hope these patterns belong to this repository.

**Comment by iluwatar** [comment]
Hi @pavansn ,

Surely these patterns all belong here. You are welcome to contribute. I suggest you make an individual pull request out of each of the patterns so we can review and comment easily.
