### ISSUE TITLE
Queue-Based Load Leveling pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#450]
https://msdn.microsoft.com/en-us/library/dn589783.aspx

**Comment by Amarnath510** [comment]
@iluwatar 
I want to work on this. I read the doc and I think I can do it.
I am 4 years of work ex on Java/J2EE but I am beginner to open source contributions so please help me.
Where can I start? Where to ask questions if there are any?

**Comment by iluwatar** [comment]
@Amarnath510 your contribution is welcome. Please read https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute first. You can ask discuss the implementation here or in the Gitter chat  https://gitter.im/iluwatar/java-design-patterns.

**Comment by Amarnath510** [comment]
@iluwatar 
I have done a basic UML diagram in which I am presenting my classes, interfaces and their relationships.
![uml](https://cloud.githubusercontent.com/assets/4599623/20237995/2b12882e-a907-11e6-91db-a41a71330237.gif)

NOTE: I haven't followed any code conventions as of now. This is just for design discussions.

- I have created 3 Worker threads each one submitting different number of tasks to the BlockingQueue. After each Message object submit the Thread sleeps for 0.001s.
- ServiceExecutor class will pick up each Message object from the BlockingQueue and serves it.
- No matter how much load is been submitted by the task(s) the ServiceExecutor will pick up only 1 message task at a time from the Queue.

This is my understanding and the UML diagram for the same. Please feel free to correct me.

**Comment by iluwatar** [comment]
@Amarnath510 according to my understanding of the pattern the design draft looks correct. The task generators produce tasks that go into a queue and the service consumes the tasks from the queue at its own rate.

**Comment by Amarnath510** [comment]
@iluwatar 
Thanks for the review.
Yes. The Task generators generate tasks at any rate and submit them to the queue and the ServiceExecutor executes the tasks one after the other from the Queue.
I will proceed to code and then if are any corrections we can discuss them during code review.

**Comment by iluwatar** [comment]
:+1:

**Comment by Amarnath510** [comment]
@iluwatar 
I have completed coding. I want to send the code for review.
Can you please let me know the steps I have to do for the code review?
I have knowledge about usual "git init", "git commit" .. but it seems to be different here.

**Comment by iluwatar** [comment]
The steps are described here https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute. Don't hesitate to ask if you need further information.

**Comment by Amarnath510** [comment]
@iluwatar 
Thanks for your help. I have submitted the code for review.

**Comment by iluwatar** [comment]
The pattern example has been merged. The next steps would be to create a blog post or presentation about it. See https://github.com/iluwatar/java-design-patterns/issues/341 and https://github.com/iluwatar/java-design-patterns/issues/197 for more information.

**Comment by Amarnath510** [comment]
@iluwatar 
I have few questions regarding blog creation.
I read [How to create Blog Entry](https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute#blog)
Following are the steps which I want to do,
1. Should I do a pull request of branch [gh_pages](https://github.com/iluwatar/java-design-patterns/tree/gh-pages) ?
2. Then I should create a folder under _posts with name "queue-load-leveling" right?
3. Give file name as, 2016-11-30-queue-load-leveling.md
4. And write the blog as per the "Structure of the blogpost." 

Are the steps correct? 
I have a doubt at step-1 above so was asking.

**Comment by iluwatar** [comment]
@Amarnath510 the answer to all the questions is "yes, you got it right" :smile:

**Comment by Amarnath510** [comment]
@iluwatar 
:)
Sorry to bother you. But I am facing issue that is the reason I wrote step by step above.
When I do a "new pull request" at [gh-pages](https://github.com/iluwatar/java-design-patterns/tree/gh-pages) for branch **gh-pages** I got the below screen.

<img width="598" alt="untitled" src="https://cloud.githubusercontent.com/assets/4599623/20799796/54a6b668-b809-11e6-9679-c2ccf210aba6.png">

How do I pull the branch **gh-pages**?

**Comment by iluwatar** [comment]
Try clicking the link "compare across forks" and selecting your fork's gh-pages branch.

**Comment by Amarnath510** [comment]
@iluwatar 
Thanks. Solved the issue. 👍

**Comment by Amarnath510** [comment]
@iluwatar 
I have completed the blog. Please comment for the same.
There is a issue with the blog images. I have done the same as mentioned in the reference blog but the images are not resolving.

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling
