### ISSUE TITLE
Retry pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#451]
https://msdn.microsoft.com/en-us/library/dn589788.aspx

**Comment by iluwatar** [comment]
I will implement this pattern.

**Comment by npathai** [comment]
There are two ways in which the retries can be done: sync and async. I guess that above link is an asynchronous one :+1: 

Synchronous retry: http://docs.spring.io/spring-batch/reference/html/retry.html 
Asynchronous retry pattern: https://dzone.com/articles/asynchronous-retry-pattern

I hope it helps.

**Comment by iluwatar** [comment]
Thanks for the links. I will look into them.

**Comment by iluwatar** [comment]
Async part will be implemented in #460

**Comment by iluwatar** [comment]
https://github.com/jhalterman/failsafe

**Comment by igroeg** [comment]
Hi, I want to give that pattern a try. Do I have any deadlines? (It's good for me to know some reasonable estimations for a patterns like this)

**Comment by iluwatar** [comment]
@igroeg great, I'll mark this issue to be under construction. There are no deadlines as such but if nothing happens during few months I'll start asking questions. Feel free to ask for support by commenting on this issue or discussing it in Gitter.

**Comment by llorllale** [comment]
Hi, @igroeg @iluwatar is this issue still being worked on?

**Comment by iluwatar** [comment]
Ping @igroeg

**Comment by iluwatar** [comment]
This issue is free for taking again (ping @llorllale)

**Comment by llorllale** [comment]
Please assign to me, @iluwatar

**Comment by iluwatar** [comment]
Ok @llorllale
