### ISSUE TITLE
Throttling pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#456]
https://msdn.microsoft.com/en-us/library/dn589798.aspx

**Comment by rastdeepanshu** [comment]
Can I work on this pattern if no one else is working? Also is there a deadline to complete it?

**Comment by iluwatar** [comment]
Ok @rastdeepanshu go ahead. No strict deadlines. Please ask for help if you are stuck.

**Comment by rastdeepanshu** [comment]
@iluwatar I have created a service which can throttle based on time i.e. a service is accessible for a number of times per second. Any other calls more than the allowed calls are rejected.

Is that something of interest?

**Comment by iluwatar** [comment]
@rastdeepanshu that sounds like a great example.

**Comment by rastdeepanshu** [comment]
@iluwatar I am getting this error while building the project:

`Failed to execute goal com.github.markusmo3.urm:urm-maven-plugin:1.4.4:map (default) on project throttling: /Users/drastogi/java-design-patterns/throttling/etc/throttling.urm.puml
`

I am not sure what needs to be done. Can you tell?

**Comment by rastdeepanshu** [comment]
@iluwatar Awaiting review

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/throttling
