### ISSUE TITLE
Valet Key pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#457]
https://msdn.microsoft.com/en-us/library/dn568102.aspx

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/valet-key

**Comment by EdisonE3** [comment]
Can I take this?  And I can finsh a demo before next week. @ohbus

**Comment by ohbus** [comment]
> Can I take this? And I can finish a demo before next week. @ohbus

Good Luck!

**Comment by EdisonE3** [comment]
I'm so sorry that I'm too busy to keep on doing this issue. 
Maybe can let this issue free and assign to others. @iluwatar @ohbus

**Comment by ohbus** [comment]
> I'm so sorry that I'm too busy to keep on doing this issue.
> Maybe can let this issue free and assign to others. @iluwatar @ohbus

Do you want to continue this later or would want to completely let this go to be taken by somebody else?

**Comment by EdisonE3** [comment]
> > I'm so sorry that I'm too busy to keep on doing this issue.
> > Maybe can let this issue free and assign to others. @iluwatar @ohbus
> 
> Do you want to continue this later or would want to completely let this go to be taken by somebody else?

I want to completely let this go to be taken by somebody

**Comment by iluwatar** [comment]
This issue is free for taking again. Please note that it's a cloud pattern and according to https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections it needs to be implemented using cloud technologies.
