### ISSUE TITLE
Add related patterns section in pattern template

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#458]
Most of the time there are a group of patterns that work together and I think having related patterns section will help us to bring them together in form of a graph.

One example is regarding #451 where it is related to #413 .

**Comment by iluwatar** [comment]
:+1: for adding this to our [pattern template](https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template).

**Comment by npathai** [comment]
@iluwatar Ok I will do it.

**Comment by npathai** [comment]
@iluwatar Added. Closing this issue.

**Comment by iluwatar** [comment]
:+1:
