### ISSUE TITLE
Borg design pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#459]
http://python-3-patterns-idioms-test.readthedocs.io/en/latest/Singleton.html
https://www.quora.com/How-do-I-implement-a-Borg-design-pattern-in-Java

**Comment by Crossy147** [comment]
I will work on this pattern tomorrow.

**Comment by iluwatar** [comment]
Great, please go ahead.

**Comment by Crossy147** [comment]
As far as I see, there already exists a monostate pattern which actually is a borg pattern
[Monostate](https://github.com/iluwatar/java-design-patterns/tree/master/monostate)
What should i do then?

**Comment by iluwatar** [comment]
Well spotted. Borg seems to be an alias for Monostate. It's also said here: http://c2.com/cgi/wiki?MonostatePattern

We should add "Also known as" section with Borg to https://github.com/iluwatar/java-design-patterns/blob/master/monostate/README.md. Would you like to do it?

**Comment by Crossy147** [comment]
yes, i will add this alias today, and open pr to close this issue.
