### ISSUE TITLE
Chain of responsiblity pattern - javax.servlet.Filter as real example is missed

### ISSUE THREAD

**Issue by pnowy** [iluwatar/java-design-patterns#463]
I think that on the chain of responsibility pattern on the section real word examples the most important java real word example is missed.

I suggest to add there **javax.servlet.Filter** as the best patter for the people who meet this patter the first time.

I could create the pull request if it is needed.

**Comment by iluwatar** [comment]
Thanks @pnowy Please create a pull request and we'll review it.

**Comment by pnowy** [comment]
Pull request has been created!
