### ISSUE TITLE
Add pattern statistics to web site

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#465]
Show overall numbers of available patterns, categories and tags.

https://github.com/iluwatar/java-design-patterns/wiki/07.-Working-with-the-web-site

**Comment by stangles** [comment]
Hi, I would like to pick up this issue. I have a few questions about it:

* Should this be a separate page on the website?
* How does this differ from the "Patterns" page that breaks the patterns down by tag count and category count?
* Should it display design pattern statistics in a static way, or should users be able to interact/manipulate an interface in some way to get statistics on a subcategory of design patterns?

Thanks!

**Comment by iluwatar** [comment]
Hi @stangles 

My idea was to put the counts (total number of patterns, total number of categories and total number of tags) on the page http://java-design-patterns.com/patterns/. I'd say these are static counts and display the same number despite the state of the page.

I'll change the labels to indicate you are working on it.

**Comment by markusmo3** [comment]
I quickly did this issue to get into the whole JDP thing again after i was away for a bit (again.. ^^).
Hopefully you dont mind, stangles >.<

**Comment by stangles** [comment]
Nope, not at all! I didn't get around to this soon enough--glad you got it
done!

**Comment by iluwatar** [comment]
Looks good @markusmo3 :+1:
