### ISSUE TITLE
Monitor Object pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#466]
https://en.wikipedia.org/wiki/Monitor_(synchronization)
http://www.javaworld.com/article/2077769/core-java/better-monitors-for-java.html

**Comment by Amarnath510** [comment]
@iluwatar I want to work on this.

**Comment by iluwatar** [comment]
@Amarnath510 yes, please go ahead :+1:

**Comment by Amarnath510** [comment]
@iluwatar 
I am working on this one. I'll be submitting the design in a week.

**Comment by iluwatar** [comment]
Great @Amarnath510, I'll update the issue labels.

**Comment by Amarnath510** [comment]
@iluwatar  Could you also check the [blog post](https://github.com/iluwatar/java-design-patterns/pull/526) and review it?
I have made all the suggested changes.

**Comment by Amarnath510** [comment]
@iluwatar 
I am occupied these days and I'll be busy for the next couple of weeks or so.
Could you please mark this pattern as "help wanted" if you need to complete this soon.
In case you are not in a hurry I can take this up after a month.

**Comment by iluwatar** [comment]
@Amarnath510 I'll mark the issue free for taking. Feel free to reclaim it later.

**Comment by PJozeph** [comment]
@iluwatar apologize to write here without any suggestion, i am code newbie at the stage of figuring out how to contribute.
the task here is the demonstrate how Hoare-style monitors is working ?

**Comment by iluwatar** [comment]
@PJozeph that is correct. To get started please read through https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute.

**Comment by nikhilbarar** [comment]
I'd like to implement this. Please let me know if its still open

**Comment by iluwatar** [comment]
Yes, go ahead @nikhilbarar

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by Meccota** [comment]
Is this issue still open? I saw there are commits, if it needs implementation I would like to take it

**Comment by iluwatar** [comment]
@Meccota yes please go ahead

**Comment by iluwatar** [comment]
@Meccota are you working on this?

**Comment by ohbus** [comment]
This issue is free for taking again
