### ISSUE TITLE
Data Bus pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#467]
http://c2.com/cgi/wiki?DataBusPattern

**Comment by PJozeph** [comment]
@iluwatar can i work on this ?

**Comment by iluwatar** [comment]
@PJozeph ok, the issue is yours.

**Comment by PJozeph** [comment]
@iluwatar thanks, since i am newbie i reckon i need a bit more time, how does it work is there a deadline ?

**Comment by iluwatar** [comment]
@PJozeph there is no deadline. Feel free to ask for support at https://gitter.im/iluwatar/java-design-patterns or by commenting this issue.

**Comment by PJozeph** [comment]
@iluwatar  sorry but cant handle with the issue,

**Comment by iluwatar** [comment]
It's ok, someone else can take it.

**Comment by kemitix** [comment]
I'd like to give this a go.

**Comment by iluwatar** [comment]
Ok @kemitix

**Comment by kemitix** [comment]
Initial implementation of the pattern has been added: PR #544 

Still to write README.md, javadoc and proper comments.
