### ISSUE TITLE
Event-based Asynchronous pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#469]
https://msdn.microsoft.com/en-us/library/wewwczdw(v=vs.110).aspx

**Comment by waisuan** [comment]
Hello, @iluwatar .

**I'd like to work on this pattern, if that's okay.**

My preliminary idea of implementation is as follows:-
- Create a single AsyncManager that controls/manages a pool of running/canceled/completed threads/tasks.
- Create a simple command line client interface to interact with the AsyncManager.
- AsyncManager will handle the creation and invocation of new tasks. [Cancellations of tasks will also go through here]
- AsyncManager will be able to handle BOTH synchronous and asynchronous tasks.
- Each task must be able to handle completions, cancellations, and progress updates gracefully.

Let me know if there is anything else that I need to be aware of for this task. :)

**Comment by iluwatar** [comment]
Hi @waisuan 

The presented plan looks good to me. I'll change the status of the task to indicate you're working on it.
