### ISSUE TITLE
Serverless pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#473]
http://microservices.io/patterns/deployment/serverless-deployment.html

**Comment by npathai** [comment]
http://pca.st/BQAH

**Comment by dheeraj-mummareddy** [comment]
I can signup for this.

**Comment by iluwatar** [comment]
It's yours @dheeraj-mummareddy :+1:

**Comment by iluwatar** [comment]
@dheeraj-mummareddy  are you still implementing this?

**Comment by dheeraj-mummareddy** [comment]
@iluwatar yes I can still implement this. sorry, this did not show up in my issues list.

**Comment by iluwatar** [comment]
@dheeraj-mummareddy thanks, let's keep it `under construction` then. Sorry, only people with write access can be added to assignees list.
