### ISSUE TITLE
Change landing page directly to /patterns/

### ISSUE THREAD

**Issue by markusmo3** [iluwatar/java-design-patterns#481]
As the title suggests we should think about changing the landing page directly to the "content".

**Comment by iluwatar** [comment]
Maybe we can rename the "Home" link to "Readme" and just reconfigure the front page?

**Comment by iluwatar** [comment]
We should also consider reorganizing the navigation links. Now it's

`readme - faq - blog - patterns - principles`

Maybe we could use

`patterns - principles - blog - readme - faq`

**Comment by markusmo3** [comment]
The redirect is working, but not optimal.

@iluwatar you might be able to make a proper redirect at s3, i tried with the [s3_website plugin](https://github.com/iluwatar/java-design-patterns/blob/gh-pages/s3_website.yml#L28-L29) but it didnt work.

Could you look into that? Best would be a redirect that is direct, without the generated index.html flashing in for a split second.

**Comment by npathai** [comment]
I would like to see navigation link to our gitter chat room as well.
So the order can be 
`patterns - principles - blog - readme - faq - chat`

**Comment by markusmo3** [comment]
There is a reason i removed so much from the header and footer. (like our brand, the github symbols etc)
I want everything to look very clean and organized, another (somewhat redundant) link to gitter would mess a bit with that idea.

What is the usecase of this change? I only see random/new people coming to our chat, that didnt even read the "readme" or our github page. Do we want to send those sorts of people directly to our chat?
Lowering the point of entry has a big flip side...

But if you insist, i will add it, as im not that active in the main room anyways.

**Comment by npathai** [comment]
@markusmo3 True. Previously home page had gitter badge so we didn't need it so much. Currently readme is not landing page, so I thought it can be an add and provide visibility to chat as well. We can wait for @iluwatar to pitch in this and then come to a decision.

**Comment by iluwatar** [comment]
Can't we serve the patterns directly from the root java-design-patterns.com and not java-design-patterns.com/patterns? This would solve the problem without redirect.

:+1: for adding the chat link.

**Comment by markusmo3** [comment]
We could. But to be consistent we would need to change the permalinks of each pattern to the root also. And if we didnt do it it would be inconsistent url design.
```
/ is patterns list page
/patterns/abstract-document or /abstract-document/ is pattern page
/blog/ is blog list page
/blog/blablabla is blog page itself
```

I think i mentioned it in gitter allready why i dont like putting the /patterns/ page directly at root. You might want to read it there. It would just be unorganized, patterns thrown into the root directory. And inconsistent because the other "content in list form" the blogposts arent thrown into root. 

The more i think about it the more i dont like this change anymore. It just makes the site inkonsistent no matter how we do it. (The redirect on landing page is also not good)
And might throw of new users because they are immediatly confronted with content they might not understand,

I liked the old system, it introduced the new users and for returning visitors the content is one click or one bookmark away.

I'll let you two decide what to do here alone. But if you decide to do the landing page thing ill add the chat llink too.

**Comment by iluwatar** [comment]
Thanks for explaining @markusmo3 Out of these alternatives I would revert back to the old design where we have the landing page at the root and patterns are one click away.

**Comment by npathai** [comment]
Understanding the fact that this cannot be done, I am ok with it :+1:
