### ISSUE TITLE
SEO (Search Engine Optimization)

### ISSUE THREAD

**Issue by markusmo3** [iluwatar/java-design-patterns#482]
Our github link ranks pretty high on google, but our website does not. We should try and change that.
This is a very general issue, ideas will be summed up into a task list in this original post.
- [x] Index the website @ Google Console
- [ ] Marketing, getting publicity, social media coverage, etc.
- [ ] Analyze traffic @ Google Analytics and find out more about how to make it better
- [ ] Check out githubs SEO feature @ https://github.com/blog/2162-better-discoverability-for-github-pages-sites
- [ ] Use more SEO compliant html-tags (tables instead of pure lists, h? instead of CSS'ed divs, ...)

Other issues that could influence this one
- [x] #480 Enable access to website with www.
- [x] #481 Change landing page directly to /patterns/

**Comment by iluwatar** [comment]
#480 and #481 may also improve our Google ranking.

**Comment by npathai** [comment]
Are we going to update our content layout of patterns page to make it SEO friendly? The fluffycat website is doing good job here. The idea is to have pattern categories as header for table and then show all patterns of that category in tabular form. Yes maybe we will loose some flexibility here, but there can be other ways out as well. @markusmo3 @iluwatar You are better at this, so I leave it up to you to decide.

To be honest I don't know whether our current layout poses any issues for page ranking, but I just tried to reverse engineer why fluffycat and oodesign rank so high.

**Comment by npathai** [comment]
http://www.tutorialspoint.com/seo/seo-optimized-metatags.htm

**Comment by npathai** [comment]
https://github.com/jekyll/jekyll-seo-tag

**Comment by markusmo3** [comment]
Thanks for the links @npathai 
They both add to the 4th checkmark.

I think we should primarily design our website for humans. But if e.g. a change in the html-tag usage or the addition of better 'SEO tags' (the metadata stuff) results in better page ranking then we should definitly do it! So i dont think it is worth the hassle to completely restructure the site just so some robots can read our site better.

Though using tables might just be possible with some CSS magic, so it is a point to look into.
[Added the new checkbox "use more SEO compliant html-tags"]

And to be totally honest, in my own mind, a project on github always has a better ranking (for me), so if it appears in the first 3-10 results i'll allways click that one first.

**Comment by iluwatar** [comment]
Issue has been splitted in https://github.com/iluwatar/java-design-patterns/wiki/17.-Search-Engine-Optimization
