### ISSUE TITLE
Support code embedding

### ISSUE THREAD

**Issue by markusmo3** [iluwatar/java-design-patterns#486]
Probably good idea to use https://gist-it.appspot.com/

Think about compatibility when adding/removing lines from existing code. The blogpost shouldnt break then!

**Comment by iluwatar** [comment]
Tested locally and gist-it seems to work fine. See https://github.com/iluwatar/java-design-patterns/pull/487 utilizing gist-it.

**Comment by markusmo3** [comment]
Yep as mentioned in gitter i have take a look allready. But i want to finalize the embedding process with templates. So that you dont have to write the really long string anymore and just something like that:
```
{% include gist file="src/main/java/...blablabla" %}
```

And also the commit hash thing, because we need some approach to making those code samples "static".  Static because as mentioned in gitter, we would get problems when updating the source code by adding/removing more lines. as the "slice" command would now probably slice incorrectly. (Especially when using gist-it for small parts of a file, instead of displaying the whole file)

**Comment by iluwatar** [comment]
- For static samples we could utilize normal Gist
- I've used slice command to just strip away the license headers

**Comment by npathai** [comment]
I guess when something in the source changes we will have to update the pattern page as well with it. The web page content must reflect the source changes. 
Any example where we would have static samples? And yes in that case we could utilize normal gist as @iluwatar has mentioned.

One thing that we will have to be strict about is file name changes. If someone changes the filename then gist-it will break as it is dependent on filename. If filename changes then we will have to specify in wiki that web page should also be updated. Plus we will have to be extra careful while reviewing PRs.

**Comment by markusmo3** [comment]
Im unsure if my point came across correctly, so let me give you an example:

Lets look at [CacheStore](https://github.com/iluwatar/java-design-patterns/blob/master/caching/src/main/java/com/iluwatar/caching/CacheStore.java)

If we want to show the reader, how the read method of a cache is implemented, it would hinder if we would display the whole file. Instead we might want to select only the `readthrough` method: [L76-87](https://github.com/iluwatar/java-design-patterns/blob/master/caching/src/main/java/com/iluwatar/caching/CacheStore.java#L76-L87)

Okay now, method gets displayed correctly, everything fine.
But now, like half a year later we notice that we use Sysout for logging, but want to change to java.util.Logger. This would introduce the new class variable `Logger logger`, BUT also add 1/2 lines above our method. So instead of our method being displayed at the blog, we would get [some wierd, syntactically incorrect snippet](https://github.com/iluwatar/java-design-patterns/blob/master/caching/src/main/java/com/iluwatar/caching/CacheStore.java#L75-L86)
because a newline is in and a curly bracket is missing.

This is the usecase i see for using commit hashes.
I dont want unexpected failure of the website or the dependency to change a lot of different stuff if someone want to help us out!

Filename changing is just another reason to use commithashes in that case :smile:

**Comment by npathai** [comment]
@markusmo3 I got your point. Yes commit hash would be great. I was also wondering if we could implement a nifty webhook that comments on the PR about possible changes in gists that we have attached on webpages. But there is one problem with this, we may have attached the page at multiple locations, how will we keep all of them in sync when something changes. Manual search?

**Comment by markusmo3** [comment]
Phew, you want some heavy features! gist-it itself doesnt support comments so it would be something i would have to develop (nope, too much work for now, there is more important stuff) but im unsure if gist supports it.

To the synchronization:
I intend to only reuse the blogposts. The patternpage or any other page that wants to include that post would get another front matter variable that looks something like this: 
```
relatedBlogPosts:
 - x
 - y
```

**Comment by iluwatar** [comment]
:+1: for commit hashes. Sooner or later the blogs are going break otherwise.

**Comment by markusmo3** [comment]
As also described in the "gistit-html" file itself:

```
EXAMPLE USAGE: (have "hash: 1f27dbb" in the front matter)
{% include gistit.html file="visitor/pom.xml" %}
```
