### ISSUE TITLE
Pipeline pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#496]
https://msdn.microsoft.com/en-us/library/ff963548.aspx

**Comment by ghost-60** [comment]
Working on it

**Comment by iluwatar** [comment]
Ok @ghost-60

**Comment by iluwatar** [comment]
@ghost-60 are you still working on this?

**Comment by ghost-60** [comment]
Sorry.... not yet

**Comment by iluwatar** [comment]
My question, do you still want to keep the issue or can someone else take it?

**Comment by ghost-60** [comment]
Someone else can take it. Sorry.

**Comment by iluwatar** [comment]
It's ok @ghost-60. This issue is free for taking again.

**Comment by urielatzmon** [comment]
can I take it?

**Comment by iluwatar** [comment]
Sure @urielatzmon go ahead

**Comment by iluwatar** [comment]
@urielatzmon  are you still implementing this?

**Comment by jjjimenez100** [comment]
Hello. Can I take on this issue and make a PR?

**Comment by iluwatar** [comment]
Ok @jjjimenez100

**Comment by havanagrawal** [comment]
If this is inactive, I'd love to take this up

**Comment by iluwatar** [comment]
Yes, it seems so. Please go ahead @havanagrawal

**Comment by iluwatar** [comment]
The issue is free

**Comment by jjjimenez100** [comment]
Hi. I'll continue working on this one (for real now). Just forked the repository. Will have you pinged when the PR's up. 

Thanks!

**Comment by iluwatar** [comment]
@jjjimenez100 ok the second time's a charm, or how it goes :smirk:
