### ISSUE TITLE
Combinator pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#499]
https://gtrefs.github.io/code/combinator-pattern/

**Comment by matthewwier** [comment]
Hi, I would like to take that, is it possible?

**Comment by iluwatar** [comment]
Yes, please go ahead @matthewwier

**Comment by iluwatar** [comment]
@matthewwier  are you still implementing this?

**Comment by Willem-van-den-Berg** [comment]
Sure...its free

**Comment by iluwatar** [comment]
@matthewwier does not seem to be active on this so @asavelev1 it is ok to start on this

**Comment by iluwatar** [comment]
This issue is free to take again

**Comment by besok** [comment]
I can take it if nobody minds

**Comment by iluwatar** [comment]
Ok @besok
