### ISSUE TITLE
Null object as a singleton

### ISSUE THREAD

**Issue by petrnohejl** [iluwatar/java-design-patterns#50]
It is recommended to implement null object as a singleton.

In the example, NullNode (https://github.com/iluwatar/java-design-patterns/blob/master/null-object/src/main/java/com/iluwatar/NullNode.java) is not a singleton.

**Comment by iluwatar** [comment]
Resolved with commit https://github.com/iluwatar/java-design-patterns/commit/89e6692ba8189eddea20b1f34a98fc0425576428
