### ISSUE TITLE
Logging framework

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#502]
Instead of printing output to `System.out` we should use a logging framework such as Log4j to allow redirecting and filtering of output. In some cases this also eases testing. The refactoring should be applied across all the patterns.

**Comment by dbryla** [comment]
I'll handle this. :) I propose to go with SLF4J API and Logback implementation.

**Comment by iluwatar** [comment]
@dbryla the proposal is ok for me, you are good to go.

**Comment by dbryla** [comment]
Should I leave System.out in applications with tests based on StdOut or should I rewrite tests?

**Comment by iluwatar** [comment]
We want to migrate the tests also. If it causes trouble we can deal with it later.

**Comment by dbryla** [comment]
PR: https://github.com/iluwatar/java-design-patterns/pull/515

Build on travis failed:

> The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

> The build has been terminated.

Can we increase limit?
