### ISSUE TITLE
Commander pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#505]
http://www.grahamlea.com/2016/08/distributed-transactions-microservices-icebergs/

**Comment by raviteja1992y** [comment]
Hi @iluwatar, I read about it. I even have a bit of experience of this. I would like to work on this

**Comment by raviteja1992y** [comment]
Hi @iluwatar, Are you sure that this is a pattern worth mentioning? I am not totally convinced. Because I have google searched 'commander pattern' and this doesn't seems to be famous. I may need to do some research for knowing the credibilty of this pattern.

**Comment by iluwatar** [comment]
@raviteja1992y it may not be so famous but another source I found is here https://www.youtube.com/watch?v=B1-gS0oEtYc. Let me know if you are working on this?

**Comment by AnaghaSasikumar** [comment]
PR #857
