### ISSUE TITLE
SonarQube reports code smells

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#508]
Java Design Patterns is analyzed with SonarQube.com static analysis. The analysis shows some blocker level code smells that should be fixed:

https://sonarqube.com/component_issues/index?id=com.iluwatar%3Ajava-design-patterns#resolved=false|severities=BLOCKER|types=CODE_SMELL

**Comment by andreybleme** [comment]
@iluwatar Hello. I can help with this one :100: 
I'm on it.

**Comment by sangupta** [comment]
I will take care of this.

**Comment by iluwatar** [comment]
Thank you @sangupta you're good to go!

**Comment by iluwatar** [comment]
@sangupta are you still working on this?

**Comment by sangupta** [comment]
@iluwatar Am sorry - have been pressed for time lately. Will have sometime in March - when I should be able to lend a helping hand.

**Comment by Praveer-grover** [comment]
@iluwatar I can begin on this if no one else is looking at it, to start with I was just going through delegation and builder pattern. I can create a pull request with sonar fixes for those, is it okay?

**Comment by iluwatar** [comment]
@Praveer-grover this is ok, please go ahead.

**Comment by mookkiah** [comment]
Updated sonarqube url
https://sonarcloud.io/project/issues?id=com.iluwatar%3Ajava-design-patterns&resolved=false&severities=BLOCKER&types=CODE_SMELL

@Praveer-grover Are you still working on these issues? Let me know if you want me to share some modules?

**Comment by iluwatar** [comment]
Ping @Praveer-grover

**Comment by dosdebug** [comment]
@mookkiah Are you planning to completely work on this ticket or you need a helping hand? ;)

**Comment by mookkiah** [comment]
Either way is fine for me. As @Praveer-grover is not responding, I will look at sonarqube reported issues in prototype module (maybe this weekend). @dosdebug, you are welcome to help another module. Please just comment so we don't step on each other.

**Comment by dosdebug** [comment]
@mookkiah I will be working on `dao` and `naked-objects-dom` then.

**Comment by iluwatar** [comment]
Hey @mookkiah and @dosdebug are you guys still working on this?

**Comment by mookkiah** [comment]
I will work on prototype module.

**Comment by dosdebug** [comment]
@iluwatar No Sir, not working on this.

**Comment by olcbean** [comment]
Note : 
The problem with the `dao` seems to be cause by the fact that SonarQube does not support `@Nested` : SQ currently ignores any `@Nested` classes, in other words it does not verify if there is a test within or not.

**Comment by iluwatar** [comment]
There are still 4 blockers and 37 criticals. See https://sonarcloud.io/project/issues?id=com.iluwatar%3Ajava-design-patterns&resolved=false&severities=BLOCKER%2CCRITICAL&types=CODE_SMELL. This issue is free for taking, if someone would like to help.

**Comment by olcbean** [comment]
Hm.... there is something strange here. I just opened one of the `Blockers` : https://sonarcloud.io/project/issues?id=com.iluwatar%3Ajava-design-patterns&open=AVfejjZoPl_GJI-SB0qL&resolved=false&severities=BLOCKER and although the analysis is run on `October 24, 2018, 10:43 PM Version 1.21.0-SNAPSHOT` SonarCloud is displaying outdated source code : from 2 years ago instead of the one fixed in #810....

Oh, actually #810 has been merged on `October 25` : a day later. I guess the analysis does not contain the changes done in #810 ( if I am to trust the timestamps of GitHub and SonarCloud ). I would guess the blockers will be fixed in the next analysis.

Just my 2c ;)

PS : This may explain the 4 blockers but the criticals still need to be fixed.

**Comment by IAmPramod** [comment]
@iluwatar I will start working on this and raise a PR shortly.

**Comment by iluwatar** [comment]
Ok @IAmPramod

**Comment by kanwarpreet25** [comment]
@iluwatar  Is this available ?

**Comment by kanwarpreet25** [comment]
@IAmPramod  Are you still working on this ?

**Comment by kanwarpreet25** [comment]
Hi @iluwatar  : Pull request raised for this
