### ISSUE TITLE
Staged event-driven architecture (SEDA)

### ISSUE THREAD

**Issue by V-K-Singh** [iluwatar/java-design-patterns#517]
It will be very helpful if you can provide an example on SEDA
please follow the below link for more details
http://pages.cs.wisc.edu/~remzi/Classes/739/Fall2016/Papers/seda.pdf

**Comment by iluwatar** [comment]
It seems there already is an issue about SEDA. See here https://github.com/iluwatar/java-design-patterns/issues/307. @V-K-Singh can you please comment on that issue instead?
