### ISSUE TITLE
Decorator: Composition or Aggregation?

### ISSUE THREAD

**Issue by thomasoss** [iluwatar/java-design-patterns#518]
Hello, I refere to decorator pattern
I think the relationship between decorator and target (in the code example between Troll und SmartTroll) ist not a composition as described in the code comment lines of class App. In a compostion both instances canncot live without the other one. But the target (Troll) could live without the decorator (Smart Troll). Consequently this is a aggregation?
Greetings
Thomas

**Comment by iluwatar** [comment]
Good point @thomasoss and I tend to agree with you.

> Composition implies a relationship where the child cannot exist independent of the parent. 
> Aggregation implies a relationship where the child can exist independently of the parent.

Looking forward to pull request fixing this issue.

**Comment by thomasoss** [comment]
done
Greetings Thomas
