### ISSUE TITLE
Attach tutorial links to patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#525]
In the [pattern template](https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template) there is section for Tutorials. Here we should list tutorials explaining the pattern. One example is here http://java-design-patterns.com/patterns/hexagonal/.

**Comment by gangadkho** [comment]
I checked the hexagonal patterns page. Its having the tutorial link to java-design-pattern (hexagonal pattern) tutorial. Can the patterns also have tutorial links to external sites?

**Comment by iluwatar** [comment]
@gangadkho that is a good question. But if we allowed links to external sites and content, would we bump into copyright issues and lawsuits?

**Comment by gangadkho** [comment]
@iluwatar Would'nt that be a promotion for external sites? We are just providing the link to their websites(not copying the contents in to our website).  Does that sound correct? Correct me if I am wrong.

**Comment by iluwatar** [comment]
I don't think it's that simple. For example, see http://www.internetlegalattorney.com/website-external-links-framing-liability-guide/ for potential risks.

**Comment by jayant96** [comment]
Is this issue closed or still open as three blog present in sites are linked in respective patterns? 
Also what is the decision on using external links ?

**Comment by markusmo3** [comment]
I dont think hyperlinking would be an issue.

> “…hyperlinking does not itself involve a violation of the Copyright Act (whatever it may do for other claims) since no copyright is involved. The customer is automatically transferred to the particular, genuine Web page of the original author. There is no deception in what is happening. This is analogous to using a library’s card index to get reference to particular items, albeit faster and more efficiently.”

Thats what i learned when the issue first came up a couple of years ago

> "However, using external links on your website may create legal liability in some cases. External links can be unlawful when they i) cause consumer confusion; ii) encourage or facilitate illegal copyright infringement by others; or iii) violate other laws."

i) they wont, its a hyperlink, in blue color and most of the times the URL is in full text
ii) might be an issue, if the linked site is infringing, but i think we can take that risk
iii) nope, unless we link to drugsites or other dubious stuff

If the added links are checked and approved by a contributor (that means the site is working and looks at least somewhat credible), then i dont see any problem in linking to other tutorials.
With that we are providing publicity and also indirectly give money (with page hits/ads) to the original tutorial author.


Source of quotes: http://www.internetlegalattorney.com/website-external-links-framing-liability-guide/

**Comment by iluwatar** [comment]
Thank you @markusmo3 for the statement. In light of this, I think we can start accepting links to other sites as well.

**Comment by 9527BOM** [comment]
where is the Design description?

**Comment by mattj256** [comment]
These are our current links to tutorials:

- queue-load-leveling: [Queue-Based Load Leveling Pattern](http://java-design-patterns.com/blog/queue-load-leveling/)
- proxy: [Controlling Access With Proxy Pattern](http://java-design-patterns.com/blog/controlling-access-with-proxy-pattern/)
- hexagonal: [Build Maintainable Systems With Hexagonal Architecture](http://java-design-patterns.com/blog/build-maintainable-systems-with-hexagonal-architecture/)

Right now we only have three tutorial blog posts, and I see issue #341 requesting more blog posts.

Do we have any preference for which website we link to?  Here are some examples of things I could link to:

- Iterator: http://www.tutorialspoint.com/java/java_using_iterator.htm
- Abstract Factory: http://www.tutorialspoint.com/design_pattern/abstract_factory_pattern.htm

**Comment by iluwatar** [comment]
@mattj256 the links to tutorialspoint seem ok so we could add them.

**Comment by OrangePants-R** [comment]
@iluwatar I'd be happy to add the external links.  Would you assign to me?

**Comment by iluwatar** [comment]
Ok @OrangePants-R

**Comment by kanwarpreet25** [comment]
Is it available @iluwatar

**Comment by iluwatar** [comment]
Yes the issue is open @kanwarpreet25

**Comment by kanwarpreet25** [comment]
Working on it

**Comment by iluwatar** [comment]
Ok @kanwarpreet25

**Comment by iluwatar** [comment]
Help wanted

**Comment by iluwatar** [comment]
Sounds great @vaibhav-if. I'll assign the issue to you!

**Comment by vaibhav-if** [comment]
Hi @iluwatar, I have added a few PRs to be in time for hacktoberfest, will add more in coming days.

**Comment by Arpit-101** [comment]
Hi @iluwatar, I'm a beginner to all this and recently I've learnt java and javascript, I'm out here looking for projects to improve my skills but having a bit trouble to understand things here. It would be great help if you guide me to some resources which will help me to learn more in java and javascript, so that I can start contributing to project like these. Sorry for being off topic but please help me out.

**Comment by bikashdaga** [comment]
> These are our current links to tutorials:
> 
> * queue-load-leveling: [Queue-Based Load Leveling Pattern](http://java-design-patterns.com/blog/queue-load-leveling/)
> * proxy: [Controlling Access With Proxy Pattern](http://java-design-patterns.com/blog/controlling-access-with-proxy-pattern/)
> * hexagonal: [Build Maintainable Systems With Hexagonal Architecture](http://java-design-patterns.com/blog/build-maintainable-systems-with-hexagonal-architecture/)
> 
> Right now we only have three tutorial blog posts, and I see issue #341 requesting more blog posts.
> 
> Do we have any preference for which website we link to? Here are some examples of things I could link to:
> 
> * Iterator: http://www.tutorialspoint.com/java/java_using_iterator.htm
> * Abstract Factory: http://www.tutorialspoint.com/design_pattern/abstract_factory_pattern.htm

Hey,  
You can refer this too - https://www.scaler.com/topics/design-patterns/factory-design-pattern/
