### ISSUE TITLE
Checkstyle improvements

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#539]
Currently Checkstyle does not check for type Javadocs.Rule `JavadocType` should be added. Rule that causes trouble and should be removed is `AvoidStarImport` since IntelliJ IDEA likes to organize imports automatically this way.

**Comment by muditporwal** [comment]
Will this suffice ?

    <module name="JavadocType"/>

Or need more customization ?

    <module name="JavadocType">
      <property name="authorFormat" value="\S"/>
    </module>

**Comment by iluwatar** [comment]
Is `authorFormat` necessary? My suggestion would be like this.

```
<module name="JavadocType">
    <property name="scope" value="public"/>
</module>
```

And remove the star import.

```
<module name="AvoidStarImport"/>
```

**Comment by muditporwal** [comment]
How do we get the missing JavaDoc ? Is it ok for me to suggest javadoc in my pull request (the build is breaking at the moment) ?

**Comment by iluwatar** [comment]
Yes, please suggest changes so that build works.
