### ISSUE TITLE
Incorrect history stack handling in command pattern

### ISSUE THREAD

**Issue by mihaildemidoff** [iluwatar/java-design-patterns#547]
Hello!

Thank you for your work.
I found one small problem in command pattern. I agree that code should be light as possible and some details may be ommited, but examples should be correct.
Problem: InvisibilitySpell and ShrinkSpell have incorrect redo and undo mechanism. For example: if you execute ShrinkSpeel 2 times Goblin will never return to Big size.
I think we should add stack of states in commands to properly handle redo and undo operations.

**Comment by mattj256** [comment]
@iluwatar I'd like to work on this.

The Size enumerated type has small, medium, large, and undefined.  It seems that only small and medium are ever used.  Should "large" and "undefined" be removed?  Or should the goblin start out large?

**Comment by iluwatar** [comment]
Ok @mattj256 you can start work on this. I think we can remove the unused enumerations.

**Comment by dosdebug** [comment]
@iluwatar A Goblin initially starts with `NORMAL` size. Casting a shrink spell will make it `SMALL`. What if a shrink spell is casted again? Should size be cyclic e.g. `Small -> Normal -> Large -> Small`? Or, if Goblin is already `SMALL`, casting shrink spell should not work?

**Comment by iluwatar** [comment]
@dosdebug I would say shrink spell makes smaller until the smallest possible (SMALL) after which it has no effect.

**Comment by dosdebug** [comment]
@iluwatar Sure, a PR is submitted to you. Please see when you have time.
