### ISSUE TITLE
"Aggregator microservices"  design pattern doesn't show exception handling 

### ISSUE THREAD

**Issue by neerajmahajan** [iluwatar/java-design-patterns#549]
"Aggregator microservices"  design pattern doesn't show how exception handling would be done if the one or multiple services used are down and how client calling the aggregator microservice would cope in this situation.

**Comment by while1do** [comment]
Cann't we consider 

`    try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
      HttpGet httpGet = new HttpGet("http://localhost:51515/information");
      try (CloseableHttpResponse httpResponse = httpClient.execute(httpGet)) {
        response = EntityUtils.toString(httpResponse.getEntity());
      }
    } catch (IOException e) {
      LOGGER.error("Exception caught.", e);
    }`

in com.iluwatar.aggregator.microservices.ProductInformationClientImpl as example of fallback strategy ([https://blogs.oracle.com/developers/getting-started-with-microservices-part-three](url))?
Or do i not understand the task?

**Comment by ddunig2** [comment]
Has this issue been resolved?

**Comment by IAmPramod** [comment]
@ddunig2 I don't see a PR against this. If you want to resolve, you can go ahead.

**Comment by jarpit96** [comment]
Hi, I am raising a PR for this, where ClientProtocolException is caught and  the error log statements are updated.

**Comment by jarpit96** [comment]
https://github.com/iluwatar/java-design-patterns/pull/958

**Comment by iluwatar** [comment]
Exception handling was improved, but the original issue still remains unsolved

**Comment by iluwatar** [comment]
Under investigation by @jarpit96

**Comment by jarpit96** [comment]
@iluwatar @ddunig2 To implement fallback pattern, is returning default literals/constants sufficient ?

**Comment by iluwatar** [comment]
I would probably display an error message to the user in case one of the microservices does not respond or some other fault occurs

**Comment by jarpit96** [comment]
#971

**Comment by jarpit96** [comment]
I have added fall backs in Aggregator Service when other microservices fail. Default error messages (Product Title and Inventory) are returned to the user.
