### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by fernandojunior** [iluwatar/java-design-patterns#55]
Great job.
How about repository? 
Reference: http://martinfowler.com/eaaCatalog/repository.html

**Comment by iluwatar** [comment]
Thanks for pointing that out. It is definitely on the roadmap.

**Comment by iluwatar** [comment]
@fernandojunior The example is now available.

**Comment by fernandojunior** [comment]
I didn't know Spring has this functionality...
Thanks!
