### ISSUE TITLE
Double Buffer pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#550]
http://gameprogrammingpatterns.com/double-buffer.html

**Comment by gabex89** [comment]
Hello @iluwatar, I would like to take this pattern. Thanks!

**Comment by iluwatar** [comment]
Ok @gabex89

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by havanagrawal** [comment]
I'd love to take this up

**Comment by Azureyjt** [comment]
@iluwatar May I take this issue?

**Comment by iluwatar** [comment]
Ok @Azureyjt
