### ISSUE TITLE
Game Loop pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#551]
http://gameprogrammingpatterns.com/game-loop.html

**Comment by prakis** [comment]
@iluwatar  this is another pattern I can contribute to.

**Comment by iluwatar** [comment]
Ok @prakis

**Comment by raviteja1992y** [comment]
@prakis are you working on it?

**Comment by prakis** [comment]
@raviteja1992y  Yes, I started working on it.

**Comment by prakis** [comment]
Hello Raviteja( @raviteja1992y ), I got very busy with my office work if you are interested to implement this pattern please go ahead.

**Comment by raviteja1992y** [comment]
even i am not working on this

**Comment by iluwatar** [comment]
Ok, the issue is free for taking again

**Comment by okinskas** [comment]
I'd like to pick up this pattern 👍

**Comment by iluwatar** [comment]
Ok @okinskas

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by Azureyjt** [comment]
@iluwatar May I pick this up?

**Comment by iluwatar** [comment]
Ok @Azureyjt
