### ISSUE TITLE
Update Method pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#552]
http://gameprogrammingpatterns.com/update-method.html

**Comment by ungoranita** [comment]
Hello @iluwatar I would like to take this pattern. Thanks!

**Comment by iluwatar** [comment]
Ok @ungoranita

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by lodenrogue** [comment]
I've used a similar pattern in the past when designing a game entity system. An additional interface I found useful for the entity class is a render() method. To abstract view from logic.

The entity interface then looks like this:
Entity
+ update()
+ render()

**Comment by iluwatar** [comment]
@lodenrogue would you like to try implementing this one?

**Comment by lodenrogue** [comment]
Sure. I'll try to work on it.

**Comment by iluwatar** [comment]
Ok @lodenrogue

**Comment by iluwatar** [comment]
@lodenrogue  are you still implementing this?

**Comment by lodenrogue** [comment]
No sorry. Got busy. Please make it available for others

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by TaninIvan** [comment]
Hello, @iluwatar 
May I have a try on this?

**Comment by iluwatar** [comment]
Ok @TaninIvan

**Comment by iluwatar** [comment]
The task is free to take

**Comment by Azureyjt** [comment]
@iluwatar May I pick up this issue?

**Comment by iluwatar** [comment]
Ok @Azureyjt
