### ISSUE TITLE
Bytecode pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#553]
http://gameprogrammingpatterns.com/bytecode.html

**Comment by abhishek7** [comment]
@iluwatar, would love to work on this if no one else has claimed it yet.

**Comment by iluwatar** [comment]
Ok @abhishek7

**Comment by iluwatar** [comment]
@abhishek7  are you still implementing this?

**Comment by abhishek7** [comment]
@iluwatar apologies for the delay, did not have a chance to make additional progress on it. Feel free to give it to someone else. If I do have time, I'll open up a PR and reference the issue accordingly.

**Comment by iluwatar** [comment]
The issue is free to take again

**Comment by pzawitowski** [comment]
Hi @iluwatar, if nobody is working on this then I can try to implement this pattern.

**Comment by iluwatar** [comment]
Ok @pzawitowski
