### ISSUE TITLE
Subclass Sandbox pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#554]
http://gameprogrammingpatterns.com/subclass-sandbox.html

**Comment by szokekristof** [comment]
Hello @iluwatar I would like to take this pattern. Thanks!

**Comment by iluwatar** [comment]
Ok @szokekristof

**Comment by iluwatar** [comment]
@szokekristof  are you still implementing this?

**Comment by iluwatar** [comment]
The task is free to take

**Comment by Azureyjt** [comment]
@iluwatar May I pick up this issue?

**Comment by iluwatar** [comment]
Sure go ahead @Azureyjt
