### ISSUE TITLE
Type Object pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#555]
http://gameprogrammingpatterns.com/type-object.html

**Comment by Imp92** [comment]
Hello @iluwatar I would like to take this pattern. Thanks!

**Comment by iluwatar** [comment]
Ok @Imp92

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by laubera** [comment]
Hey, @iluwatar  I would like to take this pattern. Thanks.

**Comment by iluwatar** [comment]
@laubera ok

**Comment by iluwatar** [comment]
@laubera  are you still implementing this?

**Comment by AnaghaSasikumar** [comment]
PR #848
