### ISSUE TITLE
Component pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#556]
http://gameprogrammingpatterns.com/component.html

**Comment by abhi-agr** [comment]
Is it different from https://github.com/iluwatar/java-design-patterns/issues/509

**Comment by saakaarv** [comment]
I would like to implement this one.

**Comment by iluwatar** [comment]
Ok @saakaarv

**Comment by iluwatar** [comment]
@saakaarv  are you still implementing this?

**Comment by saakaarv** [comment]
Sorry, No, You can make this issue free for implementation again.

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by kanwarpreet25** [comment]
Hi @iluwatar  , I am working over it. Branch named "component" created. Will raise the pull request once completed.

**Comment by iluwatar** [comment]
Ok @kanwarpreet25

**Comment by kanwarpreet25** [comment]
Hi @iluwatar  : Pull request raised for this issue

**Comment by iluwatar** [comment]
This issue is free to take again

**Comment by Hrighter** [comment]
Hi，I wrote a demo of component pattern and raised a pull request.

**Comment by Ooi-YeeJing** [comment]
Can I work on this issue?

**Comment by iluwatar** [comment]
Ok @Ooi-YeeJing

**Comment by LeseChe** [comment]
@iluwatar if @Ooi-YeeJing is inactive, may I take and continue this issue?

**Comment by SammanPali** [comment]
> Ok @LeseChe, thanks for your help

Hey @iluwatar, I am working alongside @LeseChe for this implementation - would it be possible for me to also be assigned to this issue? 

Thanks
