### ISSUE TITLE
Service Locator pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#558]
http://gameprogrammingpatterns.com/service-locator.html

**Comment by szokekristof** [comment]
Hello @iluwatar I would like to take this pattern. Thanks!

**Comment by iluwatar** [comment]
Hi @szokekristof I think this issue may be a duplicate https://github.com/iluwatar/java-design-patterns/tree/master/service-locator. What do you think?

**Comment by szokekristof** [comment]
Hi @iluwatar,
yes it seems the same for me as well.
In this case I take another one.
thanks

**Comment by iluwatar** [comment]
Closed as duplicate
