### ISSUE TITLE
Data Locality pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#559]
http://gameprogrammingpatterns.com/data-locality.html

**Comment by prakis** [comment]
@iluwatar I like to try implementing this pattern.

**Comment by iluwatar** [comment]
Ok @prakis

**Comment by iluwatar** [comment]
@prakis  are you still implementing this?

**Comment by ranjeet-floyd** [comment]
@iluwatar  Can i take this please ?. Raised PR for same https://github.com/iluwatar/java-design-patterns/pull/889.  Thanks

**Comment by iluwatar** [comment]
Ok @ranjeet-floyd
