### ISSUE TITLE
Better View/Navigation ?

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#56]
Heya there,
first of all, i love this resource and use it quite often. the only thing slightly annoying is the layout. Would be really awesome to view this resource in bootstrap with categories or something like that.

If something like that is done "hardcoded" the project will probably loose on contributions, so a converter of sorts should be used.

One last point, i found this Site that looks pretty good, but i dont know if it would be suitable. I also have no idea if it even works, because here everything is one single markdown document, while those at the site are multiple.
http://phpmyadmin.readthedocs.org/en/QA_4_4/
(topic is not important)

Just an idea C:

~Markus

**Comment by iluwatar** [comment]
Thanks for your comment. I totally agree that there is lots of room to improve. We should evaluate some of the most popular solutions for the frontend and then just migrate to that.

**Comment by noobxgockel** [comment]
Hello again,
it might have been a while since i created this issue, ut i have looked around and found some things out i want to share:

Github provides so called github-pages, those are built either static html pages or built with jekyll, maybe that could be used. Seems quite nice for displaying simple data. As far as i have seen it should be possible to categorize and tag posts. There would be some additional work though to get the site to display everything correctly when a new pattern is added for example. Writing a little script to do the additional work shouldn't be hard though. Hope it helps to clear that point up a bit.

And if you want, i could (try to) help with migrating to jekyll if you choose to do so.

**Comment by iluwatar** [comment]
Hi @noobxgockel 

Sorry for the delayed answer. I've been travelling for the last few days.

It would be great to improve the user experience by adding a project web site using github pages. My personal priority is currently on developing the content of the project (improve the existing and add more patterns).

Would you be interested to take this issue and start developing the site for the project from scratch? I can provide you push access and will of course help you wherever you need.

**Comment by noobxgockel** [comment]
No problem, i've been busy too c:

yeah i can take this issue on, and having push access would be pretty nice for that. But dont expect design wonders from me ;)

**Comment by iluwatar** [comment]
@noobxgockel I've added you as a collaborator to the project. You should be able to push to the repository.

Let me know if there's anything you need to advance this issue.

**Comment by noobxgockel** [comment]
Nice C: today im still a bit busy, but tomorrow i'll start for real.

Just some things i thought i'd mention beforehand so you can maybe comment on those.
- I'd put everything pattern related into the master branch and everything website related into the gh-pages branch. To link those 2 together i'd use the git module feature and maybe change the travis.yml so the website is automagically updated each build.
- For this to work properly i'd take on the task of splitting the main README.md up. The description of the pattern would be put inside of the folder named something like index.md or pattern.md (because some folders allready contain a README file) The main README.md could be left in the root directory but i'd suggest to replace it with a simple one with links to the page...
- I havent looked around much for a theme for the website but im thinking about using this one: http://jekyllthemes.org/themes/cool-concise-high-end/ Seems quite fitting for such a site


Any comments, suggestions, critic on that ?

**Comment by iluwatar** [comment]
Thanks for your thoughts. I think it sounds great in general. Here's some comments:

- Branches master & gh-pages are ok (currently there is also cpp branch where we may get C++ ports of the patterns at some point)
- I haven't used git modules before, but for what I've just read it is going to suit us fine
- Automatic updating of the web site is a great feature. Semiautomatic one command publishing might also be good enough for a start at least.
- You're welcome to split and edit the README.md and I think that the plan to put the pattern description into the folder is good.
- The theme you mentioned is ok for me. Is it easy/possible to change it later on?

**Comment by noobxgockel** [comment]
Sounds good C:

It would also be possible to incorperate the cpp patterns into the website with little effort. But maybe the repository name is silightly confusing then.
And to the theme changing. Well it would be possible and it might be quite easy because it should be possible to just swap out the .css and maybe some .js files. But im not too sure about that. If an issue like that comes up you can assign it to me and i'll look into it :)

**Comment by iluwatar** [comment]
The cpp branch is currently on hold so let's just ignore it at the moment. Better not design too much ahead, we can change things when the need arises.

**Comment by npathai** [comment]
@iluwatar Github pages will suffice. IMO we should dedicate a page for applications of patterns.

**Comment by npathai** [comment]
:+1:

**Comment by mafagafogigante** [comment]
I went through Jekyll tutorials to set up [my website](https://mafagafogigante.github.io/) and would be willing to help if needed.

BTW, where is the branch?

I think that a new repository is also not bad idea, it's up to you. It provides some nice decoupling but may breaks some Travis magic.

Theme-changing shouldn't be too hard. Jekyll uses static HTML includes and [Liquid](http://liquidmarkup.org/) to generate the pages. Besides that all there is to change is CSS and JS (if used).

**Comment by iluwatar** [comment]
ping @noobxgockel

**Comment by noobxgockel** [comment]
Yeah, sorry about that, i started but never really finished ^^ Kinda busy atm, but if you want i can commit the stuff i have currently and someone else can take it. Site works but is kinda flawed because i dont intend to use patterns as jekyll posts but rather static pages (those who know jekyll know what im talking about) ^^

**Comment by mafagafogigante** [comment]
I think that a script that rendered a markdown page for every DP is not so hard to craft.

**Comment by iluwatar** [comment]
@noobxgockel it would be great if you could commit the current work.

**Comment by mafagafogigante** [comment]
Yeah, I also want it. I may even make some progress on it.

**Comment by noobxgockel** [comment]
@mafagafogigante Yeah its not hard to just display the patterns. But i want to use the theme i posted above and include a tag/category search functionality. Maybe even some overview pages etc... But i will try to make as much progress today and commit it. So others can help C:
Sorry again that i was away for that long...

**Comment by noobxgockel** [comment]
Just as i update:
Worked on it today and made quite a bit of progress, but its too late now to organize a partial commit. I'll ramp up a commit tomorow, maybe even with some more of site done C:

**Comment by mafagafogigante** [comment]
Good job. Waiting to see it, may put some effort into this in the weekend.

**Comment by noobxgockel** [comment]
Here is the first batch!
Yes its not optimal right now, but i got to get some sleep too, will write TODO's and sorts tomorrow...

PS: the site works mostly (except some css) its just the links that dont, they somehow cut out the "/java-design-patterns/" part...

**Comment by iluwatar** [comment]
This is great! Now we have something to show. I will report new issues on my findings.
