### ISSUE TITLE
Dirty Flag pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#560]
http://gameprogrammingpatterns.com/dirty-flag.html

**Comment by abhi-agr** [comment]
I am working on this.

**Comment by iluwatar** [comment]
Ok @abhi-agr

**Comment by prakis** [comment]
@abhi-agr I implemented something similar in my scene graph code without knowing this pattern. If you need collaborator in this pattern please let me know.

**Comment by iluwatar** [comment]
@abhi-agr  are you still implementing this?

**Comment by prakis** [comment]
Sorry I am not working on this, I got busy with my work.

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by waisuan** [comment]
@iluwatar 

Hello. I would like to work on this particular pattern. I'll be drawing up inspiration from https://www.takeupcode.com/podcast/89-design-patterns-dirty-flag/ . 

Is that alright?

**Comment by waisuan** [comment]
Kindly take a look at my pull request and lemme know if I've missed out on something. Thanks! @iluwatar

**Comment by npathai** [comment]
Closing this issue. PR successfully merged.
