### ISSUE TITLE
Object Pool pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#561]
http://gameprogrammingpatterns.com/object-pool.html

**Comment by abhi-agr** [comment]
I would like to work on it. Can I take this?

**Comment by iluwatar** [comment]
Is it the same as https://github.com/iluwatar/java-design-patterns/tree/master/object-pool ?

**Comment by abhi-agr** [comment]
Yeah seems to be same. Do you know why it came up as task again in the list as new pattern?

**Comment by iluwatar** [comment]
My mistake. I will close this as duplicate.
