### ISSUE TITLE
Spatial Partition pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#562]
http://gameprogrammingpatterns.com/spatial-partition.html

**Comment by szoeke** [comment]
hi @iluwatar 
I'm willing to implement this pattern.

**Comment by iluwatar** [comment]
Ok @szoeke

**Comment by prakis** [comment]
@szoeke This is pretty interesting pattern, please let me know if you need help in implementing/discussing this pattern.

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by danielsiwiec** [comment]
@iluwatar I'll take a stab at this

**Comment by iluwatar** [comment]
Ok @danielsiwiec

**Comment by iluwatar** [comment]
@danielsiwiec  are you still implementing this?

**Comment by danielsiwiec** [comment]
@iluwatar sorry, no - I got side tracked into other things. Please take me off of it for the time being.

**Comment by iluwatar** [comment]
This issue is free for taking again

**Comment by karmagamer** [comment]
I'd like to try to implement this. This looks interesting. @iluwatar

**Comment by iluwatar** [comment]
Ok @karmagamer

**Comment by karmagamer** [comment]
@iluwatar I am on it. I will update you once I am finished,

**Comment by tliecau** [comment]
@karmagamer  please let me know if you need help with implementing or something with this pattern. I would love to help

**Comment by karmagamer** [comment]
@tliecau Sure buddy, so far it's coming along fine. I will update you in a week if I am stuck or need help.

**Comment by AnaghaSasikumar** [comment]
Hi, is this done? 
I have been working on something for the last few days and it is working...if it's not done can I submit a PR?

**Comment by AnaghaSasikumar** [comment]
Ok sure @karmagamer i'll give it a shot then 👍😀

**Comment by AnaghaSasikumar** [comment]
PR #797
