### ISSUE TITLE
Collection Pipeline pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#564]
https://martinfowler.com/articles/collection-pipeline/
https://www.ibm.com/developerworks/library/j-java8idioms2/index.html

**Comment by abhi-agr** [comment]
I read the articles linked here. In java, this is inherent in Streams and Lambdas to use the collection-pipeline.

I am not sure what we can do to represent this pattern as we don't need to write any new classes / interfaces to implement. For example, to implement State pattern, I need to come up with new classes to make the flow work.

**Comment by iluwatar** [comment]
In my opinion we can just create an example that utilizes Java's lambdas and streams and explain it in light of the pattern.

**Comment by abhi-agr** [comment]
ok...thanks

**Comment by GauravAggarwal** [comment]
I would like to work on the same, have gone through the links mentioned by you and it seems pretty straight forward to implement

**Comment by iluwatar** [comment]
@abhi-agr are you working on this or is it ok for @GauravAggarwal to implement it?

**Comment by abhi-agr** [comment]
I am working on it. Sorry Gaurav.

**Comment by iluwatar** [comment]
@abhi-agr are you still working on this?

**Comment by nikhilbarar** [comment]
Can i pick it if it's still open

**Comment by nikhilbarar** [comment]
PR #757 Please let me know if any changes are required. Thanks.

**Comment by iluwatar** [comment]
Ok @nikhilbarar

**Comment by npathai** [comment]
Merged succesfully, closing this. Thanks @nikhilbarar :+1:
