### ISSUE TITLE
Marker Interface pattern

### ISSUE THREAD

**Issue by 4lexis** [iluwatar/java-design-patterns#567]
http://jtechies.blogspot.rs/2012/07/item-37-use-marker-interfaces-to-define.html

I would love to work on this. I am new to open source projects. Didn't see marker interface pattern on your list, so can this be added? @iluwatar

**Comment by iluwatar** [comment]
@4lexis it would be great addition. Will you work on this yourself?

**Comment by 4lexis** [comment]
Yeah

**Comment by iluwatar** [comment]
Ok
