### ISSUE TITLE
Translate to PT-BR

### ISSUE THREAD

**Issue by lubarinobr** [iluwatar/java-design-patterns#574]
I want to help in this project Translating this repo to PT-BR. Can I do this work ?

**Comment by juanpablolvl99** [comment]
lubarinobr, i wanna help you with the translate

**Comment by iluwatar** [comment]
This is about translating the web site, right? I'm not sure if it has any mechanisms in place to support multiple languages. Maybe @markusmo3 can comment on this?

**Comment by markusmo3** [comment]
I reviewed this request a while ago, as i was messaged via email.

It would be quite the big deal to make the website work with multiple languages and i dont have a lot of time atm. It would theoretically be possible with jekyll and i'd be grateful if anyone else wants to help on this issue.

**Comment by lubarinobr** [comment]
Ok, I'll study some possible solution and post here before we start.

**Comment by dhsrocha** [comment]
You are not alone @lubarinobr . I'll join you in this cause! :)

**Comment by jonatasemidio** [comment]
I was reading this comments and after looking for some @github solution I've found one discussion and described one possible pattern to use. At least in this first moment.

This is just a way to organize our README.me files in different languages: https://github.com/jonatasemidio/multilanguage-readme-pattern

With this approach we can add independent translated files in each "design pattern folder".

**Comment by lubarinobr** [comment]
@dhsrocha Thanks
@jonatasemidio excelent I think that this can a good option to translate but for now. When we can talk about it ?

**Comment by jonatasemidio** [comment]
We can talk any time here  (;D) !

The point is, we need to ask for one of the responsible for this repo to add in the [wiki](https://github.com/iluwatar/java-design-patterns/wiki) one more page to define how to contribute with new languages and define one tag to use in translation problems.

**Comment by iluwatar** [comment]
Related issue https://github.com/iluwatar/java-design-patterns/issues/428
Support for multiple languages is on our roadmap, but the work has not yet started https://github.com/iluwatar/java-design-patterns/wiki/13.-Roadmap

**Comment by lubarinobr** [comment]
Good @iluwatar , @jonatasemidio May you help me with this Job ? We need to think the better solution to do it.

**Comment by iluwatar** [comment]
I think the scope of this would be to 1) translate the web site texts 2) translate the readmes 3) create mechanisms on the web site to switch language of 1 and 2.

**Comment by iluwatar** [comment]
The problem is that the original web site developer @markusmo3 hasn't been active anymore and we need to find a new core team member for this task. The person we are looking for needs to have some Jekyll and Ruby skills...

**Comment by lubarinobr** [comment]
I understand, I not have any skills with Jekyll or Ruby, But I think we can translate the readmes only to begin the process to translate the contents.

**Comment by iluwatar** [comment]
As this is a bigger roadmap item, I intend to write a preliminary plan how to implement it. I'll let you know when it's ready for comments.

**Comment by iluwatar** [comment]
Moved to https://github.com/iluwatar/java-design-patterns-web/issues/3
