### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#577]
Edward J Beckett @edwardbeckett May 11 02:55
@iluwatar Two links redirect to compromised sites... 1. http://java-design-patterns.com/principles/#liskov-substitution-principle resource [The Liskov Substitution Principle] 2. http://java-design-patterns.com/principles/#openclosed-principle [SOLID JavaScript: The Open/Closed Principle]

**Comment by guptasaloni** [comment]
i wanted to contribute..plz can u tell me exactly the what the problem is

**Comment by iluwatar** [comment]
@guptasaloni if you open the page linked above and click the mentioned links `The Liskov Substitution Principle` and `SOLID JavaScript: The Open/Closed Principle` it will redirect to some advertisements. The links should be removed or fixed.

**Comment by prakis** [comment]
@guptasaloni are you working on this?

**Comment by Jahhein** [comment]
This is part of a sub-repository at

https://github.com/webpro/programming-principles/tree/265a41c3a3a624f128dd68e6126fba2f7bedbffe

How might you suggest we fix this on java-design-pattern's repository? Fork and fix it on the other repository?

**Comment by iluwatar** [comment]
I think editing the corresponding readme files should be enough. Probably just removing the compromised links is enough for now. There's more information about the web site building process here https://github.com/iluwatar/java-design-patterns/wiki/07.-Working-with-the-web-site

**Comment by Jahhein** [comment]
I have opened a pull requests on the origin repository for that page to fix these links. I simply removed them entirely there. If you wish to go an alternative route, let me know. I am in the Gitter room for java-design-patterns.

https://github.com/webpro/programming-principles/pull/24

**Comment by revg** [comment]
Both links work fine for me

**Comment by ryantheleach** [comment]
That's because they have been replaced already. 

@iluwatar This can probably be closed.

**Comment by iluwatar** [comment]
@ryantheleach @revg thanks for notifying and thank to @Jahhein for fixing this issue. I'm closing it now.
