### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#591]
Java 9 general availability is just a few months away and we should start migrating the codebase to work on top of that. This is a huge issue and needs more discussion, planning and splitting.

**Comment by iluwatar** [comment]
There is now branch called `java9` where we aim to make the project work with JDK9. Pull requests helping towards that goal will be gratefully accepted.

**Comment by iluwatar** [comment]
The Java 9 build fails with the following output: 
[build.txt](https://github.com/iluwatar/java-design-patterns/files/1272821/build.txt)

**Comment by iluwatar** [comment]
List of changes for Java 9: https://docs.oracle.com/javase/9/whatsnew/toc.htm

**Comment by iluwatar** [comment]
The following commands install the Oracle's JDK9 EA on Ubuntu.

```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java9-installer
```

I also had to edit .bashrc and set
`export JAVA_HOME=/usr/lib/jvm/java-9-oracle/`

After which Java version displays as follows
```
$ java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by danielsiwiec** [comment]
I'll take a look at this issue

**Comment by iluwatar** [comment]
Ok @danielsiwiec

**Comment by danielsiwiec** [comment]
@iluwatar the PR above makes `mvn test` pass. Tested with Java 9ea14-zulu

**Comment by danielsiwiec** [comment]
What else is needed for this issue to be resolved?

**Comment by iluwatar** [comment]
- We should switch to using JDK9 at some point. When is the proper time? Does Travis support it already? The Travis build file should be modified for this and `java9` branch merged to master.
- How do we utilize the new Java 9 features? Separate issues should be created.

**Comment by iluwatar** [comment]
Tried the branch with openjdk-9 but the build fails with
```
Unrecognized option: --add-modules
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by javatlacati** [comment]
I hope this pom from my project can help you.

https://github.com/javatlacati/datastrructureskotlin/blob/Java9/pom.xml

**Comment by namannigam** [comment]
@iluwatar There is a sample shared at [SO-46084751](https://stackoverflow.com/questions/46084751/how-to-express-dependency-in-maven-on-java-ee-features-for-transition-to-java-9/46086920#46086920) on how to add the --add-modules to compiler args. Still curious to know what modules are you actually adding explicitly? (Reason being, one could look at the [JEP-320](http://openjdk.java.net/jeps/320) and see if using those dependencies could be the ideal state that the application should move to.)

**Comment by iluwatar** [comment]
Plans shifter to Java 11 support https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition
