### ISSUE TITLE
Effective Dating

### ISSUE THREAD

**Issue by gcraig** [iluwatar/java-design-patterns#592]
Objects that manage (a) expired dates for a given promotion or service as well as (b) date ranges: valid goods and services from validDate to expirationDate.

~~Something akin to page 14 of:~~

~~http://download.microsoft.com/download/4/E/3/4E36B655-568E-4D4A-B161-152B28BAAF30/Using_Date_Effective_Patterns_AX2012.pdf~~

To state the obvious, despite the MS reference, the goal is to produce a clean, efficient Java 9 product.

<a href="/iluwatar/java-design-patterns/labels/new%20pattern" style="color: #332900">new pattern</a>

**Comment by gcraig** [comment]
Hey folks! =) This is my first external contribution. Please let me know if I wander off the path; nevertheless, I'm working on this new pattern and we'll see what you all think. Thank you!

**Comment by gcraig** [comment]
Grace periods can be included as well as PTP (Promise to Pay), those are dates (and integer values of how many time a customer was truthful and successful) that are used in Collections and counted such that those who pay late can be evaluated and denied help in the future if they request assistance near pay days.

**Comment by iluwatar** [comment]
@gcraig looks interesting. Does the paper represent single pattern or multiple? Setting the labels requires write access to the repository.

**Comment by gcraig** [comment]
@iluwatar I haven't read the entire paper. I wanted to do a quick search to have some sort of artifact that I could point to in order to share the idea of (a) expiration date, (b) validDate, a generic event, i.e., promotions or sales that could be set in the future, but created early on. That of course would require, expireDate, and (c) a lone expireDate for those events that are always running but need an end. I think as we flesh out this pattern, starting small and easy KISS, we'll learn if it can be a Single or Multiple pattern through testing.

I can vouch for this used in a Rolling Delivery. We had over 2,000+ users. Not that much but we wanted the Support Staff (now DevOps) to watch the users (100 or so at a time.) It was a login event change in conjunction with some other business logic changes. I had to write a bunch of "IF" statements all over the place that checked the User levels, the current date, and the logins. It worked, but it was messy to me. Thus, if we could encapsulate it in a pattern, I think it would help some other people. Finally, thanks for tagging this effort. I didn't know it required "write access".

**Comment by gcraig** [comment]
Per the Wiki and process for contribution, here is the description of an implementation I thought initially would be passable. Annotations that represent the state of a given Object with Dates (<Java8, >Java8, & JodaTime, even ISO-8601 format) and essentially a Valid flag indicating True or False status. Using Annotations allows us to flesh out this pattern without a data backend, validate that it's a worthy pattern (although I've ran across a good use case in the real world where this would have been helpful), and finally, provide a simple implementation. I know it somewhat flies in the face by hard (coding) defining a date, but that's what Annotations do regarding their passed data. Some folks' use cases may only require a given date and then once it passes, never need this again. 

I am building out: 

(I use a fictitious Promotion Object as an example that is constantly under Date manipulation. I.e., Promoting new goods or services with discounts, etc. on an E-Commerce website.)

(1) @ValidDate, for specifying a Promotion on a given future date. The Date flag needs some thought. isValid, isCurrentDateValid, etc.

(2) @ExpirationDate, for specifying a Promotion that will end on a given date. 

(3) @ValidDateRange, where the developer can specify multiple instances of turning off and on a given Object. 

I thought about preceding each Annotation with EffectiveDateXXXXX but feel that it becomes too verbose as most anti-Java folks claim. So long as we don't have any name collisions, and even that is resolved via packaging, I think I'm headed in the right direction.

Grace periods and PTP (Promise to Pays) can be added, too. I will put some thought into that and post back. I thought Interfaces (along with Java 8 default method Interfaces) would be nice to add; yet, I don't want to create too much too soon, causing confusion. Simple Annotations and Example Unit Tests are my goal. I will focus on UML diagrams now after this post and Java code. Again, for the Annotations and first pass, I am keeping it simple: KISS.

Unless anyone has some thoughts on alternative implementations? What do you folks think? Thanks! @iluwatar

**Comment by gcraig** [comment]
(Apologies for the non-camelcase, dunno why it is not displaying correctly; at least on my end.)

**Comment by iluwatar** [comment]
Sorry, I don't want to be too difficult but I'm still unsure what is the design pattern here. The paper "describes how to use valid time state tables to store and track object history over its lifetime". Do you have better reference what it is we are trying to achieve? Usually the recognized design patterns are well known and described in some pattern catalog e.g. books, online catalogs or web sites.

**Comment by gcraig** [comment]
@iluwatar , no please, don't feel that way. I'm easy going. Plus, if we find out this isn't a beneficial or real pattern, then I'm ready to nuke it. The questions you bring up are valid. I'd like to do a couple things: 1. Produce a better "design" document. Nothing too crazy. Easy, quick Markdown README. 2. Also, a UML diagram. I can describe better the situation I used (and possibly dig up some old code.) -- Needs Discussion is an apt tag.

**Comment by gcraig** [comment]
@iluwatar, here is a much better resource of what I was referring to when I communicated "Effective Dating". Date ranges, dates of when products go valid, etc. It's applicable to almost every domain I've ever worked in - banking, e-commerce, insurance, HR, inventory management, etc. The first message resource I posted was rather hasty. I apologize. Here is an article with a much more detailed description of the (a) design pattern or (b) use of collective design patterns (much like Fowler's work). I think you'll be able to make a decision after I (1) post a UML, (2) detailed README, and (3) look at this resource: 

http://infullbloom.us/1055/the-future-of-hrm-software-effective-dating/. 

Thanks for reading!

**Comment by gcraig** [comment]
If I had to sum it up, @iluwatar, it would be an OOP pattern for "Start and End Dates, with Date Ranges."

**Comment by gcraig** [comment]
@iluwatar I'll create a UML diagram (migrate that to the Wiki's recommendation) and commit some working code, all to my repo, before creating a PR for you; forgive me for talking myself through the process. I want to make sure I'm correct. Thanks again for the help =)

**Comment by gcraig** [comment]
@iluwatar Is it considered bad manners to ask for your private email (or other channel) in case I have a few process/policy questions? I also intend to keep minimal "touch" so as we can focus on real work. Thank you.

**Comment by gcraig** [comment]
@iluwatar It simply occurred to me that this perhaps should be nuked from the repo. This is a "business" solution whereas all the patterns in this deliverable are "technical" in nature. I don't see a case for keeping "effective-dating", despite it being a valid concern and application of controlled logic. I'm trying to come up with a single reason and I'm drawing a blank. What are your thoughts? Do you mind if I continue the work and publish it here on GH if we remove it? And, of course, may I continue to contribute to your project here? It caught my eye and I've been a fan since.
