### ISSUE TITLE
Maven hangs during `mvn clean install` for reactor pattern

### ISSUE THREAD

**Issue by Jahhein** [iluwatar/java-design-patterns#596]
Maven seems to hang during reactor pattern's testing and will not complete.

Below is my maven version and a link to a gist of 2 run attempts. I waited for over 30 minutes on the second attempt and a it never completed.

I am not sure if this is the only pattern that does it but it happens every time.

`
$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
`

https://gist.github.com/Jahhein/0a6e91c44a7603839841389881800442

**Comment by Nish-Hub** [comment]
Can you once try changing maven version to 1.7

**Comment by Jahhein** [comment]
Will do, I see a package named mvnvm that manages maven versions, do you recommend it?

**Comment by Nish-Hub** [comment]
I am sorry , i meant changing version of jdk to 1.7 in maven. I believe u will find a maven.bat file.wherein u can specify the jdk version to use.

**Comment by Jahhein** [comment]
I do not have a maven.bat file or a *.bat file all.

**Comment by Jahhein** [comment]
Also want to add that maven was installed via homebrew. I will take into consideration this is an issue with my system for now and look further into fixing it. However if someone can let me know if they have the same issue, it'll save me a lot of time.

**Comment by gopinath-langote** [comment]
@Jahhein : Looks like Test was failing / waiting in code as per log. 

`Running com.iluwatar.reactor.app.ReactorTest` Here, Logging stopped. 

Have you reached to the problem? why is this happening?

**Comment by Jahhein** [comment]
@gopinath-langote Maven should report errors, test passes and fails. However maven hangs. Process hanging in computing means is just doesn't finish or the process is halted. 

Why this occurs no one knows or hasn't told me. No one has also informed me if they were able to replicate the issue either.

**Comment by iluwatar** [comment]
Can you run the test in debugger or add some log statements to see where it hangs exactly?

**Comment by Jahhein** [comment]
@iluwatar Sure, any suggestions on logging it exactly? It's maven, so all I can think of is verbose output of maven?

**Comment by iluwatar** [comment]
@Jahhein can you pull the latest source code and run the tests again on your computer and post the output?

**Comment by Jahhein** [comment]
@iluwatar Re-running now. I decided to re-install maven via homebrew and perhaps it'll make a difference. I don't have any maven related shell variables either.

**Comment by Jahhein** [comment]
@iluwatar Success! Thank you.

I've updated my gists above with a new output log of reactor and another file of the the last few lines of an entire project build with maven.

The entire project now builds on my system! Time to check this off as closed. 👍

**Comment by iluwatar** [comment]
Ok, closing the issue. Please reopen if the issue reoccurs.
