### ISSUE TITLE
Model View ViewModel MVVM?

### ISSUE THREAD

**Issue by ryantheleach** [iluwatar/java-design-patterns#601]
Anyone experienced with using Model View View Model?

https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel

popularised by Microsoft, in use in Knockout.js 

I was wondering if it had a Java analog, considering it's been used on .net.

**Comment by wcoder** [comment]
For implementation MVVM pattern needs abstraction of View

Video about implementation basic MVVM on example of Java Swing:
https://www.youtube.com/watch?v=-IIXlqF94WA

Exists a lot of examples for Android.
for Swing: https://github.com/vyshkov/mvvm

**Comment by ryantheleach** [comment]
WPF on C# also uses this pattern extensively.

**Comment by wcoder** [comment]
Exactly, because .NET has native (in the language) implementation of MVVM (used in WPF, UWP, Xamarin and etc.)

**Comment by javatlacati** [comment]
Yes it's nicely used as part of [Dukescript](http://dukescript.com/) and you can experiment with it using DEW: https://github.com/jtulach/dew

**Comment by metal4g** [comment]
@ryantheleach MVVM is perfectly used in JAVA in projects using the zkoss framework. For example https://www.zkoss.org/zkdemo/getting_started/mvvm
