### ISSUE TITLE
Searching for patterns doesn't work as expected

### ISSUE THREAD

**Issue by mibac138** [iluwatar/java-design-patterns#607]
When using the search box on the [patterns](http://java-design-patterns.com/patterns/) site I wanted to see the Prototype pattern. 

I started writing:
- `p` - not much changed
- `r` - the same
- `o` - every pattern disappeared
- this continues until `p`
- `p` - 3 patterns appear: `Naked Objects` (how?), `Property` and `Prototype`
- `e` - still 3 patterns appearing

Why does searching act so weird? I suppose this is a bug

**Comment by iluwatar** [comment]
Ping @markusmo3

**Comment by markusmo3** [comment]
Its black magic, i dont understand myself ^^
Anyone is free to try and fix it!

Here some important parts:
* it uses elasticlunr.com
* https://github.com/iluwatar/java-design-patterns/blob/gh-pages/search_index.json
* https://github.com/iluwatar/java-design-patterns/blob/gh-pages/static/js/search.js
* https://github.com/iluwatar/java-design-patterns/blob/98827c9537ef868fda01868b2f6dc91d28b2a36c/pages/patterns.html#L18-L24

**Comment by iluwatar** [comment]
Thanks @markusmo3 looks like nice puzzle :smile:

**Comment by danielsiwiec** [comment]
I took a stab at this and realized that replacing it with Lunr which supports wildcard searches makes it possible to search by shorter substrings.

Additionally, I removed the index boosts on certain fields, as they were never used anyway - they don't affect what is being returned by the query, only the score field in the result items and so far, this field isn't used by this application

**Comment by iluwatar** [comment]
@danielsiwiec see https://github.com/iluwatar/java-design-patterns/issues/653 Any idea what is going on?
