### ISSUE TITLE
Model View ViewModel (MVVM) pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#61]
https://en.wikipedia.org/wiki/Model_View_ViewModel

**Comment by pikuldorota** [comment]
Hi, could I work on this one?

**Comment by iluwatar** [comment]
Sure, go ahead @pikuldorota :+1:

**Comment by salman-bhai** [comment]
Is this still under construction?

**Comment by iluwatar** [comment]
Ping @pikuldorota

**Comment by pikuldorota** [comment]
Hi, I'm sorry but I wouldn't manage to finish this task.

**Comment by iluwatar** [comment]
No problem @pikuldorota. The task is free for taking again.

**Comment by 257ramanrb** [comment]
Hi @iluwatar , I want to take up this issue. Kindly, assign it to me.

**Comment by ohbus** [comment]
@257ramanrb Good Luck on your journey. I have assigned you this pattern. Be Sure to check our [Wiki](https://github.com/iluwatar/java-design-patterns/wiki) section for all your queries.

Kindly mention a timeframe when can we expect a Pull Request against this.

Please keep us posted of all your hurdles here. We will be happy to help you out.

**Comment by 257ramanrb** [comment]
Thanks @ohbus 

I am aiming to raise a Pull Request by `31st Dec, 2020` against this issue. I'll keep you updated about the progress and in case of any hurdles or change in timeline.

**Comment by 257ramanrb** [comment]
@ohbus Due to some personal obligations, I wouldn't be able to complete the task.

**Comment by ohbus** [comment]
@257ramanrb No problem. This issue is free for taking again.
