### ISSUE TITLE
Module pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#62]
https://en.wikipedia.org/wiki/Module_pattern

**Comment by inbravo** [comment]
Please assign; i can start ...

**Comment by iluwatar** [comment]
@inbravo you're good to go. Assigning can be used only for members with push access.

**Comment by iluwatar** [comment]
@inbravo are you implementing this? Please let us know if you no longer work on the issue.

**Comment by inbravo** [comment]
Apologies, i forgot about it. Please allow me to finish this by End of This week......

**Comment by inbravo** [comment]
It is done, i will create a pull request for review ...
