### ISSUE TITLE
Why should this be volatile? Is there any reason?

### ISSUE THREAD

**Issue by tg9963** [iluwatar/java-design-patterns#626]
https://github.com/iluwatar/java-design-patterns/blob/6c9e005a799fddd0200b4276d96b338dcb13b488/singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java#L36

**Comment by iluwatar** [comment]
> The Java volatile keyword guarantees visibility of changes to variables across threads.

`instance` is null checked on line https://github.com/iluwatar/java-design-patterns/blob/master/singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java#L59 and this is not inside synchronized block so some other thread may update it simultaneously. Volatile keyword is used here to guarantee accurate visibility to the latest state of the variable across threads.
