### ISSUE TITLE
Can't get h2 jar package in IntelliJ

### ISSUE THREAD

**Issue by steeeeets** [iluwatar/java-design-patterns#635]
After import the project into my IntelliJ, I found there is an issue that JdbcDataSource can't be imported in java-design-patterns/dao/src/main/java/com/iluwatar/dao/App.java. After specify the version in pom, the jar package can be downloaded and the issue is gone.

I'm a newbie to Maven, not sure what is wrong, but following dependency works.
Can anyone let me know if this is a real issue?
\<dependency>
        \<groupId>com.h2database\</groupId>
        \<artifactId>h2\</artifactId>
        \<version>1.4.196\</version>
\</dependency>

#help wanted
#question

**Comment by iluwatar** [comment]
Could not reproduce. Can you share the version of your IDE and the exact steps you do?

**Comment by dosdebug** [comment]
@steeeeets Can not reproduce either. Please specify maven version you currently are using as well.

**Comment by gpqhl0071** [comment]
我猜想你的h2 jar包，应该下载中途失败了，所以maven不会重新去下载，检查下maven本地仓库中的目标jar是否下载完整。

**Comment by fengdada1** [comment]
oh god
