### ISSUE TITLE
newer's question about syntax

### ISSUE THREAD

**Issue by wl020814** [iluwatar/java-design-patterns#649]
hello,i am a newer. i've seen the code:
       Callback c = () -> LOGGER.info("I'm done now.");

Is it the same as :
     Callback c = new Callback(){
     @override
     public void call(){
             LOGGER.info("I'm done now.");
    }
}

Thanks for help. where could i get the syntax?

**Comment by dosdebug** [comment]
@wl020814 Yes, it's same but with lambdas. You can read more about [Lambda Expressions](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html)
