### ISSUE TITLE
Active Object concurrency pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#65]
https://en.wikipedia.org/wiki/Active_object

**Comment by iluwatar** [comment]
Thinking in Java book

**Comment by hannespernpeintner** [comment]
I'll give it a try :)

**Comment by hannespernpeintner** [comment]
I pushed a module in a new branch. Since I wasn't satisfied with the simple "I have my own thread"-implementation one can find everywhere, I implemented return values with futures and a task queue as well.

Would be glad if I get some comments. If the code is good, I will add readme and uml stuff.

Thanks :)

**Comment by iluwatar** [comment]
Real world example: http://doc.akka.io/docs/akka/2.4.1/java/typed-actors.html

**Comment by Rzeposlaw** [comment]
Hello, can I work on this now?

**Comment by iluwatar** [comment]
Ok @Rzeposlaw it is yours.

**Comment by tzutalin** [comment]
@Rzeposlaw,
   It will be nice to explain the difference between active object pattern and event-driven-architecture/event-asynchronous.

**Comment by isabiq** [comment]
I think the two patterns have some similarities but they are different in many aspects. The main goal of the event asynchronous is to hide the complexity of a multi-threaded design. Normally, a user want to execute his tasks asynchronously so he delegates the tasks to another objects that control and supervise the execution of these tasks. For me, The pattern has a really narrow use case, and I see it mainly used in GUI applications when performing short background operations and publishing results to the UI thread.
For the active object it is a pattern used to decouple method invocation from its execution. It is a complex pattern that hold in its implementation other patterns. So here, it is about a client calling a proxy to benefit from a certain service not delegating a task of his. Also, while both pattern use multi-threaded environments, the active object introduces other concepts, like a scheduler which provide another layer of managing and prioritizing requests, a servant for defining the behavior and state and method requests.

**Comment by iluwatar** [comment]
@Rzeposlaw  are you still implementing this?

**Comment by iluwatar** [comment]
This issue is free again

**Comment by noamgrinch** [comment]
Hey, @iluwatar I have implemented this pattern and ready to push to my branch.
May I please get permissions to commit and push?

**Comment by noamgrinch** [comment]
@iluwatar ?

**Comment by iluwatar** [comment]
@noamgrinch please follow the normal Github forking workflow. You don't need write access to this repository, you can fork it on your own account and propose changes from there. See [Github's documentation](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).
