### ISSUE TITLE
Searching/Filtering  at http://java-design-patterns.com/patterns/ doesn't work

### ISSUE THREAD

**Issue by tomyy** [iluwatar/java-design-patterns#653]
* I tried to search for "abstract": all patterns a shown, no indication that anything was searched
* I tried to restrict the categories to 'Creational': still all patterns are shown
* I tried to restrict the tags to 'Gang of Four': still all patterns are shown

To make sure that it is not my browser I tried to do this with Mozilla Firefox 56.0, Google Chrome 61.0.3163.100 and Microsoft Edge 40.15063.0.0 and I had the same problem with every one of these browsers.

**Comment by aldaircruz** [comment]
I have the same issue, I got those errors:

![imagem](https://user-images.githubusercontent.com/17972991/31317532-78664386-ac3a-11e7-8ae5-6a51c900aedb.png)

![imagem](https://user-images.githubusercontent.com/17972991/31317534-96ddaff2-ac3a-11e7-9036-f134ab1ba54e.png)

**Comment by iluwatar** [comment]
Thanks for reporting @tomyy and @aldaircruz We are looking into it.

**Comment by dungnart** [comment]
I can not do any Search/Filter on http://java-design-patterns.com/patterns/ site. Please check it. Thank you !

**Comment by nathancyam** [comment]
It seems if the patterns' content contains any braces, it breaks JSON parsing. I've got a PR here (https://github.com/iluwatar/java-design-patterns/pull/657) that adds the `url_encode` filter to ensure this doesn't happen again.

The build seems to be breaking, but it looks like Travis can't resolve certain URLs.
