### ISSUE TITLE
Balking pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#66]
https://en.wikipedia.org/wiki/Balking_pattern

**Comment by AlexandrKoshi** [comment]
I try to implement it :)

**Comment by protopapa** [comment]
Hi! i would like to take that one. is it ok ?

**Comment by iluwatar** [comment]
Sure, I will change the labels.

**Comment by protopapa** [comment]
Nice. Thanks!

**Comment by protopapa** [comment]
Hey!It was some busy months, together with the vacations. I will come back with this soon. Is that OK ?

**Comment by iluwatar** [comment]
No problem @protopapa , you can work on it when you're able.

**Comment by Rzeposlaw** [comment]
Hi, I'm not sure if anybody still is doing this pattern. If it's possible I want to take it. I would be very glad if you will inform me about its availability as soon as possible. Thank you very much!

**Comment by iluwatar** [comment]
@protopapa are you currently working on this or may @Rzeposlaw take it?

**Comment by Rzeposlaw** [comment]
Hi, I want to remind you about my question. Could I work with this pattern in this situation? :)

**Comment by iluwatar** [comment]
There's no answer from @protopapa so far. I think we can assume that it is no longer under construction and you can take it. @Rzeposlaw, you're good to go!

**Comment by protopapa** [comment]
Sorry for disappearing.  And I just got synced, please ignore my commit. My bad and I was late.
