### ISSUE TITLE
Is it threadsafe ? 

### ISSUE THREAD

**Issue by Krandelbord** [iluwatar/java-design-patterns#666]
Seems like lastServedId field from LoadBlanacer.class is shared among all instances.
I think this is not threadsafe and will crash when mutiple threads will try to increment it.

https://github.com/iluwatar/java-design-patterns/blob/390c33e36e82b558e8cab6028d96e49c0a20da9f/monostate/src/main/java/com/iluwatar/monostate/LoadBalancer.java#L39

**Comment by npathai** [comment]
@Krandelbord You are correct. It is not thread safe as field is being shared without synchronization. Can you raise a PR with the fix?

**Comment by Mathias83** [comment]
Perhaps change to atomicInteger?!

**Comment by Krandelbord** [comment]
If I use AtomicInteger then I have to make reading, comparing, incrementing, and setting to zero as one atomic operation.
It will end up in something like that
```
private static AtomicInteger lastServedId = new AtomicInteger();
  public void serverRequest(Request request) {
    int serverIdToUse = lastServedId.getAndUpdate((lastServedId) -> lastServedId < servers.size() - 1 ? ++lastServedId : 0);
    Server server = servers.get(serverIdToUse);
    server.serve(request);
  }
```
Doesn't look good. So I decided to make method synchronized.

**Comment by Mathias83** [comment]
Is Volatile a Solution?!

**Comment by fluxw42** [comment]
No, ```volatile``` is not suitable for cases where you want to read-update-write as an atomic operation; access to a volatile variable never has the potential to block: you're only ever doing a simple read or write ([source](https://www.javamex.com/tutorials/synchronization_volatile.shtml)).
