### ISSUE TITLE
Consider adding another badge

### ISSUE THREAD

**Issue by zafarella** [iluwatar/java-design-patterns#672]
@iluwatar as this project is open-source, I was thinking why not add https://bestpractices.coreinfrastructure.org
as a badge. It will be like cool both standardization + learning for readers.
You have to create the project there and add the badge.

Others probably also can contribute whenever you create it.
> Just thought, please ignore if not relevant

**Comment by iluwatar** [comment]
I have no previous experience in the "CII Best Practices Badge Program". I see they have some [criteria](https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md) that has to be met for a project to "self-certify". I briefly looked at it and it seems that we are already passing all their tests. So if you @zafarella or somebody else want to work on this and get us the badge I'm ok with it.
