### ISSUE TITLE
add free static code analyzer

### ISSUE THREAD

**Issue by zafarella** [iluwatar/java-design-patterns#673]
@iluwatar  what do you think of adding https://about.sonarcloud.io/
it's free for open-source. IMHO, valuable addition

**Comment by iluwatar** [comment]
We already have it, see https://sonarcloud.io/dashboard?id=com.iluwatar%3Ajava-design-patterns. Related https://github.com/iluwatar/java-design-patterns/issues/674

**Comment by zafarella** [comment]
:+1
Closing as dup.
