### ISSUE TITLE
SonarQube update

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#674]
Hi,

About 6 months ago, we renamed SonarQube.com to SonarCloud. The URL of the service changed from https://sonarqube.com to https://sonarcloud.io.

I am contacting you because we noticed that you are still using the old URL (sonarqube.com) to point to the service when you run analyses. Typically, this is set through the "sonar.host.url" property in your build scripts, or in your CI tool configuration (like an end-point in VSTS or a global config in Jenkins).

In a few months, we are going to drop the old URL to keep only https://sonarcloud.io. You probably want to take a look at this early to prevent any futur errors in your build jobs.

Also, if you are using Travis as your CI engine to trigger the analyses, I suggest that you take a look at our [Travis Add-on](https://docs.travis-ci.com/user/sonarcloud/). Relying on this add-on would allow to not be impacted by potential similar changes in the future.

Hope you enjoy the service!

Best regards,
Fabrice Bellingard | SonarSource
SonarQube & SonarCloud Product Manager
https://sonarsource.com

**Comment by SferaDev** [comment]
Just editing https://github.com/iluwatar/java-design-patterns/blob/master/.travis.yml#L20 should work unless you want to add the Travis Add-on.
