### ISSUE TITLE
event-asynchronous pattern   class diagram is error

### ISSUE THREAD

**Issue by fleaLi** [iluwatar/java-design-patterns#675]
The ThreadCompleteListener can't find “notifyOfThreadComplete” method

**Comment by iluwatar** [comment]
Link to the diagram, please?

**Comment by fleaLi** [comment]
https://github.com/iluwatar/java-design-patterns/blob/master/event-asynchronous/etc/event-asynchronous.png

**Comment by ThatGuyWithTheHat** [comment]
May I take this issue?

**Comment by ThatGuyWithTheHat** [comment]
I am a bit confused. What should the .png look like?

**Comment by iluwatar** [comment]
I think the method name has changed. `ThreadCompleteListener#notifyOfThreadComplete` no longer exists. The current version of the class has a different method, see here https://github.com/iluwatar/java-design-patterns/blob/master/event-asynchronous/src/main/java/com/iluwatar/event/asynchronous/ThreadCompleteListener.java. So you should just update the class diagram. We have used http://www.objectaid.com/ to generate the class diagrams.

**Comment by iluwatar** [comment]
Go ahead @ThatGuyWithTheHat, just ask if you need more help.
