### ISSUE TITLE
Pattern : trampoline. Is it needed?

### ISSUE THREAD

**Issue by besok** [iluwatar/java-design-patterns#677]
Hi!
I have not found a pattern Trampoline in the list.
I want to discuss adding this pattern to list.

Will be it right?
I can do it if it is possible.

**Comment by iluwatar** [comment]
Can you please provide links to the pattern?

**Comment by besok** [comment]
Shure.
Wiki - https://en.wikipedia.org/wiki/Trampoline_(computing) (high-level programming)
good example - https://medium.com/@johnmcclean/trampolining-a-practical-guide-for-awesome-java-developers-4b657d9c3076
stackoverflow - https://stackoverflow.com/questions/189725/what-is-a-trampoline-function

2017-12-11 21:42 GMT+03:00 Ilkka Seppälä <notifications@github.com<mailto:notifications@github.com>>:

Can you please provide links to the pattern?

**Comment by iluwatar** [comment]
The links look good to me. Who would like to implement?

**Comment by besok** [comment]
I can do it if you don't mind.

**Comment by iluwatar** [comment]
Ok @besok

**Comment by besok** [comment]
ok. In 1-2 week this pattern weil be in pull request.
