### ISSUE TITLE
Dev Wiki IDE instructions do not work on windows 10

### ISSUE THREAD

**Issue by ThatGuyWithTheHat** [iluwatar/java-design-patterns#685]
When following the instructions [here](https://github.com/iluwatar/java-design-patterns/wiki/12.-IDE-instructions) the check styles plugin does not show up. Even after I restart my computer and ensure the plugin is installed. This is an issue with *Eclipse* and *IntelliJ* so I don't expect anyone to fix it. If someone has found a workaround it might be helpful to add that to the instructions.

These instructions work just fine using ubuntu 17.10

**Comment by 15838028035** [comment]
i have the same problem , i use windows 7  ,eclipse 4.5.2 , checkstyle 6.10

**Comment by joseph-mccarthy** [comment]
I have not had an issue. Could you please provide some more information?
