### ISSUE TITLE
Remove redundant explicit super() constructor calls

### ISSUE THREAD

**Issue by lotsabackscatter** [iluwatar/java-design-patterns#694]
The super() calls (taking no arguments) are inserted during compile time, so just make the code more verbose than required.

One example is found in the [HeroStat ](https://github.com/iluwatar/java-design-patterns/blob/master/value-object/src/main/java/com/iluwatar/value/object/HeroStat.java#L40) class.

**Comment by james-a-roland** [comment]
@iluwatar I'll take this if no one else has

**Comment by iluwatar** [comment]
@james-a-roland there is a pull request about this, see https://github.com/iluwatar/java-design-patterns/pull/695. But I have a feeling it does not solve all redundant calls to `super()`. Either work with @jonatasemidio by reviewing the PR or create your own PR that resolves all the cases. I will assign the issue to you.

**Comment by jonatasemidio** [comment]
Hi @james-a-roland and @iluwatar,
Do you know what type of unit test can I include to check this other cases?

**Comment by iluwatar** [comment]
I would probably just `grep` through all `super` occurrences

**Comment by james-a-roland** [comment]
@iluwatar - Pull request can be found here https://github.com/iluwatar/java-design-patterns/pull/697

**Comment by jonatasemidio** [comment]
@iluwatar, another consideration... I know that grep can find all occurrences, but we might have some samples that super() calls some father's constructors.

Hi @james-a-roland, To solve #694 ... How did you checked all super() occurrences?

**Comment by olcbean** [comment]
I used `grep 'super()'`

**Comment by james-a-roland** [comment]
Same as @olcbean - any calls to super() called from a custom constructor were deleted. Since all objects are POJO's, I think this is a safe operation.

**Comment by jonatasemidio** [comment]
So... In this case, we can use #697 instead of #695
