### ISSUE TITLE
could you give a code format template file in project ?

### ISSUE THREAD

**Issue by 15838028035** [iluwatar/java-design-patterns#700]
could you give a code format template file in project ?  when i use eclipse (4.5.2) ,checkstyle(6.16.0),
i do like this:
Right click java-design-patterns project in Project Explorer and choose Checkstyle - Create formatter profile

but eclipse not alert dialog for me to save file , could you add checkstyle code format template ?

**Comment by 15838028035** [comment]
@iluwatar  could you help me ?

**Comment by kanwarpreet25** [comment]
Hi @15838028035 
To enable checkstyle in your project. 
1) Go to Windows->Preferences->Checkstyle->New
2) Select External Configuration file from type . 
3) Browse-> java-design-patterns folder-> checkstyle.xml -> Give name to your configuration->Ok.
4) Now right click on your project-> properties->Checkstyle 
5) Enable checkstyle active for this project and select the configuration from the dropdown which you configured in step3. 
6) The checkstyle will be enabled for your project
