### ISSUE TITLE
ci problem  could you help me ?

### ISSUE THREAD

**Issue by 15838028035** [iluwatar/java-design-patterns#703]
i see this project used travis-ci ,   build successfully .
now i have two project on github , project-common-core, project-A,
this all maven project ,  projectA dependies project-common-core,  

when i use travis-ci build project-A,  build failure, the error message is that 

can't find project-comon-core  some class?  what should i do ?
@iluwatar

**Comment by namannigam** [comment]
@15838028035 I am not sure how is it related to the repository here. But you can make sure that `project-A` relies on a released version of `project-common-core`. Else you might want to build both of them sequentially when pulled under the same remote directory.

**Comment by 15838028035** [comment]
Hi,   my project is maven project  !   i  have write   project-A relies on a released version of project-common-core, 

how can i write .travis.yml, next is my  yml config


language: java

jdk:
  - oraclejdk8
 
 
after_success:
- mvn   cobertura:cobertura  sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
notifications:
  email:
    - 15838028035@163.com





could you  help me ?






At 2018-01-23 14:45:13, "Naman Nigam" <notifications@github.com> wrote:


@15838028035 I am not sure how is it related to the repository here. But you can make sure that project-A relies on a released version of project-common-core. Else you might want to build both of them sequentially when pulled under the same remote directory.

**Comment by joseph-mccarthy** [comment]
How is this even related? Could this issue be closed? @iluwatar

**Comment by iluwatar** [comment]
Yes, I agree @joseph-mccarthy, it's not related. So let's close this issue.
