### ISSUE TITLE
ci problem could you help me ?

### ISSUE THREAD

**Issue by 15838028035** [iluwatar/java-design-patterns#704]
@iluwatar   
Hi , i have a project on github , i add  ci ,sonar  , but sonar build file ,could you help me ?

my project next:
https://github.com/15838028035/bsweb-common-core

.travis.yml content:

language: java

jdk:
  - oraclejdk8
 
  
after_success:
- mvn   cobertura:cobertura  sonar:sonar -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=$SONAR_TOKEN  -X
notifications:
  email:
    - 15838028035@163.com

sudo: required

i have config SONAR_TOKEN in CI  config page .
one build log is:
https://api.travis-ci.org/v3/job/332599647/log.txt

build sonar failure , could you help me ?

**Comment by 15838028035** [comment]
@iluwatar  could you help me ?

**Comment by iluwatar** [comment]
I recommend following the tutorial at https://about.sonarcloud.io/get-started/. The issue is not related to this project so I'm closing it.

**Comment by 15838028035** [comment]
Okay thanks

发自我的 iPhone
