### ISSUE TITLE
about prototype's clone method

### ISSUE THREAD

**Issue by yunhenk** [iluwatar/java-design-patterns#707]
Hi, this is the code in the prototype pattern.And I wonder why this clone() method creates a new object rather than clone itself? Thanks.

> 
public class OrcBeast extends Beast {

  public OrcBeast() {}

  @Override
  public Beast clone() throws CloneNotSupportedException {
    return new OrcBeast();
  }

  @Override
  public String toString() {
    return "Orcish wolf";
  }

}

**Comment by mookkiah** [comment]
I just created a pull request (https://github.com/iluwatar/java-design-patterns/pull/709/files) which uses copy constructor. Added an instance variable to represent the clone operation.

**Comment by yunhenk** [comment]
mookkiah fixed the method, users are expected to implement the copy method by making deep copy

**Comment by iluwatar** [comment]
@yunhenk thanks for noticing this
