### ISSUE TITLE
Lock pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#71]
https://en.wikipedia.org/wiki/Lock_(computer_science)

**Comment by gwildor28** [comment]
Hi, Id like to have a go at implementing this pattern. If I base it around the code on this website: 

http://tutorials.jenkov.com/java-concurrency/locks.html

Would that be OK? Do you have any specific requirements for how you want this implemented?

**Comment by gwildor28** [comment]
Hi, I'm just bumping this

**Comment by iluwatar** [comment]
Sorry for the late answer @gwildor28 Your suggestion is fine. I would like to see the example present the different types of locks and show how they are used. No other specific requirements, just follow how the other examples have been implemented e.g. [Caching](http://java-design-patterns.com/patterns/caching/)

**Comment by gwildor28** [comment]
I've created an example of a mutex and a semaphore. Do you want these to be in different packages? e.g. com.iluwatar.lock.mutex/com.iluwatar.lock.semaphore

**Comment by iluwatar** [comment]
It depends on the implementation. We can comment this when you create the pull request.
