### ISSUE TITLE
New pattern:CircuitBreaker

### ISSUE THREAD

**Issue by besok** [iluwatar/java-design-patterns#712]
I couldn't found a pattern "CircuitBreaker" for reactive systems.
Could I implement this?

The common idea - a control pattern for service state .
Breaker can be with 3 states
-> half open - if the service is normal and breaker cheks the service availability and then swith state.
-> open - if the service is failure and breaker must return fast reject
-> close - if the service is normal and request goes to service.

[link-Martin Fowler](https://martinfowler.com/bliki/CircuitBreaker.html)
[wiki(electricity) - analogue](https://en.wikipedia.org/wiki/Circuit_breaker)

**Comment by iluwatar** [comment]
Duplicate. See https://github.com/iluwatar/java-design-patterns/issues/413 and https://github.com/iluwatar/java-design-patterns/issues/414
