### ISSUE TITLE
Ambassador Pattern

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#722]
https://docs.microsoft.com/en-us/azure/architecture/patterns/ambassador

**Comment by harshitrathod** [comment]
@npathai According to me this pattern is just extended use of proxy pattern. Here at edge service, we are putting our logic for the proxy which hides actual Application and also provides us extendibility to put our circuit breaking and other logic in that.
Eg. Hibernate Transaction management uses proxy pattern in which it provide extendibility to provide support for commits/roll-back 
Let me know if it makes any sense

**Comment by okinskas** [comment]
@harshitrathod despite this seeming like an extension of proxy as you stated, is it still viable to create an example? If so I would be interested in doing so.

**Comment by iluwatar** [comment]
Yes, go ahead @okinskas

**Comment by npathai** [comment]
@harshitrathod Yeah it makes sense. It is almost (if not exactly) same as Remote Proxy pattern.
