### ISSUE TITLE
Intermittent test failure in Balking pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#727]
See Travis log https://travis-ci.org/iluwatar/java-design-patterns/builds/353446296

**Comment by sreebasavamanju** [comment]
i think in local it was successfully passed tests!

**Comment by iluwatar** [comment]
Yes, it happens only now and then.

**Comment by iluwatar** [comment]
Duplicate of https://github.com/iluwatar/java-design-patterns/issues/699
