### ISSUE TITLE
Add language to Readme snippets for highlighting

### ISSUE THREAD

**Issue by Deathnerd** [iluwatar/java-design-patterns#728]
Hello,

First off, awesome repo. I love having this handy for self-study or looking up things in a pinch. Very well done, guys!

While reading through some of the `Readme.md` files though, I've noticed a lack of syntax highlighting in the code samples. See [the chain pattern for an example](https://github.com/iluwatar/java-design-patterns/tree/master/chain). This is trivial to add as GitHub supports it as part of their flavor of Markdown. 

I'm more than happy to fork and update them later tonight if possible. However, I'm not sure if that will break the build tools for the site. Can anyone enlighten me if it's possible?

Thanks!

**Comment by Deathnerd** [comment]
Gah. It appears I can't add labels to this issue. I was going to label it as `Enchancement` and `Question`

**Comment by iluwatar** [comment]
Thanks @Deathnerd. Have you checked the web site http://java-design-patterns.com/patterns/chain/ that is generated from the `README.md` files? The web site is the primary display of the site. Browsing Github can be a bit crude.

**Comment by Deathnerd** [comment]
@iluwatar I have! That was actually my first exposure to the repository. However in that page you linked, it suffers from the same problem: No syntax highlighting. I'm assuming that Jekyll is used for both the GH Pages and the Amazon S3 version of the site, yes? I haven't done much with Jekyll, but a quick Googlin' tells me that it should by default (I hope) Jekyll 3 comes with the `rouge` highlighter [(source)](https://mycyberuniverse.com/web/syntax-highlighting-jekyll.html). Even then it looks like adding it to Jekyll 2 should be relatively easy. Anyways... If the post I linked is to be believed, then I think my proposed changes would also reflect upon the site as well.

Another thing related to this. If I go through and add the language identifiers to all of the code blocks, then I would think that the contributing wiki should be updated somewhere to include them as rules for contributing changes as well. For consistency sake.

**Comment by iluwatar** [comment]
@Deathnerd you are right, syntax highlighting is missing. Jekyll is used for GH pages and AWS version. If you have made or are going to make we would gladly accept a patch that would add the syntax highlighting. Note that there are some instructions for getting started with JDP web site development here https://github.com/iluwatar/java-design-patterns/wiki/07.-Working-with-the-web-site.

**Comment by iluwatar** [comment]
If you are working on this, I will add the `under construction` label here, yes?

**Comment by Deathnerd** [comment]
@iluwatar Yeah I'll get this under way sometime soon. Probably tomorrow :)

**Comment by iluwatar** [comment]
Ok @Deathnerd

**Comment by Deathnerd** [comment]
@iluwatar PRs #731 and #730 address these changes both for the site pages and the patterns respectively
