### ISSUE TITLE
Consistent naming and tagging for EIP patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#733]
Some of the EIPs have used naming convention beginning with eip-xxx. Apply this naming to all EIPs to make them consistent.

Also should check that EIPs at http://java-design-patterns.com/patterns/ have consistent categories and tags.

**Comment by Deathnerd** [comment]
I know this issue is closed, but for those of us who are a little slow... What does EIP mean exactly?

**Comment by iluwatar** [comment]
Enterprise Integration Patterns, see the book by mr. Hohpe https://en.wikipedia.org/wiki/Enterprise_Integration_Patterns
