### ISSUE TITLE
Acyclic Visitor pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#734]
http://condor.depaul.edu/dmumaugh/OOT/Design-Principles/acv.pdf

**Comment by Argyro-Sioziou** [comment]
Hello! @giorgosmav21 and I are a team from Athens University of Economics and Business. We have an assignment to contribute to a project. Can we work on this issue?

**Comment by calvinspider** [comment]
@iluwatar hello,is this project still continuing？Can I join in and work on this issue?

**Comment by iluwatar** [comment]
@calvinspider this issue is already assigned to @Argyro-Sioziou and @giorgosmav21. You should negotiate with them if you want to help.
