### ISSUE TITLE
Request for contribution

### ISSUE THREAD

**Issue by kfragkedaki** [iluwatar/java-design-patterns#738]
I found interesting your project and I'd like to contribute to this. Is there anything that needs improvement?

**Comment by iluwatar** [comment]
Look into issues list https://github.com/iluwatar/java-design-patterns/issues. Some of the major categories are Java 9 support, new patterns, quality improvements, pattern descriptions, blogs, presentations. See wiki (https://github.com/iluwatar/java-design-patterns/wiki) for some general instructions.

**Comment by npathai** [comment]
I think we can close this issue now.
@kfragkedaki Let us know if you have any further questions.
