### ISSUE TITLE
What's the difference between “API Gateway” and “Aggregator Microservices”? Isn't it the same?

### ISSUE THREAD

**Issue by htpbackup** [iluwatar/java-design-patterns#756]
[API Gateway](http://java-design-patterns.com/patterns/api-gateway/)

[Aggregator Microservices](http://java-design-patterns.com/patterns/aggregator-microservices/)

**Comment by harshsri2208** [comment]
@htpbackup refer this link : https://dzone.com/articles/microservice-pattern-api-gateway

**Comment by npathai** [comment]
Before closing this issue, this question can be made part of FAQ.

**Comment by kanwarpreet25** [comment]
Hi @npathai  I will get it done
