### ISSUE TITLE
Configurable Converter Pattern

### ISSUE THREAD

**Issue by nikhilbarar** [iluwatar/java-design-patterns#758]
Basic idea of a converter is to convert a source class into a target class. There's an approach which extends this behaviour and provides a way to create configurable converters using an collection of populators and enums.

Converter creates instances of beans and populators instantiate those instances using source object. Each Converter can contains list of populators.

Any set of populators can be mapped to an enum and used in the converter.

For example:
Customer may contain profile info, addresses and orders.

To convert a Customer object we'll define 3 populator beans:
profilePopulator, addressPopulator and orderPopulator

Convert method would look something like (CustomerSource, CustomerTarget, Collection<CustomerOption>)

This would be better in cases where we dont need to convert the complete source object to target object. In addition to this same populator can be used to create a different converter. For example addressPopulator can be used in orderConverter.

**Comment by iluwatar** [comment]
Any links to references where this pattern is mentioned?

**Comment by nikhilbarar** [comment]
We're using this in our project on SAP Hybris. This is the closest match i could find https://hybrisinstructive.blogspot.com/2017/12/converters-and-populators-in-hybris.html

**Comment by nikhilbarar** [comment]
Hi, any updates on this?

**Comment by ernestasdeveloper** [comment]
Hi Nikhilbarar, I am curious to ask why you are using that solution instead of already built libraries like Dozer Mapper?

**Comment by iluwatar** [comment]
@nikhilbarar have you seen this https://xsolve.software/blog/converter-pattern-in-java-8/? Is it similar to what you are trying to achieve? See also https://java-design-patterns.com/patterns/data-mapper/ and https://java-design-patterns.com/patterns/converter/
