### ISSUE TITLE
Components in a Java Server Page

### ISSUE THREAD

**Issue by nikhilbarar** [iluwatar/java-design-patterns#759]
In a standard spring mvc application, a page is created by providing a mapping for its request in a Controller class which returns a jsp view which the server converts into HTML and sends to some browser.

There's another approach which allows you to define a page as a list of reusable components. Each component has its own controller and view (jsp).

The view (jsp) of the parent page will have a tag to render it's child component. The logic to invoke the controller of each component to fill the model object will be written in the Tag Library Descriptor of the tag. The view associated with the component will be returned from its controller.

This way when a request for a page is made, it'll create the final view by combining the views of all its child components.

**Comment by iluwatar** [comment]
Do you have a name or reference for this pattern?

**Comment by nikhilbarar** [comment]
Hi, any updates on this?

**Comment by gdiazs** [comment]
There are some aproachs ( sorry for my english guys)  that match with you said ( if I understood well :) )

Like apache wicket, taperstry and even jsf . All they are component based pattern. Apache wicket its the most lightweight I guess.

**Comment by iluwatar** [comment]
@nikhilbarar The link looks like a tutorial on how to create a new page with Hybris framework. As such I don't see how it would fit the definition of a pattern. I agree with @gdiazs that there are multiple approaches for doing this, basically one per framework. Design patterns are framework agnostic, although a framework or library can implement a pattern.
