### ISSUE TITLE
Singleton Double Locking

### ISSUE THREAD

**Issue by VivekVinushanth** [iluwatar/java-design-patterns#760]
Why the static variable is volatile in double locking check.That might lead to un atomic actions still right?

**Comment by iluwatar** [comment]
The volatile keyword guarantees visibility of changes to variables across threads. So if some thread has already initialized the singleton instance it is guaranteed to be visible in check https://github.com/iluwatar/java-design-patterns/blob/master/singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java#L59

**Comment by VivekVinushanth** [comment]
Thank you for clarification

**Comment by npathai** [comment]
@VivekVinushanth Read [Java Concurrency In Practice](https://www.amazon.com/Java-Concurrency-Practice-Brian-Goetz/dp/0321349601) for in-depth clarification on volatile, synchronized, etc.

Closing this issue for now.
