### ISSUE TITLE
ThreadSafeDoubleCheckLocking.java: Instantiating by Reflection call will be successful if you do that firstly

### ISSUE THREAD

**Issue by DovahYol** [iluwatar/java-design-patterns#761]
https://github.com/iluwatar/java-design-patterns/blob/987994f0fe5747e5524bc43c3b2000bee478c0c3/singleton/src/main/java/com/iluwatar/singleton/ThreadSafeDoubleCheckLocking.java#L43-L45
Instance will be null, and you can create a singleton object by reflection without an exception.

**Comment by iluwatar** [comment]
Yes, that is true. But I think that is the way the code is supposed to work. It allows creating one and only one instance, right?

**Comment by DovahYol** [comment]
Actually you can create another instance via `ThreadSafeDoubleCheckLocking.getInstance()`, or as many instances as possible via reflection.

**Comment by iluwatar** [comment]
Can someone verify this?

**Comment by npathai** [comment]
@iluwatar Sure. I will have a look at it.

**Comment by IAmPramod** [comment]
I think we can create multiple instances of a singleton class only in case of lazy initialization as in the above example.
If we change that to eager initialization, this check will be sufficient to create multiple instances of this class.

**Comment by Azureyjt** [comment]
@iluwatar May I pick this up?

**Comment by iluwatar** [comment]
@Azureyjt please go ahead

**Comment by Azureyjt** [comment]
PR created. Please kindly review it :) @iluwatar
