### ISSUE TITLE
how can i find the url Quality Gate from  README.md  from sonar.io?

### ISSUE THREAD

**Issue by 15838028035** [iluwatar/java-design-patterns#762]
Hi , i have buildm install  a sonar  in my compute, i want to add the quality gate to readMe.md.

how can i find the url Quality Gate from  README.md  from sonar.io?
https://sonarcloud.io/api/project_badges/measure?project=com.iluwatar%3Ajava-design-patterns&metric=alert_status

could you help me ?

**Comment by npathai** [comment]
@15838028035 Sorry didn't understand your question. Can you please ask this question on gitter chatroom?
Closing this issue for now. Reopen in case there is a problem.
