### ISSUE TITLE
Categories and tags selection

### ISSUE THREAD

**Issue by DiscipleOfShinku** [iluwatar/java-design-patterns#764]
When I select desired categories and tags, read about one of provided patterns and want to return to the same filtered patterns list, I have to move back in a browser history (because the "Patterns" link in the main menu loads the page from scratch). Further, checkboxes save their states except for "categories" and "tags" chekboxes themselves and all patterns are loading, so I have to click on one of checkboxes to apply filtering.
Maybe returning to a filtered list can be simplified.

Also, how about selecting tags alter category amount indicators and vice versa, so each indicator shows a number of links you will actually see if toggle on corresponding category/tag?

**Comment by iluwatar** [comment]
Issue moved to https://github.com/iluwatar/java-design-patterns-web/issues/4
