### ISSUE TITLE
The web site should use https

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#766]
At the moment java-design-patterns.com uses http and browser gives nasty warning when trying to access the site. We should take into use https protocol to get rid of the warning.

**Comment by mobiuscog** [comment]
As you're hosted on AWS Cloudfront, you could either use the free SNI Custom SSL (https://aws.amazon.com/cloudfront/custom-ssl-domains/) or look to add a LetsEncrypt SSL certificate (https://letsencrypt.org/getting-started/)

**Comment by a894164233** [comment]
You can try.([https://certbot.eff.org/ ](https://certbot.eff.org/ )) It is easier.

**Comment by iluwatar** [comment]
https://medium.com/@itsmattburgess/hosting-a-https-website-using-aws-s3-and-cloudfront-ee6521df03b9

**Comment by iluwatar** [comment]
Implemented. The web site is now served using HTTPS. Try http://java-design-patterns.com, it will redirect to https://java-design-patterns.com.
