### ISSUE TITLE
Thread local storage pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#77]
https://en.wikipedia.org/wiki/Thread-local_storage

**Comment by thomasoss** [comment]
I would like to deal with this
Greetings Thomas

**Comment by iluwatar** [comment]
Yes, great @thomasoss, the issue is yours!

**Comment by thomasoss** [comment]
The coding is done and I also worked through the Checkstyle Pluging messages. But for using  "ObjectAid UML Explorer for Eclipse" the purchase of a license is obligatory. Is there another way to create the UMLs in the format you need?

**Comment by mrcrow85** [comment]
@thomasoss The license is only needed if you want to use the extra diagrams, the free version already has the class diagrams feature which is the diagram you need.

**Comment by thomasoss** [comment]
@mrcrow85 thank you. Worked.
Now the UML is created. Looking into the existing etc folders is see xyz.urm.puml-files too. Can ObjectAid create this file. I couldn't find out how.
In the readme.md there is a pumlid: Where does this come from?
Greetings Thomas

**Comment by iluwatar** [comment]
We are in the process of switching the tool used to create the UML diagrams. This is discussed in https://github.com/iluwatar/java-design-patterns/issues/190. If you want, you can try the steps proposed by @markusmo3 to generate the pumlid or optionally just leave the pumlid empty for now.

**Comment by thomasoss** [comment]
... ok - the tls.urm.puml was generated by the Maven build. Because my environment is configured for Gradle I had to do the Maven build in a second Eclipse project to which I copied the source code files. And I oversaw the puml created in the etc folder.

**Comment by thomasoss** [comment]
@iluwatar and @markusmo3 
creation of the pumlid worked fine with your instructions. Thank you
