### ISSUE TITLE
how can i config my eclipse ?

### ISSUE THREAD

**Issue by 15838028035** [iluwatar/java-design-patterns#771]
hi , i use eclipse ,   see it :

    Download Eclipse from https://eclipse.org/downloads/ Choose Eclipse IDE for Java Developers or Eclipse IDE for Java EE Developers
    Import the project File - Import - Existing Maven projects - point to the project root folder
    Configure Checkstyle plugin Window - Preferences - Checkstyle - New - External Configuration File -> Name it and point to checkstyle.xml -> Set as default
    Right click java-design-patterns project in Project Explorer and choose Checkstyle - Create formatter profile
    Activate formatter profile Window - Preferences - Java - Code style - Formatter - Active profile -> choose the one you just created -> Apply1
    You can run Checkstyle in Eclipse IDE by selecting the project(s) in package/project explorer, right-clicking the project and choosing Checkstyle - Check Code with Checkstyle

when i do this 
  Right click java-design-patterns project in Project Explorer and choose Checkstyle - Create formatter profile

failure , not alert any dialog for me to do next , could you help me ?

**Comment by iluwatar** [comment]
Sorry, I don't follow you. Can you send a screenshot what happens?

**Comment by harshsri2208** [comment]
@iluwatar you can follow the video in this link:
https://youtu.be/WIzzHeWukUU
