### ISSUE TITLE
Implement Retry pattern with exponential backoff 

### ISSUE THREAD

**Issue by awesomefei** [iluwatar/java-design-patterns#775]
In practice, we often retry with exponential backoff to avoid making traffic congestion/server load worse, would be nice to implement this option.

Also, I would like to implement this.

**Comment by iluwatar** [comment]
Yes, I agree. Go ahead @awesomefei

**Comment by AnaghaSasikumar** [comment]
Hi, is this done?

**Comment by AnaghaSasikumar** [comment]
Created pull request #797 in case it's still needed. I am new to open source, would really appreciate any feedback. I used this source to do it: https://cloud.google.com/storage/docs/exponential-backoff
