### ISSUE TITLE
Implement Iterator for Binary Search Tree

### ISSUE THREAD

**Issue by mitchellirvin** [iluwatar/java-design-patterns#778]
The current iterator implementation is only against a List. I think the beauty/power of an iterator is best exemplified in its implementation against more complex data structures. I'd like to implement an Iterator over a BST (for starters).

**Comment by mitchellirvin** [comment]
I've started work on this issue preemptively!

**Comment by iluwatar** [comment]
Ok @mitchellirvin

**Comment by npathai** [comment]
Great work @mitchellirvin. Closing this issue now.
