### ISSUE TITLE
ClassCastException was throwed in App.java#52

### ISSUE THREAD

**Issue by yushouling** [iluwatar/java-design-patterns#781]
The row that has an exception was:
hayes.accept(conUnix); // Hayes modem with Unix configurator

Because of ConfigureForUnixVisitor didn't implements HayesVisitor.

#java-design-patterns/acyclic-visitor

**Comment by npathai** [comment]
@iluwatar That is not a bug, it is expected to happen. I will change the log level and use `instanceof` instead to resolve the confusion.

**Comment by iluwatar** [comment]
Well done @npathai Thank you!
