### ISSUE TITLE
it would be nice to use docker build this project , could that support it ?

### ISSUE THREAD

**Issue by 15838028035** [iluwatar/java-design-patterns#789]
it would be nice to use docker build this project , could that support it ?

**Comment by 15838028035** [comment]
@bellingard

**Comment by iluwatar** [comment]
Yes, it would be quite easy to add that but the real question is why would one want to do that?

**Comment by 15838028035** [comment]
I think it is a good demo for developer   To learn docker !  Use docker ! 

发自我的 iPhone

**Comment by npathai** [comment]
IMHO I don't think there is any need for docker. We should not make this project kitchen sink for everything.

**Comment by npathai** [comment]
IMHO there is no need for docker.
