### ISSUE TITLE
module/output.txt & module/error.txt change on build

### ISSUE THREAD

**Issue by LyndonArmitage** [iluwatar/java-design-patterns#795]
First off great project here, thanks for spending time collating all this information! :+1: 

Something very minor I noticed when building the project locally with `mvn clean package` is that the files:

`module/output.txt` and `module/error.txt` end up being change to not include the MIT licence.

Perhaps they should be removed with `git rm` and then added to the ignore file as they are generated by tests? Or the [test](https://github.com/iluwatar/java-design-patterns/blob/master/module/src/test/java/com/iluwatar/module/FileLoggerModuleTest.java) should use a [temporary file](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempFile(java.nio.file.Path,%20java.lang.String,%20java.lang.String,%20java.nio.file.attribute.FileAttribute...))?

I've attached a diff for what it is worth: [diff.txt](https://github.com/iluwatar/java-design-patterns/files/2396099/diff.txt)

**Comment by iluwatar** [comment]
@LyndonArmitage thanks for the improvement suggestion. I think those files could be removed from git and added to `.gitignore`. I would be glad to accept pull request for this.

**Comment by LyndonArmitage** [comment]
See PR: #796
