### ISSUE TITLE
Recognize contributors

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#798]
We should follow this nice specification to recognize our contributors https://github.com/kentcdodds/all-contributors

**Comment by npathai** [comment]
We should implement this :+1: Great find.

**Comment by iluwatar** [comment]
@all-contributors please add @bernardosulzbach for code

**Comment by iluwatar** [comment]
@all-contributors please add @yusufaytas for code

**Comment by iluwatar** [comment]
@all-contributors please add @ankurkaushal for code

**Comment by iluwatar** [comment]
@all-contributors please add @pitsios-s for code

**Comment by iluwatar** [comment]
@all-contributors please add @llitfkitfk for content

**Comment by iluwatar** [comment]
@all-contributors please add @vehpsr for code

**Comment by iluwatar** [comment]
@all-contributors please add @mookkiah for code

**Comment by iluwatar** [comment]
@all-contributors please add @llorllale for code

**Comment by iluwatar** [comment]
@all-contributors please add @igeligel for code

**Comment by iluwatar** [comment]
@all-contributors please add @hbothra15 for code

**Comment by iluwatar** [comment]
@all-contributors please add @giorgosmav21 for code

**Comment by iluwatar** [comment]
@all-contributors please add @oconnelc for code

**Comment by iluwatar** [comment]
@all-contributors please add @npczwh for code

**Comment by iluwatar** [comment]
@all-contributors please add @leogtzr for code

**Comment by iluwatar** [comment]
@all-contributors please add @hannespernpeintner for code

**Comment by iluwatar** [comment]
@all-contributors please add @dgruntz for code

**Comment by iluwatar** [comment]
@all-contributors please add @christofferh for code

**Comment by iluwatar** [comment]
@all-contributors please add @AnaghaSasikumar for code

**Comment by iluwatar** [comment]
@all-contributors please add @waisuan for code

**Comment by iluwatar** [comment]
@all-contributors please add @perwramdemark for code

**Comment by iluwatar** [comment]
@all-contributors please add @leonmak for code

**Comment by iluwatar** [comment]
@all-contributors please add @kanwarpreet25 for code

**Comment by iluwatar** [comment]
@all-contributors please add @MSaifAsif for code

**Comment by iluwatar** [comment]
@all-contributors please add @Alwayswithme for code

**Comment by iluwatar** [comment]
@all-contributors please add @ranjeet-floyd for code

**Comment by iluwatar** [comment]
@all-contributors please add @mitchellirvin for code

**Comment by iluwatar** [comment]
@all-contributors please add @kirill-vlasov for code

**Comment by iluwatar** [comment]
@all-contributors please add @joningiwork for code

**Comment by iluwatar** [comment]
@all-contributors please add @jarpit96 for code

**Comment by iluwatar** [comment]
@all-contributors please add @hoangnam2261 for code

**Comment by iluwatar** [comment]
@all-contributors please add @fanofxiaofeng for code

**Comment by iluwatar** [comment]
@all-contributors please add @dmitraver for code

**Comment by iluwatar** [comment]
@all-contributors please add @besok for code

**Comment by iluwatar** [comment]
@all-contributors please add @baislsl for code

**Comment by iluwatar** [comment]
@all-contributors please add @akrystian for code

**Comment by iluwatar** [comment]
@all-contributors please add @Rzeposlaw for code

**Comment by iluwatar** [comment]
@all-contributors please add @LuigiCortese for code

**Comment by iluwatar** [comment]
@all-contributors please add @Juaanma for code

**Comment by iluwatar** [comment]
@all-contributors please add @7agustibm for code

**Comment by iluwatar** [comment]
@all-contributors please add @yosfik for code

**Comment by iluwatar** [comment]
@all-contributors please add @vanogrid for code

**Comment by iluwatar** [comment]
@all-contributors please add @valdar-hu for code

**Comment by iluwatar** [comment]
@all-contributors please add @staillebois for code

**Comment by iluwatar** [comment]
@all-contributors please add @sankypanhale for content

**Comment by iluwatar** [comment]
@all-contributors please add @prafful1 for content

**Comment by iluwatar** [comment]
@all-contributors please add @pnowy for code

**Comment by iluwatar** [comment]
@all-contributors please add @lbroman for code

**Comment by iluwatar** [comment]
@all-contributors please add @kaiwinter for code

**Comment by iluwatar** [comment]
@all-contributors please add @jjjimenez100 for code

**Comment by iluwatar** [comment]
@all-contributors please add @dzmitryh for code

**Comment by iluwatar** [comment]
@all-contributors please add @christophercolumbusdog for code

**Comment by iluwatar** [comment]
@all-contributors please add @anthonycampbell for code

**Comment by iluwatar** [comment]
@all-contributors please add @amogozov for code

**Comment by iluwatar** [comment]
@all-contributors please add @alexsomai for code

**Comment by iluwatar** [comment]
@all-contributors please add @MaVdbussche for code

**Comment by iluwatar** [comment]
@all-contributors please add @Harshrajsinh for code

**Comment by iluwatar** [comment]
@all-contributors please add @Deathnerd for code

**Comment by DavidCanlla** [comment]
Fuck off with the spam

**Comment by iluwatar** [comment]
@all-contributors please add @Anurag870 for code

**Comment by iluwatar** [comment]
@all-contributors please add @Amarnath510 for code

**Comment by iluwatar** [comment]
@all-contributors please add @trautonen for code

**Comment by iluwatar** [comment]
@all-contributors please add @yorlov for code

**Comment by iluwatar** [comment]
@all-contributors please add @varunu28 for code

**Comment by iluwatar** [comment]
@all-contributors please add @PalAditya for code

**Comment by iluwatar** [comment]
@all-contributors please add @grzesiekkedzior for code

**Comment by iluwatar** [comment]
@all-contributors please add @sivasubramanim for code

**Comment by iluwatar** [comment]
@all-contributors please add @d4gg4d for code

**Comment by iluwatar** [comment]
@all-contributors please add @vertti for code

**Comment by iluwatar** [comment]
@all-contributors please add @Bobo1239 for content

**Comment by iluwatar** [comment]
@all-contributors please add @Jahhein for content

**Comment by iluwatar** [comment]
@all-contributors please add @iamrichardjones for content

**Comment by iluwatar** [comment]
@all-contributors please add @rachelcarmena for content

**Comment by iluwatar** [comment]
@all-contributors please add @zd-zero for content

**Comment by iluwatar** [comment]
@all-contributors please add @webpro for content

**Comment by iluwatar** [comment]
@all-contributors please add @hbothra15 for design

**Comment by iluwatar** [comment]
I think I've now listed all the contributors to the system. Note that also contributions to these repositories affect this system and the web site https://java-design-patterns.com

**Comment by webpro** [comment]
Thank you, but when you start to recognize contributors I think it might be more appropriate to start the page at https://java-design-patterns.com/principles/ with a clear statement saying where this content is originally coming (cloned) from.

**Comment by iluwatar** [comment]
Thanks @webpro, it's a great suggestion, and I'll make that happen. There's already your name at the bottom of the page but I also think it's good to state the origins at the top too. I created a new issue about this https://github.com/iluwatar/programming-principles/issues/2

**Comment by iluwatar** [comment]
@all-contributors please add @MananS77 for review

**Comment by iluwatar** [comment]
@all-contributors please add @nishant- for code

**Comment by iluwatar** [comment]
@all-contributors please add @raja-peeyush-kumar-singh for code

**Comment by iluwatar** [comment]
@all-contributors please add @charlesfinley for review

**Comment by iluwatar** [comment]
@all-contributors please add @xdvrx1 for review

**Comment by iluwatar** [comment]
@all-contributors please add @xdvrx1 for ideas

**Comment by iluwatar** [comment]
@all-contributors please add @Ascenio for review

**Comment by iluwatar** [comment]
@all-contributors please add @eimanip for code

**Comment by iluwatar** [comment]
@all-contributors please add @grzesiekkedzior for review

**Comment by iluwatar** [comment]
@all-contributors please add @jeff303 for code

**Comment by iluwatar** [comment]
@all-contributors please add @byoungju94 for code

**Comment by iluwatar** [comment]
@all-contributors please add @JackieNim for code
