### ISSUE TITLE
Master-Worker pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#799]
https://docs.gigaspaces.com/sbp/master-worker-pattern.html

**Comment by AnaghaSasikumar** [comment]
So, are we looking to implement this using Gigaspace or w/o it? I've never used Gigaspace before, if it's the latter, I'd like to give this a shot.

**Comment by iluwatar** [comment]
No need for Gigaspace. Please go ahead @AnaghaSasikumar

**Comment by AnaghaSasikumar** [comment]
Created #816 pull request
