### ISSUE TITLE
Pipes And Filters (EIP)

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#82]
https://code.google.com/p/pipelinepattern/

**Comment by npathai** [comment]
It is an Enterprise Integration pattern also known as Pipes and Filters pattern. It is also documented in the book POSA 1 (Pattern Oriented Software Architecture) as an architectural pattern. A link to description of this pattern [Pipes and Filters - MSDN](https://msdn.microsoft.com/en-us/library/dn568100.aspx)

**Comment by npathai** [comment]
I am reading this pattern maybe I can submit an implementation to this. @iluwatar Are you working on it?

**Comment by iluwatar** [comment]
Ok, thanks for the analysis @npathai . This issue is then part of #93. I was thinking that Enterprise Integration Patterns might be implemented using Apache Camel. What do you think?

**Comment by npathai** [comment]
@iluwatar Yes there are two options either Apache Camel or Mule ESB.
Will we add dependency of Apache Camel? I have read source of Camel for personal project and we can create stripped down version of this particular pattern. I will just have to refer it again. What's your opinion on this?

**Comment by iluwatar** [comment]
My first choice for the pattern examples is self implemented source code. Sometimes this may not be reasonable though. Recently I was working on Naked Objects pattern and after a bit of research and talks with Mr. Dan Haywood I found out that basically Apache Isis is the pattern implementation. It does not make sense to implement a functionally identical framework yourself. The same discovery I made when I was implementing Repository pattern, I ended up using Spring Data for the example.

I think that implementing the Enterprise Integration Patterns is going to require a framework, either self made or then one of the readily available ones as you mentioned. Many of the patterns seem to build on the previous ones. I'm not an integration expert, but I think it would be huge effort to start implementing an enterprise integration framework from scratch. We would be spending far more time on the framework than on the examples. 

It is my understanding that most of the patterns have been implemented in Apache Camel and this is the most capable of the frameworks. So this is why I think we should add Apache Camel (my preference) as a dependency and using that prepare the examples.

**Comment by npathai** [comment]
@iluwatar  Fair enough. My vote is for Apache Camel as well. We should implement all possible EIPs in #93 using Apache Camel.

**Comment by iluwatar** [comment]
Ok, I will create the issues for the EIPs.

**Comment by iluwatar** [comment]
The pattern is commonly utilized in multimedia streaming frameworks such as DirectShow and GStreamer http://patterns-wg.fuka.info.waseda.ac.jp/SPAQU/proceedings2009/8-F3(P)-SPAQu_CameraReadyVerNew_Dajsuren_vdBrand.pdf

**Comment by iluwatar** [comment]
https://msdn.microsoft.com/en-us/library/dn568100.aspx

**Comment by iluwatar** [comment]
http://iteratrlearning.com/java/2016/12/26/pipes-and-filters-actors-akka-java.html

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/pipes-and-filters

**Comment by robertvolkmann** [comment]
@iluwatar still necessary after sunsetting the existing EIP patterns?

**Comment by iluwatar** [comment]
Thanks for noticing @robertvolkmann, I'll close this
