### ISSUE TITLE
SonarQube reports security issues

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#820]
SonarQube reports 9 critical level security issues.

https://sonarcloud.io/project/issues?id=com.iluwatar%3Ajava-design-patterns&resolved=false&severities=BLOCKER%2CCRITICAL&types=SECURITY_HOTSPOT

**Comment by trumvekhuya** [comment]
Can i take this @iluwatar ?

**Comment by npathai** [comment]
I was working on this, but @trumvekhuya you can go ahead with this :+1:

**Comment by trumvekhuya** [comment]
okay, thank @npathai
