### ISSUE TITLE
About the Builder Pattern - good first issue

### ISSUE THREAD

**Issue by jrxxjr** [iluwatar/java-design-patterns#822]
I made a new way to use the pattern builder, i want to commit, but i'm not allowed, i made the project fork. Please give permission for me ?

**Comment by iluwatar** [comment]
You should not try to commit directly into this repository. You create a fork repository and make changes there. When ready, you create a pull request from your fork into this repository.

**Comment by jrxxjr** [comment]
I created the pull request, but and now ?

**Comment by jrxxjr** [comment]
I have a question and a problem The classes I created do not give an error in my local build, nor in Travis, in the Build Builder Pattern section, which is where my change was.
Here's the error I found in Travis's output:
java.io.FileNotFoundException: /home/travis/build/iluwatar/java-design-patterns/naked-objects/dom/log4j.properties (No such file or directory)
Attached log of Travis build.
[log.txt](https://github.com/iluwatar/java-design-patterns/files/2601659/log.txt)

**Comment by jrxxjr** [comment]
Another question, can i only create new items in existing Design Patterns, or can i also make small improvements to existing source codes ?
