### ISSUE TITLE
Parallel Change pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#83]
http://martinfowler.com/bliki/ParallelChange.html

**Comment by l-cortese** [comment]
Uhm, this one seems to be more a "refactoring pattern" rather than a design pattern. I can't imagine a way to "code" this behaviour/pattern, what do you think?

**Comment by npathai** [comment]
Remote API development is the only case where it can be applied directly. But yes I agree with @l-cortese we don't need to implement this as a design pattern.

**Comment by iluwatar** [comment]
Agreed, this is not a design pattern.
