### ISSUE TITLE
Layers architectural pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#84]
https://en.wikipedia.org/wiki/Multilayered_architecture

**Comment by iluwatar** [comment]
https://hendryluk.wordpress.com/2009/08/17/software-development-fundamentals-part-2-layered-architecture/

http://www.methodsandtools.com/archive/onionsoftwarearchitecture.php

**Comment by npathai** [comment]
@iluwatar It is also described in Pattern Oriented Software Architecture Vol-1 book.

**Comment by iluwatar** [comment]
@npathai Thanks for the tip. Unfortunately I don't have that book (yet). Would you recommend the book series?

**Comment by npathai** [comment]
@iluwatar Here you go http://www.amazon.com/Pattern-Oriented-Software-Architecture-Volume-Patterns/dp/0471958697
It's a 5 volume book series. Worth the money.

**Comment by npathai** [comment]
@iluwatar I will review it once I am done with active PR.
