### ISSUE TITLE
Client-Server (Sockets) pattern

### ISSUE THREAD

**Issue by ranvirgraol** [iluwatar/java-design-patterns#841]
Client-Server communication over sockets is old concept. Plan to build something simple with either sockets or using GRPC.

**Comment by IAmPramod** [comment]
@ranvirgraol Can you elaborate a bit more on this?

**Comment by iluwatar** [comment]
https://en.wikipedia.org/wiki/Client%E2%80%93server_model

**Comment by ormalka12** [comment]
Hi, @iluwatar I would like to take this pattern. Thanks!

**Comment by iluwatar** [comment]
Ok @ormalka12

**Comment by iluwatar** [comment]
@ormalka12 still working on this?

**Comment by ormalka12** [comment]
No, sorry

בתאריך יום ב׳, 6 ביולי 2020, 19:27, מאת Ilkka Seppälä ‏<
notifications@github.com>:

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by iluwatar** [comment]
Under construction by @Mediocrity7

**Comment by iluwatar** [comment]
The task is free for taking again

**Comment by Ooi-YeeJing** [comment]
Can I work on this issue?

**Comment by iluwatar** [comment]
Sure, go ahead @Ooi-YeeJing

**Comment by JW-HUANG1111** [comment]
Can I work on this issue?

**Comment by iluwatar** [comment]
Yes, go ahead @JW-HUANG1111

**Comment by junnnnn777** [comment]
Can I work on this issue? Thanks

**Comment by JW-HUANG1111** [comment]
> Yes, go ahead @JW-HUANG1111

Sorry, sir, I may not have time for this issue, Maybe some others can take it.
