### ISSUE TITLE
Unnecesary return

### ISSUE THREAD

**Issue by lprone** [iluwatar/java-design-patterns#845]
https://github.com/iluwatar/java-design-patterns/blob/55c75799831716b6248ceefa1315881e7f90806b/spatial-partition/src/main/java/com/iluwatar/spatialpartition/QuadTree.java#L58

you can change this block
`
    if (!this.boundary.contains(p)) {
      return;
    } else {
`

to this other most clear:
`
    if (this.boundary.contains(p)) {
`

**Comment by markbolster12** [comment]
I don't really think this is an issue at all. This is a code style suggestion, and in my opinion, both are equally clear.

**Comment by iluwatar** [comment]
Yes, just create a pull request and we can improve the style.

**Comment by lprone** [comment]
Fixing issue #846

**Comment by kanwarpreet25** [comment]
Hi @iluwatar  
I can take this up

**Comment by iluwatar** [comment]
Ok @kanwarpreet25
