### ISSUE TITLE
static enum

### ISSUE THREAD

**Issue by lprone** [iluwatar/java-design-patterns#846]
https://github.com/iluwatar/java-design-patterns/blob/55c75799831716b6248ceefa1315881e7f90806b/facade/src/main/java/com/iluwatar/facade/DwarvenMineWorker.java#L89

Enums don't need to be defined as a static. Can change it to :
`
enum Action {
`

**Comment by markbolster12** [comment]
It might be best just to put a comment saying so if needed. It doesn't really matter if it's there or not. It actually might be clearer to have it.
[Java Reference on Enums](https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.9)

**Comment by iluwatar** [comment]
Well spotted @lprone. I will gladly accept a pull request that removes the unnecessary `static`.
