### ISSUE TITLE
Monostate pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#85]
http://www.objectmentor.com/resources/articles/SingletonAndMonostate.pdf
http://c2.com/cgi/wiki?MonostatePattern

**Comment by amit2103** [comment]
@iluwatar  Can I implement this ?

**Comment by npathai** [comment]
@amit2103 Sure go ahead. We welcome contribution. Go through the wiki once for developer information. If you do decide to pick it up then leave a comment I will change the labels. Awaiting response.

**Comment by amit2103** [comment]
@iluwatar  I will take this up..I will go through the wiki. I am taking this up. And hope to submit a pull request soon.

**Comment by amit2103** [comment]
Hi All, I have created a pull request please review.

**Comment by iluwatar** [comment]
Well done @amit2103
