### ISSUE TITLE
Twin project is failing because its tests.

### ISSUE THREAD

**Issue by alonsoir** [iluwatar/java-design-patterns#860]
$ mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.2", arch: "x86_64", family: "mac"

running mvn package...
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.iluwatar.twin.AppTest
09:49:46.774 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
09:49:46.778 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
09:49:46.778 [Thread-2] INFO com.iluwatar.twin.BallItem - move
09:49:47.033 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
09:49:47.033 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
09:49:47.033 [Thread-2] INFO com.iluwatar.twin.BallItem - move
09:49:47.284 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
09:49:47.284 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
09:49:47.284 [Thread-2] INFO com.iluwatar.twin.BallItem - move
09:49:47.524 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
09:49:48.279 [main] INFO com.iluwatar.twin.BallThread - Begin to resume BallThread
09:49:48.292 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
09:49:48.292 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
09:49:48.292 [Thread-2] INFO com.iluwatar.twin.BallItem - move
09:49:48.547 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
09:49:48.548 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
09:49:48.548 [Thread-2] INFO com.iluwatar.twin.BallItem - move
09:49:48.799 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
09:49:48.799 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
09:49:48.799 [Thread-2] INFO com.iluwatar.twin.BallItem - move
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.392 sec - in com.iluwatar.twin.AppTest
Running com.iluwatar.twin.BallItemTest
09:49:49.250 [main] INFO com.iluwatar.twin.BallItem - move
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
09:49:49.257 [main] INFO com.iluwatar.twin.GameItem - draw
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
09:49:49.257 [main] INFO com.iluwatar.twin.BallItem - doDraw
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.204 sec - in com.iluwatar.twin.BallItemTest
Running com.iluwatar.twin.BallThreadTest
09:49:49.285 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
09:49:50.288 [main] INFO com.iluwatar.twin.BallThread - Begin to resume BallThread
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.045 sec <<< FAILURE! - in com.iluwatar.twin.BallThreadTest
testResume()  Time elapsed: 1.021 sec  <<< ERROR!
java.lang.VerifyError: (class: org/mockito/internal/verification/VerificationOverTimeImpl, method: verify signature: (Lorg/mockito/internal/verification/api/VerificationData;)V) Incompatible argument to function
        at com.iluwatar.twin.BallThreadTest.lambda$testResume$1(BallThreadTest.java:91)
        at com.iluwatar.twin.BallThreadTest.testResume(BallThreadTest.java:77)

testSuspend()  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.VerifyError: (class: org/mockito/internal/verification/VerificationOverTimeImpl, method: verify signature: (Lorg/mockito/internal/verification/api/VerificationData;)V) Incompatible argument to function
        at com.iluwatar.twin.BallThreadTest.lambda$testSuspend$0(BallThreadTest.java:59)
        at com.iluwatar.twin.BallThreadTest.testSuspend(BallThreadTest.java:51)

Results :

Tests in error: 
  BallThreadTest.testResume:77->lambda$testResume$1:91 » Verify (class: org/mock...
  BallThreadTest.testSuspend:51->lambda$testSuspend$0:59 » Verify (class: org/mo...

Tests run: 7, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.830 s
[INFO] Finished at: 2019-02-19T09:49:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project twin: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/aironman/IdeaProjects/java-design-patterns/twin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
MacBook-Pro-Retina-de-Alonso:twin aironman$

**Comment by id4us** [comment]
I see the same issue and seems to be caused by Mockito ```timeout(2000).atLeastOnce()``` . It is highly likely that mockito verify has a bug method  with Junit5. 
I am happy to fix the tests.

**Comment by medkhelifi** [comment]
Is this issue still open?

**Comment by alonsoir** [comment]
Yes, it is working. Thank you guys.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.iluwatar.twin.AppTest
23:53:00.101 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
23:53:00.104 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
23:53:00.104 [Thread-2] INFO com.iluwatar.twin.BallItem - move
23:53:00.356 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
23:53:00.356 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
23:53:00.356 [Thread-2] INFO com.iluwatar.twin.BallItem - move
23:53:00.606 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
23:53:00.606 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
23:53:00.606 [Thread-2] INFO com.iluwatar.twin.BallItem - move
23:53:00.853 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
23:53:01.608 [main] INFO com.iluwatar.twin.BallThread - Begin to resume BallThread
23:53:01.620 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
23:53:01.621 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
23:53:01.621 [Thread-2] INFO com.iluwatar.twin.BallItem - move
23:53:01.872 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
23:53:01.873 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
23:53:01.873 [Thread-2] INFO com.iluwatar.twin.BallItem - move
23:53:02.123 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
23:53:02.124 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
23:53:02.124 [Thread-2] INFO com.iluwatar.twin.BallItem - move
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.415 sec - in com.iluwatar.twin.AppTest
Running com.iluwatar.twin.BallItemTest
23:53:02.609 [main] INFO com.iluwatar.twin.BallItem - move
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
23:53:02.617 [main] INFO com.iluwatar.twin.GameItem - draw
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
23:53:02.617 [main] INFO com.iluwatar.twin.BallItem - doDraw
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.233 sec - in com.iluwatar.twin.BallItemTest
Running com.iluwatar.twin.BallThreadTest
23:53:02.643 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
23:53:03.645 [main] INFO com.iluwatar.twin.BallThread - Begin to resume BallThread
23:53:04.117 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.563 sec - in com.iluwatar.twin.BallThreadTest

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.366 s
[INFO] Finished at: 2019-07-29T23:53:05+02:00
[INFO] ------------------------------------------------------------------------
aironman@MacBook-Pro-Retina-de-Alonso ~/j/twin>
