### ISSUE TITLE
Didn't get the point

### ISSUE THREAD

**Issue by abdesamie** [iluwatar/java-design-patterns#861]
I don't understand the utility of this pattern, please could you give a real world example, as i see it just simple CRUD in-memory operations? Where the performance improvements is ?

**Comment by iluwatar** [comment]
Which pattern are you talking about?

**Comment by abdesamie** [comment]
Ah sorry i thought i posted it in the correct repo, anyway : 
I talked about DATA-TRANSFER-OBJECT design pattern, from the example i could not deduce what the problem to be resolved and how
https://github.com/iluwatar/java-design-patterns/tree/master/data-transfer-object

**Comment by iluwatar** [comment]
DTOs are used to decrease the amount of (possibly expensive) calls to the data provider interface. The client needs to do only single call and is provided with an aggregate object containing the data.

I agree that the example may be a bit simplistic with only single API and single customer data type.

**Comment by abdesamie** [comment]
Thanks for clarification
