### ISSUE TITLE
Add Role pattern

### ISSUE THREAD

**Issue by gavenkoa** [iluwatar/java-design-patterns#862]
https://hillside.net/plop/plop97/Proceedings/riehle.pdf
http://wiki.c2.com/?RoleObject

**Comment by JimMinor** [comment]
Anyone is working on this?

**Comment by iluwatar** [comment]
No, it's free for taking. Assigned to you @JimMinor now.

**Comment by alvigar** [comment]
I would like to do this

**Comment by iluwatar** [comment]
@JimMinor are you working on it?

**Comment by JimMinor** [comment]
@iluwatar Not yet, i only studied the docs. I can leave it to @alvigar.

**Comment by iluwatar** [comment]
@alvigar it's yours now, please go ahead!

**Comment by iluwatar** [comment]
The task is free to take again

**Comment by besok** [comment]
I can take it if nobody minds.

**Comment by iluwatar** [comment]
Thanks @besok go ahead
