### ISSUE TITLE
Strangler pattern

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#870]
Incrementally migrate a legacy system by gradually replacing specific pieces of functionality with new applications and services. As features from the legacy system are replaced, the new system eventually replaces all of the old system's features, strangling the old system and allowing you to decommission it.

https://docs.microsoft.com/en-us/azure/architecture/patterns/strangler

**Comment by ZhouSky** [comment]
Hi, I'd like try to write a simple demo for this pattern.

**Comment by iluwatar** [comment]
Yes @ZhouSky go ahead

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/strangler
