### ISSUE TITLE
Sidecar pattern

### ISSUE THREAD

**Issue by npathai** [iluwatar/java-design-patterns#871]
Deploy components of an application into a separate process or container to provide isolation and encapsulation. This pattern can also enable applications to be composed of heterogeneous components and technologies.

This pattern is named Sidecar because it resembles a sidecar attached to a motorcycle. In the pattern, the sidecar is attached to a parent application and provides supporting features for the application. The sidecar also shares the same lifecycle as the parent application, being created and retired alongside the parent. The sidecar pattern is sometimes referred to as the sidekick pattern and is a decomposition pattern.

https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar

**Comment by lilangelrey99** [comment]
Really?

**Comment by ormalka12** [comment]
Hi, @npathai  I would like to take this pattern. Thanks!

**Comment by iluwatar** [comment]
Yes, go ahead @ormalka12

**Comment by iluwatar** [comment]
@ormalka12 still working on this?

**Comment by ormalka12** [comment]
I sorry no:(

בתאריך יום א׳, 31 במאי 2020, 11:25, מאת Ilkka Seppälä ‏<
notifications@github.com>:

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by iluwatar** [comment]
https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar

**Comment by igroeg** [comment]
I guess this pattern is rather more of a docker/k8s configuration than java code. Am I wrong?

**Comment by ohbus** [comment]
> I guess this pattern is rather more of a docker/k8s configuration than java code. Am I wrong?

@iluwatar and the _mailing list members_ What are your thoughts on this?

**Comment by iluwatar** [comment]
It's a cloud pattern so I would like to see it implemented using AWS or some other cloud platform like here: https://github.com/iluwatar/java-design-patterns/tree/master/cloud-static-content-hosting. The sidecar could be a Docker container running alongside the information system. The platform to demonstrate this could be EC2 instance running Docker containers, ECS, EKS etc.

@ohbus sorry I didn't get what you mean by mailing list members..?

**Comment by ohbus** [comment]
> @ohbus sorry I didn't get what you mean by mailing list members..?

Sorry, might have been a typo while copy pasting in a hurry.
