### ISSUE TITLE
org.slf4j.Logger unresolved import

### ISSUE THREAD

**Issue by spaniard96** [iluwatar/java-design-patterns#874]
In **com.iluwatar.adapter.FishingBoat.java** the follwing imports are unresolved:
* `import org.slf4j.Logger;`
* `import org.slf4j.LoggerFactory;`

**Comment by swathisprasad** [comment]
Hi, I checked this file and I see no problem with the imports. Am I missing something here?

**Comment by id4us** [comment]
@spaniard96 , I dont see the problem either.

**Comment by iluwatar** [comment]
Closing the issue, since there seems to be no problem with the import
