### ISSUE TITLE
AppTest for dependency-injection returns WARNINGs

### ISSUE THREAD

**Issue by tomaszwojciechowski** [iluwatar/java-design-patterns#876]
Is it wanted result?

`15:04:12.785 [main] INFO com.iluwatar.dependency.injection.Tobacco - AdvancedSorceress smoking SecondBreakfastTobacco
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/C:/Users/User/.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
15:04:13.136 [main] INFO com.iluwatar.dependency.injection.Tobacco - GuiceWizard smoking Rivendell`

**Comment by abhi52** [comment]
Not able to reproduce this. There was no warning for me in this test class.

**Comment by iluwatar** [comment]
Not able to reproduce either. Closing this issue.
