### ISSUE TITLE
Dirty Flag pattern Issue

### ISSUE THREAD

**Issue by sajankumarma** [iluwatar/java-design-patterns#883]
https://github.com/iluwatar/java-design-patterns/blob/fedc2d9e47cb2b44aa4ea23aed9d117bbd4ed069/dirty-flag/src/main/java/com/iluwatar/dirtyflag/App.java#L60

Creating object of World class inside Thread's Run method doesn't make sense, as every time it is creating new object and reading the file. It should be outside this thread's run method.

for now it is like this
    executorService.scheduleAtFixedRate(new Runnable() {
      @Override
      public void run() {
      World world = new World();
        List<String> countries = world.fetch();

but it should be like this
    executorService.scheduleAtFixedRate(new Runnable() {
      World world = new World();
      @Override
      public void run() {
        List<String> countries = world.fetch();

**Comment by ranjeet-floyd** [comment]
@iluwatar  I want take this.  Thanks

**Comment by iluwatar** [comment]
Ok @ranjeet-floyd

**Comment by Rocangus** [comment]
Is this fixed already?

**Comment by OAkala** [comment]
Is this issue already resloved?
