### ISSUE TITLE
Factory Method

### ISSUE THREAD

**Issue by 1170200227** [iluwatar/java-design-patterns#893]
The class ElfBlacksmith and OrcBlacksmith implements the interface Blacksmith in the factory method. They complete the method manufactureWeapon. But we can modify this method with static. So we don't generate too much memory when we call factory method.

**Comment by 1171430615** [comment]
> The class ElfBlacksmith and OrcBlacksmith implements the interface Blacksmith in the factory method. They complete the method manufactureWeapon. But we can modify this method with static. So we don't generate too much memory when we call factory method.

This improvement is somewhat similar to the singleton pattern

**Comment by Azureyjt** [comment]
@iluwatar May I pick this up?

**Comment by hbothra15** [comment]
I would like to take this up

**Comment by iluwatar** [comment]
Ok @hbothra15

**Comment by hbothra15** [comment]
hi @1170200227,
Just wanted to confirm are you looking to see somthing as below
`  private static Map<WeaponType, OrcWeapon> weaponProtoType = new HashMap<>(WeaponType.values().length);
  {
    for (WeaponType type : WeaponType.values()) {
      weaponProtoType.put(type, new OrcWeapon(type));
    }
  }
  @Override
  public Weapon manufactureWeapon(WeaponType weaponType) {
    return weaponProtoType.get(weaponType);
  }`

**Comment by hbothra15** [comment]
Hi @1171430615 
Any feedback on above comment
