### ISSUE TITLE
Question About Interpreter Pattern

### ISSUE THREAD

**Issue by guozix** [iluwatar/java-design-patterns#894]
I have examined the code in Interpreter pattern. This example parse the specified string and output the expected computing result. But I don't really get the meaning of using this pattern in soving this problem. I have known that interpreter pattern can be used to parse expression. So can you provide another clearer example for demonstrating the purpose of this pattern?

**Comment by 1171430615** [comment]
This pattern is particularly cumbersome when used with regular expressions

**Comment by sophonie** [comment]
Hi,

Watch this youtube video, this is a good example to understand Interpreter Design Pattern
[](https://www.youtube.com/watch?v=6CVymSJQuJE)
