### ISSUE TITLE
typo in FYI comment at "java-design-pattern/acyclic-visitor"

### ISSUE THREAD

**Issue by lebel-louisjacob** [iluwatar/java-design-patterns#895]
From here:
https://github.com/iluwatar/java-design-patterns/blob/fedc2d9e47cb2b44aa4ea23aed9d117bbd4ed069/acyclic-visitor/src/main/java/com/iluwatar/acyclicvisitor/App.java#L50

The comment should be:
```text
// Hayes modem with Dos configurator 
```

**Comment by saksham93** [comment]
I am working on this issue.

**Comment by iluwatar** [comment]
Ok @saksham93

**Comment by saksham93** [comment]
Pull Request raised
