### ISSUE TITLE
Code is not justifiable with the example statement (Factory Pattern)

### ISSUE THREAD

**Issue by foxt7ot** [iluwatar/java-design-patterns#900]
As stated in an example 

> Blacksmith manufactures weapons. Elves require Elvish weapons and orcs require Orcish weapons. Depending on the customer at hand the right type of blacksmith is summoned.

So my understanding is this that there will be only one Blacksmith who will cater the requirement of both Orcs and Elves but the code specified in the example tells me different story by looking at the code I am understanding that there are 2 different Blacksmith who have expertise in their area, I mean ElvisBlacksmith knows how to create elves weapon and OrcBlacksmith in orc weapon.

**Comment by iluwatar** [comment]
> Depending on the customer at hand the right type of blacksmith is summoned.

In my opinion this is self-explanatory. If the orcs need weapons OrcBlacksmith is created. If the elves need weapons ElfBlacksmith is created. These are two different instances of Blacksmith interface.

**Comment by hbothra15** [comment]
Hi @foxt7ot 
As mentioned in 2nd line i.e
`Depending on the customer at hand the right type of blacksmith is summoned`
We will have two blacksmith.
If it helps you can imagine we have a small Factory/Shop where we have this two blacksmith working and as per requirement we give job to the respective Blacksmith.

I hope that helps.
