### ISSUE TITLE
Web site update failing

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#912]
See log https://travis-ci.org/iluwatar/java-design-patterns/builds/564609653

The problem seems to be related to s3_website and Java version

**Comment by ptrax** [comment]
I made a PR to take care of the Java issue, but a bunch of other errors came up with SSL errors in the HTML-Proofer and "Access key can't be null" errors in the s3_website push. I'll have to look into that.

**Comment by iluwatar** [comment]
There's more information about the web site update at https://github.com/iluwatar/java-design-patterns/wiki/07.-Working-with-the-web-site

**Comment by iluwatar** [comment]
@ptrax I merged the PR and it seems that the web site update system now works. See https://java-design-patterns.com it has the deployed commit information on the bottom of the screen. The access keys you mentioned are defined in the `secure` fields of [.travis.yml](https://github.com/iluwatar/java-design-patterns/blob/gh-pages/.travis.yml)

**Comment by ptrax** [comment]
Thanks @iluwatar, I had just realized a few minutes ago that the access tokens weren't working since the PR came from my fork which didn't have access to those secure environment variables. Figured a post-merge build would work!

**Comment by iluwatar** [comment]
Well done for fixing this, much appreciated @ptrax :+1:
