### ISSUE TITLE
async-method-invocation tests are failing

### ISSUE THREAD

**Issue by alonsoir** [iluwatar/java-design-patterns#914]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.iluwatar.async.method.invocation.AppTest
00:02:43.640 [executor-2] INFO com.iluwatar.async.method.invocation.App - Task completed with: test
00:02:43.686 [main] INFO com.iluwatar.async.method.invocation.App - Some hard work done
00:02:43.736 [executor-4] INFO com.iluwatar.async.method.invocation.App - Task completed with: 20
00:02:43.736 [executor-4] INFO com.iluwatar.async.method.invocation.App - Callback result 4: 20
00:02:43.837 [executor-1] INFO com.iluwatar.async.method.invocation.App - Task completed with: 10
00:02:43.937 [executor-5] INFO com.iluwatar.async.method.invocation.App - Task completed with: callback
00:02:43.937 [executor-5] INFO com.iluwatar.async.method.invocation.App - Callback result 5: callback
00:02:44.036 [executor-3] INFO com.iluwatar.async.method.invocation.App - Task completed with: 50
00:02:44.037 [main] INFO com.iluwatar.async.method.invocation.App - Result 1: 10
00:02:44.037 [main] INFO com.iluwatar.async.method.invocation.App - Result 2: test
00:02:44.037 [main] INFO com.iluwatar.async.method.invocation.App - Result 3: 50
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.841 sec - in com.iluwatar.async.method.invocation.AppTest
Running com.iluwatar.async.method.invocation.ThreadAsyncExecutorTest
Tests run: 8, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.763 sec <<< FAILURE! - in com.iluwatar.async.method.invocation.ThreadAsyncExecutorTest
testLongRunningTaskWithCallback()  Time elapsed: 0.224 sec  <<< ERROR!
java.lang.VerifyError: (class: org/mockito/internal/verification/VerificationOverTimeImpl, method: verify signature: (Lorg/mockito/internal/verification/api/VerificationData;)V) Incompatible argument to function
	at com.iluwatar.async.method.invocation.ThreadAsyncExecutorTest.lambda$testLongRunningTaskWithCallback$5(ThreadAsyncExecutorTest.java:191)
	at com.iluwatar.async.method.invocation.ThreadAsyncExecutorTest.testLongRunningTaskWithCallback(ThreadAsyncExecutorTest.java:165)

testLongRunningTaskWithoutCallback()  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.VerifyError: (class: org/mockito/internal/verification/VerificationOverTimeImpl, method: verify signature: (Lorg/mockito/internal/verification/api/VerificationData;)V) Incompatible argument to function
	at com.iluwatar.async.method.invocation.ThreadAsyncExecutorTest.lambda$testLongRunningTaskWithoutCallback$3(ThreadAsyncExecutorTest.java:147)
	at com.iluwatar.async.method.invocation.ThreadAsyncExecutorTest.testLongRunningTaskWithoutCallback(ThreadAsyncExecutorTest.java:124)

Results :

Tests in error: 
  ThreadAsyncExecutorTest.testLongRunningTaskWithCallback:165->lambda$testLongRunningTaskWithCallback$5:191 » Verify
  ThreadAsyncExecutorTest.testLongRunningTaskWithoutCallback:124->lambda$testLongRunningTaskWithoutCallback$3:147 » Verify

Tests run: 9, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for java-design-patterns 1.21.0-SNAPSHOT:
[INFO] 
[INFO] java-design-patterns ............................... SUCCESS [  1.674 s]
[INFO] abstract-factory ................................... SUCCESS [ 10.028 s]
[INFO] tls ................................................ SUCCESS [  7.628 s]
[INFO] builder ............................................ SUCCESS [  7.323 s]
[INFO] factory-method ..................................... SUCCESS [  7.309 s]
[INFO] prototype .......................................... SUCCESS [  7.963 s]
[INFO] singleton .......................................... SUCCESS [  7.832 s]
[INFO] adapter ............................................ SUCCESS [  7.234 s]
[INFO] bridge ............................................. SUCCESS [  7.415 s]
[INFO] composite .......................................... SUCCESS [  7.087 s]
[INFO] dao ................................................ SUCCESS [  8.823 s]
[INFO] data-mapper ........................................ SUCCESS [  7.149 s]
[INFO] decorator .......................................... SUCCESS [  7.123 s]
[INFO] facade ............................................. SUCCESS [  7.108 s]
[INFO] flyweight .......................................... SUCCESS [  7.341 s]
[INFO] proxy .............................................. SUCCESS [  7.335 s]
[INFO] chain .............................................. SUCCESS [  7.168 s]
[INFO] command ............................................ SUCCESS [  7.380 s]
[INFO] interpreter ........................................ SUCCESS [  8.480 s]
[INFO] iterator ........................................... SUCCESS [  7.478 s]
[INFO] mediator ........................................... SUCCESS [  7.762 s]
[INFO] memento ............................................ SUCCESS [  6.841 s]
[INFO] model-view-presenter ............................... SUCCESS [ 13.041 s]
[INFO] observer ........................................... SUCCESS [ 10.902 s]
[INFO] state .............................................. SUCCESS [  7.015 s]
[INFO] strategy ........................................... SUCCESS [  7.300 s]
[INFO] template-method .................................... SUCCESS [  7.402 s]
[INFO] visitor ............................................ SUCCESS [  8.021 s]
[INFO] double-checked-locking ............................. SUCCESS [ 12.127 s]
[INFO] servant ............................................ SUCCESS [  7.394 s]
[INFO] service-locator .................................... SUCCESS [  7.185 s]
[INFO] null-object ........................................ SUCCESS [  6.963 s]
[INFO] event-aggregator ................................... SUCCESS [  8.199 s]
[INFO] callback ........................................... SUCCESS [  7.012 s]
[INFO] execute-around ..................................... SUCCESS [  6.784 s]
[INFO] property ........................................... SUCCESS [  6.920 s]
[INFO] intercepting-filter ................................ SUCCESS [ 12.587 s]
[INFO] producer-consumer .................................. SUCCESS [ 19.376 s]
[INFO] poison-pill ........................................ SUCCESS [  7.964 s]
[INFO] reader-writer-lock ................................. SUCCESS [ 16.811 s]
[INFO] lazy-loading ....................................... SUCCESS [ 13.190 s]
[INFO] service-layer ...................................... SUCCESS [ 16.222 s]
[INFO] specification ...................................... SUCCESS [  8.222 s]
[INFO] tolerant-reader .................................... SUCCESS [  7.107 s]
[INFO] model-view-controller .............................. SUCCESS [  7.451 s]
[INFO] flux ............................................... SUCCESS [  8.489 s]
[INFO] double-dispatch .................................... SUCCESS [  7.843 s]
[INFO] multiton ........................................... SUCCESS [  6.956 s]
[INFO] resource-acquisition-is-initialization ............. SUCCESS [  6.857 s]
[INFO] thread-pool ........................................ SUCCESS [ 11.574 s]
[INFO] twin ............................................... SUCCESS [ 11.549 s]
[INFO] private-class-data ................................. SUCCESS [  7.086 s]
[INFO] object-pool ........................................ SUCCESS [ 12.919 s]
[INFO] dependency-injection ............................... SUCCESS [  8.177 s]
[INFO] naked-objects ...................................... SUCCESS [  0.138 s]
[INFO] naked-objects-dom .................................. SUCCESS [  7.539 s]
[INFO] naked-objects-fixture .............................. SUCCESS [  0.402 s]
[INFO] naked-objects-integtests ........................... SUCCESS [ 11.590 s]
[INFO] naked-objects-webapp ............................... SUCCESS [  0.818 s]
[INFO] front-controller ................................... SUCCESS [  7.929 s]
[INFO] repository ......................................... SUCCESS [ 16.328 s]
[INFO] async-method-invocation ............................ FAILURE [  9.781 s]
[INFO] monostate .......................................... SKIPPED
[INFO] step-builder ....................................... SKIPPED
[INFO] business-delegate .................................. SKIPPED
[INFO] half-sync-half-async ............................... SKIPPED
[INFO] layers ............................................. SKIPPED
[INFO] eip-message-channel ................................ SKIPPED
[INFO] fluentinterface .................................... SKIPPED
[INFO] reactor ............................................ SKIPPED
[INFO] caching ............................................ SKIPPED
[INFO] eip-publish-subscribe .............................. SKIPPED
[INFO] delegation ......................................... SKIPPED
[INFO] event-driven-architecture .......................... SKIPPED
[INFO] api-gateway ........................................ SKIPPED
[INFO] image-microservice ................................. SKIPPED
[INFO] price-microservice ................................. SKIPPED
[INFO] api-gateway-service ................................ SKIPPED
[INFO] factory-kit ........................................ SKIPPED
[INFO] feature-toggle ..................................... SKIPPED
[INFO] value-object ....................................... SKIPPED
[INFO] module ............................................. SKIPPED
[INFO] monad .............................................. SKIPPED
[INFO] mute-idiom ......................................... SKIPPED
[INFO] mutex .............................................. SKIPPED
[INFO] semaphore .......................................... SKIPPED
[INFO] hexagonal .......................................... SKIPPED
[INFO] abstract-document .................................. SKIPPED
[INFO] aggregator-microservices ........................... SKIPPED
[INFO] information-microservice ........................... SKIPPED
[INFO] aggregator-service ................................. SKIPPED
[INFO] inventory-microservice ............................. SKIPPED
[INFO] promise ............................................ SKIPPED
[INFO] page-object ........................................ SKIPPED
[INFO] sample-application ................................. SKIPPED
[INFO] test-automation .................................... SKIPPED
[INFO] event-asynchronous ................................. SKIPPED
[INFO] event-queue ........................................ SKIPPED
[INFO] queue-load-leveling ................................ SKIPPED
[INFO] object-mother ...................................... SKIPPED
[INFO] data-bus ........................................... SKIPPED
[INFO] converter .......................................... SKIPPED
[INFO] guarded-suspension ................................. SKIPPED
[INFO] balking ............................................ SKIPPED
[INFO] extension-objects .................................. SKIPPED
[INFO] marker ............................................. SKIPPED
[INFO] cqrs ............................................... SKIPPED
[INFO] event-sourcing ..................................... SKIPPED
[INFO] data-transfer-object ............................... SKIPPED
[INFO] throttling ......................................... SKIPPED
[INFO] unit-of-work ....................................... SKIPPED
[INFO] partial-response ................................... SKIPPED
[INFO] eip-wire-tap ....................................... SKIPPED
[INFO] eip-splitter ....................................... SKIPPED
[INFO] eip-aggregator ..................................... SKIPPED
[INFO] retry .............................................. SKIPPED
[INFO] dirty-flag ......................................... SKIPPED
[INFO] trampoline ......................................... SKIPPED
[INFO] serverless ......................................... SKIPPED
[INFO] ambassador ......................................... SKIPPED
[INFO] acyclic-visitor .................................... SKIPPED
[INFO] collection-pipeline ................................ SKIPPED
[INFO] master-worker-pattern .............................. SKIPPED
[INFO] spatial-partition .................................. SKIPPED
[INFO] commander .......................................... SKIPPED
[INFO] typeobjectpattern .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:43 min
[INFO] Finished at: 2019-07-30T00:02:46+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project async-method-invocation: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/aironman/java-design-patterns/async-method-invocation/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :async-method-invocation

**Comment by iluwatar** [comment]
Could not reproduce, but that doesn't mean it's not broken

**Comment by snehalatapandit** [comment]
Hi,
Verified the issue. The issue seems to be similar to IssueID #860. However, the issue is not reproducible,
