### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#915]
The html-proofer that is included in Travis build indicates that we have some broken links.

```shell
Running ["HtmlCheck", "ImageCheck", "ScriptCheck", "LinkCheck"] on ["./_site/"] on *.html... 
Checking 391 external links...
Ran on 133 files!
- ./_site/patterns/acyclic-visitor/index.html
  *  internally linking to ../visitor/README.md, which does not exist (line 1)
- ./_site/patterns/half-sync-half-async/index.html
  *  External link http://www.cs.wustl.edu/~schmidt/PDF/PLoP-95.pdf failed: 404 No error
- ./_site/patterns/intercepting-filter/index.html
  *  External link http://www.javagyan.com/tutorials/corej2eepatterns/presentation-tier-patterns failed: 403 No error
  *  External link https://struts.apache.org/docs/interceptors.html failed: 404 No error
htmlproofer 3.0.6 | Error:  HTML-Proofer found 4 failures!
The command "bash cibuild.sh" exited with 1.
```

See full log at https://travis-ci.org/iluwatar/java-design-patterns/builds/565304449

**Comment by kpatrzek** [comment]
Hi @iluwatar 
I try to reproduce the bug but I can't. Somebody fix it ? please.
Best regards.

**Comment by snehalatapandit** [comment]
@iluwatar , 
Hi, can I look at this change?

**Comment by iluwatar** [comment]
Yes @snehalatapandit

**Comment by hbothra15** [comment]
Hi @iluwatar, it seems this is again failing for different link
https://travis-ci.org/iluwatar/java-design-patterns/builds/583292258
In https://github.com/iluwatar/java-design-patterns/tree/master/partial-response credit section we are providing link for Partial Response in RESTful API Design and its respective URL is no more active and gives Page Not found error, hence Automagic is also failing

Do let me know if I can take this up ?

**Comment by iluwatar** [comment]
Please go ahead @hbothra15

**Comment by hbothra15** [comment]
Done, and created a PR for the same
