### ISSUE TITLE
Tests failing in Twin module.

### ISSUE THREAD

**Issue by snehalatapandit** [iluwatar/java-design-patterns#922]
----------------------
 T E S T S
-------------------------------------------------------
Running com.iluwatar.twin.AppTest
15:50:58.934 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
15:50:58.939 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
15:50:58.939 [Thread-2] INFO com.iluwatar.twin.BallItem - move
15:50:59.189 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
15:50:59.189 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
15:50:59.189 [Thread-2] INFO com.iluwatar.twin.BallItem - move
15:50:59.439 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
15:50:59.439 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
15:50:59.439 [Thread-2] INFO com.iluwatar.twin.BallItem - move
15:50:59.680 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
15:51:00.431 [main] INFO com.iluwatar.twin.BallThread - Begin to resume BallThread
15:51:00.440 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
15:51:00.440 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
15:51:00.440 [Thread-2] INFO com.iluwatar.twin.BallItem - move
15:51:00.690 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
15:51:00.690 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
15:51:00.690 [Thread-2] INFO com.iluwatar.twin.BallItem - move
15:51:00.941 [Thread-2] INFO com.iluwatar.twin.GameItem - draw
15:51:00.941 [Thread-2] INFO com.iluwatar.twin.BallItem - doDraw
15:51:00.941 [Thread-2] INFO com.iluwatar.twin.BallItem - move
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.487 sec - in com.iluwatar.twin.AppTest
Running com.iluwatar.twin.BallItemTest
15:51:01.504 [main] INFO com.iluwatar.twin.BallItem - move
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
15:51:01.515 [main] INFO com.iluwatar.twin.GameItem - draw
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
15:51:01.515 [main] INFO com.iluwatar.twin.BallItem - doDraw
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.294 sec - in com.iluwatar.twin.BallItemTest
Running com.iluwatar.twin.BallThreadTest
15:51:01.553 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
LOGBACK: No context given for com.iluwatar.twin.BallItemTest$InMemoryAppender[null]
15:51:02.555 [main] INFO com.iluwatar.twin.BallThread - Begin to resume BallThread
15:51:02.981 [main] INFO com.iluwatar.twin.BallThread - Begin to suspend BallThread
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.505 sec <<< FAILURE! - in com.iluwatar.twin.BallThreadTest
testResume()  Time elapsed: 1.228 sec  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked:

Wanted but not invoked:
ballItem.draw();
-> at com.iluwatar.twin.BallThreadTest.lambda$testResume$1(BallThreadTest.java:88)
Actually, there were zero interactions with this mock.

        at com.iluwatar.twin.BallThreadTest.lambda$testResume$1(BallThreadTest.java:88)
        at com.iluwatar.twin.BallThreadTest.testResume(BallThreadTest.java:73)

Results :

Failed tests:
  BallThreadTest.testResume:73->lambda$testResume$1:88
Wanted but not invoked:
ballItem.draw();
-> at com.iluwatar.twin.BallThreadTest.lambda$testResume$1(BallThreadTest.java:88)
Actually, there were zero interactions with this mock.

Tests run: 7, Failures: 1, Errors: 0, Skipped: 0

**Comment by iluwatar** [comment]
Could not reproduce
