### ISSUE TITLE
Need to update doc/code for adapter pattern

### ISSUE THREAD

**Issue by hbothra15** [iluwatar/java-design-patterns#925]
As mentioned in Adapter doc Captain class should be implementing RowingBoat, but in sample code i.e.
https://github.com/iluwatar/java-design-patterns/blob/master/adapter/src/main/java/com/iluwatar/adapter/Captain.java
Captain class actually doesn't extends.

Although It is small, and if required I can fix the doc, but still would require author to give his/her input before I do the same.

**Comment by felipebraga** [comment]
You could open a PR to fix this.

**Comment by hbothra15** [comment]
On it

**Comment by iluwatar** [comment]
@hbothra15 which document are you referring to?

**Comment by iluwatar** [comment]
@hbothra15 you are right. Documentation and implementation are not in sync.
