### ISSUE TITLE
Enterprise integration patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#93]

**Comment by iluwatar** [comment]
Apache Camel

**Comment by npathai** [comment]
@iluwatar Should we add some more patterns that fall into this category? But I think we should first figure out how we are going to implement them.

**Comment by iluwatar** [comment]
See my comment in #82 Just looked at the book, there seems to be 65 EIP patterns there.

**Comment by iluwatar** [comment]
This epic was split in issues and will now be closed. Discussion about implementation technique of EIPs can be found in #82

**Comment by npathai** [comment]
@iluwatar Great, you split all EIPs :)
