### ISSUE TITLE
Github reports security vulnerabilities

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#933]
![image](https://user-images.githubusercontent.com/582346/65894272-266ef300-e3b2-11e9-9f71-046923607de6.png)

![image](https://user-images.githubusercontent.com/582346/65894326-3dade080-e3b2-11e9-920b-b524d0edbfda.png)

**Comment by hbothra15** [comment]
HI @iluwatar 
I would like to take this up

**Comment by iluwatar** [comment]
Ok @hbothra15

**Comment by haridevelops** [comment]
is this still work in progress or shall i pick up ? @hbothra15 @iluwatar

**Comment by iluwatar** [comment]
Ping @hbothra15

**Comment by gaurav9822** [comment]
@iluwatar Want to take this issue. Is there anything else we need to do apart from upgrading the concerned dependencies?

**Comment by iluwatar** [comment]
@gaurav9822 update the dependencies and after that verify that build and tests still work

**Comment by gaurav9822** [comment]
@iluwatar I have raised a ticket on Spring JIRA.
URL - https://jira.spring.io/projects/DATAJPA/issues/DATAJPA-1610?filter=allopenissues

Also, after discussing with Spring developers, they have told to upgrade spring-boot as well in order to support spring-data 1.11.

**Comment by iluwatar** [comment]
Makes sense, those artifacts are probably dependent of each other. It's worth trying at least.
