### ISSUE TITLE
Add a real world examples section

### ISSUE THREAD

**Issue by palash25** [iluwatar/java-design-patterns#938]
Hi :wave: thank you for putting this project together. 

I wanted to suggest an addition to each of the patterns that might be beneficial for newbie devs like me would be to add a "Real World Examples" section (with links to OSS projects that use the design pattern) just below the applicability / when to use section.

Even though most of the descriptions are quite straightforward and well explained sometimes it is helpful to see how a certain pattern is implemented in a real-world software.

**Comment by iluwatar** [comment]
Hi @palash25 it's always good to hear feedback. What comes to "real world examples" section we already have that, at least in theory. See the pattern template in wiki here https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template. Many patterns may just not have any examples yet, but additions are always welcome.
