### ISSUE TITLE
WARNING when building project

### ISSUE THREAD

**Issue by perwramdemark** [iluwatar/java-design-patterns#939]
When building project with mvn install you get below warning. You need to setup the JXR plugin to get ride of this for multi-module projects.

[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ abstract-factory ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
Unable to locate Source XRef to link to - DISABLED

**Comment by perwramdemark** [comment]
I can fix it!

**Comment by iluwatar** [comment]
Nice @perwramdemark, go ahead!

**Comment by iluwatar** [comment]
Related to https://github.com/iluwatar/java-design-patterns/issues/944
