### ISSUE TITLE
Java 11 support: Maven plugin upgrade

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#943]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

We need to update the Maven plugins used in the build to versions that support Java 11. The plugins include at least

- maven-compiler-plugin
- jacoco-maven-plugin
- maven-checkstyle-plugin
- maven-surefire-plugin
- maven-pmd-plugin
- license-maven-plugin

**Comment by perwramdemark** [comment]
I'll fix..

**Comment by iluwatar** [comment]
Thanks @perwramdemark, go ahead
