### ISSUE TITLE
Java 11 support: Get rid of compiler warnings

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#944]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

In this task we run the regular build and inspect the compiler output for warnings. We are especially interested in deprecation warnings, those are going to break things when Java version is updated. The target of the task is to get rid of as many warnings as possible.

**Comment by yashsugandh** [comment]
I'll get rid of it.

**Comment by perwramdemark** [comment]
@iluwatar compiling project with java 8 I don't get any other compiler warnings.

**Comment by iluwatar** [comment]
Yes, I can confirm. We can close this issue.
