### ISSUE TITLE
Update the link of the Principle Keep things DRY 3rd resource "Don't Repeat Yourself" 

### ISSUE THREAD

**Issue by zd-zero** [iluwatar/java-design-patterns#946]
Currently, on the Resources of [Keep Things Dry](https://java-design-patterns.com/principles/#keep-things-dry) section, it is linked to `http://programmer.97things.oreilly.com/wiki/index.php/Don't_Repeat_Yourself`
but now it doesn't exist anymore and redirects to `https://www.oreilly.com/`.

**Comment by josediego** [comment]
I'll be glad to help with this.

**Comment by sohilladhani** [comment]
I think it has moved to https://www.oreilly.com/library/view/97-things-every/9780596809515/ch30.html.

**Comment by ba-nyar-naing** [comment]
I'm new come here and can you let me create a PR with above link?

**Comment by zd-zero** [comment]
Closing the issue as it is already resolved.
https://github.com/webpro/programming-principles/pull/28

**Comment by iluwatar** [comment]
Thanks @zd-zero for taking care of this :+1:
