### ISSUE TITLE
Java 11 support: Run the build on JDK 11

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#948]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

In this task we run the regular build entirely on the newer JDK 11 in a way that lets us gather all errors instead of stopping the build to the first failure (see https://blog.codefx.org/java/planning-your-java-9-update/). Report the list of errors under this issue.

**Comment by perwramdemark** [comment]
Lets give it a try..

**Comment by iluwatar** [comment]
Ok @perwramdemark

**Comment by perwramdemark** [comment]
@iluwatar would it be possible to setup CI build with JDK11?

**Comment by iluwatar** [comment]
Added issue https://github.com/iluwatar/java-design-patterns/issues/973 where this is resolved

**Comment by iluwatar** [comment]
Build with JDK11 from current master branch (commit 90ea4506caa653711f69fabb99ee7ac26c4ecce7) produces the following output.

![image](https://user-images.githubusercontent.com/582346/66600101-6fdaf180-ebad-11e9-894c-79c277a725a3.png)

The modules that are failing
- service-layer
- naked-objects
- repository
- layers
- cqrs
- eip-wire-tap
- eip-splitter
- eip-aggregator
- trampoline

Full build output in the attachment 
[output.txt](https://github.com/iluwatar/java-design-patterns/files/3714293/output.txt)

**Comment by iluwatar** [comment]
Let's continue from here in other issues

**Comment by iluwatar** [comment]
See https://github.com/iluwatar/java-design-patterns/issues/976
@perwramdemark will you work on that?
