### ISSUE TITLE
about Command Pattern

### ISSUE THREAD

**Issue by proandceo** [iluwatar/java-design-patterns#95]
First of all, thank you for this good site and I'm studying various design pattern by referencing yours.

But I have a question about "Command Pattern"
I am confused about "Invoker and Receiver" because your example seems to be one(Wizard) including both Invoker and Receiver.
I guess it will separate Wizard into Invoker and Receiver to help others' understanding.
If I misunderstand it, would you explain it for me?

thank you
Rex

**Comment by iluwatar** [comment]
Hi @proandceo 

I'm not sure I understand your question. In the Command pattern example the wizard (invoker) casts spells (command) on the goblin (receiver). Please clarify what you mean by "Invoker and Receiver"?

**Comment by proandceo** [comment]
Thank you for your advice which made me understood easily.

I am afraid that I still confused, based on I'm not professional programmer for Design Patter, goblin is the receiver, wizard is invoker.
But compared your UML and others, it seems to be different so, I am confused. 
![image](https://cloud.githubusercontent.com/assets/3205452/8421935/dcc1746e-1f0f-11e5-9e82-265486373388.png)

**Comment by iluwatar** [comment]
I agree the UML diagram of the Command pattern could be updated and clarified. The blocks and relations are the same as in your diagram. I will work on this and provide an update.

**Comment by iluwatar** [comment]
@proandceo I have now updated the Command pattern example. The UML diagram was updated and more code comments were added.
