### ISSUE TITLE
Java 11 support: Get rid of JavaEE, Corba and JavaFX

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#954]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Java EE, Corba and JavaFX have been deprecated in newer JDK versions. Are there any dependencies to those in this project? If there is, we should get rid of them. (see https://blog.codefx.org/java/java-9-migration-guide/)

**Comment by jarpit96** [comment]
Hi, I have created a pull request for this issue.

**Comment by jarpit96** [comment]
https://github.com/iluwatar/java-design-patterns/pull/957

**Comment by ryantheleach** [comment]
A lot of this stuff has just been migrated to community projects...

Shouldn't J-EE move to Jakarta? I didn't think J-EE was truly deprecated.
JavaFX to https://openjfx.io/

**Comment by iluwatar** [comment]
@ryantheleach yes, I agree that stuff should be moved and not totally removed. Maybe an inaccurate term there in the issue subject..

**Comment by iluwatar** [comment]
Links:
https://blog.codefx.org/java/java-9-migration-guide/#Dependencies-On-Java-EE-Modules
https://jaxenter.com/jdk-11-java-ee-modules-140674.html
