### ISSUE TITLE
Java 11 support: URLClassLoader

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#956]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Casting to URLClassLoader no longer works in newer Java versions. Do we have that in this project? In that case we should get rid of it.

Links:
https://blog.codefx.org/java/java-9-migration-guide/

**Comment by jarpit96** [comment]
I just checked in the project, there is no usage of URLClassLoader.

**Comment by iluwatar** [comment]
Thanks @jarpit96 for checking this. In that case we can close this issue.
