### ISSUE TITLE
Automate static analysis with Travis

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#96]
https://scan.coverity.com/travis_ci

**Comment by sharifmamun** [comment]
Hi @iluwatar I was planning to work on this but I can see that you already added the repo to Coverity. Can you please close this issue?

**Comment by iluwatar** [comment]
The project has been manually scanned with Coverity, but this task is about automating the scan so manual steps would no longer be necessary.

**Comment by iluwatar** [comment]
Static analysis is now automated with PMD plugin
