### ISSUE TITLE
Java 11 support: Runtime layout

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#961]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Java runtime layout has drastically changed in JDK9. Do we have dependencies to old runtime such as rt.jar tools.jar or dt.jar? Report the findings under this issue.

Links:
https://blog.codefx.org/java/java-9-migration-guide/

**Comment by jarpit96** [comment]
I just checked the project, there are no usages for such old runtime jar.

**Comment by iluwatar** [comment]
Thanks @jarpit96, we can then check this completed :heavy_check_mark:
