### ISSUE TITLE
Java 11 support: Xbootclasspath

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#962]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Option -Xbootclasspath has been removed. Do we have this in this project? Report findings under this issue.

Links:
https://blog.codefx.org/java/java-9-migration-guide/

**Comment by jarpit96** [comment]
We don't have any usages of -Xbootclasspath in the project.

**Comment by iluwatar** [comment]
Thanks for looking into this. We can mark this fixed.
