### ISSUE TITLE
Java 11 support: Currency formats

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#966]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Do we use currency formats that could cause problems, as described in https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/? Report findings under this issue.

**Comment by iluwatar** [comment]
Hello @mgabor6 :wave: I think it's a good first issue. Please go ahead with the check.

**Comment by mgabor6** [comment]
Thanks! I've checked the code base specifically for currency formatting, and there are no usage of it. Although there is possible, that the same could occur at general number or date formatting, because they both depends on Locale, so I've started to dive into Java 11 formatting, and will write some tests for these.

**Comment by iluwatar** [comment]
Ok @mgabor6 let us know how it goes :+1:

**Comment by iluwatar** [comment]
@mgabor6 any news?

**Comment by iluwatar** [comment]
The result of the investigation was that Java currencies are not used in the project.

**Comment by mgabor6** [comment]
Hey @iluwatar . Sorry for the hiatus, I had ongoing projects, and they just ended. From now on I'll have some spare time to dive into Java 11 formatting if needed.

**Comment by iluwatar** [comment]
@mgabor6 no problem. I think there's nothing to investigate in this issue anymore, but please look into other tasks if you find something interesting.

https://github.com/iluwatar/java-design-patterns/issues

**Comment by mgabor6** [comment]
Thanks :)
