### ISSUE TITLE
Repository pattern logging is broken

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#969]
While running the Repository pattern example I noticed that logging doesn't work. It should log some things to standard output, see for example here https://github.com/iluwatar/java-design-patterns/blob/master/repository/src/main/java/com/iluwatar/repository/App.java#L74

**Comment by erikgajdos1997** [comment]
Hello, so the issue is to repair logging in repository pattern? 
If yes, can i take this issue to do?

**Comment by iluwatar** [comment]
Yes and yes @erikgajdos1997

**Comment by erikgajdos1997** [comment]
Can you assign me to this issue? @iluwatar

**Comment by erikgajdos1997** [comment]
I send pull request, just need review
