### ISSUE TITLE
Single logging framework should be enforced

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#970]
As aligned in https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections we should use Slf4j API with Logback implementation as logging framework. However, some patterns are still using log4j. In this issue we migrate them to Logback.

**Comment by lauramurinova** [comment]
Hello, I would like to try and solve the issue.

**Comment by iluwatar** [comment]
Thanks @lauramurinova, go ahead

**Comment by iluwatar** [comment]
Ok @lauramurinova and thanks for notifying

**Comment by iluwatar** [comment]
Assigned to @jjjimenez100

**Comment by jjjimenez100** [comment]
PR: https://github.com/iluwatar/java-design-patterns/pull/982
