### ISSUE TITLE
Java 11 support: Update Travis to build on JDK 11

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#973]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

The purpose is to update the Travis CI build to use JDK 11, instead of the old JDK 8.

**Comment by JasonSarwar** [comment]
Can I try this out?

**Comment by iluwatar** [comment]
Go ahead @JasonSarwar

**Comment by iluwatar** [comment]
See `.travis.yml` in https://github.com/iluwatar/java-design-patterns/pull/959

**Comment by iluwatar** [comment]
Set Travis to build on both openjdk8 and openjdk 11 in commits https://github.com/iluwatar/java-design-patterns/commit/795b6be17d270e93ccfc871fa4976f052c33a181 and https://github.com/iluwatar/java-design-patterns/commit/71f26c3e59f45d0e62b7137a75705a522d43cdec

**Comment by JasonSarwar** [comment]
I was a little late on the draw. Sorry about that!
