### ISSUE TITLE
Security alert in spring-data-jpa

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#978]
Github reports security alert in spring-data-jpa dependency. It should be upgraded in this task.

![image](https://user-images.githubusercontent.com/582346/66677909-5603e200-ec73-11e9-961f-5d77bd1bc771.png)

**Comment by Mistral** [comment]
Can I do this task?

**Comment by iluwatar** [comment]
Go ahead @Mistral

**Comment by bsshashank** [comment]
Sorry did not see that it was already assigned.

**Comment by iluwatar** [comment]
@Mistral are you working on this?

**Comment by prakhyatsinghal** [comment]
Can I work on this ?

**Comment by iluwatar** [comment]
Yes, assigned to you @prakhyatsinghal, since @Mistral is not responding.

**Comment by interactwithankush** [comment]
Please assign this to me.

**Comment by mohanaraosv** [comment]
I have already done changes here https://github.com/iluwatar/java-design-patterns/pull/1870, Please assign to me.

**Comment by iluwatar** [comment]
To be fair, I think @mohanaraosv expressed interest first. Let's try to complete this task in https://github.com/iluwatar/java-design-patterns/pull/1870

**Comment by interactwithankush** [comment]
Sounds good @iluwatar

**Comment by samratpodder** [comment]
What is the status of this Issue ? Is it resolved or is anyone working on it? @iluwatar

**Comment by iluwatar** [comment]
It's not resolved yet. Would you like to pick it up @samratpodder?

**Comment by akhil9281** [comment]
I would like to work on this issue for `hacktoberfest`.

**Comment by pchugh17** [comment]
Let me know if contribution is needed for this. I would like to take this up or similar issues.

**Comment by samratpodder** [comment]
> It's not resolved yet. Would you like to pick it up @samratpodder?

Yes, I would like to work on it. @iluwatar

**Comment by iluwatar** [comment]
Assigned to @samratpodder

**Comment by iluwatar** [comment]
@pchugh17 the issue is freed again if you want to take it?

**Comment by iluwatar** [comment]
> samratpodder @samratpodder Oct 14 18:22
@iluwatar I am unable to upgrade the Spring Data JPA version. It seems that Spring Version as well as the SpringBoot Version is very much outdated. To upgrade the JPA version we also require upgrading the other two which is introducing too many test failures across the majority of modules. I would suggest taking the initiative to upgrade the entire repository to the latest Spring Versions. If you want I can create a PR to push the changes to POM.xml but it would fail the build. Otherwise, unassign me from the Issue iluwatar/java-design-patterns#978

**Comment by robertvolkmann** [comment]
Created #2131 to fix the above security alert.
