### ISSUE TITLE
Java 11 support: Naked Objects pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#983]
In issue https://github.com/iluwatar/java-design-patterns/issues/976 JDK11 build was taken to use but one problem related to Naked Objects pattern remains. Issue description from @lbroman:

> In my PR #980 I have left language source and target at 8 for the naked-objects/dom module. This is because java 11 bytecode breaks the datanucleus enhancer, even if they claim that 5.2 should support java 11 bytecode.
I have tried fiddling with the datanucleus dependency versions because the module uses datanucleus core 5 and apis from 4 so I thought that might be the problem. However, bumping up the versions breaks other stuff as they seem to have moved around some classes between 4 and 5.

**Comment by tejashreeegithub** [comment]
hi,
please can u help me to run naked objects pattern project.. please.. i am new to maven. i tried to build naked objects project. Seperate jars are getting created for dom,fixture,integtests and webapp folder and also simpleapp.war inside webapps/target. How do i run this war file?
I installed tomcat also..

**Comment by iluwatar** [comment]
@tejashreeegithub there are many ways but probably easiest is to use the executable jar. First build it with `mvn clean package` and then in the webapp/target you can run `java -jar naked-objects-webapp-1.22.0-SNAPSHOT-jetty-console.jar`

**Comment by iluwatar** [comment]
One way to resolve this issue could be to try to update the whole pattern. The instructions can be found on the Apache Isis website https://isis.apache.org/guides/ugfun/ugfun.html#_ugfun_getting-started_simpleapp-archetype.

**Comment by tejashreeegithub** [comment]
> @tejashreeegithub there are many ways but probably easiest is to use the executable jar. First build it with `mvn clean package` and then in the webapp/target you can run `java -jar naked-objects-webapp-1.22.0-SNAPSHOT-jetty-console.jar`
One small help.. what could be the output of it.? Actually i was able to see sc
<img width="839" alt="nakedObjectsPage" src="https://user-images.githubusercontent.com/56831314/67261555-d4a41f00-f4be-11e9-903e-6efdc3a9ed56.png">
But can we see any naked objects structure using this url localhost:8081.

Please help me in how this project shows up as result

**Comment by iluwatar** [comment]
You can click the links there in the web app to go deeper. Learn more about Apache Isis and naked objects pattern by reading https://isis.apache.org/guides/ugfun/ugfun.html

**Comment by hartpoli** [comment]
> You can click the links there in the web app to go deeper. Learn more about Apache Isis and naked objects pattern by reading https://isis.apache.org/guides/ugfun/ugfun.html

I try so hard for understand that content inside there. 😐😐😐

**Comment by mohanaraosv** [comment]
@iluwatar The above link is broken could you please update it with the relevant URL.

**Comment by hartpoli** [comment]
ok.

> 

tq

**Comment by robertvolkmann** [comment]
@iluwatar Could I work on this?

**Comment by iluwatar** [comment]
Sure @robertvolkmann, go ahead!
