### ISSUE TITLE
Java 11 support: Start using var

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#984]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Start using local-variable type inference (var). It is a nice example of syntactic sugar that helps reduce boilerplate code (see https://www.infoq.com/articles/upgrading-java-8-to-12/ and https://winterbe.com/posts/2018/09/24/java-11-tutorial/)

It's a huge task to do this for all the patterns at once so it is possible to create pull requests for individual patterns. This way we can complete the task gradually. The following checklist tracks which patterns have already been refactored.

[x] abstract-document
[x] abstract-factory
[x] acyclic-visitor
[x] adapter
[x] aggregator-microservices
[x] ambassador
[x] api-gateway
[x] async-method-invocation
[x] balking
[x] bridge
[x] builder
[x] business-delegate
[x] bytecode
[x] caching
[x] callback
[x] chain
[x] circuit-breaker
[x] collection-pipeline
[x] command
[x] commander
[x] composite
[x] converter
[x] cqrs
[x] dao
[x] data-bus
[x] data-locality
[x] data-mapper
[x] data-transfer-object
[x] decorator
[x] delegation
[x] dependency-injection
[x] dirty-flag
[x] double-checked-locking
[x] double-dispatch
[x] eip-aggregator
[x] eip-message-channel
[x] eip-publish-subscribe
[x] eip-splitter
[x] eip-wire-tap
[x] event-aggregator
[x] event-asynchronous
[x] event-driven-architecture
[x] event-queue
[x] event-sourcing
[x] execute-around
[x] extension-objects
[x] facade
[x] factory-kit
[x] factory-method
[x] feature-toggle
[x] fluentinterface
[x] flux
[x] flyweight
[x] front-controller
[x] guarded-suspension
[x] half-sync-half-async
[x] hexagonal
[x] intercepting-filter
[x] interpreter
[x] iterator
[x] layers
[x] lazy-loading
[x] leader-election
[x] marker
[x] master-worker-pattern
[x] mediator
[x] memento
[x] model-view-controller
[x] model-view-presenter
[x] module
[x] monad
[x] monostate
[x] multiton
[x] mute-idiom
[x] mutex
[x] naked-objects
[x] null-object
[x] object-mother
[x] object-pool
[x] observer
[x] page-object
[x] partial-response
[x] pipeline
[x] poison-pill
[x] priority-queue
[x] private-class-data
[x] producer-consumer
[x] promise
[x] property
[x] prototype
[x] proxy
[x] queue-load-leveling
[x] reactor
[x] reader-writer-lock
[x] repository
[x] resource-acquisition-is-initialization
[x] retry
[x] role-object
[x] semaphore
[x] servant
[x] serverless
[x] service-layer
[x] service-locator
[x] singleton
[x] spatial-partition
[x] specification
[x] state
[x] step-builder
[x] strategy
[x] template-method
[x] thread-pool
[x] throttling
[x] tls
[x] tolerant-reader
[x] trampoline
[x] twin
[x] typeobjectpattern
[x] unit-of-work
[x] value-object
[x] visitor

**Comment by Anurag870** [comment]
I am working on this

**Comment by iluwatar** [comment]
Ok @Anurag870

**Comment by zbeach** [comment]
I'd also like to work on this!

**Comment by iluwatar** [comment]
@Anurag870 could you state which patterns will you be working on? @zbeach can then look at some others.

**Comment by Anurag870** [comment]
@zbeach I will keep updating the list here: 

abstract-document
abstract-factory
acyclic-visitor
adapter
aggregator-microservices

**Comment by gvsharma** [comment]
I would like to work on this?

**Comment by iluwatar** [comment]
Ok @gvsharma, just declare what patterns you will be working on so the work won't conflict with @Anurag870 and @zbeach

**Comment by gvsharma** [comment]
I will work on below patterns
[ ] serverless
[ ] service-layer
[ ] service-locator
[ ] singleton
[ ] state
[ ] step-builder
[ ] strategy
[ ] template-method
[ ] thread-pool
[ ] throttling

**Comment by gvsharma** [comment]
> I will work on below patterns
> [ ] serverless
> [ ] service-layer
> [ ] service-locator
> [ ] singleton
> [ ] state
> [ ] step-builder
> [ ] strategy
> [ ] template-method
> [ ] thread-pool
> [ ] throttling

Done with changes. Thank you

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up ambassador async-method-invocation balking bridge builder in https://github.com/iluwatar/java-design-patterns/pull/1076

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up remaining b-c in https://github.com/iluwatar/java-design-patterns/pull/1081

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up starting with a in https://github.com/iluwatar/java-design-patterns/pull/1084
@iluwatar picked up from t-v in https://github.com/iluwatar/java-design-patterns/pull/1085

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all c-e in https://github.com/iluwatar/java-design-patterns/pull/1111 and https://github.com/iluwatar/java-design-patterns/pull/1112

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all f in https://github.com/iluwatar/java-design-patterns/pull/1115

**Comment by anuragagarwal561994** [comment]
@iluwatar picked remaining g,h,i in https://github.com/iluwatar/java-design-patterns/pull/1116

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all s in https://github.com/iluwatar/java-design-patterns/pull/1120

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all q-r in https://github.com/iluwatar/java-design-patterns/pull/1121

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all p in https://github.com/iluwatar/java-design-patterns/pull/1122

**Comment by npczwh** [comment]
@iluwatar, updated the below patterns in #1190:
layers
lazy-loading
leader-election

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all m in https://github.com/iluwatar/java-design-patterns/pull/1220

**Comment by npczwh** [comment]
@iluwatar, updated the below patterns in #1222:
object-mother
object-pool
observer

**Comment by venkatrs-ch197** [comment]
Hi,

I'd like to work on **[ ] module** pattern.
Can I proceed with this?

**Comment by venkatrs-ch197** [comment]
Hi @iluwatar,

Can you please look into my pull request #1238 and let me know if any changes required.

Thanks,
Venkat

**Comment by anuragagarwal561994** [comment]
@iluwatar picked remaining in https://github.com/iluwatar/java-design-patterns/pull/1479
