### ISSUE TITLE
Java 11 support: Utilize new methods

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#987]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

This is a refactoring ticket where we start to utilize new Java 11 functionality.

1) Collecting to unmodifiable collections is possible using the new Collector for Streams operations to put the results into an immutable collection (see https://www.infoq.com/articles/upgrading-java-8-to-12/)

2) Predicate::not provides an easy way to negate predicate lambdas or method references, again reducing the boilerplate in our code (see https://www.infoq.com/articles/upgrading-java-8-to-12/)

3) New methods on Optional give even more options for coding in a functional style when using an Optional instead of having to use clumsy if statements (see https://winterbe.com/posts/2018/09/24/java-11-tutorial/)

4) Streams have new methods ofNullable, dropWhile, takeWhile (see https://winterbe.com/posts/2018/09/24/java-11-tutorial/)

5) String has new helper methods (see https://winterbe.com/posts/2018/09/24/java-11-tutorial/)

6) InputStream finally gets a super useful method to transfer data to an OutputStream (see https://winterbe.com/posts/2018/09/24/java-11-tutorial/)

7) Convenience Factory Methods for Collections make it significantly easier to create collections like lists, maps and sets (see https://winterbe.com/posts/2018/09/24/java-11-tutorial/)

It's a huge task to do this for all the patterns at once so it is possible to create pull requests for individual patterns. This way we can complete the task gradually. The following checklist tracks which patterns have already been refactored.

[x] abstract-document
[x] abstract-factory
[x] acyclic-visitor
[x] adapter
[x] aggregator-microservices
[x] ambassador
[x] api-gateway
[x] async-method-invocation
[x] balking
[x] bridge
[x] builder
[x] business-delegate
[x] bytecode
[x] caching
[x] callback
[x] chain
[x] circuit-breaker
[x] collection-pipeline
[x] command
[x] commander
[x] composite
[x] converter
[x] cqrs
[x] dao
[x] data-bus
[x] data-locality
[x] data-mapper
[x] data-transfer-object
[x] decorator
[x] delegation
[x] dependency-injection
[x] dirty-flag
[x] double-checked-locking
[x] double-dispatch
[x] eip-aggregator
[x] eip-message-channel
[x] eip-publish-subscribe
[x] eip-splitter
[x] eip-wire-tap
[x] event-aggregator
[x] event-asynchronous
[x] event-driven-architecture
[x] event-queue
[x] event-sourcing
[x] execute-around
[x] extension-objects
[x] facade
[x] factory-kit
[x] factory-method
[x] faq.md
[x] feature-toggle
[x] fluentinterface
[x] flux
[x] flyweight
[x] front-controller
[x] guarded-suspension
[x] half-sync-half-async
[x] hexagonal
[x] intercepting-filter
[x] interpreter
[x] iterator
[x] layers
[x] lazy-loading
[x] leader-election
[x] marker
[x] master-worker-pattern
[x] mediator
[x] memento
[x] model-view-controller
[x] model-view-presenter
[x] module
[x] monad
[x] monostate
[x] multiton
[x] mute-idiom
[x] mutex
[x] naked-objects
[x] null-object
[x] object-mother
[x] object-pool
[x] observer
[x] page-object
[x] partial-response
[x] pipeline
[x] poison-pill
[x] priority-queue
[x] private-class-data
[x] producer-consumer
[x] promise
[x] property
[x] prototype
[x] proxy
[x] queue-load-leveling
[x] reactor
[x] reader-writer-lock
[x] repository
[x] resource-acquisition-is-initialization
[x] retry
[x] semaphore
[x] servant
[x] serverless
[x] service-layer
[x] service-locator
[x] singleton
[x] spatial-partition
[x] specification
[x] state
[x] step-builder
[x] strategy
[x] template-method
[x] thread-pool
[x] throttling
[x] tls
[x] tolerant-reader
[x] trampoline
[x] twin
[x] typeobjectpattern
[x] unit-of-work
[x] value-object
[x] visitor

**Comment by leonmak** [comment]
HI I would like to work on this, noticed it was combined from a few tickets, do I make a PR for each?

**Comment by iluwatar** [comment]
Let's use the same gradual approach as we are doing in https://github.com/iluwatar/java-design-patterns/issues/984. You can do the refactoring for a single pattern or many. We'll then track the progress with a checklist.

@leonmak ok, you're good to go

**Comment by Anurag870** [comment]
@iluwatar I will work on the following patterns:
unit-of-work
value-object
visitor

**Comment by iluwatar** [comment]
Ok @Anurag870

**Comment by leonmak** [comment]
I would like to work on:

- [] abstract-document
- [] collection-pipeline
- [] commander
- [] composite
- [] converter

**Comment by leonmak** [comment]
Also would like to work on:
- [ ] dao
- [ ] double-dispatch
- [ ] facade
- [ ] flyweight

**Comment by Anurag870** [comment]
Also checked in code after checking 

typeobjectpattern, tolerantreader, twin, trampoline

**Comment by iluwatar** [comment]
Ok @leonmak 
@Anurag870 do you mean that code for those patterns has already been refactored?

**Comment by leonmak** [comment]
cool, thanks.
some more which I've worked on:
- [ ] hexagonal
- [ ] iterator
- [ ] layers
- [ ] leader-election
- [ ] observer
- [ ] page-object
- [ ] partial-response
- [ ] sample-application
- [ ] servant
- [ ] service-layer
- [ ] thread-pool

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up ambassador async-method-invocation balking bridge builder in https://github.com/iluwatar/java-design-patterns/pull/1076

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up remaining b-c in https://github.com/iluwatar/java-design-patterns/pull/1081

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up starting with a in https://github.com/iluwatar/java-design-patterns/pull/1084

**Comment by anuragagarwal561994** [comment]
@iluwatar picked up from t-v in https://github.com/iluwatar/java-design-patterns/pull/1085

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all c-e in https://github.com/iluwatar/java-design-patterns/pull/1111 and https://github.com/iluwatar/java-design-patterns/pull/1112

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all f in https://github.com/iluwatar/java-design-patterns/pull/1115

**Comment by anuragagarwal561994** [comment]
@iluwatar picked remaining g,h,i in https://github.com/iluwatar/java-design-patterns/pull/1116

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all s in https://github.com/iluwatar/java-design-patterns/pull/1120

**Comment by anuragagarwal561994** [comment]
@iluwatar picked q-r in https://github.com/iluwatar/java-design-patterns/pull/1121

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all p in https://github.com/iluwatar/java-design-patterns/pull/1122

**Comment by anuragagarwal561994** [comment]
@iluwatar picked all m in https://github.com/iluwatar/java-design-patterns/pull/1220

**Comment by vINCENT8888801** [comment]
Hi, I am new to this project. May I work on [ ] null-object?

**Comment by anuragagarwal561994** [comment]
@iluwatar picked remaining patterns in https://github.com/iluwatar/java-design-patterns/pull/1479

**Comment by iluwatar** [comment]
Ok @anuragagarwal561994

**Comment by anuragagarwal561994** [comment]
@iluwatar finally is it time that we close this :D

**Comment by iluwatar** [comment]
@anuragagarwal561994 I really think so 😄 I'm grateful for your persistent effort on this 👍🏻
