### ISSUE TITLE
Java 11 support: HttpClient

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#988]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Patterns Aggregator Microservices and API Gateway are currently using Apache HttpClient in their implementation. Java 11 provides its own HttpClient and we should switch to that instead to get rid of unnecessary external dependencies.

Links:
https://winterbe.com/posts/2018/09/24/java-11-tutorial/#http-client

**Comment by oconnelc** [comment]
I'd be interested in looking into this, can I go ahead and try?

**Comment by iluwatar** [comment]
Ok @oconnelc

**Comment by oconnelc** [comment]
Which version of JDK should I compile against? Should I use Oracle or Openjdk?

**Comment by iluwatar** [comment]
We have just switched to openjdk11
