### ISSUE TITLE
Package patterns into executable jars

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#989]
The design pattern applications are easy to run within an IDE but it would be nice to be able to run them effortlessly having only the jar files.

In this task we are going to add and configure maven-assembly-plugin to package the patterns into executable jars, so that they can later be run like `java -jar pattern.jar`.

Links:
https://www.baeldung.com/executable-jar-with-maven

**Comment by eater-of-souls** [comment]
I think I'll try my hand at this

**Comment by iluwatar** [comment]
Sure @eater-of-souls :smiling_imp:

**Comment by iluwatar** [comment]
This issue is free to take again

**Comment by hbothra15** [comment]
Before taking this up, I would Like to know do we want to add this for all patterns right
for e.g If I want to run abstract-pattern then I need to run `java -jar abstractpattern.jar`

**Comment by iluwatar** [comment]
That's correct @hbothra15.

**Comment by hbothra15** [comment]
Then please do assign this to me will shortly raise MR for 1 of the package and if that's good will do the same for rest

**Comment by iluwatar** [comment]
Ok @hbothra15
