### ISSUE TITLE
final initialization pattern?

### ISSUE THREAD

**Issue by ryantheleach** [iluwatar/java-design-patterns#99]
Is there a pattern that deals with keeping references final, but initializing them after construction somehow because allowing this references to escape is potentially bad?

**Comment by iluwatar** [comment]
There is a pattern called [Private Class Data](https://en.wikipedia.org/wiki/Private_class_data_pattern) that probably achieves what you need. An example is provided [here](https://github.com/iluwatar/java-design-patterns/tree/master/private-class-data/src/main/java/com/iluwatar/privateclassdata).
